### ISSUE TITLE
bug:system UI freeze and shutdown

### ISSUE THREAD

**Issue by MARCOS752wh** [crdroidandroid/issue_tracker#1]
### Issue type

Other

### Device

Poco x3 pro (vayu)

M2102J20SI

### crDroid version

crDroid 8

### Bug description

 When entering games, it freezes, the system ui stopped and when entering other applications such as YouTube and high consumption of ram memory by the system and a slight lag when playing videos on YouTube or on tik tok or another application and the applications do not close properly.

### Steps to reproduce

Enter a game, lower quick settings bar or notifications

Lag in Videos: enter the YouTube or tik tok apk and play.

### Relevant log (logcat/build log)

```shell
09-25 10:19:17.753 E/ActivityManager(1526): Unable to freeze binder for 31302 com.google.android.webview:webview_service

09-25 10:13:55.227 E/android.system.suspend@1.0-service(620): failed to read wakeup reasons: Invalid argument

09-25 10:20:14.615 E/cr_CompositorSurfaceMgr(26682): surfaceDestroyed format : -3
09-25 10:20:24.671 E/NgaGrpcClient(20492): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)

09-25 10:21:00.613 E/SQLiteDatabase(30398): Error inserting transferred=1 media_job_uuid=6e96cfd1-1a13-4926-a186-e8b45b01096c transcoded=0 gif_attribution=0 first_scan_length=0 direct_path=/v/t62.7117-24/20102410_807597787237672_4087668416074007241_n.enc?ccb=11-4&oh=01_AVzDESrUB-NzbeMFmYq09-pQtPzZ_OJfv5gpuEtNphbA1w&oe=63555422 thumbnail_height_width_ratio=0.0 is_animated_sticker=0 file_hash=KkdLHrFIXcEsQeieIKi7rDEdXZ73w8wm/t+IQkP5GjQ= file_path=Media/WhatsApp Voice Notes/202240/PTT-20220925-WA0001.opus file_size=11792 partial_media_hash=null face_x=0 face_y=0 height=0 trim_to=0 media_key_timestamp=1664122854000 message_url=https://mmg.whatsapp.net/d/f/AncYcvy4pO3QHIZNmmxeOsRGEwa7gtZfnXE9rJYR7a9k.enc media_caption=null trim_from=0 mime_type=audio/ogg; codecs=opus partial_media_enc_hash=null width=0 original_file_hash=null has_streaming_sidecar=0 autotransfer_retry_enabled=1 message_row_id=16712 multicast_id=null enc_file_hash=Ku0Z7R3OCwVkNA4EoizpYW9c1rD+LgiBZf4VH5rFgJc= mute_video=0 page_count=0 first_scan_sidecar=null suspicious_content=0 file_length=11792 media_name=null media_duration=5 chat_row_id=113 media_key=[B@ee0b106

09-25 10:21:24.138 E/NgaGrpcClient(20492): NgaGrpcClient$1.onFailure():154 Handshake failed!

09-25 10:14:03.269 E/BcSmartspaceCard(2226): No tap action can be set up

09-25 10:23:16.969 E/ocess.gservice(2170): Not starting debugger since process cannot load the jdwp agent.

09-25 10:21:07.726 E/adsprpcd(1308): vendor/qcom/proprietary/commonsys-intf/adsprpc/src/apps_std_imp.c:596:Error 0xffffffff: apps_std getenv failed: ADSP_LIBRARY_PATH Unknown error -1
```

### Screenshots or videos

 It is not possible for me because the system ui freezes and closes

### Solution

Optimize a little more for ram and its use by polishing memory management a bit and have a special memory management and memory release gip menu for easy use and stop of ram consumption

### Additional context

 It is really a very good rom and I am using it every day and it is really a very good job that was done with this rom, the truth is, congratulations for your work and thank you very much for giving us this automated and optimized system for our devices in I really appreciate it and please can you add a little more customization and what is a few more letter fonts and be able to have a black theme I mean amoled please, it would look very cool for xd
Well thank you very much for your work really and thank you for your help and for your collaboration with us users

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
Let know if issue persist on 8.10
If yes, try a clean flash with recommended gapps.

**Comment by MARCOS752wh** [comment]
well I have the recommended gaaps and I have flashed as the telegram group dictates and at the moment I have not had crashes the truth but it was something that persisted

**Comment by MARCOS752wh** [comment]
Here is the log
[logcat.txt](https://github.com/crdroidandroid/issue_tracker/files/10063364/logcat.txt)

[logcat.txt](https://github.com/crdroidandroid/issue_tracker/files/10063365/logcat.txt)

**Comment by MARCOS752wh** [comment]
The system ui crash is always persisting and I did 4 clean flashes, even flashie miui and everything else

**Comment by gwolf2u** [comment]
crDroid 8 for vayu is EoL
update to newer
