### ISSUE TITLE
bug: title (<-- change me)

### ISSUE THREAD

**Issue by adrianooooo** [crdroidandroid/issue_tracker#100]
### Issue type

Source code related

### Device

Guacamole

### crDroid version

crDroid 9

### Exact version / Build date

crDroidAndroid-13.0-20230120-guacamole-v9.1.zip

### Bug description

https://paste.crdroid.net/LFxSFx

### Steps to reproduce

https://paste.crdroid.net/LFxSFx

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/LFxSFx
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Gapps issue
Also bad formatting of bug report
