### ISSUE TITLE
bug: parked call cause beep beep 

### ISSUE THREAD

**Issue by lindahl85** [crdroidandroid/issue_tracker#101]
### Issue type

Feature not working as intended

### Device

Oneplus 8t (kebab) + oneplus 9 (lemonade) 

### crDroid version

crDroid 9

### Exact version / Build date

crDroidAndroid-13.0-20230119-kebab-v9.1

### Bug description

When call waiting is active, a beep beep tone can be heard when a second person calls. That's correct.

But if you are in a call and the other person parks your call it will trigger this found. Both my oneplus 9 and 8t have this now. It has never been seen on crdroid but started sometime on crdroid 9. Crdroid 8 never had that issue. 

### Steps to reproduce

Make a call. Let the person you talk with park the call. Now you will hear beep-beep. 

### Relevant log (logcat/build log)

```shell
Not possible now
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
just the way Android 13 works

**Comment by lindahl85** [comment]
That must be wrong since it can´t be seen on Samsung devices with Android 13.
