### ISSUE TITLE
Battery indicator is missing in landscape mode

### ISSUE THREAD

**Issue by Luciogi** [crdroidandroid/issue_tracker#102]
### Issue type

Feature not working as intended

### Device

Redmi 9T (chime)

### crDroid version

crDroid 9

### Exact version / Build date

9.1/2023-01-14

### Bug description

_same as title_

### Steps to reproduce

1. Go to Crdroid settings
2. then "QUICK SETTINGS" tab
3. Change "Battery location" to "quick statusbar"
4. Rotate device in landscape 
5. You will not see battery indicator

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/TsnIdl
```

### Screenshots or videos

https://user-images.githubusercontent.com/84625092/213879999-cb5f91d7-fb57-433b-86b6-0b2803ce9e44.mp4

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
can't confirm with latest code
![photo_2023-02-04_13-25-36](https://user-images.githubusercontent.com/877292/216764686-1a83d108-6ece-4597-b51d-3e5ecdc5d13a.jpg)
![photo_2023-02-04_13-25-43](https://user-images.githubusercontent.com/877292/216764688-cae5ace9-54f0-4582-b2f8-caaeede70626.jpg)

**Comment by Luciogi** [comment]
@gwolf2u Screenshot is in portrait mode (Bug is in landscape mode)

**Comment by Luciogi** [comment]
@gwolf2u Are you used crdroid 9.1 or unreleased version?

**Comment by gwolf2u** [comment]
quick statusbar is not available in landscape
and I am using released version, just not for your device
