### ISSUE TITLE
bug: option to enable Local Terminal app missing in Settings

### ISSUE THREAD

**Issue by AceDicer** [crdroidandroid/issue_tracker#104]
### Issue type

Feature not working as intended

### Device

Poco F2 Pro (lmi)

### crDroid version

crDroid 9

### Exact version / Build date

9.1/2023-01-10

### Bug description

In Settings, searching for "terminal" to enable the local terminal app gives a result that leads to Settings -> Developer Settings, but the option is not highlighted. Furthermore, looking for the option by hand shows that the option is missing altogether.

### Steps to reproduce

Go to Settings, enable developer settings and search for "terminal" and press the only result given. This will redirect you to the correct menu, but the toggle is missing.

### Relevant log (logcat/build log)

```shell
[none]
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
terminal no longer shipped with cr9
