### ISSUE TITLE
Traffic indicator bug

### ISSUE THREAD

**Issue by sifatefat** [crdroidandroid/issue_tracker#106]
### Issue type

User interface

### Device

Redmi Note 11

### crDroid version

crDroid 9

### Exact version / Build date

9.1/2023-01-05

### Bug description

In the status bar, network traffic indicator padding looks weird when more than one or two icons enabled (like mute+dnd/dnd+alarm)

It also looks bad when arrows are enabled in network traffic indicator settings

But it should be like this (i added a photo) where it will show a dot that means another icons are available if the there's not enough space

![IMG_20230124_223404](https://user-images.githubusercontent.com/109143536/214353710-0198dfe8-b475-49e7-98c2-cb458efba5be.jpg)
![IMG_20230124_214959](https://user-images.githubusercontent.com/109143536/214353719-5ccecd37-19eb-4f4c-a442-75a1388dd14b.jpg)
![IMG_20230124_214916](https://user-images.githubusercontent.com/109143536/214353723-6dba0cfa-5a57-461f-a9ac-5384d0f1d09e.jpg)
![IMG_20230124_214750](https://user-images.githubusercontent.com/109143536/214353729-82265576-2298-4614-b58b-a2669ae22a8b.jpg)

### Steps to reproduce

Step 1. Go to crdroid settings
Step 2. Enable network traffic indicator
Step 3. Don't hide arrows
Step 4. Use more icon (like mute+dnd+alarm+Bluetooth) or anything you want
Step 5. Now see the padding 

### Relevant log (logcat/build log)

```shell
I don't think a log need for this. If I am wrong, sorry for that.
```

### Solution

Please fix the padding also, the traffic indicator is kinda like adjusted with wifi icon, it looks bad, also if the trafic scale is larger it looks good too, otherwise it looks bad (you can add a customization option for this, sparkos has this kind of thing)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
not enough space to list all I guess
@Jabiyeff can confirm

**Comment by sifatefat** [comment]
> not enough space to list all I guess @Jabiyeff can confirm

No main concern is, it is overlapping, it should be dot (.) Which means there are more icons here!

**Comment by gwolf2u** [comment]
correct, but since is text based and dynamic width, the status bar is not able to adapt properly
that's the way it is
@neobuddy89 think this can be changed somehow?
