### ISSUE TITLE
bug: Sound selector showing resource string

### ISSUE THREAD

**Issue by Kodayoda713** [crdroidandroid/issue_tracker#111]
### Issue type

Source code related

### Device

Lemonadep, LE2125

### crDroid version

crDroid 9

### Exact version / Build date

1/27/2023

### Bug description

When selecting a custom ringtone from internal storage, the result in the file location, rather than the sound name (see attached screenshot).

### Steps to reproduce

1. Navigate to "Sound & Vibration"
2. Scroll to "Phone ringtone" and select 
3. Scroll to bottom of subsequent sound picker and select "Add Ringtone"
4. Select sound from internal storage
5. Once selected scroll to top and see resource location instead of file name

### Relevant log (logcat/build log)

```shell
NA
```

### Screenshots or videos

![IMG_20230127_232451](https://user-images.githubusercontent.com/114315350/215350995-1da1f9fe-796b-43d9-8a9d-2bbe942666c8.png)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
all good with latest build
![Screenshot_20230204-131539_Settings](https://user-images.githubusercontent.com/877292/216764250-48f3446b-f713-48d7-8603-af4acb45026e.png)
