### ISSUE TITLE
Different bugs will be listed here

### ISSUE THREAD

**Issue by llXxViCxXll** [crdroidandroid/issue_tracker#112]
### Issue type

Source code related

### Device

Poco x3 Pro

### crDroid version

crDroid 9

### Exact version / Build date

9.1

### Bug description

Different issues

### Steps to reproduce

I loved when I first started using CrDroid on my Poco X3 Pro. It was CrDroid 8.3. I slowly adapted to all of its features and loved the potential of everything I could do with it.

In order to not get loaded with new stuff every new update, ever since I installed CrDroid 8.4, I decided to wait until the Android 13 realease for this custom rom to fully enjoy it.

My experience with it has been so bad. I don't know if it's my device, an error during install (which I doubt, because I installed both CrDroid 9.0 and 9.1, and basically everything is the same, discarding some problems being fixed); but I just want to know if this is a thing that is happening to everybody using the Poco X3 Pro like me ever since they installed the CrDroid 9.0 update or if is just me...

Sadly for me, this version is FILLED with bugs:

- A weird black space on the Messenger app after like an hour of using it.
- A lot of notifications not being shown while using battery save mode (which was not the case on CrDroid 8)
- WAY TOO MANY apps that can't be used because, whenever you open them, they close INSTANTLY (which is really frustrating, because it happens with my bank and my notes app). The only "workaround" I've found is to restart the phone; but it's not a guaranteed fix and it just works for some minutes after restarting the device or until you close the app.
- No links being able to get open on apps (for example, trying to open a link on facebook or Instagram. The app just restarts).
- Google security backup not being able to be made succesfully.
- WhatsApp chats' backup unable to start.
- Mail app only opening to show the list of e-mails; but closing instantly after trying to open any e-mail received.
Etc...

It gets me really sad, because ever since I started using CrDroid and got the hang of it, I fell in love with it, and it pains me that right now my time with it is such a shame with all the issues it has.

As I said earlier, I want to know if those problems I mentioned are well known to the developer of this version, or if it's just me that has them, to try and find another way around to continue using CrDroid or if I better just give up

### Relevant log (logcat/build log)

```shell
01-29 16:52:28.377 E/BundleHelper(12099): MetaData is null. Unable to get meta data for com.bbva.bgm.loginui.activity.WelcomeUserDistributionActivity
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
one bug at a time or we can't track

**Comment by llXxViCxXll** [comment]
Thanks for your help

**Comment by llXxViCxXll** [comment]
> one bug at a time or we can't track

Thanks for your help
