### ISSUE TITLE
bug: Clock and date misalignment in notification shade

### ISSUE THREAD

**Issue by Kodayoda713** [crdroidandroid/issue_tracker#113]
### Issue type

User interface

### Device

Lemonadep, LE2125

### crDroid version

crDroid 9

### Exact version / Build date

1/27/2023

### Bug description

When setting a new wallpaper (using lawn chair launcher), then subsequently pulling down notification shade, clock and date are Misaligned and shift to the left, not accounting for the camera cutout. Screenshot does not show camera cutout obviously, but should be shifted over for account for the cutout.

### Steps to reproduce

1. Set new wallpaper
2. Pull down notification shade
3. Swipe up shade
4. Pull down again

### Relevant log (logcat/build log)

```shell
NA
```

### Screenshots or videos

![Screenshot_20230129-133801_Lawnchair](https://user-images.githubusercontent.com/114315350/215372555-0bcf16fa-a4d6-47b1-afc8-0c83ea27f0fb.png)

### Solution

Swipe up notification shade, and clock and date are aligned correctly to account for camera cutout 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
can't confirm this one
running clean flash with latest build with stock crDroid launcher
