### ISSUE TITLE
bug: (raphael) Phone reboots after connecting to hotspot

### ISSUE THREAD

**Issue by auvio323** [crdroidandroid/issue_tracker#114]
### Issue type

Other

### Device

Xiaomi Mi 9t Pro / Redmi K20 Pro (Raphael)

### crDroid version

crDroid 9

### Exact version / Build date

9.1/2023-1-19

### Bug description

After connecting to my created hotspot, my phone freezes up for about 3 seconds and then reboots as soon as I connect to the hotspot on another device (it says incorrect password on it and then disappears from the list)

### Steps to reproduce

1.- Go to network settings
2.- Toggle the switch for the hotspot
3.- Connect to the hotspot on a second device
4.- Phone freezes
5.- Phone reboots

### Relevant log (logcat/build log)

```shell
No clue where to find this. I went into Mattlog but it froze so I couldn't capture anything, and I typed in logcat into Termux and didn't see anything relavent.
```

### Additional context

An application called SecureTether WiFi which uses WiFi Direct with a proxy configured on the connected device works, but as expected, the connection is slower than it would be with using the built in Hotspot, and not all devices support proxies so it would not be able to connect on some. After 21 days, the trial of this app will run out and I do have it purchased before but I can't use it because I use MicroG on my device and it does not support in app purchases. I also shouldn't have to use this solution anyways and the built-in one should just work as it did in MiUI.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
adb logcat needed
submit with full log
