### ISSUE TITLE
traffic indicator doesn't appear in lockscreen

### ISSUE THREAD

**Issue by Yuko-sa** [crdroidandroid/issue_tracker#116]
### Issue type

Feature not working as intended

### Device

Miatoll

### crDroid version

crDroid 9

### Exact version / Build date

Wed Jan 25 08:49:34 UTC 2023

### Bug description

1. Traffic indicator doesn't appear in lockscreen but shows in home screen status bar.

Preview
![Screenshot_20230204-223824_Wallpaper and style~2](https://user-images.githubusercontent.com/121550441/216780586-0d16527b-489e-4646-ba55-2f318edf08c7.png)

I also noticed some other things that are not working as intended

2. Wallpaper & styles option doesn't show current wallpaper and theme picer doesn't works for these 

Preview
![Screenshot_20230204-224737_Wallpaper and style](https://user-images.githubusercontent.com/121550441/216780701-09b048ea-44ce-46d7-9ef2-bd0caae313a4.png)

3. Settings menu doesn't show current user image. But if you tap on it, it will open current user menu

Preview 
![Screenshot_20230204-224238_Settings~3](https://user-images.githubusercontent.com/121550441/216780861-6d50d28d-1b23-4329-b3d6-5dd4e26ba3d1.png)
![Screenshot_20230204-224954_Google Play services](https://user-images.githubusercontent.com/121550441/216780863-103ce66d-d098-486d-b181-0dd9db629c6c.png)

### Steps to reproduce

.

### Relevant log (logcat/build log)

```shell
None
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
one bug at a time, not all in one so we can track
