### ISSUE TITLE
bug: Lock screen Face unlock

### ISSUE THREAD

**Issue by shethk94** [crdroidandroid/issue_tracker#118]
### Issue type

Feature not working as intended

### Device

Beryllium

### crDroid version

crDroid 9

### Exact version / Build date

9.1/Fri Feb  3 00:09:34 EET 2023

### Bug description

The option, when swiping on lockscreen for allow face unlock on lockscreen is not working as intended.
Faceunlock should only start after swiping up on screen but instead it starts immediately with screen turn on.

### Steps to reproduce

Tap on  settings / Display / Lock screen / Allow face unlock on lock screen and choose "when swiping on lock screen" 
Then lock the phone and turn back on FU starts immediately.

### Relevant log (logcat/build log)

```shell
No logs
```

### Screenshots or videos

![Screenshot_20230207-020105_Settings](https://user-images.githubusercontent.com/87633083/217139003-6570554f-09f4-4893-9a35-322c130bf1d6.png)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
#nofix

**Comment by jason-eu** [comment]
> #nofix

Damn
