### ISSUE TITLE
bug: Wallpaper colour not correct 

### ISSUE THREAD

**Issue by shethk94** [crdroidandroid/issue_tracker#119]
### Issue type

Feature not working as intended

### Device

Beryllium 

### crDroid version

crDroid 9

### Exact version / Build date

9.1/Fri Feb  3 00:09:34 EET 2023

### Bug description

Monet colour are not changing as we select different option from wallpaper colour options.

### Steps to reproduce

Change to any wallpaper from 
Wallpaper and style/wallpaper colour/ choose different colour
Mostly from last options as you can see from the screenshot I attached.

### Relevant log (logcat/build log)

```shell
No logs.
```

### Screenshots or videos

![Screenshot_20230207-085001_Wallpaper and style~2](https://user-images.githubusercontent.com/87633083/217140766-8aa1a938-166b-4e85-86df-bb23ad758e73.png)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is now fixed with upcoming update
