### ISSUE TITLE
3-button navigation app switch is broken

### ISSUE THREAD

**Issue by eadyo** [crdroidandroid/issue_tracker#12]
### Issue type

User interface

### Device

Xiaomi Mi 9 (cepheus) - but apparently it's same bug on all the different models.

### crDroid version

crDroid 8

### Bug description

With 3-button navigation I get this bug when I press App Overview button too fast bad shit happens. Either it shows some blank application, makes the button stuck or just goes to main screen. Xiaomi Mi 9, CR 8.9.

In the video above first I show how it works, pressing the button slowly. Then I break things, always the 2nd time I press the button faster than my grandma.

### Steps to reproduce

1. Change system navigation option to 3-button navigation.
2. Open at least 2 apps.
3. Switch between them fast - as in press App Overview button quick.
4. First switch should work fine - it always breaks on the 2nd quicker switch.

### Relevant log (logcat/build log)

```shell
I can't create private logs right now.
```

### Screenshots or videos

Uploading video_2022-10-02_22-25-52.mp4…

### Additional context

crDroid Home

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by eadyo** [comment]
https://user-images.githubusercontent.com/109316496/193474985-33463357-922f-477e-a81b-bca508c3796c.mp4

I don't know why video didn't upload.

**Comment by africabloe** [comment]
**Redmi Note 4X (mido)** 
3-button on screen navigation it works excellent here. 
There is no problem at all for my device. It can work very fast without breaks. 
And imagine. My mobile released on February 2017. And I have 67 apps... 

https://user-images.githubusercontent.com/67532153/193491492-ba714ba0-4f58-466c-bd21-0e7840ee786b.mp4

**Comment by gwolf2u** [comment]
@raystef66 can you confirm?

**Comment by raystef66** [comment]
> @raystef66 can you confirm?

Tested rn and no issues. Never had blank one tbh.
Advise : Clean flash recommended and do follow flash instructions on XDA.
If issue persist ask in group https://t.me/crdroidmi9

**Comment by eadyo** [comment]
Let me be clear, it doesn't always happen. I can provide you some logs later today. There was 1 other guy on discord who confirmed this issue too.

**Comment by eadyo** [comment]
![Screenshot_20221005-135010_crDroid Home](https://user-images.githubusercontent.com/109316496/194054744-cb6c47b6-0eef-401f-a42e-fe1863bc24ac.png)
This time I tested it different way there was crDroid Home popping up. I don't have any other launcher installed btw.

**Comment by raystef66** [comment]
Let me again be clear as well :  I don(t have the issue and refer to my previous answer above.
