### ISSUE TITLE
bug: Notification Qs lag

### ISSUE THREAD

**Issue by shethk94** [crdroidandroid/issue_tracker#120]
### Issue type

User interface

### Device

Beryllium 

### crDroid version

crDroid 9

### Exact version / Build date

9.1/Fri Feb  3 00:09:34 EET 2023

### Bug description

While Swiping down notification panel it lags a bit.
Mostly when there is lots of notifications or some running notification like downloading/uploading or some processing.
Also after swiping up from lock screen and from hole screen you swipe down notification panel it lags.

### Steps to reproduce

Just swipe down from Home screen.

### Relevant log (logcat/build log)

```shell
No logs
```

### Screenshots or videos

![Screenshot_20230207-090821_crDroid Home](https://user-images.githubusercontent.com/87633083/217142306-52923966-5af6-4673-a432-0db221fd53e4.png)

### Solution

Awaken is most stable you can check it's github for most issues.

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unfortunately there's no way to fix what Google broke starting with Material You
