### ISSUE TITLE
bug: Error in mobile data and Wifi in apps

### ISSUE THREAD

**Issue by CrazyBytesVE** [crdroidandroid/issue_tracker#124]
### Issue type

Feature not working as intended

### Device

Miatoll

### crDroid version

crDroid 9

### Exact version / Build date

9.1/2023-01-25

### Bug description

There are times when some apps randomly stop having Internet and you have to enter their settings and deactivate/reactivate the Wi-Fi switches or mobile data. It happens randomly, with no apparent fixed cause. It is more frequent with Play Store, but fails in other apps. 

### Steps to reproduce

seems that it happens when you change from Wifi to mobile or another wifi

### Relevant log (logcat/build log)

It was not possible to attach the logcat, it exceeds the limit of 65536 characters. It can be downloaded from https://drive.google.com/file/d/1-9zad4-iSyyo2bzICbmP4IGD_XVgknKC/view?usp=drivesdk

### Screenshots or videos

![IMG_20230211_185612_970](https://user-images.githubusercontent.com/16071024/218284566-ec574576-2dd1-4176-abfa-5f97573e374d.jpg)
![IMG_20230211_185612_999](https://user-images.githubusercontent.com/16071024/218284569-92177bb5-3dc0-4707-9ec1-9fbc1f67bf2a.jpg)

### Solution

Turn off and back on Mobile Data or Wi-Fi in the app in question

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
I can't confirm this one
might be device specific or some other issue related to gapps
