### ISSUE TITLE
quick settings: clock text could be hard to read in landscape mode when switching to light theme

### ISSUE THREAD

**Issue by zhmars** [crdroidandroid/issue_tracker#126]
### Issue type

User interface

### Device

Redmi Note 7 (lavender)

### crDroid version

crDroid 9

### Exact version / Build date

9.1 / 2023-02-10

### Bug description

When switching to light theme and landscape mode, the clock text in quick settings is white, which make it hard to read.

### Steps to reproduce

- Switch to light theme (Go to Settings and disable `Dark theme`)
- Open Gallery/Messaging app (no issue with Phone/Calculator/Settings apps)
- Rotate device in landscape
- Pull down QS panel

### Relevant log (logcat/build log)

```shell
*No response*
```

### Screenshots or videos

![Screenshot_20230212-155652_Gallery](https://user-images.githubusercontent.com/18466397/218308867-39e7c163-829c-45a1-aa6a-851bb0883bf2.png)

### Additional context

I'm **not** running latest version (9.1 / 2023-02-12), but the issue should still present as no related commits try to fix it.

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
![photo_2023-04-07_19-56-42](https://user-images.githubusercontent.com/877292/230647480-87cfdcd2-f333-4703-810a-24c1c5e3de38.jpg)
