### ISSUE TITLE
quick settings: CPU Info tile show wrong temp

### ISSUE THREAD

**Issue by zhmars** [crdroidandroid/issue_tracker#127]
### Issue type

User interface

### Device

Redmi Note 7 (lavender)

### crDroid version

crDroid 9

### Exact version / Build date

9.1 / 2023-02-10

### Bug description

CPU Info tile shows wrong temp on my device, but apps like [SmartPack/SmartPack-Kernel-Manager](https://github.com/SmartPack/SmartPack-Kernel-Manager) and [Grarak/KernelAdiutor](https://github.com/Grarak/KernelAdiutor) have no such issue.

### Steps to reproduce

- Pull down QS panel
- Enable CPU Info tile

### Relevant log (logcat/build log)

```shell
No response
```

### Screenshots or videos

![Screenshot_20230212-171133_crDroid Home](https://user-images.githubusercontent.com/18466397/218310417-ced490b0-cb66-41c8-8cdd-7f4f4dce29cf.png)

![Screenshot_20230212-171427_SmartPack-Kernel Manager](https://user-images.githubusercontent.com/18466397/218310457-7618b6d0-6a1a-47b5-b668-8e717f2ebd89.png)

### Additional context

I'm **not** running latest version (9.1 / 2023-02-12), but the issue should still present as no related commits try to fix it.

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
@Prashant-1695 fix via commit
https://github.com/crdroidandroid/android_device_oneplus_sm8350-common/commit/ea3a98a0ea392d82151534db6df95a5f51a19a4c
