### ISSUE TITLE
Launcher3: memory info in recent view is not consistent with the info in Developer options

### ISSUE THREAD

**Issue by zhmars** [crdroidandroid/issue_tracker#129]
### Issue type

User interface

### Device

Redmi Note 7 (lavender)

### crDroid version

crDroid 9

### Exact version / Build date

9.1 / 2023-02-10

### Bug description

It is not a bug actually, but I think it is good to make the info more consistent :)

The memory info in recent view showed `767 MB Available | 3 GB Total` on my device. But `2.9 GB` total memory was shown in `Developer options -> Memory` and `572 MB` free memory was shown in `Running services`. There are also some commits we may consider to cherry-pick:

https://github.com/ricedroidOSS/android_packages_apps_Launcher3/commit/53816f71fad340f57cb0203746859a4ce1fc2c5b
https://github.com/ricedroidOSS/android_packages_apps_Launcher3/commit/b87e962c76eeb5fc8fced1bc1feaf00080eaea90
https://github.com/ricedroidOSS/android_packages_apps_Launcher3/commit/c1d051e4cb7c10944fca1bf395c7ec1d34ccf956

### Steps to reproduce

- Go to Home settings and enable `Memory info` in recent view
- Check to memory info in recent view and `Developer options`

### Relevant log (logcat/build log)

```shell
No response
```

### Screenshots or videos

![Screenshot_20230212-154322_crDroid Home](https://user-images.githubusercontent.com/18466397/218323324-a859963a-503e-4f2f-9965-584e4ca6762b.png)

### Additional context

I'm not running latest version (9.1 / 2023-02-12), but the issue should still present as no related commits try to fix it.

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
one in launcher shows without cache
cached memory is still free to use memory so calculation is not bad
