### ISSUE TITLE
bug: Bluetooth enables by itself

### ISSUE THREAD

**Issue by Amby713** [crdroidandroid/issue_tracker#13]
### Issue type

Feature not working as intended

### Device

Xiaomi m10t (apollo)

### crDroid version

crDroid 8

### Bug description

When I pull the quick settings and disable Bluetooth, it automatically enables itself after a certain duration. I'm not sure exactly how long, but I disabled my bt so that I could just navigation and hear it on my phone, it turned on and I didn't realize it. It connected to my car and went silent and I missed my exit
Had to disable bt again and keep checking to see that it's disabled while driving.

Happened on crdroid 7.x and 8.x

### Steps to reproduce

Disable Bluetooth
User phone normally
Bluetooth automatically re-enables itself

### Relevant log (logcat/build log)

```shell
N/A
```

### Solution

None

### Additional context

None

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
log needed
