### ISSUE TITLE
Messaging: message operation icons are hard to distinguish in light theme

### ISSUE THREAD

**Issue by zhmars** [crdroidandroid/issue_tracker#130]
### Issue type

User interface

### Device

Redmi Note 7 (lavender)

### crDroid version

crDroid 9

### Exact version / Build date

9.1 / 2023-02-10

### Bug description

When switching to light theme, the selected message operation icons at the upper right corner are hard to distinguish.

### Steps to reproduce

- Go to display settings and disable `Dark theme`
- Open Messaging app and select a message
- Check operation icons at the upper right corner

### Relevant log (logcat/build log)

```shell
No response
```

### Screenshots or videos

![Screenshot_20230212-234158_短信](https://user-images.githubusercontent.com/18466397/218324130-f5428341-97ae-460f-9479-601e6c9c0bfb.png)

### Additional context

I'm not running latest version (9.1 / 2023-02-12), but the issue should still present as no related commits try to fix it.

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ShevT** [comment]
I can't reproduce

**Comment by zhmars** [comment]
> I can't reproduce

Thanks for reply. Would you mind to post a screenshot?

It can only be reproduced on **a selected message** (not a selected conversation) in **light theme**.

screenshot for a selected conversation
![2023-03-03_19-27](https://user-images.githubusercontent.com/18466397/222711938-a5823e04-51ce-401d-82d4-4e67ead8cef8.png)

screenshot for a selected message
![2023-03-03_19-28](https://user-images.githubusercontent.com/18466397/222711953-cb4337c5-8514-402e-9d1a-0bdd95d3520a.png)

**Comment by ShevT** [comment]
I confirm

**Comment by DarkJoker360** [comment]
![photo_2023-05-15_11-38-07](https://github.com/crdroidandroid/issue_tracker/assets/31246543/65528b91-edcc-4618-8bf7-edd1802728d7)


Fixed: https://github.com/crdroidandroid/android_packages_apps_Messaging/commit/24035b783902ed424dfbd9c278421ba1df5b6435
