### ISSUE TITLE
Lockscreen weather icon position

### ISSUE THREAD

**Issue by Yuko-sa** [crdroidandroid/issue_tracker#132]
### Issue type

User interface

### Device

Gram ( miatoll)

### crDroid version

crDroid 9

### Exact version / Build date

20230125

### Bug description

Lockscreen weather appears at the same line with date and the same goes for alarm and dnd icon.  And also weather icon only shows white colour even when using weather icon pack.
This issue wasn't there in CR droid 8.

### Steps to reproduce

.

### Relevant log (logcat/build log)

```shell
None
```

### Screenshots or videos

Screenshot 1

![IMG_20230215_234710_561](https://user-images.githubusercontent.com/121550441/219119337-33f64282-ab90-4efb-b0bd-734611a981fa.jpg)

Screenshot 2
![IMG_20230215_234707_664](https://user-images.githubusercontent.com/121550441/219119422-c5f6acb7-6919-476e-9a37-04f87fab5655.jpg)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
Both implementation are different. Not a bug.
