### ISSUE TITLE
NAV BAR layout crossed

### ISSUE THREAD

**Issue by Moya78** [crdroidandroid/issue_tracker#133]
### Issue type

User interface

### Device

Alioth 

### crDroid version

crDroid 9

### Exact version / Build date

9.2/15-02/2023

### Bug description

"Normal" spacing is swapped with "Compact" spacing. 

### Steps to reproduce

CrDroid settings - Navigation - layout
Check Navbar spacing:
- Normal selection renders compact spacing
- compact selection renders normal spacing 

### Relevant log (logcat/build log)

```shell
N/A
```

### Solution

Swap them back

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment]
Afaik you're the one using Nova launcher. So can't comment on this as not stock launcher. 
@gwolf2u what do you think about this?

**Comment by Moya78** [comment]
I was using Nova on all previous builds. There was no issues. Its started on 15-02 build only

**Comment by gwolf2u** [comment]
no such issue here
just tried
