### ISSUE TITLE
Abnormal battery drain caused by "getWifiLinkLayerStats_1_3_Internal(l.1153)" bug

### ISSUE THREAD

**Issue by Andrea-1693** [crdroidandroid/issue_tracker#135]
### Issue type

Source code related

### Device

Redmi Note 8 Pro (begonia)

### crDroid version

crDroid 9

### Exact version / Build date

9.2 / 2023-02-15

### Bug description

When the phone is connected to the wifi network we experience an unusual acceleration in battery discharge, even when the phone is in an idle state.

MatLog detects this error every 3 seconds:
E/WifiVendorHal(1292): getWifiLinkLayerStats_1_3_Internal(l.1153) failed {.code = ERROR_NOT_SUPPORTED, .description = }

When the phone is not connected to the wifi network (even just out of coverage, without disabling) and is only connected to the mobile network, the battery discharge returns to normal and the error disappears.

### Steps to reproduce

Coming from the latest firmware (V12.5.15.0.RGGEUXM), simply do a clean install of crDroid 9.2 (with or without NikGApps Basic, it doesn't change). Already after the first start, just connect the phone to the wifi network and MatLog immediately detects the error.

### Relevant log (logcat/build log)

```shell
...

02-19 13:16:54.669 E/WifiVendorHal(1292): getWifiLinkLayerStats_1_3_Internal(l.1153) failed {.code = ERROR_NOT_SUPPORTED, .description = }

02-19 13:16:57.697 E/WifiVendorHal(1292): getWifiLinkLayerStats_1_3_Internal(l.1153) failed {.code = ERROR_NOT_SUPPORTED, .description = }

02-19 13:17:00.720 E/WifiVendorHal(1292): getWifiLinkLayerStats_1_3_Internal(l.1153) failed {.code = ERROR_NOT_SUPPORTED, .description = }

...
```

### Screenshots or videos

![Screenshot_20230219-124124_crDroid Home](https://user-images.githubusercontent.com/125914793/220184684-800d6363-7843-4530-a73d-6067ab2dad60.png)

1. Phone in idle state connected to the wifi network (MatLog error present).
2. Phone in use and various tests carried out to understand if the error causes stability/speed problems of wifi connection.
3. Phone in idle state connected to mobile (4G) network (MatLog error not present).
4. Phone in idle state reconnected to the wifi network (MatLog error present).

### Solution

This is not a solution but just disconnect the phone from wifi (even just out of coverage, without disabling) and connect to mobile (4G) network, the error goes away and the battery drain goes back to normal.

### Additional context

This issue was not present in crDroid 9.1 (but there is a more serious battery drain due to the SafetyNet error fixed in this version)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DarkJoker360** [comment]
Hi, thanks for reporting. It will be solved in the next update.
