### ISSUE TITLE
Allow independent configuration of app drawer icon grid

### ISSUE THREAD

**Issue by ripple404** [crdroidandroid/issue_tracker#136]
### Issue type

User interface

### Device

OnePlus 6 (enchilada)
OnePlus 6T (fajita)

### crDroid version

crDroid 9

### Exact version / Build date

9.2/2023-02-23

### Bug description

Stock launcher used to have the option to configure the icon grid for app drawer independently on crDroid 8 but it doesn't anymore on crDroid 9. Would be nice to have that back.

### Steps to reproduce

Only one grid configurable on Wallpaper and Styles and it's for home screen

### Relevant log (logcat/build log)

```shell
No log
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ripple404** [comment]
I didn't know if this was a feature request or bug, but the only flag available was 'bug', so I used that.

**Comment by gwolf2u** [comment]
for now no plans for that
