### ISSUE TITLE
hold home button to take screen shoot not working if disabled (hold  home for assistant)

### ISSUE THREAD

**Issue by Bazaleem** [crdroidandroid/issue_tracker#137]
### Issue type

Feature not working as intended

### Device

redmi note 9 pro (joyeuse)

### crDroid version

crDroid 9

### Exact version / Build date

9.1

### Bug description

cannot edit home button to do action like taking screen shoot (if disable hold home for assistant )

https://user-images.githubusercontent.com/126260641/221242385-3af17b54-45ed-4a88-83da-ec6f44c8013e.mp4

### Steps to reproduce

record a video

### Relevant log (logcat/build log)

```shell
...
```

### Screenshots or videos

https://user-images.githubusercontent.com/126260641/221240829-b2da37eb-1521-4493-9425-e40a49ba72f1.mp4

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
so what is the exact issue here?
