### ISSUE TITLE
bug: usb

### ISSUE THREAD

**Issue by yhulier** [crdroidandroid/issue_tracker#139]
### Issue type

Feature not working as intended

### Device

Redmi note 8 pro

### crDroid version

crDroid 9

### Exact version / Build date

TQ1A.230205.002

### Bug description

Es When connecting to a computerIt is difficult to choose a data transfer mode, because from the pop-up menu you cannot select any options. 

### Steps to reproduce

Step 1, This happens when the cell is connected to a computer

### Relevant log (logcat/build log)

```shell
Sorry I Cant
```

### Screenshots or videos

![Screenshot_20230225-193852_Configuración](https://user-images.githubusercontent.com/96425511/221384527-8959fede-2123-408a-9065-4ae5f9c747b8.png)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DarkJoker360** [comment]
This is not happening to me, I can normally choose any option. Any more details about your setup? thanks.
