### ISSUE TITLE
bug: freezing on home screen

### ISSUE THREAD

**Issue by pepestepanek** [crdroidandroid/issue_tracker#140]
### Issue type

User interface

### Device

MI9T Pro (raphael)

### crDroid version

crDroid 9

### Exact version / Build date

2023-02-15

### Bug description

For the last 2 days the phone has been randomly freezing when I quit apps. It stays on the home screen and is unresponsive. Only rebooting via power + volume down helps.

### Steps to reproduce

Try opening and closing applications.

### Relevant log (logcat/build log)

```shell
I don't, matlog doesn't have logs before rebooting the device.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by pepestepanek** [comment]
The phone keeps freezing. Today it happened that after freezing and then connecting to the charger the phone started to respond. I am attaching the MatLog output.
[logs-2023-02-28-20-09-18.zip](https://github.com/crdroidandroid/issue_tracker/files/10853994/logs-2023-02-28-20-09-18.zip)

**Comment by gwolf2u** [comment]
what mods you have installed?
need logs from /data/anr/
