### ISSUE TITLE
bug: Requirement for READ_PRIVILEGED_PHONE_STATE permission makes applications unusable in certain cases

### ISSUE THREAD

**Issue by dmitrmax** [crdroidandroid/issue_tracker#141]
### Issue type

Source code related

### Device

This is observed on markw, but as code show it is applicaple to any device on crDroid in general

### crDroid version

crDroid 9

### Exact version / Build date

9.1

### Bug description

Hi!

I was investigating issue why many messengers with audio calls failed to produce ringtone on incoming call. I found that problem is in condition on this [line](https://github.com/crdroidandroid/android_packages_services_Telecomm/blob/b3eb0bf65a28619a3e8d4952f0d608e1ce179a2b/src/com/android/server/telecom/TelecomServiceImpl.java#L155).

Specificaly Telegram messenger fails to produce ringtone with the stack trace attached to the issue.

There is also the same issue in bug tracker of KDE https://bugs.kde.org/show_bug.cgi?id=456515 were one of the users reports that according to Android documentation this permission is not needed.

Also the same https://github.com/signalapp/Signal-Android/issues/9494 in Signal. Also it was reported against LineageOS, the same applies to crDroid.

### Steps to reproduce

Install Telegram message, sign in, make an incoming call from the other account.

### Relevant log (logcat/build log)

```shell
23_02_2023_20_23_05 D/tmessages: == Call 600003513817540173 state changed to 15 ==
23_02_2023_20_23_05 E/tmessages: java.lang.SecurityException: getDefaultOutgoingPhoneAccount: Neither user 10301 nor current process has android.permission.READ_PRIVILEGED_PHONE_STATE.
23_02_2023_20_23_05 E/tmessages: android.os.Parcel.createExceptionOrNull(Parcel.java:3028)
23_02_2023_20_23_05 E/tmessages: android.os.Parcel.createException(Parcel.java:3012)
23_02_2023_20_23_05 E/tmessages: android.os.Parcel.readException(Parcel.java:2995)
23_02_2023_20_23_05 E/tmessages: android.os.Parcel.readException(Parcel.java:2937)
23_02_2023_20_23_05 E/tmessages: com.android.internal.telecom.ITelecomService$Stub$Proxy.getUserSelectedOutgoingPhoneAccount(ITelecomService.java:1492)
23_02_2023_20_23_05 E/tmessages: android.telecom.TelecomManager.getUserSelectedOutgoingPhoneAccount(TelecomManager.java:1138)
23_02_2023_20_23_05 E/tmessages: android.media.RingtoneManager.getDefaultPhoneAccountHandle(RingtoneManager.java:906)
23_02_2023_20_23_05 E/tmessages: android.media.RingtoneManager.getCacheForType(RingtoneManager.java:1067)
23_02_2023_20_23_05 E/tmessages: android.media.MediaPlayer.setDataSource(MediaPlayer.java:1084)
23_02_2023_20_23_05 E/tmessages: android.media.MediaPlayer.setDataSource(MediaPlayer.java:1023)
23_02_2023_20_23_05 E/tmessages: org.telegram.messenger.voip.VoIPService.startRingtoneAndVibration(VoIPService.java:2933)
23_02_2023_20_23_05 E/tmessages: org.telegram.messenger.voip.VoIPService.startRingtoneAndVibration(VoIPService.java:3331)
23_02_2023_20_23_05 E/tmessages: org.telegram.messenger.voip.VoIPService.showIncomingNotification(VoIPService.java:4043)
23_02_2023_20_23_05 E/tmessages: org.telegram.messenger.voip.VoIPService.startRinging(VoIPService.java:3310)
23_02_2023_20_23_05 E/tmessages: org.telegram.messenger.voip.VoIPService.lambda$acknowledgeCall$11(VoIPService.java:1057)
23_02_2023_20_23_05 E/tmessages: org.telegram.messenger.voip.VoIPService.$r8$lambda$LjPk8Bl_hES2PdVSGhWtLvR1mEw(Unknown Source:0)
23_02_2023_20_23_05 E/tmessages: org.telegram.messenger.voip.VoIPService$$ExternalSyntheticLambda47.run(Unknown Source:8)
23_02_2023_20_23_05 E/tmessages: android.os.Handler.handleCallback(Handler.java:942)
23_02_2023_20_23_05 E/tmessages: android.os.Handler.dispatchMessage(Handler.java:99)
23_02_2023_20_23_05 E/tmessages: android.os.Looper.loopOnce(Looper.java:201)
23_02_2023_20_23_05 E/tmessages: android.os.Looper.loop(Looper.java:288)
23_02_2023_20_23_05 E/tmessages: android.app.ActivityThread.main(ActivityThread.java:7872)
23_02_2023_20_23_05 E/tmessages: java.lang.reflect.Method.invoke(Native Method)
23_02_2023_20_23_05 E/tmessages: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
23_02_2023_20_23_05 E/tmessages: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:946)
23_02_2023_20_23_05 D/tmessages: Showing incoming call notification
```

### Solution

Weaken the permission requirements as READ_PRIVILEGED_PHONE_STATE permission is not required in this place according to official Android documentation.

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this happens with different secondary user ?

**Comment by dmitrmax** [comment]
No, this happens with the primary user. I haven't tried it with the secondary user.

**Comment by gwolf2u** [comment]
this happening on cr 9.3?

**Comment by dmitrmax** [comment]
9.3 is not yet available for my gadget.

**Comment by gwolf2u** [comment]
can you provide full log on this one?
