### ISSUE TITLE
bug:  No calling beep sound and vibration on connect not working

### ISSUE THREAD

**Issue by Reveral6** [crdroidandroid/issue_tracker#142]
### Issue type

User interface

### Device

Redmi note 7 lavender

### crDroid version

crDroid 9

### Exact version / Build date

9.2  2023-02-19

### Bug description

When I call someone, there is no call tone. I don't realize that someone is picking up the phone.  Also not working this vibration on connect settings.
Update: Turning off volte and wifi call over solves the problem. but volte is not used 

### Steps to reproduce

Go to the dialer and call someone. 

### Relevant log (logcat/build log)

```shell
.
```

### Screenshots or videos

![photo_2023-03-02_01-37-00](https://user-images.githubusercontent.com/126367482/222281267-deb4a1b9-fd98-48e6-a0e2-d7ee3db419d9.jpg)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
call tone is due to old blobs on newer android revision @Prashant-1695

**Comment by Reveral6** [comment]
> call tone is due to old blobs on newer android revision @Prashant-1695
I wanted to say, I can't hear this sound when calling someone. with any rom.  youtu.be/664iWMLW4pE
 _vibration it worked with other rom but crdroid same_

**Comment by Reveral6** [comment]
> call tone is due to old blobs on newer android revision @Prashant-1695

any solution ?

**Comment by gwolf2u** [comment]
> > call tone is due to old blobs on newer android revision @Prashant-1695
> 
> any solution ?

Why not wait for a reply
Don't get pushy

**Comment by Prashant-1695** [comment]
calling sound works fine, vibration seems dead i will check it ASAP
