### ISSUE TITLE
Inconsistent media audio levels +  distortion on high volume

### ISSUE THREAD

**Issue by NotNorom** [crdroidandroid/issue_tracker#144]
### Issue type

User interface

### Device

Xiaomi Poco X3 Pro (vayu, m2102j20si)

### crDroid version

crDroid 9

### Exact version / Build date

9.2/2023-02-22

### Bug description

A 2-in-1:

Part 1:
Media volume changes randomly. Foe example even on the lowest volume setting it suddenly ramps up to full volume over the course of 1-2 seconds.
And this happens multiple times per minute. Calls do not seem to be affected.
It feels like there is some sort of audio compression/ compensation going on.
This makes it impossible to listen to any video or voice message.

Part 2:
When media volume is set to maximum, audio is SO loud that it just clips and distorts completely. Something that the device has not done on stock or other ROMs.

### Steps to reproduce

Clean install of ROM, play any audio.

### Relevant log (logcat/build log)

```shell
Sorry about the pastebin, logcat was too long to submit.

https://pastebin.com/CT9HDkSm

https://pastebin.com/raw/CT9HDkSm
```

### Additional context

firmware: fw_vayu_miui_VAYUGlobal_V14.0.1.0.TJUMIXM_050c24042a_13.0
recovery: OrangeFox-vayu-stable@R11.1_3_A12 (currently latest for my device)
gapps: NikGapps-basic-arm64-13-20230301-signed
gapps addons: NikGapps-Addon-13-SetupWizard-20230301-signed

During the logcat output, I was running firefox, playing a youtube video and changing the volume.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
@NotNorom A test build has been posted in vayu test group on telegram.
Ping me on telegram, will get you added.

**Comment by NotNorom** [comment]
Pinged!
And just wanted to add that I am also noticing similar behavior as described in #82 where notifications are played at a high volume even when set to the lowest possible setting.
