### ISSUE TITLE
bug: parked call cause beep beep (With log)

### ISSUE THREAD

**Issue by lindahl85** [crdroidandroid/issue_tracker#145]
### Issue type

Feature not working as intended

### Device

Oneplus 8t (kebab) + oneplus 9 (lemonade) + Oneplus 9 pro (lemonadep)

### crDroid version

crDroid 9

### Exact version / Build date

crDroidAndroid-13.0-20230119-kebab-v9.1
crDroidAndroid-13.0-20230505-lemonadep-v9.5

### Bug description

When call waiting is active, a beep beep tone can be heard when a second person calls. That's correct.

But if you are in a call and the other person parks your call it will trigger this too which is totally wrong and very annoying. Both my oneplus 9 and 8t have this now. It has never been seen on crdroid but started sometime on crdroid 9. Crdroid 8 never had that issue. 

Log added.
[parked call logs-2023-03-05-10-42-13.zip](https://github.com/crdroidandroid/issue_tracker/files/10921631/parked.call.logs-2023-03-05-10-42-13.zip)

### Steps to reproduce

Make a call. Let the person you talk with park the call. Now you will hear beep-beep.

### Relevant log (logcat/build log)

```shell
Zipfile is added in bug description
```

### Additional context

Related to this but the reply is incorrect.
https://github.com/crdroidandroid/issue_tracker/issues/101

It is not related to Android 13 since other A13 devices doesn´t have it. It´s related to Crdroid 9.x

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by lindahl85** [comment]
The issue is still active in:
crDroidAndroid-13.0-20230406-kebab-v9.3

**Comment by lindahl85** [comment]
I bough a new Oneplus 9 pro and tested this unrooted with stock oxygen os android 13 and notice that the issue exists there. So how is it possible that an issue that exists on Oxygen OS can exist on crDroidAndroid-13.0-20230505-lemonadep-v9.5 too?

**Comment by lindahl85** [comment]
New log when the beeping can be heard on Oneplus 9 pro, crdroid 9.5, firmware F21.
[Parked call.txt](https://github.com/crdroidandroid/issue_tracker/files/11501132/Parked.call.txt)

**Comment by lindahl85** [comment]
Some new test. Swedish operator "Hallon" have been compared with "Telenor". No difference can be seen when different operators is used.
Issue is seen on stock and rooted with:
Oneplus 9 Pro 13.1.0.500(EX01) Firmware
crDroidAndroid-13.0-20230609-lemonadep-v9.5

Issue is not seen on OnePlus 8T with Crdroid 9 or Oxygen OS 13.1

The issue is isolated to the devices Oneplus 9 and Oneplus 9 Pro.

**Comment by gwolf2u** [comment]
this is a #nofix

**Comment by lindahl85** [comment]
> this is a #nofix

Accepted since it can be seen on a stock Oneplus 9/9 Pro too.

**Comment by lindahl85** [comment]
The issue Comes from the Google phone app according to OnePlus support. I just tested it and version 72.1 doesn't have the issue. 

![Screenshot_2023-08-03-20-31-08-80_fc704e6b13c4fb26bf5e411f75da84f2](https://github.com/crdroidandroid/issue_tracker/assets/20877425/b39f8611-f2f8-4c70-b384-cdb6045d308f)
