### ISSUE TITLE
device_lavender: no smart charging

### ISSUE THREAD

**Issue by zhmars** [crdroidandroid/issue_tracker#147]
### Issue type

User interface

### Device

Redmi Note 7 (lavender)

### crDroid version

crDroid 9

### Exact version / Build date

9.2 / 2023-02-19

### Bug description

If I understand correctly, this feature should be visible after adding related overlay config (https://github.com/crdroidandroid/android_vendor_crDroidOTA/commit/5d87da91fd52bf56178087f12577a71c7800637d). But there are no such settings (`crDroid Settings -> Miscellaneous`).

Commit https://github.com/crdroidandroid/android_device_xiaomi_lavender/commit/eff00603df0a21a0c0b58500934ae24be7c08c62 tried to enable this feature, but the config was added to `overlay-lineage/frameworks/base/packages/SystemUI/res/values/config.xml`. According to [the document](https://github.com/crdroidandroid/android#41-crdroid-features--overlays), it should be `overlay-lineage/frameworks/base/core/res/res/values/config.xml` since it is frameworks based.

### Steps to reproduce

No response

### Relevant log (logcat/build log)

```shell
No response
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
@Prashant-1695 still planning to add it?
