### ISSUE TITLE
Features: unlimited call log

### ISSUE THREAD

**Issue by Izorkin** [crdroidandroid/issue_tracker#15]
### Issue type

Other

### Device

Mi 9T (Davinci)

### crDroid version

crDroid 8

### Bug description

Add an option to remove the limit of 500 entries in the call log

### Steps to reproduce

None

### Relevant log (logcat/build log)

```shell
None
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is by design
