### ISSUE TITLE
bug: Dock icons misplaced

### ISSUE THREAD

**Issue by MohammedEttahir** [crdroidandroid/issue_tracker#150]
### Issue type

User interface

### Device

POCO X3 Pro (vayu)

### crDroid version

crDroid 9

### Exact version / Build date

crDroid 9.2 / 2023-02-23

### Bug description

When disabling the Google searchbar in the home screen, the dock icons do not go down as intended

### Steps to reproduce

Step 1. Go to crDroid Home settings
Step 2. Disable the Google search bar
Step 3. Return the the home screen

### Relevant log (logcat/build log)

```shell
N/A
```

### Screenshots or videos

![image](https://user-images.githubusercontent.com/104869780/224836432-6d51aace-fd83-48bd-a7cb-bf9df4576ab4.png)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
happening on crDroid 9.3 ?

**Comment by MohammedEttahir** [comment]
Yes, the empty space below the dock is still present on crDroid 9.3.  From: Lup GabrielSent: Friday, April 7, 2023 18:31To: crdroidandroid/issue_trackerCc: MohammedEttahir; AuthorSubject: Re: [crdroidandroid/issue_tracker] bug: Dock icons misplaced (Issue #150) happening on crDroid 9.3 ?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by MohammedEttahir** [comment]
Yes, the empty space below the dock is still present on crDroid 9.3.

**Comment by gwolf2u** [comment]
unfortunately search bar has predefined space needed, reason icons won't move down
for now there's no fix for our current launcher
