### ISSUE TITLE
bug: Colors faded when switching between 60/90hz

### ISSUE THREAD

**Issue by Bartixxx32** [crdroidandroid/issue_tracker#152]
### Issue type

Other

### Device

Gm1913 (guacamole) (europe)

### crDroid version

crDroid 9

### Exact version / Build date

9.2/2023-03-17 
(It was always an issue, i started with crdroid 9.0 and issue was there)

### Bug description

90hz refreshrate mode is making whole screen to fade a bit of greenish, hard to describe but its easily noticable when toggling between modes or set as automatic, the green going a bit greenish and colors fading

### Steps to reproduce

Toggle between refreshrates

### Relevant log (logcat/build log)

```shell
in JobStore: 5d5be35 #u0a297/1034 com.google.android.apps.photos/com.google.android.libraries.social.mediamonitor.MediaMonitorJobSchedulerService
03-18 07:23:24.428 D/vendor.qti.vibrator(1127): QTI Vibrator off
03-18 07:23:24.433 W/UriGrantsManagerService(1780): No permission grants found for com.google.android.apps.photos
03-18 07:23:24.435 I/MediaSyncManager_4807_4895(4807): SettingsContentObserver onChange false
03-18 07:23:24.437 I/DisplayDevice(1162): Display 4630946797824131201 policy changed
03-18 07:23:24.437 I/DisplayDevice(1162): Previous: {{defaultModeId=1, allowGroupSwitching=false, primaryRange=[90.00 Hz, 90.00 Hz], appRequestRange=[0.00 Hz, 90.00 Hz]}}
03-18 07:23:24.437 I/DisplayDevice(1162): Current:  {{defaultModeId=0, allowGroupSwitching=false, primaryRange=[60.00 Hz, 90.00 Hz], appRequestRange=[0.00 Hz, 90.00 Hz]}}
03-18 07:23:24.437 I/DisplayDevice(1162): 1 mode changes were performed under the previous policy
03-18 07:23:24.438 W/UriGrantsManagerService(1780): No permission grants found for com.google.android.apps.photos
03-18 07:23:24.443 D/vendor.qti.vibrator(1127): Vibrator perform effect 21
03-18 07:23:24.471 D/vendor.qti.vibrator(1127): Starting perform on another thread
03-18 07:23:24.536 D/vendor.qti.vibrator(1127): Notifying perform complete
03-18 07:23:24.567 E/sensors-hal(1074): handle_sns_std_sensor_event:74, wise_light: lux 18 ,period 7 ms, data c 0
03-18 07:23:24.603 I/vendor.qti.bluetooth@1.0-ibs_handler(1043): ProcessIbsCmd: Received IBS_WAKE_IND: 0xFD
```

### Screenshots or videos

Not visible on screemshots or video

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
happening with this build?
https://sourceforge.net/projects/crdroid/files/guacamole/9.x/crDroidAndroid-13.0-20230407-guacamole-v9.3.zip/download

**Comment by Bartixxx32** [comment]
> happening with this build?
> https://sourceforge.net/projects/crdroid/files/guacamole/9.x/crDroidAndroid-13.0-20230407-guacamole-v9.3.zip/download

Sorry for being late but as of 14 april build issue still exist, im gonna try reproduce that and attach video later if ill be able to get it using other phones camera

**Comment by Bartixxx32** [comment]
Video documentig the issue:

https://user-images.githubusercontent.com/16412925/232257987-b9acf34e-fdd0-4c67-975a-52bfd7e9c46b.mp4

**Comment by gwolf2u** [comment]
can you check on todays build
22.04.2023

**Comment by Bartixxx32** [comment]
Sorry for month of delay, im not checking my github often,

Sadly, on build "crDroidAndroid-13.0-20230521-guacamole-v9.5.zip" issue is still the same nothing changed.

**Comment by gwolf2u** [comment]
to be honest I still can't reproduce this one
might be panel related or some sort
a full log is needed if you can provide

**Comment by Bartixxx32** [comment]
Idk, if that helps but on op7pro crdroid telegram group i can find more users with issues like me, for example 

https://t.me/crDroidOP7Pro/113494

I guess it may be related to panel calibration, that oos reads? Or oos just switched refreshrate not noticable like crdroid does like switching to 60hz when not touching for some time,


Also i have looked at other roms commit history and found intresting thing in AOSPA repo, maybe can it be related?

https://github.com/AOSPA/android_device_oneplus_sm8150-common/commit/a551aec419ec429a9b7ca455209e04b7ad5c9b15

**Comment by Bartixxx32** [comment]
Video of issue (what i did when doing logs): https://www.youtube.com/watch?v=vS7wrGZ6QUc


Full logcat: [logcat.txt](https://github.com/crdroidandroid/issue_tracker/files/12135281/logcat.txt)
