### ISSUE TITLE
bug: System crash when using multiple users

### ISSUE THREAD

**Issue by newname-1** [crdroidandroid/issue_tracker#153]
### Issue type

Source code related

### Device

Miatoll, gram

### crDroid version

crDroid 9

### Exact version / Build date

10th March 2023

### Bug description

System crashing and taking way too much time to switch between users.

### Steps to reproduce

1.Go to settings
2. Enable multiple users.
3. Now pull down quick settings panel and switch user from qs user shortcut.

### Relevant log (logcat/build log)

```shell
Can't take log fully bcz it get dismissed when switching users.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
adb logcat needed

**Comment by newname-1** [comment]
> adb logcat needed

[Uploading multi users.txt…]()
Build date: Fri Apr  7 16:18:20 EEST 2023

And also navigation gestures stopes working until I open gestures option from settings.

**Comment by gwolf2u** [comment]
happening on new 9.6 release also?
