### ISSUE TITLE
Camera not using full resolution

### ISSUE THREAD

**Issue by ayushp2002** [crdroidandroid/issue_tracker#155]
### Issue type

Feature not working as intended

### Device

Redmi Note 9 Pro (miatoll)

### crDroid version

crDroid 9

### Exact version / Build date

9.2/2023-03-03

### Bug description

Rear main camera resolution is locked to 8MP in the Aperture camera app delivered with crDroid. It is also giving 8MP in a GCam port that I installed. "Open camera" installed from the play store is able to give full 12MP images from the camera.

The front camera is also locked at 4MP instead of 16MP in all the camera apps that I have tried including the stock one provided with crDroid.

### Steps to reproduce

Step 1. Click a photograph using the stock camera app on Redmi Note 9 Pro.
Step 2. Check image details to see the resolution.

### Relevant log (logcat/build log)

```shell
N/A
```

### Screenshots or videos

![Screenshot_20230330-150044_Photos_2](https://user-images.githubusercontent.com/31592771/228793980-7608e21d-de7e-4fe1-9867-1dc7ada0bda2.png)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is plain how OSS camera HAL works
