### ISSUE TITLE
SystemUpdate(3173): [Execution,ExecutionManager] warnning flood logcat and cause battery drain 

### ISSUE THREAD

**Issue by PonsAlex** [crdroidandroid/issue_tracker#156]
### Issue type

Other

### Device

Asus Zenfone5 ZE620kl X00QD

### crDroid version

crDroid 9

### Exact version / Build date

crDroid 9.2 /14/02/2023

### Bug description

Warning flood and battery drain 

### Steps to reproduce
Install OTP actualization

### Relevant log (logcat/build log)

```shell
03-30 20:44:12.257 W/SystemUpdate(3173): [Execution,ExecutionManager] Unable to create the action. Restart the execution from the scratch.
03-30 20:44:12.257 W/SystemUpdate(3173): java.lang.IllegalStateException
03-30 20:44:12.257 W/SystemUpdate(3173): 	at aamj.j(:com.google.android.gms@231115044@23.11.15 (190400-520109968):0)
03-30 20:44:12.257 W/SystemUpdate(3173): 	at celv.a(:com.google.android.gms@231115044@23.11.15 (190400-520109968):12)
03-30 20:44:12.257 W/SystemUpdate(3173): 	at com.google.android.gms.update.execution.InstallationIntentOperation.onHandleIntent(:com.google.android.gms@231115044@23.11.15 (190400-520109968):12)
03-30 20:44:12.257 W/SystemUpdate(3173): 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@231115044@23.11.15 (190400-520109968):2)
03-30 20:44:12.257 W/SystemUpdate(3173): 	at yhk.onHandleIntent(:com.google.android.gms@231115044@23.11.15 (190400-520109968):4)
03-30 20:44:12.257 W/SystemUpdate(3173): 	at gxu.run(:com.google.android.gms@231115044@23.11.15 (190400-520109968):3)
03-30 20:44:12.257 W/SystemUpdate(3173): 	at gxt.run(:com.google.android.gms@231115044@23.11.15 (190400-520109968):11)
03-30 20:44:12.257 W/SystemUpdate(3173): 	at dapd.run(:com.google.android.gms@231115044@23.11.15 (190400-520109968):2)
```

### Screenshots or videos

![Screenshot_20230330-210943_MatLog](https://user-images.githubusercontent.com/49562256/228994557-d1a3f8c5-977b-48c6-91ce-aa5e0c8486a4.png)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this seems to be rather a gapps issue
recommend clean flash with proper gapps (maybe nikgapps core?)

**Comment by PonsAlex** [comment]
Yes, i tested some Gapps packages like Nikki and MindTheGapps and this is probaly the cause. In resume i installed the atualization 9.3 with BiTGApps-arm64-13.0.0-v1.8 and solved the problem. Thanks!
