### ISSUE TITLE
bug: Pausar aplicación deja de funcionar 

### ISSUE THREAD

**Issue by zompi420** [crdroidandroid/issue_tracker#157]
### Issue type

Feature not working as intended

### Device

Redmi note 11

### crDroid version

crDroid 9

### Exact version / Build date

9.3

### Bug description

Al dejar presionado en una app para Pausar las notificaciones se detiene el proceso y no funciona 

### Steps to reproduce

Lo explicado anteriormente 

### Relevant log (logcat/build log)

```shell
?
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
English
