### ISSUE TITLE
bug: Microphone volume very low on cellular call speaker-phone

### ISSUE THREAD

**Issue by ayushp2002** [crdroidandroid/issue_tracker#159]
### Issue type

Feature not working as intended

### Device

Redmi Note 9 Pro (miatoll)

### crDroid version

crDroid 9

### Exact version / Build date

9.2/2023-03-03

### Bug description

When on a cellular phone call, the microphone is very loud and with a lot of background noise. When switching to speaker-phone, my voice is very low and high pitched. I'm sure that it is using the main microphone because I have to speak very close to it when on speaker-phone.
I other apps like WhatsApp and Discord, other people cannot hear me on a video call whereas they can hear me on an audio call(although with a lot of ambient noise), but that too only on the non-speaker mode.
The audio recorder app shows me 2 options "Phone mic" and "Redmi Note 10 Lite"(which is identified as an external microphone). Here only the "Phone mic" works and the other one does not record any sound.

P.S. The April patch is a lot more buggier and does not fix this issue.

### Steps to reproduce

Step 1. Make a phone call.
Step 2. The voice will be fine initially.
Step 3. Change to speaker mode.
Step 4. The voice will be inaudible.

### Relevant log (logcat/build log)

```shell
N/A
```

### Screenshots or videos

![Screenshot_20230403-165024_Recorder](https://user-images.githubusercontent.com/31592771/229495902-926929d3-554b-46fb-a291-8c884fc0fe27.png)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by popoA3M** [comment]
Fixed in latest 9.3 build
