### ISSUE TITLE
bug: shutdown menu not working properly

### ISSUE THREAD

**Issue by MARCOS752wh** [crdroidandroid/issue_tracker#16]
### Issue type

Feature not working as intended

### Device

Poco x3 pro (vayu) 
Model: M2102J20SI

### crDroid version

crDroid 8

### Bug description

when selecting the option to turn off in the shutdown menu, the phone turns off but turns on again as if it had been restarted and it is happening to me frequently

### Steps to reproduce

step 1- hold power button 

step2- select option turn off

 the device turns on as if it had been rebooted

### Relevant log (logcat/build log)

```shell
I can't find it because when I turn it on and search for it, it loads many logs
```

### Screenshots or videos

![Screenshot_20221005-013305_crDroid Home](https://user-images.githubusercontent.com/114353020/194006245-a6c7c355-2b31-48cd-a052-761c486e13a8.png)

### Solution

don't know

### Additional context

I hope you can fix it please, it's a very good rom, so you've really done an excellent job and well, a problem is also that when playing genshin impact the phone gets hotter than normal, I don't know if you could check that please since it's something that is reported to you but these days I have not had time to detail the error, an apology for the inconvenience

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by xNombre** [comment]
Probably caused by zram writeback

**Comment by MARCOS752wh** [comment]
I don't know bro

**Comment by neobuddy89** [comment]
@xNombre zram writeback is disabled.

@MARCOS752wh will check after i retrieve my device, it is still gone for repair ..

**Comment by MARCOS752wh** [comment]
You're fine bro I really understand, a question will a new update for the little x3 pro arrive? These days or is it stipulated for a longer time?

**Comment by MARCOS752wh** [comment]
[Uploading logcat.txt…]()

**Comment by MARCOS752wh** [comment]
The restart may appear here, well I turn it off and it always restarts and it is followed, that is, it does not turn off at all, it always turns on again

**Comment by MARCOS752wh** [comment]
[logcat.txt](https://github.com/crdroidandroid/issue_tracker/files/9947364/logcat.txt)

**Comment by MARCOS752wh** [comment]
https://user-images.githubusercontent.com/114353020/200207490-e4f07330-9c1f-4658-af0e-8a195c1b5942.mp4

**Comment by MARCOS752wh** [comment]
make a video so you can see it and it happens up to 6 times or sometimes 4 or more:/

**Comment by gwolf2u** [comment]
this happening on 8.10 ?

**Comment by xNombre** [comment]
A hint: check pstore/ramoops. This looks like kernel panic, logcat doesn't tell much.

**Comment by MARCOS752wh** [comment]
if it still happened in 8.10
