### ISSUE TITLE
Monet Theming Engine Regresion

### ISSUE THREAD

**Issue by KoremuMekuro** [crdroidandroid/issue_tracker#160]
With 9.3, firstly on redmi note 8t and then on poco f3 with second 9.3 update I noticed that monet theming options was changed and I can't have anymore vibrant colors.Only with proprietary repainter I can achive vibrant colors.Why that was changed?Is there any hope that old theming option will be returned?Or maybe there will be added options, so it will be possible to achive vibrant colors?

**Comment by neobuddy89** [comment]
describe more on "bad" results?

the old implementation didn't work as intended and color swatches in "Wallpaper & Style" didn't apply correctly.

**Comment by KoremuMekuro** [comment]
> describe more on "bad" results?
> 
> the old implementation didn't work as intended and color swatches in "Wallpaper & Style" didn't apply correctly.

By bad I mean washed, greish or text is grey and not white if luminance is less than 90 and.App folders are greish even if luminance is on 70, where qs and bg's are in their right colors.
But old implemantation worked fine on march 31st build of 9.3 for poco f3.

**Comment by Darshil-154** [comment]
> > describe more on "bad" results?
> > the old implementation didn't work as intended and color swatches in "Wallpaper & Style" didn't apply correctly.
> 
> By bad I mean washed, greish not vibrant or text is grey and not white if luminance is less than 90.App folders and app drawer are greish even if luminance is on 70 and not in the deep, darker variant of selected color as it was before, whereas qs and bg's are in their right deep, darker variant of selected color. But old implemantation worked fine on march 31st build of 9.3 for poco f3.And why then proprietary repainter works just fine(well, my only problem with it is that it's proprietary). It's bad looking for me only in dark mode, in light mode all looks fine and maybe even right, but I just love dark mode, because I feel pain in my eyes with light mode.

Same bro same issue i want to report about 'new' monet theming option

**Comment by KoremuMekuro** [comment]
> For now this is the way we can have custom colors Old implementation had more issues than fixes, so for now we keep what we have with the focus to improve when and where possible

So my only hope is on iconify or to roll back to 9.3 from march 31st or even to 9.2 for open source solution.Sad.

**Comment by KoremuMekuro** [comment]
> For now this is the way we can have custom colors Old implementation had more issues than fixes, so for now we keep what we have with the focus to improve when and where possible

I can say that tis 'new' implementation have more issues than fixes.For example luminance is affecting text, luminance at default 100 turnes any color to white and if both bg color and accent color enabled, then you'll get white as accent and grey as bg no matter what colors are selecten and niether chorma nor luminance will have any affect.

**Comment by Darshil-154** [comment]
> For now this is the way we can have custom colors Old implementation had more issues than fixes, so for now we keep what we have with the focus to improve when and where possible

No need to change monet pitch dark option is moved to dark mode 
![Screenshot_20230413-162505_Settings](https://user-images.githubusercontent.com/118457005/231737841-8e84985f-681d-408d-9e8d-1d12640c9f3b.png)
