### ISSUE TITLE
bug: Screenshot doesn´t always work

### ISSUE THREAD

**Issue by lindahl85** [crdroidandroid/issue_tracker#162]
### Issue type

Feature not working as intended

### Device

Kebab

### crDroid version

crDroid 9

### Exact version / Build date

crDroidAndroid-13.0-20230406-kebab-v9.3

### Bug description

Very strange issue that comes and go. Screenshot feature works sometimes but sometimes it stops to work. Then volume down + power gives the volume dialogue instead. It´s like the phone is missing the push on power button.

[logs-2023-04-08-11-06-30.zip](https://github.com/crdroidandroid/issue_tracker/files/11182873/logs-2023-04-08-11-06-30.zip)

### Steps to reproduce

Try to make a screenshot with volume down + power. Sometimes you get a screenshot and sometimes you don´t.

### Relevant log (logcat/build log)

```shell
See zip above.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
can't reproduce on any of my devices
@crdroidandroid/maintainers ant of you with same issue?

**Comment by jash69** [comment]
no issues here.

**Comment by iusmac** [comment]
Can't reproduce even on a 7 years old device with partially broken power button.

**Comment by masemoel** [comment]
I've never faced this lately. I'd point to a hardware issue instead...

**Comment by lindahl85** [comment]
That was strange. It started around crdroid 9.1

**Comment by lindahl85** [comment]
Now I can see it sometimes on lemonadep
crDroidAndroid-13.0-20230505-lemonadep-v9.5
It comes and go, it works some day like today so I can´t take a log. Like some other app interfere with the power button. Volume button responds. It is not a hardware issue on 3 different devices.
