### ISSUE TITLE
bug: microG installation fails on devices with dynamic partitions

### ISSUE THREAD

**Issue by staticnotdynamic** [crdroidandroid/issue_tracker#164]
### Issue type

Other

### Device

SPES

### crDroid version

crDroid 9

### Exact version / Build date

9.3/2023-04-02

### Bug description

After doing a clean ROM installation for crDroid 9.3, Installing microG through MinMicroG fails with the following error (refer to line 1164 in the attached logs):

```
Cleaning up...
Debloating
 
Doing size checks...
Pack size is 113
Free space in /mnt/system is 95
 
!!! FATAL ERROR: Not enough free space in your /mnt/system!
 
Stopping installation and Uninstalling...
umount: /system: Invalid argument
 
Installation failed!
```

Looking at https://github.com/FriendlyNeighborhoodShane/MinMicroG/issues/19 it seems the size of dynamic partition is the cause. The suggested solutions by MinMicroG developer were:
1. Flashing the  "Recovery SLAM Script" by osm0sis. For my case, flashing the script failed, causing more issues. I had to wipe my data
2. Reserve more space in the `system` parition while flashing the ROM

The second option requires the ROM developer to do that. My question is, can this easily be done ? If not, what are the alternatives ?

### Steps to reproduce

1. Flash crDroid 9.3 on a device with dynamic partitions
2. Reboot into crDroid
3. Reboot into recovery (TWRP)
4. Install MinMicroG (standard, minimal or NoGoolag version). I chose the latest beta version provided [here](https://github.com/FriendlyNeighborhoodShane/MinMicroG-abuse-CI/releases) as it provided more verbose error messages in the logs

### Relevant log (logcat/build log)

See the attached file. Removed logs from here for clarity
[recovery.log](https://github.com/crdroidandroid/issue_tracker/files/11183628/recovery.log)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Jabiyeff** [comment]
I releasing my spes builds with minimal GApps, because our device has dynamic partition. It doesn't support addon.d. So another any GApps package unneeded.

**Comment by ale5000-git** [comment]
> I releasing my spes builds with minimal GApps, because our device has dynamic partition. It doesn't support addon.d. So another any GApps package unneeded.

@Jabiyeff: microG isn't a micro version of GApps but it is an alternative completely open source.
