### ISSUE TITLE
quick settings footer bg 

### ISSUE THREAD

**Issue by newname-1** [crdroidandroid/issue_tracker#165]
### Issue type

User interface

### Device

Miatoll 

### crDroid version

crDroid 9

### Exact version / Build date

Fri Apr  7 16:18:20 EEST 2023

### Bug description

CR droid 9.2 QPR1 has transperant qs footer bg and it looks good. But 9.3 has different and it looks bad as compared to 9.2 qs.

CR droid 9.2 
![IMG_20230409_221009_864](https://user-images.githubusercontent.com/113122396/230785301-cdf297ef-d3be-4b23-8bbb-6a24e9a179aa.jpg)

9.3 QPR2
![Screenshot_20230409-221353_crDroid Home](https://user-images.githubusercontent.com/113122396/230786700-82be72b8-728b-4271-b4ef-46a4c5c6b464.png)

Previous one looks way better than the current one.

### Steps to reproduce

.

### Relevant log (logcat/build log)

```shell
.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
design choice
