### ISSUE TITLE
Glitchy transition when switching system theme.

### ISSUE THREAD

**Issue by newname-1** [crdroidandroid/issue_tracker#167]
### Issue type

User interface

### Device

Miatoll

### crDroid version

crDroid 9

### Exact version / Build date

Fri Apr  7 16:18:20 EEST 2023

### Bug description

There is a glitchy animation when switching system theme from light mode to dark mode or from dark mode to light mode.

Log
[theme_switch.txt](https://github.com/crdroidandroid/issue_tracker/files/11192520/theme_switch.txt)

Screen record

https://user-images.githubusercontent.com/113122396/230958497-90b7f1e2-08bf-4601-bd12-24a7d924e146.mp4

This issue is not present in Lineage OS and the transition between dark mode and light mode is smooth.

### Steps to reproduce

Pull down quick settings and tap on dark mode.

### Relevant log (logcat/build log)

```shell
.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is just how our theming engine controls and resets mode
for now nothing to fix but improvements might come in the future
