### ISSUE TITLE
bug: Tapeten und Stil

### ISSUE THREAD

**Issue by jason3855** [crdroidandroid/issue_tracker#17]
### Issue type

User interface

### Device

Poco x3 Pro M2102J20SG https://crdroid.net/vayu/8

### crDroid version

crDroid 8

### Bug description

While the user goes from owner to user and back to owner (multiple users). The very color of the interface (wallpaper colors) changes, this is most noticeable with themed icons. This error is common but not always the case, and it's quite annoying and problematic.

### Steps to reproduce

1.Settings 2.System 3.Multi-users 4.Guest 5. Return to owner (interface color changed by itself)

### Relevant log (logcat/build log)

```shell
---
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
no logcat
