### ISSUE TITLE
bug: title (<-- change me)

### ISSUE THREAD

**Issue by KL7000F** [crdroidandroid/issue_tracker#170]
### Issue type

Other

### Device

Poco F3

### crDroid version

crDroid 9

### Exact version / Build date

crDroid 9.3 from 09. April 2023

### Bug description

The function to change the brightness via swipe gesture on the status bar is missing. Has this been removed on purpose?

### Steps to reproduce

No steps to reproduce.

### Relevant log (logcat/build log)

```shell
No log
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Been dropped from upstream LOS as not working with qpr2
