### ISSUE TITLE
bug: wildvine not present 

### ISSUE THREAD

**Issue by way2harshraj090** [crdroidandroid/issue_tracker#176]
### Issue type

Feature is missing

### Device

veux

### crDroid version

crDroid 7

### Exact version / Build date

crDroidAndroid-13.0-20230407-veux-v9.3.zip

### Bug description

Wildvine is missing 

### Steps to reproduce

Play video in any secure app such as Netflix, jio cinema.
Mine one is specially for jio cinema.

### Relevant log (logcat/build log)

```shell
I don't know.
```

### Screenshots or videos

[Click Here](https://streamable.com/gz57kx) 

Or 
https://streamable.com/gz57kx

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
we can't do anything about this as can be device/region specific and certificates validate usually only on locked bootloader and stock firmware
