### ISSUE TITLE
bug: configuring "single tap" action for the "Recents button"

### ISSUE THREAD

**Issue by xabolcs** [crdroidandroid/issue_tracker#178]
### Issue type

Feature not working as intended

### Device

Mi 9 SE (grus)

### crDroid version

crDroid 9

### Exact version / Build date

9.4 / `TQ2A.230405.003.E1`

### Bug description

In menu "crDroid Settings" / Navigation / Actions I'd like to configure the single tap action for the "Recents/Menu" button as I did in the stock firmware.

But the is no menuitem for single tap actions, just duple taps and long press for the buttons.

### Steps to reproduce

1. go to crDroid settings
2. select "Navigation" page
3. swipe down to "Actions"

### Relevant log (logcat/build log)

```shell
N/A
```

### Screenshots or videos

Stock button settings:
![Screenshot_2023-04-24-19-35-29-470_com miui miinput-edit](https://user-images.githubusercontent.com/568751/236635385-284724a8-006b-4f5d-b91c-c129e157eddc.jpg)

crDroid action settings:
![Screenshot_20230506-110827_crDroid Home](https://user-images.githubusercontent.com/568751/236635396-8831ae83-690a-40a4-a646-f8bf637fd736.png)

### Additional context

I use **Rocky7842**'s unofficial build from [XDA](https://forum.xda-developers.com/t/rom-13-ota-crdroid-9-for-mi-9-se-grus-encryption-unofficial.4533353/ "[ROM][13][OTA] crDroid 9 for Mi 9 SE [grus][ENCRYPTION][UNOFFICIAL]"), but I was informed that is source related bug.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DarkJoker360** [comment]
There is no way to configure single tap action, you can however customize long press tap actions. This is the normal behaviour of our implementation.
