### ISSUE TITLE
pubg gaming lag

### ISSUE THREAD

**Issue by spoidy1122** [crdroidandroid/issue_tracker#18]
### Issue type

Other

### Device

alioth

### crDroid version

crDroid 8

### Bug description

ever since i install cr droid pubg lags alot it is because of thermal profile that the game lags

### Steps to reproduce

remove thermal profile

### Relevant log (logcat/build log)

```shell
there is no code just telling u that
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
irrelevant due to lack of logs and we are not gaming focused

**Comment by spoidy1122** [comment]
U should focus in gaming
