### ISSUE TITLE
bug: Government banking app fails to run specifically on CrDroid

### ISSUE THREAD

**Issue by apprehensions** [crdroidandroid/issue_tracker#182]
### Issue type

Feature not working as intended

### Device

POCO X3 NFC Codename `surya`

### crDroid version

crDroid 9

### Exact version / Build date

9.5 20230510 by maintainer TheStrechh

### Bug description

Government banking app called Mada Pay unexpectedly fails to run on CrDroid 9.0-9.5 with the same error always:
`Failure initializing Mada Pay`, the error seems to be related towards `MediaBrowserCompat` and Android Parcels, explained with code below.

I have debugged this many times and have always noticed that CrDroid is the only ROM to face this issue, And since this is a banking app, there is not much debugging to do. This app runs perfectly as intended on Lineage, AICP, Arrow and many other roms, which makes me very confused, including the fact that a ROM based on CrDroid trees such as RisingOS also works.

On a 9.5 CrDroid build by TheStrechh, the app fails with the error given above, however a 9.5 2023-05-08 CrDroid made by the official maintainer GtrCraft the app crashes with `DeadObjectException`.

### Steps to reproduce

1. Download this app, only available in Saudi Arabia region, can give APK if needed
2. Launch it
3. Observe the error message

### Relevant log (logcat/build log)

```shell
05-11 17:51:30.180  2913  3131 E MediaProvider: Creating or writing to a non-default top level directory is not allowed!
05-11 17:51:30.183  2913  3131 E MediaProvider: Creating or writing to a non-default top level directory is not allowed!
05-11 17:51:30.183  5595  5663 I System.out: Unable to create the log folder
05-11 17:51:30.201  5595  5663 W System  : Ignoring header Content-Type because its value was null.
05-11 17:51:30.201  5595  5663 W System  : Ignoring header Accept because its value was null.
```
These are the only logs i was able to get. The app is very cryptic as errors are completely unknown.

### Screenshots or videos

The message that appears when using TheStrechh CrDroid 9.5 20230510:
![image](https://github.com/crdroidandroid/issue_tracker/assets/47404953/e7fc4e85-b2b5-47f8-a37c-820914b210b3)

### Solution

Using another ROM, such as Lineage.

### Additional context

This app does not care about SafetyNet. I know root detection and this app seems to not care at all, i have a fully passing SafetyNet and this app can still fail specifically on CrDroid. It only cares about root detection such as Magisk which is easily fixed with Zygisk. 

The function that causes this error is `MediaBrowserCompat$CustomActionResultReceiver`, And also subsequently related to Android Parsels or MediaBrowserCompat, as i found by decompiling the app myself.

I understand this cannot be solved, but i have been very frustrated at how this specific ROM had always made the app fail to run. Even since version 9, and maintainers and telegram groups with no avail or to straight up get ignored.

I hope the solution to this is simple.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by apprehensions** [comment]
I would like to clarify that i have used three different builds of crDroid and these are the outcomes:
+ TheStrechh crDroidAndroid-13.0-20230510-surya-v9.5: leads to 'Failure to initialize mada Pay'
+ GtrCraft  crDroidAndroid-13.0-20230508-surya-v9.5.zip: leads to `DeadObjectException`, and 'Failure to initialize mada Pay' in some cases
+ Self-Built crDroidAndroid-13.0-20230512-surya-v9.5.zip: leads to app success.

I believe the maintainers have changed or use different trees to cause this problem, or maybe a tree has just been updated to fix this; who knows?

**Comment by apprehensions** [comment]
> Did you build user build or user-debug build?

I don't know, but at build time i remember building `brunch lineage_surya-userdebug` with trees directly from crdroidandroid such as android_{vendor,kernel,device}_xiaomi_surya and android_hardware_xiaomi.

**Comment by apprehensions** [comment]
after trying a build from TheStrechh crDroidAndroid-13.0-20230513-surya-v9.5.zip, which should be more up to date than mine, the app still fails to function.

**Comment by apprehensions** [comment]
I have used the provided crdroidandroid trees from the organization, currently I am using TheStrechh's trees at the moment. I have noticed that the application functions from a freshly baked android build, if i change a variable or use the same build many times it ceases to start. This is very complicated, but I use another app called Absher which is better in root detection, however would work alongside the government app in this original issue if it doesn't detect root as well, which isn't true on the official CrDroid builds or ROMs such as LibreMobileOS in my testing.. Kinda wanna close this issue for the time being and blame it on root detection.

**Comment by GtrCraft** [comment]
Default kernel now supports kernelSU, try to use that.

**Comment by apprehensions** [comment]
Why did this get closed? KernelSU does not help with root detection, and the app still fails to function even on a regular build.

**Comment by gwolf2u** [comment]
root is not part of android system and not a thing we build

**Comment by apprehensions** [comment]
\> "root is not part of android system and not a thing we build"
\> issue related with official crdroid builds
\> kernelsu included in official crdroid builds
