### ISSUE TITLE
bug: split-screen

### ISSUE THREAD

**Issue by GitHubIXChara** [crdroidandroid/issue_tracker#183]
### Issue type

Feature not working as intended

### Device

Device: Redmi 8 (olive)

### crDroid version

crDroid 7

### Exact version / Build date

7.13/2022-01-02

### Bug description

in split screen all working fine, but when exiting that mode, phone just locking.
if i enable function what will make messages if process exited with error: it will say: "System UI have been stopped"

### Steps to reproduce

Step 1. - enable free form windows and split screen mode
Step 2. - use 2 apps and then close split-screen mode
Step 3. - Enjoy System UI stopping

### Relevant log (logcat/build log)

```shell
cant access logcat due to system UI stopps working - i can't open matlog app.
```

### Additional context

Magisk: Yes (no modules, using only shizuku)
other Kernel: No

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is really old version and no longer maintained
latest 7.x branch is 7.30 and you are running 7.13, so really old code
