### ISSUE TITLE
bug: HD Audio is disabled in developer options. Causing digital cracking in headset.

### ISSUE THREAD

**Issue by lindahl85** [crdroidandroid/issue_tracker#184]
### Issue type

Feature not working as intended

### Device

Lemonadep
Oneplus 9 pro EU

### crDroid version

crDroid 9

### Exact version / Build date

crDroidAndroid-13.0-20230505-lemonadep-v9.5

### Bug description

Digital stutter on jabra stealth headset occur on Oneplus 9 series.
It´s actually an old issue.
https://forum.xda-developers.com/t/android-11-loss-of-hd-audio-in-developer-settings.4164439/#post-83725737

I noticed this first on OP9 in january when I bought that phone from 8T, earlier phones was 5T, 3T with crdroid but never had that issue. Now I upgraded to OP 9 Pro and see the issue again.
https://t.me/crdroidop9/54155

### Steps to reproduce

You need to have a jabra stealth headset i guess to hear the cracking or something that can support hd audio. Jabra Elite 75T does not reproduce the issue with cracking.
1. Bluetooth on. Go into developer settings and look on hd audio. It is probably turned off. It is also greyed out so you can´t activate it.
2.  Disable developer options and turn it back on. Now you can also enable hd audio. 
3. Connect headset and hd audio is still active.
4. Make a call with the headset. Audio works as ex

pected.
5. Stop the call and go back to developer settings. HD audio is now disabled.
6. Make a new call. Digital stutter is back (since HD audio is turned off)

Why is it turning of itself on OP9 series but not OP 8T?
[logs-2023-05-14-22-58-00.zip](https://github.com/crdroidandroid/issue_tracker/files/11472924/logs-2023-05-14-22-58-00.zip)

### Relevant log (logcat/build log)

```shell
Zip is included above.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by lindahl85** [comment]
Affected headset:
Volvo V60 2014
Jabra Stealth

Not affected headset
Peltor Protac XPI
Jabra Elite 75T

**Comment by lindahl85** [comment]
New logcat after request from @gwolf2u 

[Jabra stealth digital cracking.txt](https://github.com/crdroidandroid/issue_tracker/files/11501059/Jabra.stealth.digital.cracking.txt)

**Comment by gwolf2u** [comment]
can you try with latest build?
https://sourceforge.net/projects/crdroid/files/lemonadep/9.x/crDroidAndroid-13.0-20230521-lemonadep-v9.5.zip/download

**Comment by lindahl85** [comment]
> can you try with latest build? https://sourceforge.net/projects/crdroid/files/lemonadep/9.x/crDroidAndroid-13.0-20230521-lemonadep-v9.5.zip/download

I can install today but forgot my headset home so I can test on Friday

**Comment by lindahl85** [comment]
> can you try with latest build? https://sourceforge.net/projects/crdroid/files/lemonadep/9.x/crDroidAndroid-13.0-20230521-lemonadep-v9.5.zip/download

Sadly it didn't help

**Comment by lindahl85** [comment]
Adding more info.
Lag starts around 4 seconds after screen goes totally black and continue. Dimmed screen before it locks work, locked screen work, as long as the screen is lighted. No lag when doing logcat. No lag when connected to usb 2 cable. Does any clever have an idea? Tested with spotify set to high quality and jabra elite 75t.

Tested spotify with offline songs set to very high quality. Same thing there so I don´t see any difference if I stream music.

Current version
crDroidAndroid-13.0-20230526-lemonadep-v9.5

**Comment by lindahl85** [comment]
I might be on to something here. Started to uninstall apps one by one and came to Viper4Android. I noticed it wasn´t on.
I went into Magisk, it wanted to do a new installations since it wasn´t properly installed (I guess that is okay or normal since i just updated CrDroid.)
I deleted Viper and did the Magisk installation and rebooted.
Issue with Spotify is gone.
I installed Viper again and tested with it disabled. No issues.
I activated Viper, no issues.

So it might be possible that you need to be in this small window when magisk isn´t properly patched to see this issue. I will do some more headset tests and wait for next crdroid release.

I need a coffee break but I found out that something in a combination with Crdroid 9, Magisk, V4A works different than before. I still have my 8T so I could install Crdroid 9 there too again to see if I can reproduce the issue there.

**Comment by lindahl85** [comment]
It's strange. Using 230529 build with latest firmware. First call today was working with Jabra stealth, wifi call was used. Now im on a train doing a wifi call and the digital cracking is there.

Viper isn't installed this time. Dolby audio is set to smart.

**Comment by lindahl85** [comment]
Streaming Spotify is working on Jabra Stealth with screen off. Both with Dolby on and off. No difference if wifi is on or off.

Need to check calls too.

Build 20230609

**Comment by lindahl85** [comment]
Issue in calls is still active with regular call, Vowifi, volte.

**Comment by lindahl85** [comment]
Testing my old Jabra motion. I was in my house and called on wifi some days ago. No cracks.
Today I called again, both wifi and regular but I have cracks.

Jabra Elite 75t is still the only headset that doesn't have cracking sound. They do however loose bt range in my pocket fast.

**Comment by lindahl85** [comment]
Been doing some testing with Jabra support today with Elite 75T, Stealth and Motion. They want me to clear cache and storage on the built in bluetooth system app but I notice that it isn´t possible. They want me to contact OnePlus support regarding that but I but the notice here.

Elite 75T - Might have hardware issue since it´s more random cracking and headset can do random reboots.
Stealth - Works from computer but not 9 Pro. Related to ROM i guess, the want me to contact Oneplus.
Motion - Works from computer but not 9 Pro. Related to ROM i guess, the want me to contact Oneplus.

![2023-07-04 11 42 13](https://github.com/crdroidandroid/issue_tracker/assets/20877425/600b9de5-874c-40e2-b24e-d669ffa6d1aa)

So, Jabra Stealth and Jabra Motion doesn´t work together with CrDroid 9. What more can I assist with?

**Comment by gwolf2u** [comment]
sadly this is a #nofix

**Comment by lindahl85** [comment]
> sadly this is a #nofix

How come? Impossible to find?

**Comment by gwolf2u** [comment]
logs not helping and investigation resulted in no proper fix
so had to dump it

it might be because of AOSP HAL and OP doing some undisclosed changes, or might be blobs related
but so far, no fix can be provided

**Comment by lindahl85** [comment]
@gwolf2u 
I have noticed that all BT headset that use bluetooth 4.x have digital cracking sounds but not headset that use bluetooth 5.x
