### ISSUE TITLE
Color change not working

### ISSUE THREAD

**Issue by assignment776** [crdroidandroid/issue_tracker#186]
### Issue type

User interface

### Device

Redmi note 8 pro (begonia)

### crDroid version

crDroid 9

### Exact version / Build date

9.5/2023-05-05

### Bug description

System and icon colors do not change 

### Steps to reproduce

Step 1. Go to "Wallpaper & Style" menu. Step 2. Change the main colors of the system to any other color. 
Result: Colors do not change.

### Relevant log (logcat/build log)

```shell
–
```

### Screenshots or videos

![Screenshot_20230515-113625_Обои и стиль](https://github.com/crdroidandroid/issue_tracker/assets/91868210/74ae3968-d6ce-42c1-8f86-631beafbe54b)
![Screenshot_20230515-113629_Обои и стиль](https://github.com/crdroidandroid/issue_tracker/assets/91868210/a2d6c281-4e03-497a-aaae-c79e2c2bee9d)
![Screenshot_20230515-113905_crDroid Home](https://github.com/crdroidandroid/issue_tracker/assets/91868210/72d64527-89a1-4a09-b66c-d2a144b93eb0)

### Additional context

When you change the main colors of the system in the "Wallpaper and Style" menu, the colors of the icons on the main screen and in the quick settings menu do not change. Also, the background of the clock located on the notification panel also does not change.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [x] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by assignment776** [comment]
Sorry. I forgot to name the bug..

**Comment by gwolf2u** [comment]
Can't confirm
Using custom Monet colors?

![photo_2023-05-24_12-54-48](https://github.com/crdroidandroid/issue_tracker/assets/877292/7cef89f1-82ae-409f-85f0-a0a60eeb7360)
![photo_2023-05-24_12-54-52](https://github.com/crdroidandroid/issue_tracker/assets/877292/3e4a734a-78d4-41a6-b38f-beb65f27ef69)
