### ISSUE TITLE
android auto wireless and outlook issues

### ISSUE THREAD

**Issue by sharicov** [crdroidandroid/issue_tracker#187]
### Issue type

Feature not working as intended

### Device

miatoll (redmi note 9s)

### crDroid version

crDroid 7

### Exact version / Build date

9.5 May 6th 2023

### Bug description

1. Android auto wireless not connecting (works well with USB cable), multimedia system just searches for the phone and returns back to main screen, no error messages appear. On the phone it shows that android auto wireless system is available.

2. For the outlook issue, email address autocompletion shows black list which is populated with suggested email addresses, but it cannot be seen (pressing on it does select email address. ("company portal" app is installed).

### Steps to reproduce

1. press connect on car multimedia.
2. create new email and start typing in email address.

### Relevant log (logcat/build log)

```shell
no logs (no errors)
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
invalid bug report

1. android auto needs to be system app
2. no control for 3rd party apps
