### ISSUE TITLE
bug: Issue with crDroid Home, app drawer

### ISSUE THREAD

**Issue by Bartixxx32** [crdroidandroid/issue_tracker#189]
### Issue type

User interface

### Device

OnePlus 7 Pro (guacamole)

### crDroid version

crDroid 9

### Exact version / Build date

crDroidAndroid-13.0-20230519-guacamole-v9.5.zip

### Bug description

Issue with app drawer searching for apps by name does not refresh "layout i think" 

### Steps to reproduce

1. Open app list
2. Type app name
3. Click searched app right after last letter is typed

### Relevant log (logcat/build log)

```shell
I don`t think that log may be needed for this, but if so i`ll update issue when able
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/16412925/05e0fbbf-579d-4d99-848e-e905e1e6e394

Look at the scroll bar on the right, when it jumps into top, you can safely open app with no risk of opening any unwanted app

### Solution

wait longer, around 1 sec before done typing, 

It may look like 1s is nothing, but trust me, its pain when trying open some app and instead download manager opens

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this issue is fixed in newer revisions
