### ISSUE TITLE
bug: urls is clipboard will not paste in browsers

### ISSUE THREAD

**Issue by Amby713** [crdroidandroid/issue_tracker#19]
### Issue type

Feature not working as intended

### Device

Xiaomi m10t 

### crDroid version

crDroid 8

### Bug description

I noticed that when you copy a url (http://domain.com), click on an address bar of a browser, and select "text you copied", that it doesn't paste in the address bar. If you cooy text (1234) and then select "text you copied", it works. 
Tried it on bromite and chrome with the same results

### Steps to reproduce

Copy any url
Launch browser
Tap on address bar
Wait for menu popup
Click on "text you copied"
Nothing pastes

Copy any text
Launch browser
Trap on address bar
Wait for menu popup
Click on "text you copied"
Text is pasted on to address bar

### Relevant log (logcat/build log)

```shell
Logcat
https://send.zcyph.cc/download/b4064e1444a2778b/#i5QKavar7yqhoXiStbELdw
```

### Additional context

I'm on test build for 8.9 for my device (apollo) 

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Not able to reproduce here
Needs base update to cr8.10
