### ISSUE TITLE
fingerprint not working when flash crdroid 8.14 to poco f3

### ISSUE THREAD

**Issue by bach0510** [crdroidandroid/issue_tracker#190]
### Issue type

Feature not working as intended

### Device

poco f3 (redmi k40)

### crDroid version

crDroid 8

### Exact version / Build date

8.14//2023-03-23

### Bug description

fingerprint showing not register

### Steps to reproduce

open setting > setup finger print > popup error: fingerprint not registered, try again or using another finger

### Relevant log (logcat/build log)

```shell
fingerprint not registered, try again or using another finger
```

### Acknowledgements

- [x] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment]
@bach0510  Just tried to setup FP and no issue here at all. 
Follow flash instructions to the letter (check FW as well!
![Image3277302880753903166](https://github.com/crdroidandroid/issue_tracker/assets/42908970/30dfa8ef-e407-4369-91cc-5bbaa712cbc5)
![Image5800131046076506175](https://github.com/crdroidandroid/issue_tracker/assets/42908970/6a93b5a1-dcb0-42ba-99b1-1b2fe67b5d47)
) : https://forum.xda-developers.com/t/rom-12-1-official-alioth-aliothin-crdroid-v8-14-23-03-2023.4386959/page-106#post-88324725
