### ISSUE TITLE
bug: Netflix HDR Playback Stuttering on [POCO F3] [ALIOTH]

### ISSUE THREAD

**Issue by Artisians** [crdroidandroid/issue_tracker#191]
### Issue type

Feature not working as intended

### Device

Alioth

### crDroid version

crDroid 9

### Exact version / Build date

A13 - 2023-06-02

### Bug description

HDR content on Netflix stutters and is not watchable.

### Steps to reproduce

1. Open Netflix on a device that supports HDR playback.
2. Select an HDR movie or TV show.
3. Start playback and observe the stuttering.

### Relevant log (logcat/build log)

```shell
- I have checked the logs on my device but have not found any relevant information related to the HDR playback stuttering issue on Netflix.

- This issue is consistently reproducible on my device, and I have not experienced any similar issues with other streaming apps or services. (Youtube)
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/36298707/922021bd-a55e-4580-afba-bf7af2a50ebc

## Expected Behavior

HDR content should play smoothly without any stuttering or other issues.

## Actual Behavior

HDR content stutters and is not watchable.

## Environment

- Netflix app version: 8.72.0 Build 4 (50432)

## Additional Information

- This issue occurs consistently on my device.
- I have tried restarting the device and reinstalling the Netflix app, but the issue persists. (Both Beta and Regular)
- Other non-HDR content on Netflix plays without any issues.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Artisians** [comment]
If Ray requires access to my Netflix account to assist with troubleshooting the HDR playback issue, I would be happy to provide any necessary information to facilitate the process.

**Comment by raystef66** [comment]
> If @raystef66 requires access to my Netflix account to assist with troubleshooting the HDR playback issue, I would be happy to provide any necessary information to facilitate the process.

Tested and confirm some stutter on HDR Netflix.
Will check on this as soon as I can find some free time ;)
Will update when fixed.

**Comment by gwolf2u** [comment]
interested if happens on LOS
might be something specific to our sources (maybe frameworks_av?)

**Comment by raystef66** [comment]
we've tested some other roms and not happening there (except Ghostdroid, clone of crD)
we'll do a test on LOS one as well and report back

**Comment by raystef66** [comment]
> interested if happens on LOS might be something specific to our sources (maybe frameworks_av?)

we've tested LOS ([althafvly] and same stutter
https://forum.xda-developers.com/t/rom-official-alioth-13-lineageos-20-for-poco-f3-mi-11x-redmi-k40.4418635/

FYI on the 18.04  9.4  the HDR was still working after that the known problem (since then no blobs update or relevant tree changes have been made 
https://github.com/crdroidandroid/android_vendor_crDroidOTA/blob/d7e209c6f3dacdf67067f0c61474778d4c8c343b/changelog_alioth.txt#L141

https://paste.crdroid.net/qxsyVt

**Comment by raystef66** [comment]
Tested on 9.7 still same stutter.
FYI, only happening rn on my F2 pro and F3 both sm8250 devices. Not on my MI9 which is a sm8150 and HDR10+ support as well. So maybe smt to look into.
Tried different hardware_qcom-cafs but same.

**Comment by gwolf2u** [comment]
no fix can be developed for now
