### ISSUE TITLE
bug: Notification sound plays from speakers when connected to headphones

### ISSUE THREAD

**Issue by gorinexe** [crdroidandroid/issue_tracker#193]
### Issue type

User interface

### Device

Redmi Note 8 (ginkgo)

### crDroid version

crDroid 9

### Exact version / Build date

9.5/2023-05-08

### Bug description

Notification sound plays from speakers even when headphones are connected (in my case AirPods 2). If music plays from headphones and notification comes, the music starts playing from speaker with notification sound and then, plays again from headphones.

### Steps to reproduce

Step 1. Connect bluetooth headphones.
Step 2. Wait for a notification or make it yourself somehow.

### Relevant log (logcat/build log)

```shell
No related logs
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
no fix can be developed
