### ISSUE TITLE
bug: lemonadep: charging current is wrong

### ISSUE THREAD

**Issue by 532910** [crdroidandroid/issue_tracker#195]
### Issue type

Feature not working as intended

### Device

lemonadep

### crDroid version

crDroid 9

### Exact version / Build date

0-20230603

### Bug description

Charging current shown on lock screen is wrong.

### Steps to reproduce

plug in charger
check current and power shown on lock screen

### Relevant log (logcat/build log)

```shell
no log no error
```

### Screenshots or videos

![image](https://github.com/crdroidandroid/issue_tracker/assets/14617699/aad0b993-b245-498a-8e86-88acb7b3fae2)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is caused by the double batteries the phone has and AOSP code doesn't follow that unfortunately 
for now this is how it goes

**Comment by 532910** [comment]
knowingly false values must not be shown to the users
if this not going to be fixed, it should be hidden

**Comment by 532910** [comment]
Even HomeAssistant shows power correctly as voltage divisors.
https://github.com/home-assistant/android/pull/4299
Please reopen!

**Comment by 532910** [comment]
Moreover lemonadep is not the only affected device. I believe it's better to not show power at all than confuse users with wrong values!
