### ISSUE TITLE
Ambient Display causing system crash

### ISSUE THREAD

**Issue by cygiel5420** [crdroidandroid/issue_tracker#196]
### Issue type

User interface

### Device

Pixel 7 Pro (cheetah) 

### crDroid version

crDroid 9

### Exact version / Build date

9.5 / 2023-05-22

### Bug description

When Ambient Display is enabled in crdroid settings, the system crashes and reboots.

### Steps to reproduce

Enable Ambient Display in crdroid settings, both "Always show time and info" and "Always show when charging".

For "Always show time and info":
1. Put phone in the pocket UPSIDE DOWN
2. Walk for about a minute
3. Take phone out of the pocket
4. Watch the system crash and reboot

For "Always show when charging"
1. Plug the phone in to charge
2. Try to unlock phone with fingerprint sensor
3. Watch system crash and reboot

### Relevant log (logcat/build log)

```shell
Tombstones in comment
```

### Solution

For "Always show time and info" either put phone in pocket RIGHT WAY UP, or disable "Always show time and info".

For "Always show when charging" either unplug phone before trying to unlock to minimize chance of crash, or disable "Always show when charging". 

### Additional context

Took me 2 weeks to figure out why system was crashing. Narrowed it down to Ambient Display to be the cause when enabled. Did multiple factory resets just to pinpoint the cause. System crashes hard enough for ReVanced rooted apps to disappear and/or get corrupted. After system recovers, another system reboot is needed for the apps to reappear with no guarantee of them working but that might be ReVanced issue for how they implement root app installs. 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
log needed in this case

**Comment by cygiel5420** [comment]
Found 2 relevant Tombstones. Tombstone 15 is relevant to "Always show time and info", Tombstone 14 is relevant to "Always show when charging". 

[Ambient Display Tombstone Logs.zip](https://github.com/crdroidandroid/issue_tracker/files/11712735/Ambient.Display.Tombstone.Logs.zip)

**Comment by gwolf2u** [comment]
a full rebase is done with 9.7
can you confirm if still happening?

**Comment by cygiel5420** [comment]
Issue appears to be resolved. I'll test it rigorously over the next week to confirm, and report back.

**Comment by gwolf2u** [comment]
Closing for now
Do open new issue if still occurs
