### ISSUE TITLE
bug: Battery drainage 10%/night [OP 7T Pro]

### ISSUE THREAD

**Issue by markus1991** [crdroidandroid/issue_tracker#198]
### Issue type

User interface

### Device

One Plus 7T Pro

### crDroid version

crDroid 9

### Exact version / Build date

9.5/2023-06-01

### Bug description

Battery drainage was very high 5%/h. Then switched off pocket detection. => A lot better but still 10% per Night

### Steps to reproduce

Just perform clean install, drainage immediately visible 

### Relevant log (logcat/build log)

```shell
There was an error creating your issue: body is too long (maximum is 65536 characters).

This appears when i copy the logcat in here

Logcat in Comments
```

### Screenshots or videos

![Screenshot_20230615-083140_Einstellungen](https://github.com/crdroidandroid/issue_tracker/assets/3776881/51683d08-13cb-4e79-85b0-67cd0a1f473a)

### Solution

None

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by markus1991** [comment]
[logcat.txt](https://github.com/crdroidandroid/issue_tracker/files/11753686/logcat.txt)

**Comment by gwolf2u** [comment]
battery drain should be better in 9.6
however, logcat won't cover much of that, rather use battery monitor tools to check for wakeups and so
do let me know how it is in 9.6

**Comment by markus1991** [comment]
Sadly, battery drainage is still a problem with version 9.7. 
7% loss over night

Do you know a useful battery monitor? The apps I've tried are not monitoring system apps...

**Comment by ShevT** [comment]
I consider a discharge of 1% per hour normal and acceptable

**Comment by markus1991** [comment]
Yes, but it is 7%

**Comment by gwolf2u** [comment]
so to get things in order, is it 7%/h or 7%/night (few hours)
try logging stats with better battery stats app or similar

**Comment by markus1991** [comment]
It is 7% per night. So the phone is not in use.
On OOS12 it was 1% per night.

**Comment by gwolf2u** [comment]
Can't really think on oos you can get 1% per night, but ok
Anyway, as @ShevT said, 1%/h is manageable imo also so will close this
Maybe will get better when we will rebase kernel on new just released kernel source

**Comment by ShevT** [comment]
> It is 7% per night. So the phone is not in use. On OOS12 it was 1% per night.

I don't believe.
My friend has the same phone on OOS12. Overnight consumption within 10%
