### ISSUE TITLE
Cannot connect to Wifi 6Ghz networks

### ISSUE THREAD

**Issue by cygiel5420** [crdroidandroid/issue_tracker#199]
### Issue type

Feature not working as intended

### Device

Pixel 7 Pro (cheetah) 

### crDroid version

crDroid 9

### Exact version / Build date

9.5 / 2023-05-22

### Bug description

Cannot connect to 6Ghz wifi networks. Defaults to 5Ghz.

### Steps to reproduce

Try to connect to network that supports 6Ghz wifi frequencies, and is set up properly with WPA3 enabled. Watch the connection try to be established then default to 5Ghz frequencies.
When 5Ghz band on AP are disabled, the connection cannot be established. 

### Relevant log (logcat/build log)

```shell
06-16 10:27:09.611 D/WifiNative(1495): onSetCountryCodeSucceeded: US
06-16 10:27:09.611 I/WifiCountryCode(1495): Receive onSetCountryCodeSucceeded US
06-16 10:27:09.611 I/wificond(1118): Receive notifyCountryCodeChanged
06-16 10:27:09.611 I/wificond(1118): UpdateBandInfo
06-16 10:27:09.613 I/wificond(1118): 2.4Ghz frequencies: 2412 2417 2422 2427 2432 2437 2442 2447 2452 2457 2462 2467 2472
06-16 10:27:09.613 I/wificond(1118): 5Ghz non-DFS frequencies: 5180 5200 5220 5240 5745 5765 5785 5805 5825
06-16 10:27:09.613 I/wificond(1118): 5Ghz DFS frequencies: 5260 5280 5300 5320 5500 5520 5540 5560 5580 5600 5620 5640 5660 5680 5700 5720 5845 5865 5885
06-16 10:27:09.613 I/wificond(1118): 6Ghz frequencies: 5955 5975 5995 6015 6035 6055 6075 6095 6115 6135 6155 6175 6195 6215 6235 6255 6275 6295 6315 6335 6355 6375 6395 6415 6435 6455 6475 6495 6515 6535 6555 6575 6595 6615 6635 6655 6675 6695 6715 6735 6755 6775 6795 6815 6835 6855 6875 6895 6915 6935 6955 6975 6995 7015 7035 7055 7075 7095
06-16 10:27:09.613 I/wificond(1118): 60Ghz frequencies:
06-16 10:27:09.613 I/WifiNl80211Manager(1495): Receive country code change to US
06-16 10:27:09.613 I/WifiClientModeImpl[140779825:wlan0](1495): disconnectedstate enter
06-16 10:27:09.614 E/WifiScoringParams(1495): Invalid frequency(-1), using 5G as default rssi array
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
a full rebase is done with 9.7
can you confirm if still happening?

**Comment by cygiel5420** [comment]
Issue appears to be resolved. Phone sees 6Ghz WiFi networks.

**Comment by gwolf2u** [comment]
Then closing this one
