### ISSUE TITLE
Phone stuck at crdroid boot animation 

### ISSUE THREAD

**Issue by xdifardeen** [crdroidandroid/issue_tracker#201]
### Issue type

Source code related

### Device

Lavender

### crDroid version

crDroid 7

### Exact version / Build date

crDroidAndroid-11.0-20210809-lavender v7.9

### Bug description

Doesn't boot 

### Steps to reproduce

install crdroid via otg with orange fox recovery
Then reboot to system
.
.
.
The system won't boot and will be stuck at crdroid 

### Relevant log (logcat/build log)

```shell
There wasn't any error code since system didn't boot at all
```

### Solution

I don't know what might be the problem so can't really suggest a solution 

### Additional context

I installed crdroid via orange fox recovery...
Otg method
Without gapps 
Wiped everything except internet sd and otg and performed a factory reset then installed the rom the rom was flashed successfully so i rebooted the system where it was stuck

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
make sure to format data and all
use install steps from forum as they will work
