### ISSUE TITLE
bug: App preview stuck if swiping up immediately after using gesture for opening the recent apps view 

### ISSUE THREAD

**Issue by AlphaCraft9658** [crdroidandroid/issue_tracker#204]
### Issue type

User interface

### Device

Redmi Note 8 Pro (begonia)

### crDroid version

crDroid 9

### Exact version / Build date

Ex: 9.6/2023-06-29

### Bug description

The preview of the current app is stuck when opening last apps view via the navigation gesture and immediately swiping up the app.

### Steps to reproduce

1. Enable gesture navigation
2. Swipe up to open the app menu
3. Once released, immediately swipe up the preview of the current app

### Relevant log (logcat/build log)

```shell
I couldn't gather useful logs.
```

### Screenshots or videos

https://photos.app.goo.gl/qPoet2YgxSzMGw7g9
(Couldn't drag-and-drop on my phone)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
This is fixed already
Needs new build
