### ISSUE TITLE
dipper: Fingerprint unlock not working

### ISSUE THREAD

**Issue by gugukcu** [crdroidandroid/issue_tracker#208]
### Issue type

User interface

### Device

Xiaomi MI 8

🔖 Codename: dipper
📱 crDroid version: 9.6
📅 Build date: 20230704
✅ MD5: D2C0530E0D51B92273C3D8C888BFA20D
🧑‍💻 Maintainer: 竹林里有冰

### crDroid version

crDroid 9

### Exact version / Build date

9.6/2023-07-04

### Bug description

Fingerprint unlock not working without waking the screen by pressing the power button

### Steps to reproduce

Fingerprint unlock not working without waking the screen by pressing the power button

### Relevant log (logcat/build log)

```shell
Fingerprint unlock not working without waking the screen by pressing the power button
```

### Screenshots or videos

Fingerprint unlock not working without waking the screen by pressing the power button

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this issue has already been fixed in code
needs a build with a date from today onward
