### ISSUE TITLE
bug: title (<-- change me)

### ISSUE THREAD

**Issue by gugukcu** [crdroidandroid/issue_tracker#209]
### Issue type

User interface

### Device

Xiaomi MI 8

### crDroid version

crDroid 9

### Exact version / Build date

Build date: 20230704

### Bug description

Fingerprint not working when screen is off

### Steps to reproduce

Fingerprint not working when screen is off

### Relevant log (logcat/build log)

```shell
Fingerprint not working when screen is off
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
https://github.com/crdroidandroid/issue_tracker/issues/208
