### ISSUE TITLE
bug: System theme change is slow & jarring since Cr8.5

### ISSUE THREAD

**Issue by Username1-a** [crdroidandroid/issue_tracker#21]
### Issue type

User interface

### Device

Redmi 4X (Santoni)

CrDroid 8.8, Build 20220819

### crDroid version

crDroid 8

### Bug description

System theme switching on CrDroid 8.5-8.8 is more slower and jarring then in it was in older CrDroid 8.4 builds. Sometimes it can even cause SystemUI to crash and restart to lock screen (screen goes black and some time later lock screen appears). Just takes extra ≈15 seconds to switch theme in those occasions.

I think it's might be a source-side issue as I had one dude told me he has the same issue on Redmi 7a (Pine).

This issue could cause some inconvenience to the user, plus after all before in CrDroid 8.4 it behave completely fine.

### Steps to reproduce

Step 1. Tap Dark theme toggle in Quick Settings or in the Settings app>Display>Dark theme.

### Relevant log (logcat/build log)

```shell
Attached in a .zip file below as guthub won't let me submit the issue saying body is too long.
```

### Screenshots or videos

Here's comparison screen recordings between the 
1) CrDroid 8.8 (this bug is present)
and 
2) CrDroid 8.4 (no bug, theme switching is fast):

https://user-images.githubusercontent.com/47947180/198732466-355a61c7-2621-4e04-8587-30005a8a2358.mp4

https://user-images.githubusercontent.com/47947180/198732558-c05f375e-8b81-462f-9f19-66a0de34ef88.mp4

These videos were taken with stock freshly installed ROM, so no mods or anything. It's even more jarring when you enable Pure Black theme in Settings>Display>Dark Theme.

### Additional context

The logcat attached shows 1 minute range from 23:24:55 to 23:26:00, where system switching from dark to light and back, from light to dark, takes place approx. from 23:25:00 to 23:25:30. I attached logcat in a .zip file here, too, just in case.
[Logcat Slow System Theme Change.zip](https://github.com/crdroidandroid/issue_tracker/files/9891819/Logcat.Slow.System.Theme.Change.zip)

Please, if you will continue making maintenance updates to CrDroid 8, consider fixing this bug, if you can.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
there are more things to draw in UI and some devices due to limited resource can't do it fast enough
this is not to compare between crDroid revisions since some stuff gets rewritten as more features are added to ROM side
