### ISSUE TITLE
dipper: Lift to wake not working

### ISSUE THREAD

**Issue by gugukcu** [crdroidandroid/issue_tracker#210]
### Issue type

User interface

### Device

mi8 dipper

### crDroid version

crDroid 9

### Exact version / Build date

9.6

### Bug description

Lift to wake not working ( even in 9.6)

### Steps to reproduce

Lift to wake not working ( even in 9.6)

### Relevant log (logcat/build log)

```shell
Lift to wake not working ( even in 9.6)
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
logcat please
