### ISSUE TITLE
bug: 2btn nav rotation button doesnt work

### ISSUE THREAD

**Issue by SirRGB** [crdroidandroid/issue_tracker#211]
### Issue type

Feature not working as intended

### Device

akari, Xperia XZ2
cheeseburger, OP5

### crDroid version

crDroid 9

### Exact version / Build date

9.6/2023-07-01
9.7/2023-07-11

### Bug description

Rotation button does not show up when rotating

### Steps to reproduce

Disable autorotation
Enable 2 button navbar

### Relevant log (logcat/build log)

```shell
07-12 14:25:38.458 I/RotationButtonController(2083): onRotationProposal(rotation=1)
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/79085035/4dfda596-94f9-482d-8186-d7b71d4a5970

### Additional context

"I'm running latest version available on crdroid.net for this device" is misleading, as it conflicts with the above ack.
Unofficial devices can report source issues as well (like this)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
known issue, with no fix as of now
prob here is that 2button nav is actually deprecated and forward ported currently to latest 9.x branch
