### ISSUE TITLE
bug: title (parallel space bug)

### ISSUE THREAD

**Issue by starkyghayas** [crdroidandroid/issue_tracker#212]
### Issue type

User interface

### Device

Poco X3 pro vayu

### crDroid version

crDroid 9

### Exact version / Build date

Crdroid 9.6 2023-06-29

### Bug description

Parallel Space when i create 6 clone on aliexpress app n 6th clone of aliexpress app internet does not work after that when i install any app from play store like opera gx browser for example internet will not work in those new install app 
I need to restart my phone to fix this each time please fix it thanks

### Steps to reproduce

Parallel Space when i create 6 clone on aliexpress app n 6th clone of aliexpress app internet does not work after that when i install any app from play store like opera gx browser for example internet will not work in those new install app 
I need to restart my phone to fix this each time please fix it thanks

### Relevant log (logcat/build log)

```shell
07-13 18:17:34.512 D/OemPaidWifiNetworkFactory(1542): got request NetworkRequest [ REQUEST id=1561, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10442 RequestorUid: 10442 RequestorPkg: app.rvx.android.youtube UnderlyingNetworks: Null] ]
```

### Screenshots or videos

Parallel Space when i create 6 clone on aliexpress app n 6th clone of aliexpress app internet does not work after that when i install any app from play store like opera gx browser for example internet will not work in those new install app 
I need to restart my phone to fix this each time please fix it thanks

### Solution

I need to restart the phone to fix it

### Additional context

Parallel Space when i create 6 clone

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
need full logcat
