### ISSUE TITLE
bug: Audio 

### ISSUE THREAD

**Issue by MDK-Sensei** [crdroidandroid/issue_tracker#213]
### Issue type

Other

### Device

MI 11 Lite (Courbet)

### crDroid version

crDroid 9

### Exact version / Build date

9.6/Wed Jul  5 12:29:03 CEST 2023

### Bug description

Audio Lag When Playing COD Warzone Mobile 

### Steps to reproduce

1. Install CrDroid
2. Install GApps
3. Install COD Warzone Mobile (From Play Store)

### Relevant log (logcat/build log)

```shell
- (No Application Log)
```

### Screenshots or videos

[https://youtu.be/In-ZTnDhBGw](url)

### Solution

- (Have no idea why)

### Additional context

-

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
needs log
