### ISSUE TITLE
Mic doesn't work during call

### ISSUE THREAD

**Issue by Bulbek800** [crdroidandroid/issue_tracker#214]
### Issue type

Other

### Device

Xiaomi Redmi Note 9 M2003J15SC (merlinnfc)

### crDroid version

crDroid 9

### Exact version / Build date

9.5/2022-05-15

### Bug description

Mic doesn't work during call

### Steps to reproduce

Step 1. Open the default "Phone" app.
Step 2. Call any number.
Step 3. Listen to them saying "Hello?!" and have fun knowing that they doesn't hear you.

### Relevant log (logcat/build log)

```shell
None
```

### Solution

This bug sometimes doesn't show up. I'd say 60% of the calls are okay, but sometimes they do bug.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
merlinnfc is unofficial device so we have no way of contacting maintainer

**Comment by Bulbek800** [comment]
> merlinnfc is unofficial device so we have no way of contacting maintainer

oops.. my bad, 
thanks anyways!
