### ISSUE TITLE
Game Space feature 'Use ANGLE(experimental)' toggle turns off after a restart instead of staying on.

### ISSUE THREAD

**Issue by Hikoboshi00** [crdroidandroid/issue_tracker#215]
### Issue type

Feature not working as intended

### Device

Redmi K30 5G Racinf Edition / picasso

### crDroid version

crDroid 9

### Exact version / Build date

CrDroid 9.7

### Bug description

 I think there's a bug in Game Space. In the Library, I always use the option 'Use ANGLE(experimental)' on my games because it improves my framerate. However, when I restart my device, the option reverts back to being off. I didn't encounter this issue in previous versions of crdroid. Can you please take a look at this?

### Steps to reproduce

Step 1. Go to Game Space

Step 2. Click any app on the Library. (In my case, Mobile Legends Bang Bang)

Step 3. Enable 'Use ANGLE(experimental)'.

Step 4. Play the game and restart.

After you restarted, the toggle for 'Use ANGLE(experimental)' will be turned off instead of staying on like in previous versions of CrDroid.

### Relevant log (logcat/build log)

```shell
I dont know how to get this.
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
experimental features are deemed as named, experimental
so closing this for now
