### ISSUE TITLE
bug: title (<-- face unlock battery consumption)

### ISSUE THREAD

**Issue by Letscodeee** [crdroidandroid/issue_tracker#216]
### Issue type

User interface

### Device

PocoPhone F1 Beryllium

### crDroid version

crDroid 9

### Exact version / Build date

9.7/2023-07-23

### Bug description

Face unlock usage shown incorrectly 

### Steps to reproduce

Step 1 Go to crdroid settings
Step 2 Battery
Step 3 battery usage 
Step 4 Face unlock 

### Relevant log (logcat/build log)

```shell
Nill
```

### Screenshots or videos

![Screenshot_20230726-224929_Settings](https://github.com/crdroidandroid/issue_tracker/assets/91023334/f1423d99-a6ea-4e97-9e06-48e805e2afda)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is no bug

**Comment by Letscodeee** [comment]
> this is no bug

Sorry about that
