### ISSUE TITLE
Face Unlock

### ISSUE THREAD

**Issue by cygiel5420** [crdroidandroid/issue_tracker#217]
### Issue type

Feature not working as intended

### Device

Pixel 7 Pro (cheetah) 

### crDroid version

crDroid 9

### Exact version / Build date

9.7/2023-07-12

### Bug description

Face Unlock in Security Settings not present, while "com.crdroid.faceunlock" app exists in App List. 

### Steps to reproduce

Install Crdroid version 9.7, set up lockscreen unlock, find that Face Unlock is missing/not available. 

### Relevant log (logcat/build log)

```shell
No log available.
```

### Screenshots or videos

![Screenshot_20230726-213730_Pixel Launcher](https://github.com/crdroidandroid/issue_tracker/assets/133622561/f31b57c8-d922-49e3-a075-309f13eb3721)
![Screenshot_20230726-211903_Pixel Launcher](https://github.com/crdroidandroid/issue_tracker/assets/133622561/cd675001-82e7-499d-9dc9-7b94097e513b)

### Solution

In order to have Face Unlock enabled with newest Crdroid version, gain root via Magisk, enable zygisk, install Lsposed module, then UniversalAuth module and app, then set up Face Unlock. 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
@crdroidandroid/coreteam we may need a build flag to conditionally disable faceunlock for devices that wish to

**Comment by ShevT** [comment]
In general, this setting should not be there.
It is located below and is called "Face & Fingerprint Unlock"

**Comment by cygiel5420** [comment]
Agreed, however the setting is only called "Fingerprint". It completely commits Face Unlock. Please refer to attached screenshot below. 

![Screenshot_20230726-213730_Pixel Launcher](https://github.com/crdroidandroid/issue_tracker/assets/133622561/d4dd35ad-ceed-4de7-a68e-266ffcef1438)
###

**Comment by ShevT** [comment]
![IMG_20230727_090639](https://github.com/crdroidandroid/issue_tracker/assets/4339059/6b55f2c5-d490-423f-8b32-9c18f726dd5c)

![Screenshot_20230727-090543_Settings](https://github.com/crdroidandroid/issue_tracker/assets/4339059/9ee14976-939e-43cd-bffe-d92b83bb8b56)

![Screenshot_20230727-090553_Face unlock](https://github.com/crdroidandroid/issue_tracker/assets/4339059/c4571f09-b0e1-495c-bc73-5abbff1b7384)

![Screenshot_20230727-090602_Face unlock](https://github.com/crdroidandroid/issue_tracker/assets/4339059/8c36de9b-989c-4787-a59f-f734db7566b1)

**Comment by cygiel5420** [comment]
> ![IMG_20230727_090639](https://user-images.githubusercontent.com/4339059/256440988-6b55f2c5-d490-423f-8b32-9c18f726dd5c.png)
> 
> ![Screenshot_20230727-090543_Settings](https://user-images.githubusercontent.com/4339059/256441019-9ee14976-939e-43cd-bffe-d92b83bb8b56.png)
> 
> ![Screenshot_20230727-090553_Face unlock](https://user-images.githubusercontent.com/4339059/256441064-c4571f09-b0e1-495c-bc73-5abbff1b7384.png)
> 
> ![Screenshot_20230727-090602_Face unlock](https://user-images.githubusercontent.com/4339059/256441100-8c36de9b-989c-4787-a59f-f734db7566b1.png)

Hmmm... Looking at your screenshots I wonder why it's different for me.

**Comment by DarkJoker360** [comment]
crDroid Face Unlock is currently not working on Pixel 7 series devices, we are working on a solution already.
