### ISSUE TITLE
bug: Ambient Display system crash

### ISSUE THREAD

**Issue by cygiel5420** [crdroidandroid/issue_tracker#218]
### Issue type

Feature not working as intended

### Device

Pixel 7 Pro (cheetah) 

### crDroid version

crDroid 9

### Exact version / Build date

9.7/2023-07-12

### Bug description

System hard crashed randomly while Ambient Display in Crdroid settings was enabled, and phone was charging.

### Steps to reproduce

In this particular scenario:

Enable Ambient Display - all options turned on
Plug phone to charge overnight
Wake up to hard crashed system

### Relevant log (logcat/build log)

```shell
Tombstone attached in comments
```

### Solution

Turn off Ambient Display

### Additional context

System crashed before while Ambient Display was turned on, but did not produce log files for those previous events. It doesn't matter which option is enabled in Ambient Display, each one crashes the system in relation to it's description i.e. AD while charging will cause crash while phone is charging etc. At random, the system hard crashes when AD conditions are met and screen is touched, makes it seem as if sensors freak out, or there's some sort of conflict. 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by cygiel5420** [comment]
![AD_tombstone.txt](https://github.com/crdroidandroid/issue_tracker/files/12207697/tombstone_17.txt)

**Comment by neobuddy89** [comment]
log from matlog

**Comment by neobuddy89** [comment]
crash with reboot?

**Comment by cygiel5420** [comment]
> crash with reboot?

Yep

**Comment by cygiel5420** [comment]
System literally just crashed again with full reboot as I was taking my phone out of the pocket. Same behavior as with Crdroid version 9.5, except this time Tombstone files have been deleted from "data" system folder on reboot, so can't provide crash log for that event. Weird.
