### ISSUE TITLE
bug: Touch Issues in edges

### ISSUE THREAD

**Issue by nurnobi666** [crdroidandroid/issue_tracker#222]
### Issue type

Other

### Device

Sweetin

### crDroid version

crDroid 9

### Exact version / Build date

9.7/2023-07-31

### Bug description

Device: Redmi Note 10 pro max ( Sweetin)
everything is perfect in this rom, 
but i faced touch issues in pubg game. edges touch response was too week to response, i'm four finger pubg player so basically my scope and fire button is on top left and right corner ( near the upper edge ).  when i try to open scope, most of the time ( 90%) it didn't work, now i'm on another rom, and it doesn't has that touch issue, not even a single time i faced. its work absolutely fine. 

Can you guys solve that issue in the next update? 
touch response issue i faced only in pubg mobile, ( I played only pubg mobile)
MIUI game turbo has a feature name " touch resistance edge" ,, there is a option to reduce or increase touch response on the edges. it might be help you to fix that problem, its only my suggestion. But Please fixed that problem in the next update. I really like to use crdroid rom.

### Steps to reproduce

You can just install Pubg mobile and try by your self. just carefully check the all edges touch response.

### Relevant log (logcat/build log)

```shell
i already Uninstall crdroid rom. so can't able to add this.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Sweetin or sweet?

**Comment by nurnobi666** [comment]
Sweetin ( redmi note 10 pro max)
Redmi note 10 pro max also known as a Sweet device.

**Comment by gwolf2u** [comment]
While this may be subjective, I've assigned @neobuddy89 to reply here

**Comment by nurnobi666** [comment]
2 hours back, i flash Crdroid rom again and re-checked that touch issue in pubg mobile. the problem remain same before. I really like to use Crdroid. Please check that issue and solve that in the next update

**Comment by gwolf2u** [comment]
currently no fix can be developed here
