### ISSUE TITLE
bug: night light isn't active on lock screen

### ISSUE THREAD

**Issue by UnlimitedCookies** [crdroidandroid/issue_tracker#225]
### Issue type

User interface

### Device

lemonadep / Oneplus 9 Pro

### crDroid version

crDroid 9

### Exact version / Build date

9.8 / Sun Aug 13 15:08:52 EEST 2023

### Bug description

When locking the screen through the power button the blue light filter is not active anymore. This might be caused by the fingerprint reader, because when an app requests to read the fingerprint, the filter is also deactivated.

### Steps to reproduce

1. Activate night light
2. (Enable schedule)
3. Observe lock screen not being color adjusted

### Relevant log (logcat/build log)

```shell
Not applicable (I think, lmk if that's still required)
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
This is by design in order for FOD to be used
