### ISSUE TITLE
bug: cant install lastest lavender releases

### ISSUE THREAD

**Issue by Yefita** [crdroidandroid/issue_tracker#226]
### Issue type

Other

### Device

Lavender(Redmi Note 7)

### crDroid version

crDroid 9

### Exact version / Build date

9.8/13.0-20230813

### Bug description

Can not update or install this version. it always got error code 1. i check the sha256 and its match, so its not file corrupt problem, at least in my end. 

the error is: 
assert failed: update_dynamic_partitions(package_extract_file("dynamic_partitions_op_list"))
Updater process ended with ERROR: 1
Error installing ZIP file '/sdcard1/OS/crDroidAndroid-13.0-20230813-lavender-v9.8.zip'

the full orangefox log bellow.
i'm not sure if this is crdroid or my fault. so please be kind to me.

### Steps to reproduce

1. reboot to orangefox recovery.
2. flash crDroidAndroid-13.0-20230813-lavender-v9.8.zip

### Relevant log (logcat/build log)

[log file](https://github.com/Yefita/random/blob/main/recovery.log)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
you need to use compatible recovery
https://crdroid.net/lavender/9 (recovery button)
