### ISSUE TITLE
bug: No option for precise/approximate location permission

### ISSUE THREAD

**Issue by pmgying** [crdroidandroid/issue_tracker#227]
### Issue type

Feature not working as intended

### Device

Redmi Note 8T (willow/ginko)

### crDroid version

crDroid 9

### Exact version / Build date

9.8

### Bug description

Since I think about v9.6, for location permission, I lost the option to select precise or approimate location.

I do not know if the following have any effects to this, but let me write it down anyway. Since about v9.6, installing MindTheGapps will result in the crdroid setup storing at the Wifi connection screen. There has been no response no matter if the password is correct or not. The setup process have hence been stuck there forever. Switching to NikGapps (which the device's crdroid page suggests) works, so I did the switch to NikGapps core package. I am not sure if this has anything to do with the location permission issue.

### Steps to reproduce

1. Open any app that requires location permission
2. Give the app permission (either always or while the app is in use)
3. I expect to see a toggle for precise/approximate location. This is what I see in CrDroid previously. This, however, disappeared in the recent months.

### Relevant log (logcat/build log)

```shell
---
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
issue is indeed gapps related
try something for me, even if will require clean flash with format of data
install this gapps https://sourceforge.net/projects/nikgapps/files/Elite-Releases/Gwolf2u/NikGapps-T/

so:
```format data
reboot to recovery
install crdroid zip
reboot to recovery
install gapps zip```

do note reboot to recovery steps are mandatory

**Comment by pmgying** [comment]
Hi gwolf2u,
So I've tested again with your package, and the basic NikGapps package with your sequence of installation. And both allow me to select precise/approx location! Thank you.

Apparently, I missed the reboot before installing gapps. (I had been installing without this reboot, and it did work until recently.)

Thanks again. I'll close the report.

**Comment by pmgying** [comment]
Actually, now I've used it for a while and done some play store updates, I just noticed that the precise/approximate toggle is gone again. :(

I'm not sure when it started to halt working though.

**Comment by pmgying** [comment]
Actually, I've used it for a while last week. And after some google play updates, I noticed that the precise/approximate toggle is gone again. I'm not sure when it started to halt working though.

I tried again today (Aug 23) with your Elite package with the same steps you mentioned. The toggle never appeared at all.

**Comment by gwolf2u** [comment]
I still have it here
Maybe you installed rom update and didn't reboot to recovery to reinstall gapps?
Anyway this is not a rom issue and rather gapps / user install issue, so will close this
