### ISSUE TITLE
bug: Gesture Navigation pill radius cannot be changed (hints can't be disabled either)

### ISSUE THREAD

**Issue by breadland** [crdroidandroid/issue_tracker#228]
### Issue type

User interface

### Device

Xiaomi Mi Pad 5 (nabu)

### crDroid version

crDroid 9

### Exact version / Build date

9.7/August 8, 2023

### Bug description

When switching the system navigation from three-button navigation to gesture navigation, the pill radius will not be reduced despite changing it in the settings.
It's also impossible to hide the gesture navigation hints from anywhere in the settings.
Even using the Magisk Module "Fullscreen/Immersive Gestures" it will still not hide the pill / hints at the bottom of the screen.

### Steps to reproduce

(Steps to reproduce pill thickness issue)

Open settings.
Scroll down to system.
Tap gestures.
Tap system navigation.
Select gesture navigation.
Tap settings for gesture navigation.
Change pill radius to thick or thin.

Nothing will change. Pill thickness at the bottom of the screen remains the same.

(Steps to try to disable navigation hint at the bottom of the screen)
Open settings.
Type in "navigation hint"
An option will appear called "navigation hint" "Show navigation bar at the bottom of the screen"
Tap on it.
You will be brought to the same gesture navigation menu as before but there won't be an option to show/hide the navigation bar.

### Relevant log (logcat/build log)

```shell
N/A
```

### Screenshots or videos

![Screenshot_20230820-201019_Settings](https://github.com/crdroidandroid/issue_tracker/assets/28539261/78947dda-9512-42df-807c-b70befe820b8)

![Screenshot_20230820-201024_Settings](https://github.com/crdroidandroid/issue_tracker/assets/28539261/d83ac90b-b557-4fa7-bf1f-f7193e860b5f)

![Screenshot_20230820-201027_Settings](https://github.com/crdroidandroid/issue_tracker/assets/28539261/7ce54825-0941-4dc4-96f3-0dc13fd53ea4)

### Additional context

I've tried this on a clean install.
Restarting after changing the settings.
Switching back to button and then to gesture navigation again.
Etc.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by breadland** [comment]
I made sure to install the latest update from Aug 27 and the issue still remains so I'll keep this issue open.

**Comment by gwolf2u** [comment]
happening on newer revision?
