### ISSUE TITLE
bug: Logcats flooded with light sensor errors

### ISSUE THREAD

**Issue by snappyapple632** [crdroidandroid/issue_tracker#23]
### Issue type

Source code related

### Device

OnePlus 7 Pro GM1917 (guacamole)

### crDroid version

crDroid 9

### Bug description

Logcats are flooded with errors reporting information about the device's light sensor.

### Steps to reproduce

1. Open MatLog.
2. Observe light sensor errors taking up most of the screen.

### Relevant log (logcat/build log)

```shell
10-29 21:36:05.741 E/sensors-hal(1045): handle_sns_std_sensor_event:74, wise_light: lux 0 ,period 0 ms, data c 0
10-29 21:36:05.952 E/sensors-hal(1045): handle_sns_std_sensor_event:74, wise_light: lux 0 ,period 0 ms, data c 0
10-29 21:36:06.163 E/sensors-hal(1045): handle_sns_std_sensor_event:74, wise_light: lux 1 ,period 0 ms, data c 0
10-29 21:36:06.374 E/sensors-hal(1045): handle_sns_std_sensor_event:74, wise_light: lux 1 ,period 0 ms, data c 0
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by snappyapple632** [comment]
I've confirmed this issue persists after a factory reset.

**Comment by gwolf2u** [comment]
@ShevT you also see this?

**Comment by snappyapple632** [comment]
Not seeing this error anymore as of updating to the Nov. 6 build.

**Comment by gwolf2u** [comment]
Was there, did check 
Also no changes were made to ALS

**Comment by snappyapple632** [comment]
> Was there, did check Also no changes were made to ALS

You're right, I turned on autobrightness and they're still there.

**Comment by ShevT** [comment]
These are not errors. These are informational messages that are marked with "E".
These messages are generated - proprietary/vendor/lib64/sensors.ssc.so
