### ISSUE TITLE
bug: Volume Panel Slider 

### ISSUE THREAD

**Issue by FieldXRocket** [crdroidandroid/issue_tracker#233]
### Issue type

User interface

### Device

Redmi K20 Pro (Raphael)

### crDroid version

crDroid 9

### Exact version / Build date

9.8/2023-08-25

### Bug description

I install this cr droid rom in my device and looks everything is okay but after some time when I restart my device for a reason then I see that my volume panel slider length is abnormally big. 

![Screenshot](https://github.com/crdroidandroid/issue_tracker/assets/141901594/d329ea08-8c4a-4623-b741-9c39f01a11c1)

### Steps to reproduce

.

### Relevant log (logcat/build log)

```shell
.
```

### Screenshots or videos

![Screenshot](https://github.com/crdroidandroid/issue_tracker/assets/141901594/fde72cd6-a326-4836-bb9f-bd9cc23ddca8)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
@firebird11 can you check and/or confirm

**Comment by FieldXRocket** [comment]
> @firebird11 can you check and/or confirm

I am using latest crdroid rom version and i feel that the bug is fixed now because now the volume panel slider length was right after i restart my device.
