### ISSUE TITLE
WIFI and Hotspot not working

### ISSUE THREAD

**Issue by rihm9** [crdroidandroid/issue_tracker#234]
### Issue type

User interface

### Device

Poco X4 Pro (Veux)

### crDroid version

crDroid 9

### Exact version / Build date

9.7/2023-08-27

### Bug description

WIFI not working and Hotspot

### Steps to reproduce

WIFI not working and Hotspot

### Relevant log (logcat/build log)

```shell
WIFI not working and Hotspot
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/143076503/2e22f91f-ced6-46c3-aff3-f04fcdc44bc3

### Additional context

Help me

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
This device is out of support, so we can't provide any assistance 
https://crdroid.net/veux/9
