### ISSUE TITLE
Unable to complete first boot setup: Face unlock doesn't work, no way to skip it

### ISSUE THREAD

**Issue by oneofmanyacdcfanstoo** [crdroidandroid/issue_tracker#236]
### Issue type

Other

### Device

Whoop Tab-8US2 (Unisoc Tiger T310; PowerVR Rogue GE8300, 3GB Ram, 32GB ROM)

### crDroid version

crDroid 9

### Exact version / Build date

Newest available for gsi

### Bug description

During first boot, there is no way to skip setting up Face Unlock. Face unlock does not work (but my stock rom Face Unlock does), and so there is no way to continue setup and use the ROM.

### Steps to reproduce

Boot into ROM first time setup.

### Relevant log (logcat/build log)

```shell
None
```

### Solution

Make Face Unlock setup skippable during first boot or remove it altogether.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unfortunately we don't officially support GSI, so we can't provide any support on that
