### ISSUE TITLE
bug: The opposite person hears an echo of his own voice while using the phone speaker for a call.

### ISSUE THREAD

**Issue by VirajTilekar** [crdroidandroid/issue_tracker#238]
### Issue type

Other

### Device

Redmi Note 8 Pro (begonia)

### crDroid version

crDroid 9

### Exact version / Build date

9.8 / 2023-08-14

### Bug description

Whenever we call someone or receive a call from someone and turn on the speaker phone, the opposite person hears an echo of his own voice.

### Steps to reproduce

1. Call someone
2. Turn on speaker
3. Check for echo on the opposite device

### Relevant log (logcat/build log)

```shell
NA
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ahmedegg** [comment]
I got same issue here, for discord, did you find a fix for it?
