### ISSUE TITLE
bug: pulldown menu not pulling down only fixed with reboot

### ISSUE THREAD

**Issue by vatski** [crdroidandroid/issue_tracker#24]
### Issue type

User interface

### Device

alioth poco f3

### crDroid version

crDroid 8

### Bug description

The pulldown menu you acces after swiping down again after getting to the notification center does not want to appear when swiping. To fix it you can restart the phone but this is hardly practical.

### Steps to reproduce

I cannot tell what causes this problem. Only after some time using the OS does it occur.

### Relevant log (logcat/build log)

```shell
There is no crash so no crashlog
```

### Screenshots or videos

Video showing off the problem:
https://drive.google.com/file/d/18GYlc9G8r8iMh3CUagu_utWijhN2dsFz/view?usp=drivesdk

### Solution

Restart of the device

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
@raystef66 care to check if still supporting cr8

**Comment by raystef66** [comment]
Still supporting cr8.x 
Have never had this experience and tbh not heard this in my F3 group.
You can always PM on TG to look into this further on.
Btw, using the recommended 13.0.3 global?
Using stock kernel or?

**Comment by raystef66** [comment]
Not able to reproduce. As mentioned contact on TG @raystef66 if further support needed.
