### ISSUE TITLE
Bluetooth issue

### ISSUE THREAD

**Issue by hivayz64** [crdroidandroid/issue_tracker#241]
### Issue type

Feature not working as intended

### Device

redmi note 8 pro

### crDroid version

crDroid 9

### Exact version / Build date

9.8

### Bug description

the Bluetooth works so weak 

### Steps to reproduce

....

### Relevant log (logcat/build log)

```shell
....
```

### Screenshots or videos

...

### Solution

....

### Additional context

....

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Irelevant issue
