### ISSUE TITLE
bug Dialer: Numbers are not visible on a light background

### ISSUE THREAD

**Issue by garry-rogov** [crdroidandroid/issue_tracker#243]
### Issue type

User interface

### Device

willow

### crDroid version

crDroid 9

### Exact version / Build date

9.8/2023-09-13

### Bug description

When using a light theme, when the call is already underway, numbers are not visible on a light background

### Steps to reproduce

Use a light theme. Open Dialer, when calling, try to press the numbers, the numbers are not clearly visible

### Relevant log (logcat/build log)

```shell
No log
```

### Screenshots or videos

![photo_2023-09-14_21-57-16](https://github.com/crdroidandroid/issue_tracker/assets/11144513/2e4adca0-74d0-4f1e-a663-d03eaf642aec)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
use custom monet settings and change the color just a tad
really hard to fix all nuances
