### ISSUE TITLE
bug: deskclock - no vibration for alarms and timers

### ISSUE THREAD

**Issue by meiser79** [crdroidandroid/issue_tracker#245]
### Issue type

Feature not working as intended

### Device

Xiaomi Poco F3 (alioth)

### crDroid version

crDroid 9

### Exact version / Build date

crDroidAndroid-13.0-20230916-alioth-v9.8

### Bug description

The vibration feature for alarms and timers in the deskclock app does not work. If you enable vibration in the alarm or in the settings for timers, the phone does not vibrate.

### Steps to reproduce

Setup and alarm with vibration and/or enable vibration in the settings for timers. Then let the alarm be triggered or the timer elapsed.

### Relevant log (logcat/build log)

```shell
cannot find any relevant output in logcat
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment]
Confirmed.
Working on my other devices though. Will take a look into it.
