### ISSUE TITLE
Issue with lock screen mode within system profiles causing Phone to "phone is starting" deadlock

### ISSUE THREAD

**Issue by LifeIsThePain** [crdroidandroid/issue_tracker#246]
### Issue type

Feature not working as intended

### Device

Cepheus (xiaomi mi 9)

### crDroid version

crDroid 9

### Exact version / Build date

crDroid 9.8 Build 2023-09-16 (but a 9.5 build had the same issue, i tested)

### Bug description

During startup the phone will stuck with Message "Phone is starting" and can't use System UI correctly. 

### Steps to reproduce

 How to reproduce: activate and create a system profile(like "home"). Define, that is gets activated by connecting to certain WLAN(at ur home). Define in the system profile("home"), that "lock screen mode" is set to "disable lock screen". Next step, go to default system profile, and activate, that it gets activated when ur "home" WLAN is disconnected. The idea is, that while u home u don't need screen lock method and when u leave home the default system profile is activated again (with screen lock method).
I
f u restart phone (defined wlan "home" is present), and u not fast enough to enter pin(PIN was my screen lock method), u'll end up in a screen "phone is starting" and can't do nothing anymore. Not fast enough means like more like 10s after the Crdroid Logo is finished. If u enter all PINs (SIM and screen lock pin) within 10s after crDroid logo is gone the phone will start correctly. 

### Relevant log (logcat/build log)

```shell
I can't send log since i can't boot phone sucessfully when bug is present.
```

### Solution

while start up u need to be fast to enter PIN (if screen lock method is PIN), then the phone will start normal.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this was fixed in code
should be live if running a build from this week
