### ISSUE TITLE
bug: Sim card settings auto reset when Airplane mode turning on every time

### ISSUE THREAD

**Issue by shahedofficial1** [crdroidandroid/issue_tracker#248]
### Issue type

Other

### Device

Miatoll

### crDroid version

crDroid 9

### Exact version / Build date

9.8/20230910

### Bug description

Everytime I turning on the Airplane mode, the sim card preference automatically resetting. The notification coming up when Airplane mode turned on, "Sim card changed".
Need to select sim preference Everytime I turn on the Airplane mode.

### Steps to reproduce

Step 1: Turn on Airplane mode.
Step 2: Check notification.
Note: Dual sim card must.

### Relevant log (logcat/build log)

```shell
N/A
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by hajiis** [comment]
The same happens for me too.

**Comment by gwolf2u** [comment]
can't confirm this
however am running on crDroid 9.10
do update and let me know if fixed
