### ISSUE TITLE
bug: Gapps getting removed after every system update

### ISSUE THREAD

**Issue by danfr** [crdroidandroid/issue_tracker#249]
### Issue type

Feature not working as intended

### Device

Xiaomi Mi 9T DaVinci

### crDroid version

crDroid 9

### Exact version / Build date

9.9/2023-09-19

### Bug description

After each monthly update all Google services (Gapps) are missing and have to be reinstalled manually. 

I don't know if this is normal behavior, but I find it quite annoying and this means we have to have a computer available when the time comes.

I'm not a long-time crDroid user, but I've had this problem for two months in a row.

### Steps to reproduce

1. Go to crDroid settings
2. Open update panel and install the monthly update
3. Wait for reboot

Then Google-dependent applications complain about missing Google services.

### Relevant log (logcat/build log)

```shell
N/A
```

### Solution

1. Reboot in recovery mode
2. Connect phone to PC via USB
3. Sideload install the latest version of MindTheGapps
4. Reboot

Now every apps are working fine.

### Additional context

I don't know if it matters, but I use TWRP 3.7.0_9_0 as custom recovery image.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is normal for devices that have dynamic partitions
so closing this
```
update ROM
reboot to recovery
install gapps
reboot to new update
```

**Comment by danfr** [comment]
Thank you for your fast answer but how can I fix it permanently ? Is there a way to make partitons static ?

**Comment by gwolf2u** [comment]
> Thank you for your fast answer but how can I fix it permanently ? Is there a way to make partitons static ?

no
