### ISSUE TITLE
bug: adaptive playback doesn't work if we change default playback timeout

### ISSUE THREAD

**Issue by hajiis** [crdroidandroid/issue_tracker#250]
### Issue type

Feature not working as intended

### Device

miatoll

### crDroid version

crDroid 9

### Exact version / Build date

9.9/2023-09-22

### Bug description

Adaptive playback feature doesn't work if we change the playback timeout from 30 seconds to any other.
The music gets paused but it won't resume after volume turned up.

### Steps to reproduce

Go to crdroid settings - turn on adaptive playback back - change playback timeout to 100 seconds - play music - turn the volume down - turn the volume up within 100 seconds, there you can see that the media isn't resuming 

### Relevant log (logcat/build log)

```shell
Na
```

### Solution

NA

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
won't work without google framework 
that's not available in crDroid 9 and won't be
