### ISSUE TITLE
The system's power display is not sensitive

### ISSUE THREAD

**Issue by 1130381752** [crdroidandroid/issue_tracker#251]
### Issue type

User interface

### Device

guacamole

### crDroid version

crDroid 9

### Exact version / Build date

I've always had this problem

### Bug description

The system's power display is not sensitive. When using the mobile phone, the power will not continue to decay, but will drop a bit at a time. For example, it is 90% now, and it will become 85% after half an hour. It will not drop from 90 to 89, 88, 87, etc. 86, 85

### Steps to reproduce

N/A

### Relevant log (logcat/build log)

```shell
N/A
```

### Screenshots or videos

N/A

### Solution

N/A

### Additional context

N/A

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by 1130381752** [comment]
@gwolf2u 
May you have a look at this bug? Thank you very much !

**Comment by gwolf2u** [comment]
known issue, without fix
this is caused by firmware or yet to be found kernel issue
