### ISSUE TITLE
Split Screen and Pin options not appearing 

### ISSUE THREAD

**Issue by Maumin** [crdroidandroid/issue_tracker#252]
### Issue type

Feature not working as intended

### Device

Poco F4 munch

### crDroid version

crDroid 9

### Exact version / Build date

9.9 2023/09/20

### Bug description

When trying to pin an app in the recent tab and long clicking no options appear, can't use split screen nor pin.

### Steps to reproduce

1. Open recent apps
2. Long clicking any app
3. Nothing happens 

### Relevant log (logcat/build log)

```shell
09-25 14:18:22.047 W/WindowManager(1729): removeWindowToken: Attempted to remove non-existing token: android.os.Binder@4f99eee
09-25 14:18:19.615 W/UsageStatsService(1729): Unexpected activity event reported! (com.android.launcher3/com.android.quickstep.RecentsActivity event : 23 instanceId : 263590226)
I don't know what code to copy
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
since with crDroid 9.10, most of the things are rebased, do check on that version as we can't fix issues with crDroid 9.9 as code is forward pushed
if your device gets said version, adb logcat > log.txt, reproduce the issue, attach log here
