### ISSUE TITLE
Dialer: Missing Merge button if conference call

### ISSUE THREAD

**Issue by TechMatrixx** [crdroidandroid/issue_tracker#253]
### Issue type

Source code related

### Device

Oneplus 9 pro

### crDroid version

crDroid 9

### Exact version / Build date

9.9/2023-09-24

### Bug description

Dialer has missing merge button in conference call.

### Steps to reproduce

- Make a call.
- Add another call.
- No merge button

### Relevant log (logcat/build log)

```shell
Not applicable.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [ ] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
Try some other Gapps. Like MindTheGapps

**Comment by TechMatrixx** [comment]
> Try some other Gapps. Like MindTheGapps

Tried, But Same issue.

**Comment by gwolf2u** [comment]
fixed in https://github.com/crdroidandroid/android_packages_apps_Dialer/commit/1dd9de2070d759410eff45da4909ded234a448ed
