### ISSUE TITLE
bug: Overlapping wifi standard symbol

### ISSUE THREAD

**Issue by UnlimitedCookies** [crdroidandroid/issue_tracker#254]
### Issue type

User interface

### Device

lemonadep / Oneplus 9 Pro

### crDroid version

crDroid 9

### Exact version / Build date

9.9 second to latest

### Bug description

As can be seen in the screenshot, the wifi Symbol is not clearly distinguishable.

### Steps to reproduce

Activate wifi standard display in the crdroid status bar settings.

### Relevant log (logcat/build log)

```shell
Not applicable
```

### Screenshots or videos

![Screenshot_20230930-183321_crDroid Home](https://github.com/crdroidandroid/issue_tracker/assets/49200216/894fc4f5-5482-4d62-8c08-baaab158e317)

### Solution

Suggestion: Do not show wifi standard, when the exclamation mark symbol is shown.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by UnlimitedCookies** [comment]
(Also the up and download indicator on the left is cut off, which occurs sometimes)

**Comment by gwolf2u** [comment]
this is simple overlap
disable showing wifi version and you'll be fine
for now this is acceptable
