### ISSUE TITLE
bug: can't unlock screen

### ISSUE THREAD

**Issue by luminaego** [crdroidandroid/issue_tracker#255]
### Issue type

User interface

### Device

Lenovo y700 (GSI)

### crDroid version

crDroid 9

### Exact version / Build date

9.9

### Bug description

I can't unlock device on lock screen
I swipe up gesture bar, but nothing happens and see blank screen
Device unlock mode : swipe mode(not pattern)
I hope this bug is fixed
I don't know this bug only happened my device(Y700 GSI)
Sorry my english

### Steps to reproduce

1.set device unlock mode to swipe
2.lock device and turn on screen
3.try to unlock device by swiping up gesture bar

### Relevant log (logcat/build log)

```shell
I can't dump my device log now
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
GSI not supported officially
