### ISSUE TITLE
Camera Closed

### ISSUE THREAD

**Issue by Adamdcruz** [crdroidandroid/issue_tracker#258]
### Issue type

Feature not working as intended

### Device

Mi 11 lite ne 5g (lisa)

### crDroid version

crDroid 9

### Exact version / Build date

22/09/2023

### Bug description

Camera Closed on social media call at lockscreen while trying to unlock device , when received a call while device is locked state everything is working fine when trying to unlock the deice while on video call camera Closed. Can not turn on back by pressing the enable button on WhatsApp. Need to end the call and call again
.

### Steps to reproduce

Get video call on WhatsApp and same time try to come back from video screen to window mode and then the camera bug will show up

### Relevant log (logcat/build log)

```shell
https://drive.google.com/file/d/10BuW4JpyFoOG3OWSzXVXol-OJJoWUURT/view?usp=drivesdk
```

### Solution

As of now i am using the face unlock feture . May be its conflict with the camera .then can not restart camera again through the WhatsApp 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
no access to log
