### ISSUE TITLE
Battery Bar is missing

### ISSUE THREAD

**Issue by AceDicer** [crdroidandroid/issue_tracker#259]
### Issue type

User interface

### Device

Poco F2 Pro (lmi)

### crDroid version

crDroid 9

### Exact version / Build date

9.10/2023-10-14

### Bug description

Enabling Battery Bar doesn't display the bar at the top-portion of the screen.

### Steps to reproduce

1. Go to the appropriate settings (crDroid Settings/Status Bar/Battery Bar).
2. Enable Battery Bar.
3. No Battery Bar is visible disregarding how you've configured it.

### Relevant log (logcat/build log)

```shell
No entries in log related to toggling Battery Bar on and off multiple times.
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by cygiel5420** [comment]
Same issue on Pixel 7 Pro (cheetah) crdroid version 9.10

Here's what my log says:

10-27 05:44:20.976 D/ConstraintsHelper(21862): construct key=statusbar_battery_bar_blend_color available=true
10-27 05:44:20.977 D/ConstraintsHelper(21862): construct key=statusbar_battery_bar_blend_color_reverse available=true
10-27 05:44:20.978 D/ConstraintsHelper(21862): construct key=statusbar_battery_bar_animate available=true
10-27 05:44:20.979 D/ConstraintsHelper(21862): construct key=statusbar_battery_bar_enable_charging_color available=true
10-27 05:44:22.215 W/FrameTracker(21862): Missing HWUI jank callback for vsyncId: 327807, CUJ=J<SETTINGS_TOGGLE::statusbar_battery_bar>
10-27 05:44:22.215 W/FrameTracker(21862): Missing HWUI jank callback for vsyncId: 327829, CUJ=J<SETTINGS_TOGGLE::statusbar_battery_bar>
10-27 05:44:22.215 W/FrameTracker(21862): Missing HWUI jank callback for vsyncId: 327873, CUJ=J<SETTINGS_TOGGLE::statusbar_battery_bar>
10-27 05:44:22.215 W/FrameTracker(21862): Missing HWUI jank callback for vsyncId: 327939, CUJ=J<SETTINGS_TOGGLE::statusbar_battery_bar>
10-27 05:44:22.215 W/FrameTracker(21862): Missing HWUI jank callback for vsyncId: 327961, CUJ=J<SETTINGS_TOGGLE::statusbar_battery_bar>
10-27 05:44:22.215 W/FrameTracker(21862): Missing HWUI jank callback for vsyncId: 328078, CUJ=J<SETTINGS_TOGGLE::statusbar_battery_bar>
10-27 05:47:12.986 W/FrameTracker(21862): Missing HWUI jank callback for vsyncId: 455806, CUJ=J<SETTINGS_TOGGLE::statusbar_battery_bar>
10-27 05:47:12.986 W/FrameTracker(21862): Missing HWUI jank callback for vsyncId: 455872, CUJ=J<SETTINGS_TOGGLE::statusbar_battery_bar>
10-27 05:47:16.477 W/FrameTracker(21862): Missing HWUI jank callback for vsyncId: 457988, CUJ=J<SETTINGS_TOGGLE::statusbar_battery_bar>
