### ISSUE TITLE
bug: Inability to enable 120Hz refresh rate

### ISSUE THREAD

**Issue by DavidRLTG** [crdroidandroid/issue_tracker#26]
### Issue type

Other

### Device

M2012K11AG / Poco F3 / Redmi K40

### crDroid version

crDroid 9

### Bug description

Seriously! I looked in display settings, developer settings, everywhere, but I was unable to find any option to enable it! Except, well, Per-App refresh rate. Pretty unfortunate!

### Steps to reproduce

Simply open settings on the device, you will not find it anywhere

### Relevant log (logcat/build log)

```shell
There is nothing really relevant in the log..
```

### Solution

Simply, add a way, ANY WAY to enable 120Hz.
*besides per-app pls*

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is not a but, but rather a design choice

**Comment by DavidRLTG** [comment]
With all due respect,
This may be one of the stupidest design choices I've seen in a ROM so far.
But, got it! Have a good day.

**Comment by gwolf2u** [comment]
> With all due respect, This may be one of the stupidest design choices I've seen in a ROM so far. But, got it! Have a good day.

maintainer reason here
https://github.com/crdroidandroid/android/issues/106#issuecomment-1296275636
