### ISSUE TITLE
bug: Disappearing screenshot editing functions after setting Markup as default application

### ISSUE THREAD

**Issue by MisiekDP** [crdroidandroid/issue_tracker#260]
### Issue type

Feature not working as intended

### Device

OnePlus 7 Pro (guacamole)

### crDroid version

crDroid 9

### Exact version / Build date

crDroid 9.10/2023-10-15

### Bug description

Gapps used with this problem: NikGapps-Gwolf2u-arm64-13-20231010-signed

Setting the Markup application from the Gapps package as the default (forever) when editing screenshots prevents editing a screenshot after clicking the edit opltion of a previously created screenshot.
When the Markup app is not set as default (forever) and is used one time with the app selection window (only once) the bar with editing functions appears correctly.

As a bar with editing functions should be understood:
![image](https://github.com/crdroidandroid/issue_tracker/assets/22171619/9c60b3af-3b10-43ee-8f5c-20b5e23aaeae)

### Steps to reproduce

1. Set Markup as the default application for editing screenshots.
2. Take a screenshot.
3. Click on the editing option just after taking the screenshot.

### Relevant log (logcat/build log)

```shell
The adb log file is too large to paste and crashes the browser when pasting, so I include it as a text file reference:

https://puu.sh/JSGZp/474ee13677.txt
```

### Screenshots or videos

When Markup is not set as default application:
![image](https://github.com/crdroidandroid/issue_tracker/assets/22171619/47778b30-dc45-4b42-a462-fcc56fade303)

When Markup is set as default application:
![image](https://github.com/crdroidandroid/issue_tracker/assets/22171619/efdd7afa-1965-4c35-ac0f-0ffe4323142f)

Video to better illustrate the problem:
https://github.com/crdroidandroid/issue_tracker/assets/22171619/877e795f-d0b9-4cbd-b05a-0334e2c5c6ad

### Additional context

I will also add that I am not the only one with this problem (other users also have the same problem)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unfortunately I can't reproduce
even said so on Telegram
not sure if is Nikgapps issue also
@nikhilmenghani care to update on this issue if you have any updates?

**Comment by MisiekDP** [comment]
@gwolf2u I discovered something. I just noticed that the problem occurs when I have full screen gestures enabled and I also have a hidden pill at the bottom of the screen.  Can you check this?
What's more interesting is that when I display the pill, the options bar in Markup displays correctly.

![Screenshot_20231021-135400_Markup](https://github.com/crdroidandroid/issue_tracker/assets/22171619/2d016d09-9715-4d6b-bb4f-6abe125fa094)
![Screenshot_20231021-135544_Ustawienia](https://github.com/crdroidandroid/issue_tracker/assets/22171619/7389cf84-cb08-4982-b728-66e21667df94)
![Screenshot_20231021-140724_Markup](https://github.com/crdroidandroid/issue_tracker/assets/22171619/637049a6-c5e7-454d-a775-5f7ef563f490)

**Comment by MisiekDP** [comment]
@gwolf2u Have you tried to reproduce the problem I described above?

**Comment by jason-stream** [comment]
Mine disappears when I try to do a long screenshot, and this was off of a clean flash
