### ISSUE TITLE
bug: "Now Playing" feature not working

### ISSUE THREAD

**Issue by dimitarkolevdtd** [crdroidandroid/issue_tracker#262]
### Issue type

Feature not working as intended

### Device

Pixel 7 Pro (cheetah)

### crDroid version

crDroid 9

### Exact version / Build date

9.9/2023-09-25

### Bug description

The "Now Playing" feature is not recognising music.

Trying to toggle it in settings will sometimes make Android System Intelligence crash.

Trying to turn on the "Show search button" option will show the message "The search button is being set up", but that message will never disappear and the button will never appear on the lock screen.

The feature works correctly on the latest version of stock Android 13, as well as on the latest version of LineageOS 20.

### Steps to reproduce

Step 1. Get a fresh install of crDroid with NikGapps (the issue persists on every package, even on "full").
Step 2. Go through initial setup.
Step 3. Open the Google Play store and update all Google apps.
Step 4. Go to "Settings" > "Sound and vibration" > "Now Playing".
Step 5. Toggle on "Identify songs playing nearby", get kicked out of "Now Playing".
Step 6. Repeat 4 and 5 until Android System Intelligence crashes.
Step 7. Upon re-entering "Now Playing", the toggle will be on and the message "Downloading songs database" will be visible. Wait for the songs database to be downloaded.
Step 8. Play any popular song on another device. Observe that no recognition occurs.
Step 9. Toggle "Show search button on the lock screen". The message "The search button is being set up" will appear, but the search button will never show up on the lock screen.

### Relevant log (logcat/build log)

```shell
10-22 20:36:05.908 E/AiAi    (27332): (REDACTED) AiaiUncaughtExceptionHandler: %s.
10-22 20:36:05.908 E/AiAi    (27332): 
10-22 20:36:05.908 E/AiAi    (27332): Detailed stack trace: %s
10-22 20:36:05.908 E/AiAi    (27332): java.lang.ArrayIndexOutOfBoundsException: length=23488; index=28716
10-22 20:36:05.908 E/AiAi    (27332): 	at qbq.a(PG:161)
10-22 20:36:05.908 E/AiAi    (27332): 	at qgg.c(PG:20)
10-22 20:36:05.908 E/AiAi    (27332): 	at osp.w(PG:1052)
10-22 20:36:05.908 E/AiAi    (27332): 	at osp.e(PG:60)
10-22 20:36:05.908 E/AiAi    (27332): 	at osp.d(PG:14)
10-22 20:36:05.908 E/AiAi    (27332): 	at osq.onSharedPreferenceChanged(PG:24)
10-22 20:36:05.908 E/AiAi    (27332): 	at android.app.SharedPreferencesImpl$EditorImpl.notifyListeners(SharedPreferencesImpl.java:637)
10-22 20:36:05.908 E/AiAi    (27332): 	at android.app.SharedPreferencesImpl$EditorImpl.apply(SharedPreferencesImpl.java:511)
10-22 20:36:05.908 E/AiAi    (27332): 	at androidx.preference.Preference.Q(PG:7)
10-22 20:36:05.908 E/AiAi    (27332): 	at androidx.preference.TwoStatePreference.k(PG:74)
10-22 20:36:05.908 E/AiAi    (27332): 	at com.android.settingslib.widget.MainSwitchPreference.ag(PG:1)
10-22 20:36:05.908 E/AiAi    (27332): 	at com.android.settingslib.widget.MainSwitchBar.onCheckedChanged(PG:21)
10-22 20:36:05.908 E/AiAi    (27332): 	at android.widget.CompoundButton.setChecked(CompoundButton.java:222)
10-22 20:36:05.908 E/AiAi    (27332): 	at android.widget.Switch.setChecked(Switch.java:1260)
10-22 20:36:05.908 E/AiAi    (27332): 	at android.widget.Switch.toggle(Switch.java:1244)
10-22 20:36:05.908 E/AiAi    (27332): 	at android.widget.CompoundButton.performClick(CompoundButton.java:144)
10-22 20:36:05.908 E/AiAi    (27332): 	at com.android.settingslib.widget.MainSwitchBar.performClick(PG:3)
10-22 20:36:05.908 E/AiAi    (27332): 	at android.view.View.performClickInternal(View.java:7519)
10-22 20:36:05.908 E/AiAi    (27332): 	at android.view.View$PerformClick.run(View.java:29489)
10-22 20:36:05.908 E/AiAi    (27332): 	at android.os.Handler.handleCallback(Handler.java:942)
10-22 20:36:05.908 E/AiAi    (27332): 	at android.os.Handler.dispatchMessage(Handler.java:99)
10-22 20:36:05.908 E/AiAi    (27332): 	at android.os.Looper.loopOnce(Looper.java:201)
10-22 20:36:05.908 E/AiAi    (27332): 	at android.os.Looper.loop(Looper.java:288)
10-22 20:36:05.908 E/AiAi    (27332): 	at android.app.ActivityThread.main(ActivityThread.java:7936)
10-22 20:36:05.908 E/AiAi    (27332): 	at java.lang.reflect.Method.invoke(Native Method)
10-22 20:36:05.908 E/AiAi    (27332): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
10-22 20:36:05.908 E/AiAi    (27332): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:854)
10-22 20:48:14.067 E/ClientCache(439): failed to get buffer, invalid process token
10-22 20:48:14.068 E/BpTransactionCompletedListener(439): Failed to transact (-32)
10-22 20:48:14.121 E/ogle.android.as(28804): Not starting debugger since process cannot load the jdwp agent.
10-22 20:48:14.641 E/AiAiEcho(28804): EchoSearch: SettingsFetcherImpl: DB already exists.
10-22 20:48:14.937 E/tflite  (26404): third_party/tensorflow/lite/core/subgraph.cc:1059 tensor.data.raw != nullptr was not true.
10-22 20:48:15.440 E/tflite  (26404): third_party/tensorflow/lite/core/subgraph.cc:1059 tensor.data.raw != nullptr was not true.
10-22 20:48:15.700 E/SP.Service.AiAi(28804): captions_i18n_v0_en-US is opened by other clients. It will stay open until all clients close it.
10-22 20:48:15.706 E/SP.Service.AiAi(28804): captions_i18n_v0_mandatory is opened by other clients. It will stay open until all clients close it.
10-22 20:48:20.698 E/ThemeUtils(12479): View class androidx.appcompat.widget.AppCompatTextView is an AppCompat widget that can only be used with a Theme.AppCompat theme (or descendant).
```

### Screenshots or videos

![Screenshot_20231022-205045_Settings](https://github.com/crdroidandroid/issue_tracker/assets/72911640/81f0190e-d0bb-425f-9efe-9cd09dcaf285)
![Screenshot_20231022-205054_Android System Intelligence](https://github.com/crdroidandroid/issue_tracker/assets/72911640/481c88b5-e675-4f5f-a420-af9c4817dab7)

### Additional context

This is the crash log URL: https://paste.crdroid.net/rE8ymb

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jason-stream** [comment]
Have you tried with a NikGapps config ?
Does anyone else on XDA/Telegram have the issue?

**Comment by dimitarkolevdtd** [comment]
> Have you tried with a NikGapps config?
Please elaborate? I am currently using the NikGapps config file to get just the specific apps I need, but while troubleshooting I did try to enable everything manually. However, that shouldn't be necessary, since as far as I know NikGapps full does include everything.

> Does anyone else on XDA/Telegram have the issue?
If I recall correctly, there was an XDA thread about it, but it's pretty old and doesn't contain a working solution. I didn't find anything on Telegram, no duplicate issue here on GitHub either.

**Comment by jason-stream** [comment]
As in using the config if possible to exclude the installation of ASI, then installing it manually yourself from Play Store or apk.

I know most have had issues related to ASI not having some internet permissions enabled.

**Comment by neobuddy89** [comment]
We do not have google implementation in backend. I dont expect this to work.

**Comment by jason-stream** [comment]
> We do not have google implementation in backend. I dont expect this to work.

In which case their best bet for the moment might be the Ambient Music Mod I've linked above.
