### ISSUE TITLE
audio bt no working as it should

### ISSUE THREAD

**Issue by frankh93** [crdroidandroid/issue_tracker#263]
### Issue type

Feature not working as intended

### Device

Poco X5 Pro (redwood)

### crDroid version

crDroid 9

### Exact version / Build date

9.10/2023-10-15

### Bug description

Using any bt device to listen to music (headphones, speaker) it happens that when I get a notification could happen 2 scenarios:

The music gets cut in headphones/speaker and the notification sound get in the phone speaker, once that sound is played the music I was listening to comes back to the headphones/speaker
The music stop in headphones/speaker and start getting from the phone speaker without any sound made by the notification
I reported this already in the tg group but nobody has answered me so I came here looking for some help as this issue is being some annoying now. If it helps somehow, I'm using Poco X5 Pro (redwood) with latest CrDroid 9.10

Thanks beforehand

### Steps to reproduce

1. play any song in any app
2. get a notification from any app
3. it gonna happen any of the 2 scenarios I said above

### Relevant log (logcat/build log)

```shell
No logcat taken
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jason-stream** [comment]
The logs would help the developers A LOT in isolating the issue
