### ISSUE TITLE
Screen turns on and stays on for some notifications when locked

### ISSUE THREAD

**Issue by zuixalias** [crdroidandroid/issue_tracker#264]
### Issue type

Feature not working as intended

### Device

ginkgo, Redmi Note 8

### crDroid version

crDroid 9

### Exact version / Build date

9.10/2023-10-16

### Bug description

I have "Wake screen for notifications" off in my settings and all settings that might be related to this i have checked, still the phone screen turns on for notifications from some apps, once in a while, or sometimes randomly without any notification and stays on.

It used to happen once in a while but it's happening frequently these days (two days in a row), possibly due to the new apps that i have installed - Amazon, etc.

This has been and issue since i started using CrDroid, which is since Android 12.

### Steps to reproduce

No steps, maybe try installing Amazon, it seems make the issue happen on almost every notification or maybe just on delivery related notifications? (not sure)

### Relevant log (logcat/build log)

```shell
(will attach a file)
```

### Additional context

The issue was less frequent and did not affect usage but whenever it happens, the screen stays on and battery drains accordingly...unless the screen is manually turned off.

I believe Amazon app's order related notifications trigger it everytime, while other apps don't/ only on some notifications from specific apps/ or maybe it's not notifications related at all?...again, haven't observed enough to be sure.

### Acknowledgements

- [x] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
#nofix
