### ISSUE TITLE
bug: Alarm not always ringing (increasing vol)

### ISSUE THREAD

**Issue by andrewille** [crdroidandroid/issue_tracker#269]
### Issue type

Feature not working as intended

### Device

Poco F3 (alioth)

### crDroid version

crDroid 9

### Exact version / Build date

10.0/2023-11-11

### Bug description

When setting up an alarm in [DeskClock](https://github.com/crdroidandroid/android_packages_apps_DeskClock) and enabling "increasing volume", it does wake the device but the ringtone itself is silent most of the times. There seems to be a race condition.

### Steps to reproduce

1. Open DeskClock
2. Enable increasing volume
3. Set an alarm (for the next minute or so)
4. It will be silent if you are unlucky (if not, repeat again)

### Relevant log (logcat/build log)

```shell
Will create and paste one if needed, but the fix should be clear anyways.
```

### Solution

Re-apply commit [e45f4dc](https://github.com/crdroidandroid/android_packages_apps_DeskClock/commit/e45f4dcb53e17436a102966328f3ef70df074b6b).
I would have created a pull request, but branch 14.0 is not publicly visible (yet??).

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ShevT** [comment]
Yes. I confirm the problem. I have already written about it. I'll check the commit....

**Comment by ShevT** [comment]
Fixed
