### ISSUE TITLE
Stock cam not working

### ISSUE THREAD

**Issue by Mikoga92** [crdroidandroid/issue_tracker#27]
### Issue type

Other

### Device

lmi

### crDroid version

crDroid 9

### Bug description

The rear doesn't work at all. Camera app shows only black screen.

When it is swapped to front camera and closed and reopened, then the front camera works.

### Steps to reproduce

Step 1: Open stock camera
Doesn't work, neither front or rear camera

Or

Step 1: open stock camera.
Step 2: Swap to front camera and close the app and reopen.
Front camera works.

### Relevant log (logcat/build log)

```shell
10-31 15:51:23.276 E/CamX    (29533): [ERROR][CORE   ] camxchicontext.cpp:4372 CreatePipelineDescriptor() pipelineName: RealTimeFeatureZSLPreviewRaw usage: 00020000
10-31 15:51:23.276 E/CamX    (29533): [ERROR][CORE   ] camxchicontext.cpp:4372 CreatePipelineDescriptor() pipelineName: RealTimeFeatureZSLPreviewRaw usage: 00020900
10-31 15:51:23.276 E/CamX    (29533): [ERROR][CORE   ] camxpipeline.cpp:317 Initialize() Pipeline: RealTimeFeatureZSLPreviewRaw isSecureMode: 0
10-31 15:51:23.278 E/android.hardware.camera.provider@2.4-service_64(29533): AIScene:m_IndiaModelPrio 0 AI_SCENE_IN_INDIA 0
10-31 15:51:23.278 D/DirtyCamera(29533): [D][/dirtycamera_api.cpp(201)]:DirtyCamera construct...
10-31 15:51:23.278 I/XIAOMI_AIASD(29533): asd dirty ver=dirty_camera_2.3
10-31 15:51:23.278 D/DirtyCamera(29533): [D][/dirtycamera_api.cpp(264)]:DirtyCamera initialize success (background): 0.044922
10-31 15:51:23.299 I/LDC-NODE(29533): [Init()]:[222] LDC INFO [255-9],mode=5,type=0,CameraTypeId=0,viewAngle=78.300003 active(2592x1940)
10-31 15:51:23.307 E/CamX    (29533): [ERROR][FORMAT ] camximageformatmapper.cpp:754 FillImageFormatInfo() ==> isQtiMapperAvailable 1
```

### Additional context

The device has the zoom module installed.

I'm not sure whether it is the right log i added. Never done this before. i also filtered with the word 'cam'.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment]
New cr9 build does not support the zoom edition at the moment.
On F2 Pro TG group this has been mentioned. Looking into this as being kernel issue as we figured out.
So stay tuned in TG group.
(atm testing builds to hopefully fix that issue)
Temp Fox : **For now you can just flash Immensity kernel of Macka' one.**
