### ISSUE TITLE
Battery percentage inside icon visibility.

### ISSUE THREAD

**Issue by jason-stream** [crdroidandroid/issue_tracker#270]
### Issue type

User interface

### Device

Device irrelevant as the issue is present across multiple devices' UI, as witnessed on personal device and screenshots of other users' devices in the Telegram CrDroid group.

### crDroid version

crDroid 9

### Exact version / Build date

(CrDroid 10 was unavailable in the drop-down selection)
(Which is odd as 7 and 8 are still shown but as far as I know are mostly no longer maintained, while 9 is nearing EOL and 10 is coming on stream)

Android version : 14
CrDroid version : 10.0-BETA
Build number : UP1A.231105.003

### Bug description

LOW PRIORITY ISSUE ;

Battery percentage inside landscape icon (left or right) graphic seems to be missing a degree of clarity in terms of contrast, or over contrasting, of background versus foreground.

Landscape icon's size is not uniform with the rest of the icon sizes in the status bar.

### Steps to reproduce

Enable showing battery percentage inside the icon under CrDroid settings.

### Relevant log (logcat/build log)

```shell
None required.
```

### Screenshots or videos

![Screenshot_20231114-220913_Brave~2](https://github.com/crdroidandroid/issue_tracker/assets/13890252/122f303d-af58-47b7-89dd-e32f28f87f56)

![Screenshot_20231114-220921_Brave~2](https://github.com/crdroidandroid/issue_tracker/assets/13890252/45f19fd1-6e5e-492a-b9c7-dcf410ef4455)

### Solution

Possible modification(s) at source required, and/or additional customisation allowed/enabled/given/added for users of different devices.

Suggestion;

![Screenshot_20231114-220825_Brave~3](https://github.com/crdroidandroid/issue_tracker/assets/13890252/6beac36a-7334-460a-8f61-4df0f40ea04c)

### Additional context

CrDroid user interface uniformity.

I don't know what to put here, it's a relatively minor issue to focus on in my opinion in comparison to let's say HD Audio over LDAC on Bluetooth.

I decided to put it because it has "irked" me over a few versions/updates and hoped that maybe this time if I say something it may go toward a solution? Better/improved look?

With all the changes and work going into pushing CrDroid 10 I don't expect much as the issue is so minor you could probably go to jail just for looking at it funny.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jason-stream** [comment]
.

**Comment by gwolf2u** [comment]
we are still tweaking crDroid 10, so wait until released
