### ISSUE TITLE
rmx1971 repo init android 13 afte that compile and when try on realme 5 pro it stuck on boot.... On old version 9.10 crdroid trees we use had worked.

### ISSUE THREAD

**Issue by Jordibgzashtita** [crdroidandroid/issue_tracker#272]
### Issue type

Other

### Device

Realme 5 pro BEWARE.... after crdroid 9.11 realme 5 pro sdm710 just stop work.... it stuck on boot on old version 9.10 was working nothing changed in trees. On telegram im blocked... very disgraced.... latest working mode... was i imported my mother data and screen power has dissapeared.... when press power screen inmediatelly bring on desktop not lock screen. on every restart crdroid 9.10 has welcomed lock screen. after unblock sim pin, again lock screen dissapeared.... im thinking change on other custom rom.... person maked test and it was wokring flaweshly.... very digraced

### crDroid version

crDroid 9

### Exact version / Build date

9.10

### Bug description

if device realme 5 pro is not supported im changing on another custom rom and telegram group a spanish person BLOCKED men.... very disgraced.... include there i show video proof

### Steps to reproduce

just dont install crdroid

### Relevant log (logcat/build log)

```shell
no logs....
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Sorry to hear that your device has issues, but you bug report is really bad
Will close as breaks Acknowledgements
Breaks:
 * I have written a short but informative title.
 * I filled out all of the requested information in this issue properly.

Please resubmit issue properly
