### ISSUE TITLE
Make dialer notification persistence when call in progress

### ISSUE THREAD

**Issue by Jobatphysics** [crdroidandroid/issue_tracker#273]
### Issue type

Feature not working as intended

### Device

Mi439

### crDroid version

crDroid 10

### Exact version / Build date

UP1A.231105.003

### Bug description

Call notification shouldn't be easily clearable or swipeable. Because after that we can not return call ui 

### Steps to reproduce

Just call someone and swipe notification from qs panel

### Relevant log (logcat/build log)

```shell
No log needed
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
This is AOSP design by google.

https://www.reddit.com/r/tasks/comments/16g7qgi/cant_figure_out_persistent_notifications/
