### ISSUE TITLE
bug: Ota update not working  

### ISSUE THREAD

**Issue by Pfailo** [crdroidandroid/issue_tracker#274]
### Issue type

Ota update not working

### Device

pocco f2 pro

### crDroid version

crDroid 10

### Exact version / Build date

[ROM][14.0][BETA][OFFICIAL][LMI] crDroid v10.0 [17.11.2023]

### Bug description

issue: picture with app must closing

### Steps to reproduce

bug: Ota Update not working

### Relevant log (logcat/build log)

```shell
?
```

### Additional context

Please raysteff66, can you please include smart charging nearby in the next build?
I have to charge my smartphone evry day use it very often, otherwise it is very annoying.
thanks in advance!

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jason-stream** [comment]
It's extremely difficult to isolate an issue with next to no information.

Ok.

OTA update doesn't work, you claim.

HOW ?

Video ?
Logs ?
More descriptive details as to what happens?

Make an effort to support your issue claim or it'll get buried and/or ignored and/or closed.
