### ISSUE TITLE
Floating rotate button cannot be disabled

### ISSUE THREAD

**Issue by guanglinn** [crdroidandroid/issue_tracker#276]
### Issue type

User interface

### Device

Xiaomi Mi Max 2 (oxygen)

### crDroid version

crDroid 9

### Exact version / Build date

9.11/2023-11-20

### Bug description

After I disabled the option, the floating rotate button still show.

### Steps to reproduce

Settings→crDroid Settings→USER INTERFACE→disable Floating rotate button→rotate your device

### Relevant log (logcat/build log)

```shell
No log output
```

### Screenshots or videos

![Screenshot_20231124-151839_Settings~2](https://github.com/crdroidandroid/issue_tracker/assets/60415467/f42c5e1f-2963-4257-b7a1-3f0be501aee6)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
#nofix
