### ISSUE TITLE
When overheating, the mobile signal turns off and the device is forced to turn off

### ISSUE THREAD

**Issue by dlkrt** [crdroidandroid/issue_tracker#278]
### Issue type

Other

### Device

Redmi K20 Pro (raphael)

### crDroid version

crDroid 10

### Exact version / Build date

10.0-BETA/2023-12-30

### Bug description

When I play games, the device gets warm as expected. At a certain threshold (I don’t know the value), the mobile signal of SIM cards is completely turned off, no one can call me. A push notification “Your device is heating up” appears. After some time, if heating continues, the device turns off and does not even reboot. After turning it on, another notification appears: “Your device has been turned off due to overheating.”
There was no such problem on 9.11 cdDroid. I've seen this problem on other ROMs, including EvoX. When I reported a similar problem to them, they reported that this was a feature and that’s how it was intended.
I chose crDroid only because there was no such “feature”.

### Steps to reproduce

1. Run Genshin Impact or Honkai Star rail at ultra settings
2. Play 10 minutes
3. Device turns off with notifications

### Relevant log (logcat/build log)

```shell
I have a strange bug, adb logcat returns
"logcat: Logcat read failure: No such file or directory"
```

### Screenshots or videos

![image](https://github.com/crdroidandroid/issue_tracker/assets/53973634/09e1d0ed-32cd-49e4-9160-9b0f841541b6)
![image](https://github.com/crdroidandroid/issue_tracker/assets/53973634/06c64f57-25f9-42ad-8b84-b1a8813f58ca)

### Solution

Rollback to 9.11 crDroid

### Additional context

I've tried Bool-X kernel 4.14.329 insted of ROM stock Soviet Star, it didn't help, so, I guess, it's a related ROM problem.
I would like to disable this protection if possible.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
This is by design, no issue
When phone is too hot, this can result in damage, so in order to protect the device, kernel triggers limits and warns the system about the high temp
