### ISSUE TITLE
SystemUI: Bottom of notification panel is weird 

### ISSUE THREAD

**Issue by songlongdaiduong** [crdroidandroid/issue_tracker#28]
### Issue type

User interface

### Device

beyond1lte

### crDroid version

crDroid 9

### Bug description

Bottom of notification panel is weird

### Steps to reproduce

Fully pull down the notification panel

### Relevant log (logcat/build log)

```shell
No crash log
```

### Screenshots or videos

![199098731-14170e16-da06-4156-9876-4870ae256df3](https://user-images.githubusercontent.com/117042414/199274355-5a011915-cfc5-4911-9af1-58825a5d3a32.jpg)

![199098733-7363b47d-bf2b-464f-ac33-b0be28ef4751](https://user-images.githubusercontent.com/117042414/199274392-a3e75a65-a30a-4ae1-8c99-c9d632ff4781.jpg)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unofficial device for now, yet this is by design
