### ISSUE TITLE
bug: Whatsapp messages not receiving(<-- change me)

### ISSUE THREAD

**Issue by ronrozenberg** [crdroidandroid/issue_tracker#280]
### Issue type

User interface

### Device

OnePlus 7 pro (guacamole)

### crDroid version

crDroid 10

### Exact version / Build date

2.12.23

### Bug description

Whatsapp messages not being received until opening app 50% of the time

### Steps to reproduce

1. Download Whatsapp
2. Send yourself messages from another phone
3. Notice they don't always show up

### Relevant log (logcat/build log)

```shell
None
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Can't confirm this one
On my guacamole all messages arrive just on time
I use whatsapp almost every day
