### ISSUE TITLE
Internet browser locking up

### ISSUE THREAD

**Issue by elmkay3** [crdroidandroid/issue_tracker#282]
### Issue type

Feature not working as intended

### Device

Galaxy S5 LTE (SM-G900F)

### crDroid version

crDroid 7

### Exact version / Build date

7.36/2023-11-16

### Bug description

When attempting to use mobile internet, the browser will lock up while loading any variety of web pages. Cannot enter text, scroll up or down or change tab. Closing and reopening the app doesn't change anything, it just locks up immediately again before loading any page, and the freeze will carry over to any browser installed on the device. Only rebooting will reset the issue. Also the device has randomly stopped recognizing the SIM card, going to "no SIM" instead of my network provider. This has only occurred once.

### Steps to reproduce

Open stock browser and just try running various web pages, the app should lock up pretty fast. If not, then I guess it's an issue specific to my device for some reason.

### Relevant log (logcat/build log)

```shell
N/A
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jason-eu** [comment]
The logs would help

**Comment by gwolf2u** [comment]
no logs, so can't assist

**Comment by elmkay3** [comment]
I'm new to this, and didn't know how to get logs. I do now, but the length of the log is incredibly long and goes over the maximum character count of 65536. Is there a way I should be narrowing it down to a reasonable length?

**Comment by jason-eu** [comment]
> I'm new to this, and didn't know how to get logs. I do now, but the length of the log is incredibly long and goes over the maximum character count of 65536. Is there a way I should be narrowing it down to a reasonable length?

Upload it in a zip file

**Comment by elmkay3** [comment]
In a comment below I assume, have done. Thanks.
