### ISSUE TITLE
Mobile data arbitrary not working/phone freezing (rarely)

### ISSUE THREAD

**Issue by kalcho89** [crdroidandroid/issue_tracker#283]
### Issue type

Feature not working as intended

### Device

MI9T Pro Raphael.

### crDroid version

crDroid 9

### Exact version / Build date

9.11, TQ3A.230901.001

### Bug description

1. Random Mobile Data issues ( "!" exclamation mark on each sim status icon) and no internet.
Weirdly enough even with this issue at hand - some traffic still flows (like Whatsapp messages) but other like websites/Google maps/fast.com are showing "you're offline". Complete restart of the phone fixes the issue. Tried mobile networks reset which sometimes fixes it , sometimes not. Safer option is to reboot the phone.
2. Issue is exaggerated when phone is in low cellular coverage area (passing a tunnel/ in a basement/ rural area). Once you are in an area with good cellular reception again there's almost 90% chance mobile data will be bugged and you have to restart. Was passing a tunnel the other day and lost my way on the GPS nav. Restarting phone while driving is not recommended  :P
3. Random (but rare) freezing and black screen. Happened 2-3 times in combination with the above. Had to force reboot phone (holding power button for 6 seconds).
4. Extreme battery wear and heat whilst the phone has no signal/low reception.

### Steps to reproduce

1. Go to your basement/place where you'll loose cellular reception and come out in a while.
2. OR swap between WiFi-Mobile data a few times.
3. Mobile SIM Data might be with "!" Exclamation mark and not working until you restart the phone.

### Relevant log (logcat/build log)

```shell
N/A
```

### Screenshots or videos

N/A

### Solution

workaround : restarting the phone.

### Additional context

Mi 9t Pro mobile phone bought in December 2019. GLOBAL Version.
Was always on stock ROM till two weeks back when first heard good things about CrDroid. Very satisfied with it so far besides the few bugs mentioned in this bug report.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by kalcho89** [comment]
adding a follow up - possible workaround/solution : 
1. Completely reset the network / SIM settings.
2. Delete all "Access point names" saved in Settings.
3. Create a brand new - fresh AP Name using my current mobile operator recommended settings.
4. So far 7 days without an issue. Will test in low reception areas if coming out of it - mobile data connects and traffic flows.

**Comment by gwolf2u** [comment]
seems you have it figured
