### ISSUE TITLE
Camera app freezing.

### ISSUE THREAD

**Issue by kalcho89** [crdroidandroid/issue_tracker#284]
[CrashLogs (LogFox).zip](https://github.com/crdroidandroid/issue_tracker/files/13840954/CrashLogs.LogFox.zip)
### Issue type

Feature not working as intended

### Device

Mi 9T Pro Raphael

### crDroid version

crDroid 9

### Exact version / Build date

9.11 TQ3A.230901.001

### Bug description

Camera app freezing when used for taking many pictures and never opens back again until restart of the phone.
Especially noticeable if you have just taken a pic and you click the lower left corner of the screen to view it.

### Steps to reproduce

1. Take a picture.
2. Immediately touch the lower left corner on "preview" to view it.
3. App freezes or doesn't do anything to show you the pic you have just taken. Sometimes missing in  "Photo gallery" as well.
4. Restart phone get it back working.

### Relevant log (logcat/build log)

```shell
N/A
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
no logcat, no help

**Comment by kalcho89** [comment]
let me know if this is sufficient. captured some logs with logfox during one of those freezes.
[26_12-23-32-55_741.zip](https://github.com/crdroidandroid/issue_tracker/files/13773789/26_12-23-32-55_741.zip)

**Comment by gwolf2u** [comment]
@firebird11 please check out

**Comment by kalcho89** [comment]
@firebird11 - updated the thread with latest crashlogs (logfox) from today 05.01.2024.

**Comment by gwolf2u** [comment]
raphael support has been dropped for crDroid 9
