### ISSUE TITLE
Unable to connect to PC

### ISSUE THREAD

**Issue by Chenx221** [crdroidandroid/issue_tracker#285]
### Issue type

Feature not working as intended

### Device

Xiaomi POCO F2 Pro / Redmi K30 Pro (lmi)

### crDroid version

crDroid 10

### Exact version / Build date

10.0/2023-12-08

### Bug description

After dirty flashing the **2023-12-08** build of crdroid 10, I tried connecting the Android device to PC (Windows) via USB, but the device is not recognized by the PC. there is also no popup on the Android device with any of the available USB options, it only charging. This issue also causes adb to not work with a wired connection (adb via wireless connection works fine). I can confirm that this is not an issue with my PC or USB cable.

### Steps to reproduce

Step 1.Flash the 2023-12-08 build of crdroid 10 (not clean install)
Step 2. Connect Android device to PC via USB cable
Step 3. PC can't recognize the Android device and can only charge it

### Relevant log (logcat/build log)

```shell
The log below contains the process of connecting and disconnecting my PCs.
The log file is too large, so check this out:
https://pastebin.ubuntu.com/p/KNDD6HtnKZ/
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/21092976/ba9b8d7f-b679-4f24-9a62-f2a0b947c024

### Solution

I didn't find a solution, returning to a previous version might work?

### Additional context

Also the 2023-12-08 update brought another issue: the device can't enter deep sleep when it's on standby. However I don't know how to capture the logs related to this issue. 😂

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment]
Confirmed. Will check on this.

**Comment by raystef66** [comment]
Fixed.
Kernel issue and will push on next release.
