### ISSUE TITLE
bug: playback pause intermittently when enable OK Google

### ISSUE THREAD

**Issue by quangdo92** [crdroidandroid/issue_tracker#287]
### Issue type

Feature not working as intended

### Device

yoyeuse

### crDroid version

crDroid 10

### Exact version / Build date

crDroidAndroid-14.0-20231130-miatoll-v10.0-BETA
NikGapps-NikGapps-Custom-arm64-14-20231214-signed-arm64-14-20231214

### Bug description

all players are paused after 2-3 seconds then resume running, across apps:
- Youtube
- Facebook
- YT Kid
- Chrome

### Steps to reproduce

Turn on: OK Google
Play some video

### Relevant log (logcat/build log)

```shell
Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
```

### Screenshots or videos

![Screenshot_20231215-163557_Cài đặt](https://github.com/crdroidandroid/issue_tracker/assets/33422339/b74c32f4-3210-4879-993f-03fb37759080)

### Solution

Turn off OK Google

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unofficial device, so can't reach out maintainer
