### ISSUE TITLE
bug: signature spoofing didn't work 

### ISSUE THREAD

**Issue by darkgeek** [crdroidandroid/issue_tracker#288]
### Issue type

Feature not working as intended

### Device

oneplus 11 (salami)

### crDroid version

crDroid 10

### Exact version / Build date

10.0/2023-12-23

### Bug description

Signature spoofing, which is a feature required by microg, failed to function in the latest crdroid build(20231223), and microg complained that this permission cannot be granted. It used to work in previous beta build though.

### Steps to reproduce

Use ota to upgrade from previous beta version, or flash it in recovery.

### Relevant log (logcat/build log)

```shell
12-24 01:55:34.916  3404  3404 E GrantPermissionsViewModel: None of [android.permission.FAKE_PACKAGE_SIGNATURE] in {android.permission-group.NOTIFICATIONS=[android.permission.POST_NOTIFICATIONS]}
12-24 01:55:36.926  3404  3404 E GrantPermissionsViewModel: None of [android.permission.FAKE_PACKAGE_SIGNATURE] in {android.permission-group.LOCATION=[android.permission.ACCESS_COARSE_LOCATION, android.permission.ACCESS_FINE_LOCATION, android.permission.ACCESS_BACKGROUND_LOCATION], android.permission-group.PHONE=[android.permission.READ_PHONE_STATE], android.permission-group.CONTACTS=[android.permission.GET_ACCOUNTS, android.permission.READ_CONTACTS], android.permission-group.STORAGE=[android.permission.WRITE_EXTERNAL_STORAGE, android.permission.READ_EXTERNAL_STORAGE], android.permission-group.SENSORS=[android.permission.BODY_SENSORS, android.permission.BODY_SENSORS_BACKGROUND], android.permission-group.SMS=[android.permission.RECEIVE_SMS], android.permission-group.NEARBY_DEVICES=[android.permission.BLUETOOTH_ADVERTISE, android.permission.BLUETOOTH_CONNECT, android.permission.BLUETOOTH_SCAN], android.permission-group.NOTIFICATIONS=[android.permission.POST_NOTIFICATIONS], android.permission-group.READ_MEDIA_AURAL=[android.permission.READ_MEDIA_AUDIO], android.permission-group.READ_MEDIA_VISUAL=[android.permission.READ_MEDIA_VIDEO, android.permission.READ_MEDIA_IMAGES, android.permission.READ_MEDIA_VISUAL_USER_SELECTED]}
```

### Screenshots or videos

![Screenshot_20231224-020228_crDroid Home](https://github.com/crdroidandroid/issue_tracker/assets/1317617/915a6c3f-ce6e-485f-a640-00770931f2cf)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by stor-sven** [comment]
Same problem on latest build for Spacewar.

**Comment by gwolf2u** [comment]
Fixed in builds from today onward
https://github.com/crdroidandroid/android_frameworks_base/commit/3c054a7929097c9a30d0ba8294b047379a1c72b3
