### ISSUE TITLE
Last app toggle not working when animation off

### ISSUE THREAD

**Issue by Moya78** [crdroidandroid/issue_tracker#289]
### Issue type

User interface

### Device

PocoF3 (Alioth)

### crDroid version

crDroid 10

### Exact version / Build date

10/2023-12-22

### Bug description

"Animator duration scale" in developer options.
If slider reduced to less than 0.5x then last app function doesn't work (double tap recents button)
Summary: if animations are disabled then "last app" toggle function doesn't work. 

### Steps to reproduce

-Choose 3 button navigation
-Go to developer options
-Animator duration scale reduce to less than 0.5x or 0.00x
- open any two random apps
- double tap recents button to switch between apps.

### Relevant log (logcat/build log)

```shell
None
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
@raystef66 can you confirm this one?

**Comment by raystef66** [comment]
> @raystef66 can you confirm this one?

Sry for late reply as been on holiday ;)
Working fine here on all animator duration scale but have to mention the speed of double tap needs to be faster when using like 0.2 compared to 0.5.

**Comment by Moya78** [comment]
> > @raystef66 can you confirm this one?
> 
> Sry for late reply as been on holiday ;) Working fine here on all animator duration scale but have to mention the speed of double tap needs to be faster when using like 0.2 compared to 0.5.

Hi Ray, welcome back.
Yes that's my point. It's not broken. But the tap speed needs adjustment. In Cr13 even at 0.00 animation the normal tap worked on last app switch. In Cr14 It seems UI doesn't have enough time to react to tapping on low animator duration.

**Comment by raystef66** [comment]
> > > @raystef66 can you confirm this one?
> > 
> > 
> > Sry for late reply as been on holiday ;) Working fine here on all animator duration scale but have to mention the speed of double tap needs to be faster when using like 0.2 compared to 0.5.
> 
> Hi Ray, welcome back. Yes that's my point. It's not broken. But the tap speed needs adjustment. In Cr13 even at 0.00 animation the normal tap worked on last app switch. In Cr14 It seems UI doesn't have enough time to react to tapping on low animator duration.

@gwolf2u   as mentioned, not broken but tap speed needs to be faster in relation to lower animator duration scale

**Comment by gwolf2u** [comment]
is just how Google/AOSP controls stuff now
maybe can/will get adjusted in the future
so for now is just how it is

**Comment by Albert753258** [comment]
You can extract trebuchet (it is in system_ext) from your device's LOS 21 build and create simple magisk module to replace it. You can use attached module as example (it is for poco f4). Replace TrebuchetQuickStep directory in it
[los-treuchet-1.0.zip](https://github.com/crdroidandroid/issue_tracker/files/14088934/los-treuchet-1.0.zip)

**Comment by Moya78** [comment]
> You can extract trebuchet (it is in system_ext) from your device's LOS 21 build and create simple magisk module to replace it. You can use attached module as example (it is for poco f4). Replace TrebuchetQuickStep directory in it [los-treuchet-1.0.zip](https://github.com/crdroidandroid/issue_tracker/files/14088934/los-treuchet-1.0.zip)

Ok i have launcher3quickstep in CR10.
I copied the directory from system_ext to the magisk module. 
There are two directories in the module. Which one to delete?

**Comment by Albert753258** [comment]
This module removes launcher3quickstep (crdroid launcher) and installs TrebuchetQuickStep (lineageos launcher) instead of it. If you are lucky, my module (it was made for poco f4) will work on your phone out of the box. If you will encounter some bugs, you need to download latest los 21 build for your phone, extract system_ext.img from payload.bin and replace TrebuchetQuickStep directory in my module with TrebuchetQuickStep extracted from los 21 (system_ext/priv-app/TrebuchetQuickStep)

**Comment by Albert753258** [comment]
launcher3quickstep directory in module must contain only empty files

**Comment by Albert753258** [comment]
Also, this module can break some crdroid customization, because it replaces crdroid launcher with lineageos one

**Comment by Moya78** [comment]
> TrebuchetQuickStep

Ok thanks for your help. I will try it now.
Im using Nova anyway. Just want to fix the last app function thats all.

**Comment by Moya78** [comment]
> is just how Google/AOSP controls stuff now maybe can/will get adjusted in the future so for now is just how it is

Hi Gabriel, if you could please reopen. The issue is with the stock launcher not supporting last app switch not animator scale.

**Comment by raystef66** [comment]
Bottom line is @Moya78  replaced the Crdroid home with Trebuchet from LOS A14 and was therefore temp solved.

Issue was : double tap speed needs to be faster in relation to lower animator duration scale to get recents work on 3-button nav

@gwolf2u 
@neobuddy89

**Comment by Moya78** [comment]
@gwolf2u 
@neobuddy89 
The issue turns out to be with the CRhome launcher in CR10 not supporting "last app" switching in 3 button nav.  Proof is that replacing CR stock launcher with LOS 21 launcher, last app switching works.
So its not an Animator scale issue.
Thanks

**Comment by Albert753258** [comment]
Even with 1x animations crdroid launcher last app switching is very unstable 
Crdroid 10 launcher:
https://github.com/crdroidandroid/issue_tracker/assets/56261876/c0c0060d-065b-42db-95a7-6e1e16ac094c
LOS 21 launcher:
https://github.com/crdroidandroid/issue_tracker/assets/56261876/4a01248e-caf4-46ff-b3f8-b23b9ffbf6f8

**Comment by gwolf2u** [comment]
do you have blur enabled?

**Comment by Moya78** [comment]
> do you have blur enabled?

No disabled.
But Issue is the same regardless.

**Comment by gwolf2u** [comment]
still happening on 10.4 ?

**Comment by Moya78** [comment]
> still happening on 10.4 ?

Still not working on 10.4
I was using a GhostDroid launcher port. It was working fine on 10.2. But then all launcher ports stopped working on QPR2.

**Comment by Moya78** [comment]
Definitely has something to do with how the launcher handles recents.
