### ISSUE TITLE
SystemUI: Clock is missing in call

### ISSUE THREAD

**Issue by songlongdaiduong** [crdroidandroid/issue_tracker#29]
### Issue type

User interface

### Device

beyond1lte

### crDroid version

crDroid 9

### Bug description

Clock is missing in call

### Steps to reproduce

Make a call using Facebook Messenger
Press Home button to return to Home screen
Drag the Messenger call window down to hide it

### Relevant log (logcat/build log)

```shell
No crash log
```

### Screenshots or videos

![199195666-e2fe8456-f635-4001-a227-e45ca6014e07](https://user-images.githubusercontent.com/117042414/199277785-5d5b52d1-0f98-47cc-9b35-23f30089a23a.png)

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unofficial device for now
