### ISSUE TITLE
bug: Deep Sleep 50%

### ISSUE THREAD

**Issue by assis-tant** [crdroidandroid/issue_tracker#290]
### Issue type

User interface

### Device

Redmi 9/Prime (Lancelot)

### crDroid version

crDroid 9

### Exact version / Build date

10.0/2023-12-21

### Bug description

When i was in MIUI, i saw Deep Sleep 3%, but Crdroid 10.0, 58% not an big issue.

### Steps to reproduce

Step 1. Go to Settings
Step 2. About Phone
Step 3. Scroll down at last u will see

### Relevant log (logcat/build log)

```shell
I don't know where i can get logs.
```

### Screenshots or videos

![Screenshot_20231230-090306_Settings](https://github.com/crdroidandroid/issue_tracker/assets/107257111/ea64c045-bce6-456b-a2f9-2d35498c3981)

### Solution

I don't know

### Additional context

I don't know

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [x] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
deepsleep depends on numerous factors like apps keeping system awake, services, etc
as long as there isn't any battery drain, no issue
also MIUI is known for aggressive battery management features, so not best to compare with it
