### ISSUE TITLE
feature request: Add a feature to save screen recordings to External SD Card

### ISSUE THREAD

**Issue by assis-tant** [crdroidandroid/issue_tracker#291]
### Issue type

Source code related

### Device

Redmi 9 (Lancelot)

### crDroid version

crDroid 10

### Exact version / Build date

10.0/2023-10-29

### Bug description

No bug.

### Steps to reproduce

No steps.

### Relevant log (logcat/build log)

```shell
Its a requested feature.
```

### Screenshots or videos

![IMG_20231230_091901](https://github.com/crdroidandroid/issue_tracker/assets/107257111/1aadf421-858d-4eca-8b83-29fdff2b637c)
![Screenshot_20231230-091834_Chrome](https://github.com/crdroidandroid/issue_tracker/assets/107257111/824568af-20a5-4285-b949-03865a73cb0b)

### Solution

X;

### Additional context

X;

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
not planned.

**Comment by assis-tant** [comment]
> not planned.

Why, well crdroid is know for theirs customized features and extended battery and performance
