### ISSUE TITLE
BesLoudness option on reboot

### ISSUE THREAD

**Issue by damilg** [crdroidandroid/issue_tracker#294]
### Issue type

Feature not working as intended

### Device

Redmi Note 8 Pro (begonia)

### crDroid version

crDroid 9

### Exact version / Build date

9.11/2022-11-27

### Bug description

I want to have de BesLoudness option disables, because when its enabled, the minimum volume is still loud. I disable that option and it works fine, until i reboot and its enabled again.

### Steps to reproduce

Reboot the device

### Relevant log (logcat/build log)

```shell
01-04 13:08:53.610 I/ActivityManager(1274): Start proc 6938:org.lineageos.settings.besloudness/u10a377 for broadcast {org.lineageos.settings.besloudness/org.lineageos.settings.device.BootCompletedReceiver}
01-04 13:08:53.777 E/ngs.besloudness(6938): Not starting debugger since process cannot load the jdwp agent.
01-04 13:08:54.040 V/GraphicsEnvironment(6938): ANGLE Developer option for 'org.lineageos.settings.besloudness' set to: 'default'
01-04 13:08:54.042 V/GraphicsEnvironment(6938): ANGLE GameManagerService for org.lineageos.settings.besloudness: false
01-04 13:08:54.096 I/BesLoudness(6938): Booting
01-04 13:08:54.127 D/AudioALSAHardware(676): +setParameters(): SetBesLoudnessStatus=1
01-04 13:08:54.127 D/AudioALSAStreamManager(676): mBesLoudnessStatus() flag 1
01-04 13:08:54.132 D/AudioALSAStreamManager(676): setBesLoudnessStateToXML(), Set BesLoudness state to xml = 1
01-04 13:08:54.132 D/AudioALSAStreamManager(676): getBesLoudnessStateFromXML(), get BesLoudness state from xml = 1
01-04 13:08:54.132 D/AudioALSAStreamManager(676): recheck besLoudnessInXML 1
01-04 13:08:54.172 D/aurisys_lib_handler(676): lib_name mtk_bessound, 0xe97845d0, ADB_CMD_KEY_VALUE: set 512, 22, SetBesLoudnessStatus=1, retval 0
01-04 13:08:54.172 D/AudioALSAHardware(676): -setParameters(): SetBesLoudnessStatus=1
```

### Screenshots or videos

![Screenshot_20240104-133241_Ajustes](https://github.com/crdroidandroid/issue_tracker/assets/155637039/6e75d71a-75e5-4f2d-87c1-a51d41812ba7)
![Screenshot_20240104-133253_BesLoudness](https://github.com/crdroidandroid/issue_tracker/assets/155637039/c51bc376-c289-42df-942b-63d636f14e9c)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
begonia crDroid 9 is no longer on support list
update to crDroid 10
