### ISSUE TITLE
Asking for login in google translate

### ISSUE THREAD

**Issue by rickyspanish8** [crdroidandroid/issue_tracker#295]
### Issue type

User interface

### Device

Oneplus 7 t pro mclaren

### crDroid version

crDroid 7

### Exact version / Build date

30-12-2023

### Bug description

Ask for login in google services when opening the google translate.  All the time.
![Screenshot_20240104-212748_Translate](https://github.com/crdroidandroid/issue_tracker/assets/49120988/ae2110d4-ae37-434c-8502-a4b63a71db62)

### Steps to reproduce

Open the google traslate app

### Relevant log (logcat/build log)

```shell
No idea how to do that
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Terminator-J** [comment]
Can confirm same behavior on my own builds for OP6-series, using the crdroid-officisl NikGapps package.

**Comment by gwolf2u** [comment]
fixed in https://github.com/crdroidandroid/android_frameworks_base/commit/6087fa78cd1f252542354d12b0c483e5f02bc0b5
