### ISSUE TITLE
Request to add font to support Thai language.

### ISSUE THREAD

**Issue by hallcool66** [crdroidandroid/issue_tracker#297]
### Issue type

User interface

### Device

oneplus 7t pro (hotdog)

### crDroid version

crDroid 10

### Exact version / Build date

crdroid 10 (20231230)

### Bug description

the system font is not supporting Thai language so need to add font to support both english and thai.

### Steps to reproduce

1. Go to settings, crdroid settings, user interface, font style
2. Example change to comic sans
3. Open browser to surf any thai website or change system language to thai.
4. Thai letter will not be changed to the same as English letter.

### Relevant log (logcat/build log)

```shell
refer to screenshot.
```

### Screenshots or videos

![Image_20240109143413](https://github.com/crdroidandroid/issue_tracker/assets/156058190/eff8a924-87bc-429b-86e6-f953d4c01c2c)

### Solution

add font supporting Thai
[BoonJot-v2.0-otf.zip](https://github.com/crdroidandroid/issue_tracker/files/13870483/BoonJot-v2.0-otf.zip)
[Itim.zip](https://github.com/crdroidandroid/issue_tracker/files/13870486/Itim.zip)

### Additional context

Both 2 attached fonts are under Open Font License. They are also supporting English language.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
use Sans-Serif font
