### ISSUE TITLE
bug: GPS fail to verify

### ISSUE THREAD

**Issue by emeraldking6** [crdroidandroid/issue_tracker#298]
### Issue type

Feature not working as intended

### Device

alioth

### crDroid version

crDroid 9

### Exact version / Build date

9,12

### Bug description

GPS is not detecting the exact position or even not working without error, just stay as not conected, even if im conected to network and wifi

### Steps to reproduce

step 1. open google maps

### Relevant log (logcat/build log)

```shell
no error code
```

### Screenshots or videos

![WhatsApp Image 2024-01-09 at 08 46 05](https://github.com/crdroidandroid/issue_tracker/assets/64074640/4635209e-b03c-4ef7-a519-1c3d468337c8)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment]
**Just checked and no issues here.** 
Tried like GPS test app and check if you can get a fix?
What fw are you using? Check xda for proper instructions.
Maybe clean flash again in the end.
