### ISSUE TITLE
bug: Settings Services keeps stopping

### ISSUE THREAD

**Issue by P2GR** [crdroidandroid/issue_tracker#30]
### Issue type

User interface

### Device

Lemonadep

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

After the phone being idle / standby for a period of time, the Settings Services crashes and i have to hard reboot/reset the phone before it starts working again.

### Steps to reproduce

Step 1. Go to sleep for atleast a couple of hours.
Step 2. Wake up and you'll see the Settings Services has stopped and phone is frozen. 

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/SaqVYv
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
We do not use Google Settings Intelligence in crdroid 9.
Try uninstalling same in Play Store.
