### ISSUE TITLE
Sensors are all disabled, gyroscope, acerometer, magnometer all failbug: title (<-- change me)

### ISSUE THREAD

**Issue by Nanchi9292** [crdroidandroid/issue_tracker#300]
### Issue type

Other

### Device

Samsung galaxy A715F

https://github.com/crdroidandroid/issue_tracker/assets/94803997/759f569d-5d24-4403-a158-f7635a1ab6f0

![Screenshot_20240109-013136_Sensor Test](https://github.com/crdroidandroid/issue_tracker/assets/94803997/aad8a790-c0c2-4a39-b64d-3ce21d6c0354)

### crDroid version

crDroid 10

### Exact version / Build date

December 22, 2023

### Bug description

What happens is that when the automatic screen rotation does not work and the gyroscope less and it is sad because it is something very essential

### Steps to reproduce

Another problem is that when you play for a long time, crDroid restarts and freezes 

### Relevant log (logcat/build log)

```shell
I don't have the log because it is already like a compatibility problem for the Samsung Galaxy A71 version, we know that this device has many sensors
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/94803997/70e3c7eb-813e-4c0b-ba4c-dd04a774c8e3

### Solution

It's sad because the only solution is to go back to stock rom and I don't want to because the lsg caused by the original Samsung software is too much 

### Additional context

I don't know if it would be too much to ask for an update patch to solve that problem on the device 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Haky86** [comment]
I'm checking the issue by flashing the latest build.

**Comment by Haky86** [comment]
@Nanchi9292 I flashed the crDroid 10 for a71, no issues here. don't flash custom fw/kernel.
![Screenshot_20240109-185108_Sensor Test](https://github.com/crdroidandroid/issue_tracker/assets/67873807/204e78af-4b78-47af-894f-b3565b20cbdb)
![Screenshot_20240109-185112_Sensor Test](https://github.com/crdroidandroid/issue_tracker/assets/67873807/98c3818d-401f-4d48-94f4-b51b6e490007)
![Screenshot_20240109-185116_Sensor Test](https://github.com/crdroidandroid/issue_tracker/assets/67873807/23eda907-a964-44a4-b3a7-8432eff62e33)
![Screenshot_20240109-185122_Sensor Test](https://github.com/crdroidandroid/issue_tracker/assets/67873807/6ac2989e-682c-44d7-9a5c-227c24b50e30)
![Screenshot_20240109-185126_Sensor Test](https://github.com/crdroidandroid/issue_tracker/assets/67873807/21142b1e-6179-48ec-9c8e-04a3ca5eb71b)
![Screenshot_20240109-185130_Sensor Test](https://github.com/crdroidandroid/issue_tracker/assets/67873807/44dc4702-0293-414c-8116-6926e355018c)
![Screenshot_20240109-185136_Sensor Test](https://github.com/crdroidandroid/issue_tracker/assets/67873807/d16d09f4-83a2-42ab-8397-6b34b629fed5)
