### ISSUE TITLE
bug: Lack of support for IEEE 802.11r,v,w,k networks

### ISSUE THREAD

**Issue by GiacomoFicarola** [crdroidandroid/issue_tracker#301]
### Issue type

Other

### Device

Poco F2 Pro - lmi

### crDroid version

crDroid 9

### Exact version / Build date

11/2023-11-16

### Bug description

Premise:
I have a wifi network that supports mesh, this functionality works on the Samsung and MIUI devices in the house.
Problem:
When I go from one room to another the signal goes from maximum to 4 bars and vice versa.
With the CrDroid 9.11, but from the telegram channel I know that the 10 also has this problem( https://t.me/crdroidlmi/69848 ), it seems that the smartphone remains connected as much as possible to one of the APs in the network, without switching to the closest one in the mesh.

### Steps to reproduce

Go from one room to another in the house with the wifi turned on

### Relevant log (logcat/build log)

```shell
Nothing.
```

### Screenshots or videos

![photo_2024-01-09_20-11-35](https://github.com/crdroidandroid/issue_tracker/assets/156086383/af5b75b5-ab9b-4afe-a25b-fd38aa06de53)
![photo_2024-01-09_20-11-32](https://github.com/crdroidandroid/issue_tracker/assets/156086383/80ee9f36-17c0-4acd-8280-04663d65d2e2)

### Solution

I think that the management of IEEE 802.11r,v,w,k signals and the recognition of 802.11s have not been correctly implemented

### Additional context

As you can see from the photos, there would be better wifi (5 GHz) in the area at a power of -45 dBm, but the smartphone prefers the more distant one at -74 dBM.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment]
Unfortunately no supoort on LMI cr9.x anymore.
Try crDroid 10.0
