### ISSUE TITLE
Google lens in crDroid Launcher (Recents) not working anymore

### ISSUE THREAD

**Issue by invisible789** [crdroidandroid/issue_tracker#302]
[logs-2024-01-12-14-31-01.zip](https://github.com/crdroidandroid/issue_tracker/files/13917291/logs-2024-01-12-14-31-01.zip)
### Issue type

Feature not working as intended

### Device

Using crDroid official for Poco F3 by super maintainer RAYSTEF , unfortunately with latest source from crDroid, Google lens not working anymore, also Google Translate not signing in to my Google account, please fix crDroid Team, you're doing great 👍

### crDroid version

crDroid 10

### Exact version / Build date

crDroid 10.1 / 08-01-2024

### Bug description

Having Google app which is mandatory for to enable Google lens Option in crDroid Launcher, always worked, until latest sync by maintainer and it's not working anymore.

### Steps to reproduce

Install vanilla crDroid with Nik gapps having Google app or install Google app from play store, enable Google lens Option in crDroid Launcher settings - recents
Option won't show in recents for lens and so not working
Also install Google translate and it asks for to sign-in to Google account and not adding account, tried to add account manually and it says account already exists

### Relevant log (logcat/build log)

```shell
Attaching complete log so you may find something relevant to it.
```

### Screenshots or videos

![Screenshot_20240112-143650_crDroid Home](https://github.com/crdroidandroid/issue_tracker/assets/72073975/19c9f794-c853-4cbc-a215-03015a474a0d)
![Screenshot_20240112-143637_crDroid Home](https://github.com/crdroidandroid/issue_tracker/assets/72073975/39a94c90-efaf-4123-b52b-cbdea75f725d)
![Screenshot_20240112-143714_Translate](https://github.com/crdroidandroid/issue_tracker/assets/72073975/3a9027b0-38a2-4aba-bc48-185feb15ff31)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment]
Can confirm.
Happening on all my devices after 26.12 build. On 26.12 it did work.
Also, Google Translate login is reported today within our crDroid dev group.
If needed you can still open an issue on that one too.

Thx @invisible789

**Comment by raystef66** [comment]
@neobuddy89 
Thing is that only crDroid gapps gives me back Lens on Recents.
But as mentioned this option was working before on default Nik Core or other packages of Nik. Non working Lens on Recents started after 26.12 builds of mine. 
Maybe you can figure out what triggered it to not working anymore on non-crDroid Gapps package?

**Comment by gwolf2u** [comment]
fact is we didn't made specific changes to break this
maybe some packages are replace on other gapps variants that break this

does it work with Google Lens app installed?

**Comment by raystef66** [comment]
> fact is we didn't made specific changes to break this maybe some packages are replace on other gapps variants that break this
> 
> does it work with Google Lens app installed?

No, Lens doesn't work when Lens app is installed additionally as we did several test on this.

So to resume again, imo we lost Lens in Recents after +- 26th dec on Core gapps AND google app was manually flashed. No Lens app either was needed to have Lens in Recents.
To get Lens in Recents back after 26th build, we are needed to flash a gapps package WITH the Google app to get permissions or smt back in place. 

In my TG groups there were several reports on this. Not all reported because there were users already on GApps with Google app installed and didn't notice this behaviour. Also I or others reporting didn't change GApps package in the mean while.

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_packages_apps_Launcher3/commit/b4fe7452b6bcd45c7698c034118b1a904fbe54f9
