### ISSUE TITLE
The developers incorrectly disabled the rear display

### ISSUE THREAD

**Issue by lev666** [crdroidandroid/issue_tracker#303]
### Issue type

Other

### Device

Mi 11 Ultra (star/mars)

### crDroid version

crDroid 10

### Exact version / Build date

10.0/2024-01-08

### Bug description

I saw on the kernel github thread comits that the developers have disabled the rear display, but this has resulted in the rear display touchscreen now always working as the main display touchscreen, which is very annoying when using the system.

### Steps to reproduce

When the main display is on, the sensor of the second display is always active and it is perceived as the sensor of the main display and also interacts with the system as the main display.

### Relevant log (logcat/build log)

```shell
01-14 15:19:04.932 E/ANDR-PERF-OPTSHANDLER(1139): Perflock resource /sys/class/devfreq/soc:qcom,llccbw/min_freq not supported
01-14 15:19:04.932 E/ANDR-PERF-RESOURCEQS(1139): Failed to apply optimization [12, 0]
01-14 15:19:05.269 E/ANDR-PERF-MPCTL(1139):  return repeat opt = perf_lock_acq: client_pid=1081, client_tid=1081, inupt handle=0, duration=1000 ms, num_args=28, list=0x43000000 0x19 0x40800000 0x76C 0x40800100 0x5EC 0x40800200 0x746 0x40C00000 0x2 0x43400000 0x1F40 0x40C74000 0xFF 0x40408000 0x63 0x41000000 0x3 0x40C78000 0x0 0x40C7C000 0x0 0x40CA8000 0x4 0x42C10000 0x1 0x41000200 0x1 
01-14 15:19:05.590 E/QTI PowerHAL(1081): Failed to acquire lock.

01-14 15:19:05.270 E/QTI PowerHAL(1081): Failed process_boost for boost_handle
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by lev666** [comment]
Also, for some reason the wi-fi connection is not working correctly, namely that the phone on 2,4 frequency connects on wi-fi generation 4, and on frequency 5 on wi-fi generation 5. Router tp-link ax73 with support for wi-fi 6

frequency 5:
![Screenshot_20240120-145443_Настройки.png](https://github.com/crdroidandroid/issue_tracker/assets/63856055/944ef962-6575-4ca5-a494-fe721dcf7e12)


2,4 frequency
![Screenshot_20240120-145423_Настройки.png](https://github.com/crdroidandroid/issue_tracker/assets/63856055/8cc6cbb1-393d-45ea-8a8b-18a86f516fe0)

**Comment by FlowerSea0208** [comment]
First of all, I never said Mi 11 Ultra(star) was fully supported, It’s always been 11Pro(mars).
Secondly, the reason for disabling the rear display is so that it can run properly on Mi 11 Ultra without Launcher and system crashes.
Finally, you should be clear that the Mi 11 Ultra and the 11Pro are not the same phone. I did all this in crDroid so that Mi 11 Ultra users can also experience crDroid, because for regions outside of China it's mostly Mi 11 Ultra and not 11Pro, so it will always be only compatibility for Mi 11 Ultra, not full support

**Comment by lev666** [comment]
> First of all, I never said Mi 11 Ultra(star) was fully supported, It’s always been 11Pro(mars).
> Secondly, the reason for disabling the rear display is so that it can run properly on Mi 11 Ultra without Launcher and system crashes.
> Finally, you should be clear that the Mi 11 Ultra and the 11Pro are not the same phone. I did all this in crDroid so that Mi 11 Ultra users can also experience crDroid, because for regions outside of China it's mostly Mi 11 Ultra and not 11Pro, so it will always be only compatibility for Mi 11 Ultra, not full support

Good evening, thanks for your reply (even though it's not particularly relevant to the topic), I'm well aware that the mi 11 ultra ≠ mi 11 pro, but since I saw in the github comits that there were attempts to disable the second display, I thought I'd report that the second display was not fully disabled, so you could have been rude:). Good evening.

**Comment by FlowerSea0208** [comment]
> > First of all, I never said Mi 11 Ultra(star) was fully supported, It’s always been 11Pro(mars).
> > Secondly, the reason for disabling the rear display is so that it can run properly on Mi 11 Ultra without Launcher and system crashes.
> > Finally, you should be clear that the Mi 11 Ultra and the 11Pro are not the same phone. I did all this in crDroid so that Mi 11 Ultra users can also experience crDroid, because for regions outside of China it's mostly Mi 11 Ultra and not 11Pro, so it will always be only compatibility for Mi 11 Ultra, not full support
> 
> Good evening, thanks for your reply (even though it's not particularly relevant to the topic), I'm well aware that the mi 11 ultra ≠ mi 11 pro, but since I saw in the github comits that there were attempts to disable the second display, I thought I'd report that the second display was not fully disabled, so you could have been rude:). Good evening.

Sorry, the issue regarding the back screen has come up so many times that I don't really want to bother.The Mi 11 Ultra was never officially supported and all related issues should not be reported.
