### ISSUE TITLE
Incorrect battery statistics

### ISSUE THREAD

**Issue by Narcotic82** [crdroidandroid/issue_tracker#304]
### Issue type

Feature not working as intended

### Device

Poco f2 pro

### crDroid version

crDroid 10

### Exact version / Build date

10.1 11/01/24

### Bug description

When I consult the battery statistics, the information is not displayed correctly.

### Steps to reproduce

Go to battery information

### Relevant log (logcat/build log)

```shell
.
```

### Screenshots or videos

![Screenshot_20240114-144556_Ajustes](https://github.com/crdroidandroid/issue_tracker/assets/100804916/1753c96c-a030-48ef-b70b-30d90116ef29)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
@raystef66 remove the overlay or correct paths

**Comment by raystef66** [comment]
> @raystef66 remove the overlay or correct paths

This battery info is under About phone_battery information.
Afaik (checked) I don't have any overlay in my trees to point to this battery cycles/date. So what overlay you're referring at to remove this from About phone_battery information?

**Comment by gwolf2u** [comment]
yeah my bad
thought is battery stats in battery section
the stats under About page are inaccurate (as far as I know) because stats are cleared after clean flash
even in my case reports stupid data (first used date being 1 Jan 1970)
as this is not fully implements Google Android side, should deem this as a #nofix imo

**Comment by raystef66** [comment]
Unless we remove these so not displayed anymore?
https://github.com/crdroidandroid/android_packages_apps_Settings/commits/14.0/res/xml/battery_info.xml

**Comment by raystef66** [comment]
@gwolf2u  seems cycle count got fixed? On f2 pro and f3 seems counting.
The only thing left is the date of first use not displayed correctly. Maybe we can rm that in [battery_info.xml] ?(https://github.com/crdroidandroid/android_packages_apps_Settings/commits/14.0/res/xml/battery_info.xml)

**Comment by gwolf2u** [comment]
imo we should remove this altogether 
page is kinda irrelevant and can mislead users

@crdroidandroid/coreteam 
thought?

**Comment by raystef66** [comment]
> imo we should remove this altogether page is kinda irrelevant and can mislead users
> 
> @crdroidandroid/coreteam thought?

+1 as I mentioned before these are kinda useless numbers
