### ISSUE TITLE
Problem with Google account in various apps.

### ISSUE THREAD

**Issue by lev666** [crdroidandroid/issue_tracker#305]
### Issue type

Feature not working as intended

### Device

Mi 11 Ultra (Mars/Star)

### crDroid version

crDroid 10

### Exact version / Build date

10.0/2024-01-17

### Bug description

Any applications do not see Google accounts, but when trying to add it says that accounts have already been added. I'm using the gaps on CrDroid website for mi 11 pro (mars) phone. My email is partially obscured

### Steps to reproduce

I couldn't find a solution

### Relevant log (logcat/build log)

```shell
-
```

### Screenshots or videos

![Screenshot_20240117-120735_WhatsApp~2](https://github.com/crdroidandroid/issue_tracker/assets/63856055/9e61edc6-2529-41c3-9eef-b04f88b4f890)
![Screenshot_20240117-120636_Сервисы Google Play~2](https://github.com/crdroidandroid/issue_tracker/assets/63856055/9f4b44cd-498c-41e5-b9fe-9f616cc6c81c)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Terminator-J** [comment]
Seems related to https://github.com/crdroidandroid/issue_tracker/issues/295

@lev666 Any other apps besides Google Translate and WhatsApp?

**Comment by lev666** [comment]
> Seems related to https://github.com/crdroidandroid/issue_tracker/issues/295
> 
> @lev666 Any other apps besides Google Translate and WhatsApp?

As an example, I can also cite the fact that backups from google account (numbers, messages, etc.) are not restored and in the stock application "messages, contacts" also can not select already added google mail.

**Comment by lev666** [comment]
Upgrading to CrDroid 10.1 resolved this issue.
