### ISSUE TITLE
Volume panel alignment

### ISSUE THREAD

**Issue by cygiel5420** [crdroidandroid/issue_tracker#306]
### Issue type

User interface

### Device

Pixel 7 Pro (cheetah) 

### crDroid version

crDroid 10

### Exact version / Build date

10.1 2024-01-12

### Bug description

Volume panel doesn't go back to where it's supposed to be after exiting landscape mode. 

### Steps to reproduce

Play any media in landscape mode, go back to portrait mode, adjust volume - the panel will be in the middle of the screen. 

### Relevant log (logcat/build log)

```shell
Don't have one. Only screenshot.
```

### Screenshots or videos

![Screenshot_20240117-092041_crDroid Home](https://github.com/crdroidandroid/issue_tracker/assets/133622561/5e565e6e-50fb-4e67-9399-a6d6554449c8)

### Solution

Go back into landscape mode, then back into portrait. Volume panel will now be in proper place. 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
for now a "temp" fix is to go to crDroid settings and toggle volume on left and then on right (or the place you want it)
issue comes from Google upstream and usually happens when rotating screen from landscape to portrait and volume panel being opened
