### ISSUE TITLE
bug: Display Media Panel On The Right In Landscape Mode When No Notifications Are Present 

### ISSUE THREAD

**Issue by YouSummoner** [crdroidandroid/issue_tracker#308]
### Issue type

User interface

### Device

Xiaomi 11 Lite NE

### crDroid version

crDroid 10

### Exact version / Build date

10.1/2024-01-12

### Bug description

All the empty space remaining unused on the right side even if there are no notifications to display there looks bad. Instead it can be just used to show the media panel on the right side instead of hiding if below QS controls. Later if a notification does arrive, it can be shown on the right side and put the media panel under the QS controls.

### Steps to reproduce

1. Play some media on the device
2. Switch to landscape mode
3. Open the Notification panel

### Relevant log (logcat/build log)

```shell
.
```

### Screenshots or videos

![Screenshot_20240119-013130_YouTube](https://github.com/crdroidandroid/issue_tracker/assets/107224555/6f9acd44-8e09-413b-af98-9d29b2a5c41f)

### Solution

This can be a toggle in the crDroid Settings.

### Additional context

.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is by design
can be disable only by maintainer at build time
for now no ability to choose this
