### ISSUE TITLE
Feature Request: Battery Bar improvements

### ISSUE THREAD

**Issue by cygiel5420** [crdroidandroid/issue_tracker#311]
### Issue type

User interface

### Device

Pixel 7 Pro (cheetah)

### crDroid version

crDroid 10

### Exact version / Build date

10.1 / 2024-01-12

### Bug description

Currently Battery Bar is a straight line on the main screen only.
Improvements that would make the battery bar more useful in my opinion are:
- Curved corners setting, as the beginning and end parts of the bar are cut off due to the shape of the phone screen
- Battery bar visibility on lock screen and in full screen apps. Would be useful to see the battery level without having to unlock the phone screen or having to exit the full screen mode - easier to keep an eye on battery % level.

### Steps to reproduce

N/A as it's a suggestion

### Relevant log (logcat/build log)

```shell
N/A as it's a suggestion
```

### Additional context

Proposed improvements are taken directly from the PowerLine App available on the Play store, but I think it would be nice to have those settings included with CrDroid so that no additional apps have to installed and set up. Native support is always appreciated.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unfortunately currently this is the implementation we are following
we are aware that it doesn't fit all punchhole or notch devices, yet that's how it is
might be revisited later, but slim chances as the "bug" is low on priority list and a new implementation would need to have specific overlays for each device, and that's bit harder to do
