### ISSUE TITLE
Coming out of airplane mode turns on previously disabled sim card.

### ISSUE THREAD

**Issue by fama-lama** [crdroidandroid/issue_tracker#312]
### Issue type

Feature not working as intended

### Device

Poco F2 PRO lmi

### crDroid version

crDroid 10

### Exact version / Build date

Crdroid 10.1
Build date Thu Jan 11 15:57:24 CET 2024

### Bug description

I have a dual sim device, but keep one disabled because it is for a neighboring country.

Sim slot 1- roaming sim [disabled]
Sim slot 2 - local sim [enabled]

When coming out of airplane mode, both sim card becomes enabled, and I have to go into the settings app to turn the sim off.

Something more egregious is that when coming out of airplane mode, mobile data does not respect the previous state, and will switch from my local sim to the roaming sim. Putting my local sim in sim slot 1 seems to prevent this.

### Steps to reproduce

1. Disable one of two sim card (this is how I usually have it due to one sim being for a neighbor country).
2. Turn on airplane mode
3. Turn off airplane mode
4. _Disabled sim is now active and needs to be manually disabled._

### Relevant log (logcat/build log)

```shell
No logs available
```

### Solution

Restore previous sim state

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jason-eu** [comment]
Logs would help @fama-lama

**Comment by jason-eu** [comment]
> ### Steps to reproduce
> 1. Disable one of two sim card (this is how I usually have it due to one sim being for a neighbor country).
> 2. Turn on airplane mode
> 3. Turn off airplane mode
> 4. _Disabled sim is now active and needs to be manually disabled._


Logs would help @fama-lama

**Comment by Chenx221** [comment]
I reproduced this issue (i.e., the SIM card being re-enabled after turning on and then off airplane mode). Here are my logs:
[logs-2024-01-24-19-29-15.zip](https://github.com/crdroidandroid/issue_tracker/files/14037584/logs-2024-01-24-19-29-15.zip)

**Comment by gwolf2u** [comment]
> > ### Steps to reproduce
> > 
> > 1. Disable one of two sim card (this is how I usually have it due to one sim being for a neighbor country).
> > 2. Turn on airplane mode
> > 3. Turn off airplane mode
> > 4. _Disabled sim is now active and needs to be manually disabled._
> 
> Your device logs would be the most efficient way to help the developers isolate and fix (if necessary) the cause of the issue @fama-lama
> 
> Also, @gwolf2u is this a duplicate of #248 ? Then again, #248 could 10/10 points for clarity.

the other ones are from crDroid 9
can be duplicate, but different branches, so can't go with that

**Comment by raystef66** [comment]
> > > ### Steps to reproduce
> > > 
> > > 1. Disable one of two sim card (this is how I usually have it due to one sim being for a neighbor country).
> > > 2. Turn on airplane mode
> > > 3. Turn off airplane mode
> > > 4. _Disabled sim is now active and needs to be manually disabled._
> > 
> > 
> > Your device logs would be the most efficient way to help the developers isolate and fix (if necessary) the cause of the issue @fama-lama
> > Also, @gwolf2u is this a duplicate of #248 ? Then again, #248 could 10/10 points for clarity.
> 
> the other ones are from crDroid 9 can be duplicate, but different branches, so can't go with that

Already tested on F3 and working there.
But need to know if fw related or not.
@fama-lama which fw are you on?

**Comment by fama-lama** [comment]
![Screenshot_20240124-195411_Settings.png](https://github.com/crdroidandroid/issue_tracker/assets/110621069/4375cc5c-f194-495a-8e01-5bb7069fda96)

firmware V14.0.1.0.SJKMIXM

**Comment by raystef66** [comment]
Fixed on next build.
Most likely `persist.vendor.radio.apm_sim_not_pwdn=1` did the trick as being tested and missing in trees.

**Comment by fama-lama** [comment]
Tested the new build. Issue fixed. Thanks @raystef66 🫰

**Comment by raystef66** [comment]
> Reference

Sure no problem ;)
