### ISSUE TITLE
bug: wrong type of unlocking pattern !

### ISSUE THREAD

**Issue by Lordlight0** [crdroidandroid/issue_tracker#315]
### Issue type

User interface

### Device

RMX1971

### crDroid version

crDroid 10.1

### Exact version / Build date

10.1/2024.01.17

### Bug description

I set the unlocking pattern 4x4 but when I enter the option Hiden & Protected Apps in launcher, It required 3x3 pattern, I cant unlock this because I set 4x4 pattern.
This also happens when I try to see saved passwords in chrome @@

### Steps to reproduce

Before all, set the unlocking pattern to 4x4, 5x5 or 6x6
1.Go to Launcher Setting
2.Go to Miscellaneous 
3.Go to hiden & protected apps

### Relevant log (logcat/build log)

```shell
Logcat is not necessary in this situation, sir .
```

### Screenshots or videos

![Screenshot_20240125-080451_crDroid Home](https://github.com/crdroidandroid/issue_tracker/assets/59312963/f5793c4b-a587-4951-864d-825400ad58ba)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ShevT** [comment]
Fixed - https://github.com/crdroidandroid/android_frameworks_base/commit/89b99d6f9fbef44765c800eeae0e75b27702aa5d
