### ISSUE TITLE
bug: no strings to translate on crowdin

### ISSUE THREAD

**Issue by farline99** [crdroidandroid/issue_tracker#316]
### Issue type

User interface

### Device

Apollo

### crDroid version

crDroid 10

### Exact version / Build date

Unofficial

### Bug description

I am unable to translate "Allow network access", Wi-Fi data", etc strings on Crowdin because they are not available there 🙂

### Steps to reproduce

Go to crDroid settings.
Go to any about app section.
Go to mobile internet and Wi-Fi section.
See untranslated strings. Screenshot is attached.

### Relevant log (logcat/build log)

```shell
:)
```

### Screenshots or videos

![Screenshot_20240126-053934_Настройки](https://github.com/crdroidandroid/issue_tracker/assets/100877226/247c374f-4d72-4983-b7c0-f8e8880537bf)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
some strings are coming from android or LineageOS which we are based on
we only translate crDroid related changes on Crowdin so this is normal
