### ISSUE TITLE
Spotify makes my phone crash

### ISSUE THREAD

**Issue by Jingexz01** [crdroidandroid/issue_tracker#318]
### Issue type

User interface

### Device

Redmi Note 11 (spes)

### crDroid version

crDroid 10

### Exact version / Build date

10/2023-12-25

### Bug description

After launching spotify on my phone and playing music if you try to play music on the same spotify account on pc the phone screen turns on and off over and over again till you are forced to do a force restart

### Steps to reproduce

Step 1. Open spotify on your phone and play music Step 2. Open spotify app on your computer, log in the same account you are using on your phone and play music. After doing these steps your phone should be crashing over and over again, now you could only see the status bar, the phone screen would turn on and off over and over again till you do a force restart.

### Relevant log (logcat/build log)

```shell
After checking, the phone isn't logging the crashes that is happening so I have no idea on how to fix it.
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
logcat will be needed if this can be reproduced
but do this please on latest update
https://crdroid.net/spes/10
you're running outdated crDroid revision, latest being 2024-02-04

**Comment by ap4ss3rby** [comment]
While I don't use spotify (or listen to music on my phone aside from being in a pinch), I would like to know more details. Are you using wired or wireless, are you using the official spotify app or a modded one. If modded can you confirm that the crash is not unique to the modded version you are using? Are you using any mods? Please update to 10.1 and confirm.
