### ISSUE TITLE
AutoFocus issues on OnePlus 7T Pro

### ISSUE THREAD

**Issue by HighPriest** [crdroidandroid/issue_tracker#320]
### Issue type

Feature not working as intended

### Device

OnePlus 7T Pro (Hotdog)

### crDroid version

crDroid 10

### Exact version / Build date

10.1/2024-01-29

### Bug description

AutoFocus on the main camera, tends to default to very short distance. Quickly switching to narrower camera sets the focus right, but any excess movement with the main camera, tends to break it.

### Steps to reproduce

Open the camera app and use only the main camera to try, take a picture in good or bad light.

### Relevant log (logcat/build log)

```shell
-
```

### Screenshots or videos

![Screenshot_20240131-223247_Camera](https://github.com/crdroidandroid/issue_tracker/assets/58490197/5794bb53-8a5f-4f87-8ef2-11110045c206)

### Solution

OnePlus 7T Pro, should have a infrared disstance finder. If the camera app could use this distance finder, the issue might be fixed forever.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by HighPriest** [comment]
![Screenshot_20240131-231135_Settings suggestions.png](https://github.com/crdroidandroid/issue_tracker/assets/58490197/73a586f5-e623-4fc5-b6e3-35d84c926236)

A "Camera Laser Finder" shows up in settings search, but such a setting does not actually exist in this directory :(

**Comment by ShevT** [comment]
The laser sensor is working and in use.
It may need to be wiped, as well as the cameras.
This problem is also present on the official Android 12 firmware. Checked not once.
