### ISSUE TITLE
Not able to login in playstore.

### ISSUE THREAD

**Issue by Abhay534** [crdroidandroid/issue_tracker#322]
### Issue type

Feature not working as intended

### Device

k20 Pro

### crDroid version

crDroid 10

### Exact version / Build date

10.1 latest 

### Bug description

when i click login , login page comes and in 2 seconds it disappears.

### Steps to reproduce

what to do ?

### Relevant log (logcat/build log)

```shell
Not able to login in playstore
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Please fill information properly so we can validate you have a proper install.
Needed info:
- what gapps you have installed with build date and all
- this is a clean flash?
- how did you install gapps (steps procedure after rom.zip)
