### ISSUE TITLE
Vowifi/Volte switch not automatically happening

### ISSUE THREAD

**Issue by Uzumaki-D-Vishal** [crdroidandroid/issue_tracker#323]
### Issue type

Feature not working as intended

### Device

Enchilada
[logcat.txt](https://github.com/crdroidandroid/issue_tracker/files/14227738/logcat.txt)
[device_info.txt](https://github.com/crdroidandroid/issue_tracker/files/14227739/device_info.txt)
[dmesg.txt](https://github.com/crdroidandroid/issue_tracker/files/14227740/dmesg.txt)

### crDroid version

crDroid 10

### Exact version / Build date

04042024

### Bug description

Vowifi not automatically turning on 

### Steps to reproduce

Xxxx

### Relevant log (logcat/build log)

```shell
Xxxx
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Terminator-J** [comment]
Do you mean being able to hand off a call seamlessly between VoWiFi and VoLTE when moving out of range of WiFi, without the call dropping?
Does that even work in upstream LineageOS?

**Comment by Terminator-J** [comment]
Couldn't reproduce issue. Started VoWiFi calls & walked outside away from home; call handed off to VoLTE without dropping (T-Mobile SIM in USA).
