### ISSUE TITLE
Incoming calls are "Unknown" instead of phone number while using VoLTE

### ISSUE THREAD

**Issue by krolik92** [crdroidandroid/issue_tracker#324]
### Issue type

Feature not working as intended

### Device

POCO F3 (alioth)

### crDroid version

crDroid 10

### Exact version / Build date

crDroid: 10.2/2024-02-10
Firmware: fw_alioth_miui_ALIOTHEEAGlobal_V14.0.11.0.TKHEUXM

### Bug description

Incoming calls are "Unknown" instead of phone number while using VoLTE. Only disabling VoLTE solve the problem and incoming calls are shown properly.
Operator: Mobile Vikings Poland (Play MVNO)

### Steps to reproduce

1. In settings enable VoLTE
2. Incoming calls will be shown as unknown

### Relevant log (logcat/build log)

```shell
<<< log_count = 9 >>>
[02-11 09:51:01.742 21434:21434 D/LogcatReader]
[LogcatLiveFragment] onServiceConnected

[02-11 09:51:05.898 21434:21434 D/LogcatReader]
[Logcat] onActivityInBackground

[02-11 09:51:23.094 21434:21434 D/LogcatReader]
[Logcat] onActivityInForeground

[02-11 09:51:23.094 21434:21434 D/LogcatReader]
[Logcat] Posting pending logs

[02-11 09:51:23.105 21434:21434 D/LogcatReader]
[LogcatLiveFragment] onServiceConnected

[02-11 09:51:30.505 21434:21434 D/LogcatReader]
[Logcat] onActivityInBackground

[02-11 09:51:35.089 21434:21434 D/LogcatReader]
[Logcat] onActivityInForeground

[02-11 09:51:35.089 21434:21434 D/LogcatReader]
[Logcat] Posting pending logs

[02-11 09:51:35.103 21434:21434 D/LogcatReader]
[LogcatLiveFragment] onServiceConnected
```

### Screenshots or videos

![Screenshot_20240211-094143_Phone](https://github.com/crdroidandroid/issue_tracker/assets/84180079/e939c6ca-1fb3-47c8-890a-b06aedf4cd94)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by invisible789** [comment]
No such issue exists, it may be centric to you only
Volte and vowifi even doesn't have this issue at all
I recommend you to Do a clean flash to get everything in place, Thank you

**Comment by raystef66** [comment]
solution :  wrong MBN as modem was unable to pick right MBN

**Comment by oczkers** [comment]
@raystef66  did you solved this issue?

**Comment by invisible789** [comment]
> @raystef66 did you solved this issue?

This is not rom issue, instead modem issue, you can easily set right MBN to solve this issue, moreover flash latest 1.0.2 hyper fw and hopefully you don't need to do anything to fix it

**Comment by oczkers** [comment]
@invisible789 how can ichange mbn, some setprop values?

**Comment by invisible789** [comment]
> @invisible789 how can ichange mbn, some setprop values?

No, you need windows PC to do that , are you in tg group of crDroid?
