### ISSUE TITLE
bug: Screen Cast cannot turn off phone screen while watching cast on TV

### ISSUE THREAD

**Issue by xPhoenisX** [crdroidandroid/issue_tracker#325]
### Issue type

Feature not working as intended

### Device

Xiaomi Mi 10T 5G, codename: apollo

### crDroid version

crDroid 10

### Exact version / Build date

Build number: UQ1A.231205.015

### Bug description

Hey, I have a problem with my Screen Cast. Whenever I cast something from my phone to my TV, the phone screen stays on and drains the battery. I want to turn off the phone screen while watching the cast on TV, but I can't find any option to do that. Is there a way to fix this?

### Steps to reproduce

1. turn on screen cast
2. connect to device
3. play a YouTube video
4. press the phone button to turn off screen

### Relevant log (logcat/build log)

```shell
none
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unfortunately that's how it works
screen mirror just mirrors whatever is on your screen
screen off - mirroring is off
