### ISSUE TITLE
Can't take a picture from some services

### ISSUE THREAD

**Issue by dotologin01** [crdroidandroid/issue_tracker#326]
### Issue type

Other

### Device

Poco x3 pro

### crDroid version

crDroid 10

### Exact version / Build date

Crdroid 10.2

### Bug description

In WhatsApp after update I can't take picture to send, and download picture that I have from other people, on reddit it works normally,
![Screenshot_20240216-031122_WhatsApp](https://github.com/crdroidandroid/issue_tracker/assets/146325084/1e1dbf2e-c520-42d7-8e70-69f18073fd35)

And in tik Tok I can't download anything, it's create empty 0 kb files

### Steps to reproduce

Step 1. Crdroid 10.2
Step2. Try to download picture from WhatsApp or tiktok

### Relevant log (logcat/build log)

```shell
Don't know
```

### Screenshots or videos

![Screenshot_20240216-031430_Файлы](https://github.com/crdroidandroid/issue_tracker/assets/146325084/862afb22-d4b0-425f-aaca-f938e3f28a86)
Try to download videos tiktok

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
is this a cloned app where storage doesn't work?
working just fine here, but different device

**Comment by dotologin01** [comment]
No it's not clonned app, it's original, same issue have app pikabu

**Comment by gwolf2u** [comment]
this should be fixed
