### ISSUE TITLE
Incorrect sample font styles

### ISSUE THREAD

**Issue by tgex0** [crdroidandroid/issue_tracker#327]
### Issue type

User interface

### Device

Xiaomi MI 8 (dipper)

### crDroid version

crDroid 10

### Exact version / Build date

10.2/2024-02-16

### Bug description

Settings -> crDroid Settings -> User Interface -> Font style

Select any font.
Default, NothingDot57 and Sans-Serif sample fonts change to the selected font style.
They should remain showing their own respective font styles.

Screenshot shows NothingDot57 showing as redressed (I just chose redressed for the screenshot as it's a very distinctive font). Default and Sans-Serif also change.

### Steps to reproduce

1. Settings
2. crDroid Settings
3. User Interface
4. Font style
5. Choose any font
6. Check the Default, NothingDot57 and Sans-Serif sample font styles (they will have changed to the selected font style)

### Relevant log (logcat/build log)

```shell
N/A
```

### Screenshots or videos

![Screenshot_20240217-144406_Settings](https://github.com/crdroidandroid/issue_tracker/assets/160293965/118c2d48-a381-4cdc-955f-141126987a04)

### Solution

I think the problem possibly stems from the use of config_bodyFontFamily for the sample font style in the FontsPicker.java file.
I'm not sure what the best solution would be, though. 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by tgex0** [comment]
I've just noticed that the same thing happens with Default and Sans-Serif (but not NothingDot57) when applying a new font via Settings -> Wallpaper and style -> Home screen -> Font (i.e. the Aa sample text for Default and Sans-Serif takes on the selected font style).

Incidentally, the order of fonts in Settings -> Wallpaper and style -> Home screen -> Font seems a bit random and not alphabetical (does not match the order in Settings -> crDroid Settings -> User Interface -> Font style) . Not a big deal but Is this intentional? If not, I can create a new bug report. Thanks.

**Comment by gwolf2u** [comment]
#nofix
