### ISSUE TITLE
bug: App Not Responding Then Turns My Phone freeze

### ISSUE THREAD

**Issue by kudangel** [crdroidandroid/issue_tracker#33]
### Issue type

User interface

### Device

POCO X3 NFC | SURYA

### crDroid version

crDroid 8

### Exact version

8.10

### Bug description

My apps keep crashing and displaying "App Not Responding" messages, mostly from Playstore apps. When it crashes, it freezes my device, forcing me to hold down the power button to restart. My device is rooted, yet I disable all of my modules, and it still crashes. I'm hoping you can assist in resolving these issues.

### Steps to reproduce

N/A

### Relevant log (logcat/build log)

```shell
N/A
```

### Screenshots or videos

N/A

### Solution

N/A

### Additional context

N/A

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
logcat needed
ANR can be identified only via that

**Comment by kudangel** [comment]
Log cat
