### ISSUE TITLE
Cannot change vibration strength + some haptics not working

### ISSUE THREAD

**Issue by Twifus** [crdroidandroid/issue_tracker#330]
### Issue type

Feature not working as intended

### Device

Poco F1 (beryllium)

### crDroid version

crDroid 10

### Exact version / Build date

10.2/2024-02-08

### Bug description

Vibration strength can't configured, only can toggle on/off
Additionally, even when toggles are on, haptics like touch feedback, back gesture haptics and keyboard "vibrate on key press" don't work.

### Steps to reproduce

Open Settings > Sound & vibrations > Vibrations & haptics
Notice there is no slider to change strength.
Try to toggle the settings off/on.
Notice that event when toggled on, some haptics are not working.

### Relevant log (logcat/build log)

```shell
02-18 10:04:36.642 D/PrefCtrlListHelper(8315): Could not find Context-only controller for pref: com.android.settings.accessibility.VibrationPreferenceController
02-18 10:04:36.715 D/DashboardFragment(8315): Cannot find preference with key other_sounds_and_vibrations_category in Controller PreferenceCategoryController
02-18 10:04:55.272 D/DashboardFragment(8315): Cannot find preference with key other_sounds_and_vibrations_category in Controller PreferenceCategoryController
02-18 10:05:07.174 D/DashboardFragment(8315): Cannot find preference with key other_sounds_and_vibrations_category in Controller PreferenceCategoryController
02-18 10:05:08.710 D/SettingsActivity(8315): Switching to fragment com.android.settings.accessibility.VibrationSettings
02-18 10:05:08.710 D/SubSettings(8315): Launching fragment com.android.settings.accessibility.VibrationSettings
02-18 10:05:08.714 D/PrefCtrlListHelper(8315): Could not find Context-only controller for pref: com.android.settings.accessibility.VibrationMainSwitchPreferenceController
02-18 10:05:08.714 D/PrefCtrlListHelper(8315): Could not find Context-only controller for pref: com.android.settings.accessibility.RingVibrationTogglePreferenceController
02-18 10:05:08.715 D/PrefCtrlListHelper(8315): Could not find Context-only controller for pref: com.android.settings.accessibility.VibrationRampingRingerTogglePreferenceController
02-18 10:05:08.715 D/PrefCtrlListHelper(8315): Could not find Context-only controller for pref: com.android.settings.accessibility.NotificationVibrationTogglePreferenceController
02-18 10:05:08.715 D/PrefCtrlListHelper(8315): Could not find Context-only controller for pref: com.android.settings.accessibility.AlarmVibrationTogglePreferenceController
02-18 10:05:08.715 D/PrefCtrlListHelper(8315): Could not find Context-only controller for pref: com.android.settings.accessibility.MediaVibrationTogglePreferenceController
02-18 10:05:08.718 D/VibrationSettings(8315): NO dashboard tiles for VibrationSettings
02-18 10:05:08.718 D/VibrationSettings(8315): All preferences added, reporting fully drawn
```

### Screenshots or videos

Toggles instead of sliders
![Screenshot_20240218-095633_Settings](https://github.com/crdroidandroid/issue_tracker/assets/43961858/4680bed8-3e15-411e-a171-cb67a2d6da80)

AOSP Keyboard "Vibrate on keypress" is enabled, but it doesn't work
![Screenshot_20240218-101538_Android Keyboard (AOSP)](https://github.com/crdroidandroid/issue_tracker/assets/43961858/e1549385-6d5c-492c-bb37-3fb657fcc1fa)

### Solution

The Vibrations & haptics menu should look like this
![Screenshot_20240218-101212_YouTube](https://github.com/crdroidandroid/issue_tracker/assets/43961858/62c43170-85d9-4416-b738-1d92a3576432)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
some haptics works since are controlled app side or have different toggles
check crDroid settings or app settings

as for vibration strength, we don't have that implemented
