### ISSUE TITLE
bug: showing no sim card( 4g sim not working in v9.2) in gsi

### ISSUE THREAD

**Issue by mkr-infinity** [crdroidandroid/issue_tracker#331]
### Issue type

Feature not working as intended

### Device

Device= Lenovo TB-X306X

### crDroid version

crDroid 9

### Exact version / Build date

Fri Feb 17 00:45:50 UTC 2023

### Bug description

Unable to use sim card showing no sim card I have inserted sim correctly, I have checked many times same issue.

### Steps to reproduce

![Screenshot_20240224-220715_Settings](https://github.com/crdroidandroid/issue_tracker/assets/125804924/091bbc15-a914-4f57-888f-cb2e5b19ddb9)

### Relevant log (logcat/build log)

```shell
TQ1A.230205.002
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/125804924/8ecbf0de-bd63-4ffa-aa05-92551a840099

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
no log, cant proceed

**Comment by gwolf2u** [comment]
we are not officially supporting GSI so we can't control code from there

**Comment by mkr-infinity** [comment]
> no log, cant proceed

solved by installing mtk vendor in IMS section
 as i have mtk device
