### ISSUE TITLE
bug: miracast not working

### ISSUE THREAD

**Issue by csecsoliver** [crdroidandroid/issue_tracker#334]
### Issue type

Feature not working as intended

### Device

xiaomi mi 8 (dipper)

### crDroid version

crDroid 10

### Exact version / Build date

10.2/2024-03-02

### Bug description

Wfd service keeps stopping when starting screen mirroring.

### Steps to reproduce

1. Long tap screen mirroring in quick settings
2. Tap on tv name

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/j97CCn


time: 1709410322867
msg: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN7android30android_view_KeyEvent_toNativeEP7_JNIEnvP8_jobjectPNS_8KeyEventE" referenced by "/system_ext/lib64/libwfdnative.so"...
stacktrace: java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_ZN7android30android_view_KeyEvent_toNativeEP7_JNIEnvP8_jobjectPNS_8KeyEventE" referenced by "/system_ext/lib64/libwfdnative.so"...
	at java.lang.Runtime.loadLibrary0(Runtime.java:1082)
	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
	at java.lang.System.loadLibrary(System.java:1661)
	at com.qualcomm.wfd.WFDSession.<clinit>(WFDSession.java:56)
	at com.qualcomm.wfd.service.SessionManagerService.setDeviceType(SessionManagerService.java:210)
	at com.qualcomm.wfd.service.ISessionManagerService$Stub.onTransact(ISessionManagerService.java:651)
	at android.os.Binder.execTransactInternal(Binder.java:1363)
	at android.os.Binder.execTransact(Binder.java:1304)
```

### Screenshots or videos

![photo_2024-03-02_21-06-27](https://github.com/crdroidandroid/issue_tracker/assets/113012199/e04f2578-4b0a-445a-b8ad-50990cb0c591)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
#nofix
