### ISSUE TITLE
Keyboard navigation gets hidden, when Navigation hint is disabled

### ISSUE THREAD

**Issue by halfbytecode** [crdroidandroid/issue_tracker#335]
### Issue type

User interface

### Device

Google Pixel 7 Pro (cheetah)

### crDroid version

crDroid 10

### Exact version / Build date

10.2/2024-02-25

### Bug description

The keyboard navigation (downward arrow), which is used to close/minimize the keyboard, is hidden when Navigation hint is disabled.

This issue is not present on some ROMs like LineageOS, Evolution-X, and Havoc OS, the last time I checked.

### Steps to reproduce

Settings -> System -> Gestures -> Navigation mode - > Open "Gesture Navigation" settings -> Disable "Navigation hint"

Open GBoard, as usual, from a text field.

### Relevant log (logcat/build log)

```shell
N/A
```

### Screenshots or videos

Navigation hint enabled:

![Screenshot_20240304-200646_Fennec](https://github.com/crdroidandroid/issue_tracker/assets/17142444/7e866862-c927-48f3-a8e1-1e94e17407c9)

Navigation hint disabled:

![Screenshot_20240304-200559_Fennec](https://github.com/crdroidandroid/issue_tracker/assets/17142444/0553ecd9-dc13-435b-992a-469d8a2a6a7d)

Expected behavior with Navigation hint disabled (from another ROM):

![Screenshot_20230723-113939_Settings Services](https://github.com/crdroidandroid/issue_tracker/assets/17142444/9372e8bb-39f9-4d2d-9963-acdbdba5ae59)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by halfbytecode** [comment]
> why not use back gesture?

Well the absence of the keyboard navigation reduces the keyboard height and changes its placement on the screen, which can be seen in the 2nd screenshot.

The keyboard is actually much more comfortable to use with the keyboard navigation visible, due to the higher placement on the screen.

**Comment by halfbytecode** [comment]
@neobuddy89 This is also fixed in Project Matrixx, which is crDroid based.

The fix may be in one of the following commits:

https://github.com/ProjectMatrixx/android_packages_apps_Settings/commit/ab68b6b09110403e0ff63a9ad5702ff5ff9f8b9b

https://github.com/ProjectMatrixx/android_frameworks_base/commit/55e63655d22229d85fd95a2b42ffb32302460e85

https://github.com/ProjectMatrixx/android_frameworks_base/commit/ac2a3a32db59b86e7c5c64aaf56da985d42e3059

**Comment by neobuddy89** [comment]
Will check.

**Comment by halfbytecode** [comment]
On another build of Project Matrixx, this is not working unlike earlier.

I dug up some commits from Havoc OS, where this implementation seems better from using the ROM.

https://github.com/Havoc-OS/android_frameworks_base/commit/0d9b66b50ca5d6dce8630767115d5df9dc158437

https://github.com/Havoc-OS/android_frameworks_base/commit/172dd029cab7df55d1c69c8969f49c5248d681ab

https://github.com/Havoc-OS/android_frameworks_base/commit/217f52dbe95204b631ef0a5ab29e108d4befe8ca

https://github.com/Havoc-OS/android_packages_apps_Settings/commit/3d4fdb0be3ff80860c502f0713f72061155fb297

Maybe only some of these commits are needed.

**Comment by neobuddy89** [comment]
https://github.com/crdroidandroid/android_frameworks_base/commit/9ae2491c648ed6ea9a7bb275b790752b897bcecb

https://t.me/crDroidUpdates/4868

**Comment by halfbytecode** [comment]
@neobuddy89

I tried this out on the 2024-03-10 build for my device. The space below keyboard is less, with this setting turned on, than with navigation pill turned on. This makes it hard to tap on the downward arrow, used to minimize the keyboard.

Overall the height and placement of the keyboard is also not as much, as it with the navigation pill enabled. It should be as in the 3rd screenshot in my original post.

Presently this is what it looks like, with navigation pill hidden and IME space turned on:

![Screenshot_20240310-193707_Settings Suggestions](https://github.com/crdroidandroid/issue_tracker/assets/17142444/b5a578aa-6c8b-4b8c-a049-5843834e4134)

While it should be like this (screenshot from another ROM):

![Screenshot_20230723-113939_Settings Services](https://github.com/crdroidandroid/issue_tracker/assets/17142444/9372e8bb-39f9-4d2d-9963-acdbdba5ae59)

Moreover, with IME space setting enabled, 2/3 button navigation cannot be enabled now on crDroid.

**Comment by neobuddy89** [comment]
Some people prefer having no space at all. So dont want to make it transparent.

**Comment by halfbytecode** [comment]
> Some people prefer having no space at all. So dont want to make it transparent.

I meant we can make the Navigation pill transparent in the scenario: Add IMR space option is enabled + Navigation pill is hidden.

Or we can use some of the code from Havoc OS commits.

Either of these, would rectify the spacing (making it like in the 3rd screenshot in the first post), while also making the space same as with Navigation pill is enabled.

Moreover, the downward arrow is hard to press currently, which should also be fixed with this.

**Comment by halfbytecode** [comment]
Just wanted to say this may need a fix now, as it looks half baked now, with the IME switcher button also appearing on the right side below the keyboard. Below screenshot shows this.

![Screenshot_20240510-182851_crDroid Home](https://github.com/crdroidandroid/issue_tracker/assets/17142444/2258b9f2-5da4-4115-98df-759cf94fec0a)

It would be appreciated if the space below the keyboard with navigation pill disabled is (optionally) made the same as with navigation pill enabled, just like in the 3rd screenshot in the OP.

@neobuddy89
