### ISSUE TITLE
Buggy lockscreen weather condition

### ISSUE THREAD

**Issue by newname-1** [crdroidandroid/issue_tracker#336]
### Issue type

Feature not working as intended

### Device

Miatoll

### crDroid version

crDroid 10

### Exact version / Build date

Sun Feb 25, 2024

### Bug description

Lockscreen weather condition doesn't update with time. It shows sunny even at night.

![Screenshot_20240306-013834_Brave](https://github.com/crdroidandroid/issue_tracker/assets/113122396/9fff31be-cd1a-47c6-8434-831bcd353413)

### Steps to reproduce

Go to CR droid settings and then lockscreen settings
Enable lockscreen weather and weather condition.

### Relevant log (logcat/build log)

```shell
.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
issue is fixed
