### ISSUE TITLE
bug: crackling sound and temporary stops while playing music with Bluetooth

### ISSUE THREAD

**Issue by maikvitesse** [crdroidandroid/issue_tracker#340]
### Issue type

Other

### Device

POCO F2 Pro (LMI) 

### crDroid version

crDroid 10

### Exact version / Build date

10.2/2024-03-02

### Bug description

I just encountered a small problem. When I listen to music via my bluetooth earphones while the screen is off, sometimes the music stops with a crackling sound. Then a short time later the music plays again at an accelerated rate and then it works normally for quite a while until it happens again.

I also have a MatLog of this (should be found in the last lines).

### Steps to reproduce

1. Play music trough Bluetooth headset
2. Wait for the crackling sound/playback stop, music comes back at a accelerated rate
3. Music plays normally again
4. Wait till it happens again

When I turn the screen off or switch from wifi to mobile internet the problem happens faster

### Relevant log (logcat/build log)

```shell
Will upload logcat
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by maikvitesse** [comment]
[2024-03-09-18-49-30.txt](https://github.com/crdroidandroid/issue_tracker/files/14547842/2024-03-09-18-49-30.txt)

**Comment by jason-eu** [comment]
Hey, would you mind sharing

**Comment by maikvitesse** [comment]
Firmware: Global_V14.0.1.0.SJKMIXM
Gapps:  NikGapps-crdroid-official-arm64-14-20240307
Headphones model: SOUNDPEATS Air4 Lite

See screenshots for Codec and HD Audio (don't know about 'Gabeldorsche')
![Headset_Settings](https://github.com/crdroidandroid/issue_tracker/assets/4076676/60afff28-1553-4b2f-8de3-37a8a73bf7dc)
![DeveloperAudio_Settings](https://github.com/crdroidandroid/issue_tracker/assets/4076676/ffa6b361-8050-4090-bcee-7abe1cae2a30)
![DeveloperAudio_Settings2](https://github.com/crdroidandroid/issue_tracker/assets/4076676/db53c97b-415b-49e5-b473-0d550b7e0402)

**Comment by maikvitesse** [comment]
Some more information: it also depends on distance between the phone and the earphones. When I have the phone in my pocket it occurs much more often than when the phone is on the table closer to my ears.

**Comment by jason-eu** [comment]
Understood.

Keep in mind that the implementation of LDAC is problematic across most if not all AOSP based ROMs.
If you have the time to test, I would recommend trying the same headphones with a MIUI based ROM, but that may be way too much effort just for verification depending on your schedule.

With regards to the LDAC codec, if you really want to use it, I would suggest that you try the optimised or quality settings for LDAC bitrate.
This may have to be re-enabled at every reboot or reconnection/disconnection of the headphones.

**Comment by maikvitesse** [comment]
I just disabled HD-Audio and the problem is solved for me (didn't know about this option).
Don't really care about LDAC.

If I set the playback quality to "optimized for connection" in developer settings the problem is also solved.

Thanks for your help! As far as I am concerned, this issue can be closed.

**Comment by jason-eu** [comment]
Excellent, disabling HD-Audio is the solution I use as well because it stays after reboots and reconnections, unlike the quality settings option.

@gwolf2u Is there a possibility that the "optimised for connection" bitrate option can be the default going forward, as opposed to "adaptive" bitrate?
