### ISSUE TITLE
Quick settings panel bugs in landscape mode on poco X3 pro

### ISSUE THREAD

**Issue by Richinario** [crdroidandroid/issue_tracker#341]
### Issue type

User interface

### Device

POCO X3 PRO (VAYU) 256 GIGAS AND 8 RAM

### crDroid version

crDroid 10

### Exact version / Build date

28th January, 2024  and later

### Bug description

When you use the phone in landscape mode and you want to use the quick settings these bug overlapping, I have noticed that it happens more when there is a music card or audio playback, it is annoying because sometimes I can not use the quick settings panel when I watch a video or I am playing, the previous panel of the ROM crdroid versions 10 and 9 did not present this problem,  please fix it, they do a very good job and I love their ROM I promise that as soon as I have money I will make a donation because I love their work

### Steps to reproduce

Step 1: Reset Cr Droid Settings. Step 2.-Use your cell phone in landscape mode.  Step 3: Extend the quick settings panel. Step 4: The bug occurs

### Relevant log (logcat/build log)

```shell
I use the cr droid version 10.1 of January 11th, to avoid that bug but I want to update to use the new additions but the quick settings panel bug affects a lot the daily use of the device, I have used all the versions after 10.1 and they all have that big
```

### Screenshots or videos

[
![IMG_20240311_131810_207](https://github.com/crdroidandroid/issue_tracker/assets/163035502/8da8f195-4f79-45be-9eb5-466e294cdc8a)
![IMG_20240311_131810_267](https://github.com/crdroidandroid/issue_tracker/assets/163035502/fbe5d95c-172d-44bd-8212-bf2e96e87927)
![IMG_20240311_131810_048](https://github.com/crdroidandroid/issue_tracker/assets/163035502/e7b92d15-da56-47f6-8711-b1935b3e57c0)
![IMG_20240311_131801_545](https://github.com/crdroidandroid/issue_tracker/assets/163035502/a895a3ad-c2b6-424d-99f7-ddbb87c2b9f4)
](url)

### Solution

Go back to the previous version of the panel or change the dpi to 500 however everything looks small on the screen when you put that dpi

### Additional context

I love your job thank you for everything you are amazing ♥️

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Richinario** [comment]
Thank you crdroid are the best

**Comment by gwolf2u** [comment]
this is fixed
