### ISSUE TITLE
bug: Lockscreen media cover art blur filter isn't working

### ISSUE THREAD

**Issue by GabrieIBro** [crdroidandroid/issue_tracker#342]
### Issue type

Feature not working as intended

### Device

Device (miatoll)

### crDroid version

crDroid 10

### Exact version / Build date

10.2/2024-02-26

### Bug description

When Media cover art and Media cover art filter(blur) is turned on, if there's media running, the media cover will be shown on the lock screen but the blur filter doesn't apply or its level is not enough.

### Steps to reproduce

1. Go to cDroid Settings > Lock Screen.
2. Turn on Media cover art.
3. In Media cover art filter, select the blur option.
4. Run any media.
5. Check lockscreen.
 

### Relevant log (logcat/build log)

```shell
none:
```

### Screenshots or videos

My device: ![photo1710339027](https://github.com/crdroidandroid/issue_tracker/assets/106329635/e24845d4-cbee-482f-b050-e6436bdb8df8)

How it's supposed to look like(Example from internet):![Screenshot from 2024-03-13 10-43-47](https://github.com/crdroidandroid/issue_tracker/assets/106329635/8f47eee1-d018-48b3-b729-4f95fea8ea81)

### Solution

Increase the blur level or add a slider, so the user can adjust it himself.

### Additional context

Bug is present on other devices.(As per telegram channel helpdesk)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
feature has been removed
