### ISSUE TITLE
redmi note 8t no wlan

### ISSUE THREAD

**Issue by yude821** [crdroidandroid/issue_tracker#344]
### Issue type

Feature not working as intended

### Device

redmi note 8t  ginkgo

### crDroid version

crDroid 10

### Exact version / Build date

crDroidAndroid-14.0-20240209-ginkgo-v10.2

### Bug description

redmi note 8t no wlan

### Steps to reproduce

No

### Relevant log (logcat/build log)

```shell
No
```

### Screenshots or videos

no

### Solution

no

### Additional context

no

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
no logs
