### ISSUE TITLE
bug: audio stops working once headphones are plugged in | Redmi Note 12 (topaz)

### ISSUE THREAD

**Issue by gitlimes** [crdroidandroid/issue_tracker#346]
### Issue type

Feature not working as intended

### Device

Redmi Note 12 (topaz)

### crDroid version

crDroid 10

### Exact version / Build date

10.2/2024-03-08

### Bug description

The audio works fine when only using the speaker. However, once headphones are plugged into the headphone jack, audio stops working globally, and a reboot is necessary to fix it.

The headphones are detected (as noted by the Google Assistant notification, as well as the change of the volume level shown in the volume slider), but something is definitely going wrong somewhere.

### Steps to reproduce

Step 1: boot crDroid
Step 2: plug headphone in through jack
Step 3: no more audio.

### Relevant log (logcat/build log)

```shell
I'm not familiar enough with Android logcats to understand which part of the log output is the "relevant" part, so here's a recording (made with MatLog at default settings as shipped by your rom) where I plug a headphone in.

https://gist.github.com/gitlimes/c0cbba66b6dfb9cea729615e758baac1
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by NikitaSavc** [comment]
Sorry for late reply. 

For me, headphones are working. 
We noticed that many wired headphones do not work (and some do, as in my case). We'll try to fix it in the next version, thanks!

Regards, Nikita.

**Comment by NikitaSavc** [comment]
@gitlimes please, can you say, what your headphones? Manufacturer, model?

**Comment by gitlimes** [comment]
They're JBL T110 wired earbuds.

It sounds really strange to me that the headphones' make/model has anything to do with this bug, considering that the audio jack is an analog interface, but if you say so... I'm sure you know more about this than I do.

**Comment by gitlimes** [comment]
Update: after installing your latest build (`crDroidAndroid-14.0-20240505-topaz-v10.4`), I can happily report that the issue has been fixed! Closing this.

**Comment by gitlimes** [comment]
huh, works just fine for me. I'll reopen this, then.

**Comment by gwolf2u** [comment]
please submit new log with latest build
