### ISSUE TITLE
bug: color palette problem

### ISSUE THREAD

**Issue by mt190502** [crdroidandroid/issue_tracker#347]
### Issue type

User interface

### Device

Samsung A52 (SM-A525F)

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024-04-06

### Bug description

When i selected any color palette from wallpapers&style menu. Colors not matching palette.
The colors after the first 5 palettes do not match.

### Steps to reproduce

1. Go to the settings
2. Select wallpaper & style
3. Select any palette after 5 palettes

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/62564400/2964668d-1240-4b75-959e-149be77b6f48

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unfortunately this device is not on our official list, so we can't validate if code was altered in any way, or also have proper way to contact maintainer
personally, on todays build, I have no such issue, so I will have to close this issue
