### ISSUE TITLE
Bug: Root LsPosed NULL pointer exception

### ISSUE THREAD

**Issue by cygiel5420** [crdroidandroid/issue_tracker#349]
### Issue type

Other

### Device

Pixel 7 Pro (cheetah) 

### crDroid version

crDroid 10

### Exact version / Build date

10.4

### Bug description

com.android.shell NULL pointer exception when trying to open LsPosed

### Steps to reproduce

1. Gain root via KernelSU (magisk doesn't work with CrDroid version 10.4)
2. Install zygisk next module
3. Install LsPosed module
4. Reboot
5. Click on "LsPosed loaded" notification
6. Observe nothing happening besides bug report menu pop up. 

### Relevant log (logcat/build log)

```shell
Url provided for LsPosed related crash log https://paste.crdroid.net/mXt5Kj
```

### Additional context
LsPosed worked perfectly fine up until CrDroid version 10.2. It stopped working with v10.3, and still doesn't work with v10.4. 
 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
issues not related to crDroid

**Comment by cygiel5420** [comment]
LsPosed loads and works normal in the newest update. So it was a crdroid v10.4 system fault.

**Comment by gwolf2u** [comment]
If it works, doesn't mean it was crDroid issue
Roms are not created to work with modz, is the other way around

**Comment by cygiel5420** [comment]
Right, but lsposed stopped working only with v10.3 and v10.4. The error points to com.android.shell. There were other Java errors even for apps included with crdroid, but I haven't reported those in time. Now they're all gone. That's why I'm saying something was going on in v10.4. It's a great ROM, I appreciate your guys' work a lot. Thank you!

**Comment by halfbytecode** [comment]
LSPosed v1.9.3_mod by mywalkb should work fine on QPR2 builds. It also installs right over the last official LSPosed build (v1.9.2).
