### ISSUE TITLE
bug: power button 

### ISSUE THREAD

**Issue by ruddx1** [crdroidandroid/issue_tracker#350]
### Issue type

Other

### Device

Redmi note 8 (ginkgo)

### crDroid version

crDroid 10

### Exact version / Build date

crDroidAndroid-14.0-20240406-ginkgo-v10.4.zip

### Bug description

the power button can't lock for version
crDroidAndroid-14.0-20240406-ginkgo-v10.4.zip

### Steps to reproduce

No

### Relevant log (logcat/build log)

```shell
No
```

### Screenshots or videos

No

### Solution

No

### Additional context

I need update bug please 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
missing proper issue description
