### ISSUE TITLE
crDroid Home not working well with custom iconpacks

### ISSUE THREAD

**Issue by chemha** [crdroidandroid/issue_tracker#352]
### Issue type

User interface

### Device

LMI

### crDroid version

crDroid 10

### Exact version / Build date

10.3/2024-05-04

### Bug description

When trying to open/move apps a white background appears. Only happens with custom iconpacks.

### Steps to reproduce

Install a custom iconpack preferably transparent.
Use it in crDroid home.
Open/move apps.

### Relevant log (logcat/build log)

```shell
No log as this is a user interface issue.
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/36114312/6e01caa2-0f3f-438b-864d-8eed91ce34ca

### Solution

Revert the changes in the launcher. The release before latest worked fine.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
happening in crDroid 10.4 also?

**Comment by chemha** [comment]
> happening in crDroid 10.4 also?

Yes, same behaviour

**Comment by pauloconstanca** [comment]
Hello! I can say that this also happens on CrDroid 10.5, same issue as described.

**Comment by chemha** [comment]
Other users are reporting this issue on clean flash.

**Comment by gwolf2u** [comment]
#nofix
