### ISSUE TITLE
bug: title (<-- External storage keeps stopping)

### ISSUE THREAD

**Issue by Dashhamada** [crdroidandroid/issue_tracker#353]
### Issue type

Feature not working as intended

### Device

Redmi Note 10s Rosemary 
![Screenshot_20240408-170806_Files](https://github.com/crdroidandroid/issue_tracker/assets/125392912/9670981a-c3c3-4b7c-8d52-f244dc355cff)

### crDroid version

crDroid 10

### Exact version / Build date

crDroidAndroid-14.0-20240218-rosemary-v10.2.zip

### Bug description

When you open the file manager, the “External storage keeps stopping” window appears and you couldn't use external storage. 

### Steps to reproduce

Step 1

### Relevant log (logcat/build log)

```shell
Log
```

### Screenshots or videos

![Screenshot_20240408-170806_Files](https://github.com/crdroidandroid/issue_tracker/assets/125392912/cdfb4d25-d50c-41c5-a578-9a65edfd7588)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
need proper logcat please
