### ISSUE TITLE
Bug: NFC Extended Length support

### ISSUE THREAD

**Issue by Andrea-169** [crdroidandroid/issue_tracker#354]
### Issue type

Feature not working as intended

### Device

Redmi Note 8 Pro (Begonia)

### crDroid version

crDroid 10

### Exact version / Build date

10.2 (2024-02-09)

### Bug description

The "Extended Length" functionality of the NFC interface does not work with the apps that require it (e.g. CieID), making it impossible to read the cards that require support to this functionality to be read.
By approaching a card to the smartphone it is recognized, the reading starts, but after a short time the reading is interrupted with an error. By verifying the technical details of the app (contacted the technical support), the error is caused by the fact that the "Extended Length" function of the NFC interface is not supported or implemented by the android distro in use.

Restoring the original "miui_BEGONIAEEAGlobal_V12.5.15.0.RGGEUXM_cd5652a4c4_11.0" reading works properly, confirming the full hardware/firmware support.

### Steps to reproduce

Simply try reading a NFC card or NFC tag that requires support to the "Extended Length" function to be read correctly. The approach of the card/tag is recognized, but the reading goes into error.
In my case, reading the "Electronic Identity Card" via the "CieID" app.

### Relevant log (logcat/build log)

```shell
None
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Andrea-169** [comment]
Tested version 10.4 (2024-04-12) with clean installation.
Bug still present.

**Comment by gwolf2u** [comment]
need proper logcat
