### ISSUE TITLE
bug: phone reboots ui when you unlock on notificaitons

### ISSUE THREAD

**Issue by Zed9K** [crdroidandroid/issue_tracker#355]
### Issue type

User interface

### Device

dumpling

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024-04-06
it happened in all 10.x builds tho.

### Bug description

the phone reboots UI whenever you unlock it or press the power button instantly after you get a notificaion on your phone, with wake on screen for notifications on.

here is a vidoe of it happening ( sorry for the bad quality )

https://github.com/crdroidandroid/issue_tracker/assets/31599865/c629acf9-9352-4d48-a8ac-fcf85288785c

### Steps to reproduce

step 1. have wake screen for notificaions on
step 2. get a notificaion
step 3. unlock your phone using fp or even press the power button while you are getting the notification
step 4. phone reboots ui

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/VYpFoB
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/31599865/8218cd78-589b-4a4b-a0ec-fcda66a185bc

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by AodX** [comment]
i have been testing more and more lately, i think this is related to the clock font on the lockscreen ( not 100% sure ).

**Comment by gwolf2u** [comment]
unofficial builds can't be validated with code as well as no way to contact device maintainer
so no way to check this bug especially as it doesn't happen here

**Comment by Zed9K** [comment]
> unofficial builds can't be validated with code as well as no way to contact device maintainer so no way to check this bug especially as it doesn't happen here

I'm the device maintainer, and i'm planning for official soon, but i want to make sure its free of bugs.
