### ISSUE TITLE
bug: Blacked out notificaciones on Landscape

### ISSUE THREAD

**Issue by lurrutiaa** [crdroidandroid/issue_tracker#356]
### Issue type

User interface

### Device

Poco F3

### crDroid version

crDroid 10

### Exact version / Build date

10.3 2024/April/5

### Bug description

Notifications are blacked out on Landscape screen.
![Screenshot_20240409-083041_crDroid Home~2](https://github.com/crdroidandroid/issue_tracker/assets/145207515/adf7adfe-ff63-47e1-a012-c8b80d8f8016)
![Screenshot_20240409-083107_YouTube~2](https://github.com/crdroidandroid/issue_tracker/assets/145207515/85067ef6-0fec-482b-a7e4-a3e23ff49033)

### Steps to reproduce

Receive a notification, could be of any app.
Check in normal vertical mode an the notification shows the content as normal.
Flip the screen to landscape and the only or all notifications received will now show a dark gray container with no information in it.

### Relevant log (logcat/build log)

```shell
Not sure how to do this, sorry
```

### Screenshots or videos

![Screenshot_20240409-083041_crDroid Home~2](https://github.com/crdroidandroid/issue_tracker/assets/145207515/22e48113-7d36-4bc0-af84-f1c67f943baa)
![Screenshot_20240409-083107_YouTube~2](https://github.com/crdroidandroid/issue_tracker/assets/145207515/94fcadfc-6569-44bb-970f-5d33f8c4e4cd)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment]
Will be fixed on new build (10.4)

**Comment by lurrutiaa** [comment]
Good day sir,

I think this might help a bit on resolving the issue if it has not been solved.

I was playing with the titles settings and upon setting the titles columns and rows to 3,3; 2,2 the notifications actually work on landscape mode. However when I try to return to defaults the notifications now appear to be blacked out... Then if I return to the previous vertical, horizontal 3,3;2,2 it shows the notifications but really small, still shows them which is good at some point.
I'm attaching screenshots.

Hope this might help.

Warmest regards,

**Comment by raystef66** [comment]
> Good day sir, I think this might help a bit on resolving the issue if it has not been solved. I was playing with the titles settings and upon setting the titles columns and rows to 3,3; 2,2 the notifications actually work on landscape mode. However when I try to return to defaults the notifications now appear to be blacked out... Then if I return to the previous vertical, horizontal 3,3;2,2 it shows the notifications but really small, still shows them which is good at some point. I'm attaching screenshots. Hope this might help. Warmest regards, El 9 abr 2024, 10:30 AM -0600, raystef66 ***@***.***>, escribió:
> […](#)
> Will be fixed on new build (10.4) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

Thx for the feedback.
There were indeed some ways to get it working again by changing the numbers. But not a durable solution.
Lets wait the 10.4 and feel free to give some feedback on it as well.
