### ISSUE TITLE
Bug: Smart Pixels

### ISSUE THREAD

**Issue by cygiel5420** [crdroidandroid/issue_tracker#359]
### Issue type

User interface

### Device

Pixel 7 Pro

### crDroid version

crDroid 10

### Exact version / Build date

10.4

### Bug description

Enabling Smart Pixels causes certain popups (observed in Package installer) and screens (observed in App Permissions) to be unresponsive to touch.

### Steps to reproduce

Enable Smart Pixels

Package installer:
Install any app from storage
Try to click "Install"

App Permissions:
Go to any apps Permissions page
Try to scroll through the menu or click on any setting

### Relevant log (logcat/build log)

```shell
None. Unable to retrieve when screen is bugged out.
```

### Screenshots or videos

Package Installer:

https://github.com/crdroidandroid/issue_tracker/assets/133622561/dc494913-8565-4c69-a056-160d113df837

Scrolling through menus in apps and screens:

https://github.com/crdroidandroid/issue_tracker/assets/133622561/b248f67e-084c-49da-8955-675532c1fbda

### Solution

Disable Smart Pixels

### Additional context

First time this bug occurred, I thought I did something wrong when setting up my device, so I factory reset it. But then the bug happened again afterward when setting up the device again. I retraced my steps and phone started working normal after disabling Smart Pixels. I've enabled Smart Pixels again after a few hours and there is no issue yet. I'll try to retreive logs when the issue happens again. 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
known issue with smart pixels
read it's note
"Smart pixels is a power saving feature. Depending on how many pixels you decide to turn off, you could see improvement in battery life. _Note that in some cases it can result in unresponsive areas on touch screen_"
