### ISSUE TITLE
Bug: Pulse

### ISSUE THREAD

**Issue by cygiel5420** [crdroidandroid/issue_tracker#360]
### Issue type

Feature not working as intended

### Device

Pixel 7 Pro

### crDroid version

crDroid 10

### Exact version / Build date

10.4

### Bug description

Pulse isn't working despite being enabled

### Steps to reproduce

1. Enable Pulse
2. Play media
3. Observe nothing happening

### Relevant log (logcat/build log)

```shell
Can't find anything in matlog related to Pulse. Probably looking through wrong filters.
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/133622561/c6e756dd-3caf-4d78-8043-750e92e4aef6

### Solution

One way to fix is to crash the System UI by choosing different Font styles in crdroid settings. 
Another way that permanently fixed the issue was installed FDE.AI, set it to performance mode, enable CPU, and GPU tweaks. I also installed Swap torpedo module, and ram management fixes module. Not sure which one of those fixed this issue, but Pulse works without a hickup. 

### Additional context

Pulse worked fine in CrDroid version 10.2.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Pulse needs button navigation

**Comment by gwolf2u** [comment]
pulse needs button navigation

**Comment by cygiel5420** [comment]
> pulse needs button navigation

It always worked with Gesture navigation for me. It works perfectly fine now after I installed fde.ai and those 2 modules mentioned above.
