### ISSUE TITLE
Bug: Clear Calling

### ISSUE THREAD

**Issue by cygiel5420** [crdroidandroid/issue_tracker#361]
### Issue type

Other

### Device

Pixel 7 Pro

### crDroid version

crDroid 10

### Exact version / Build date

10.4

### Bug description

Clear Calling feature is missing from Sound menu

### Steps to reproduce

Install CrDroid version 10.4
Go to Sounds
Find that Clear Calling feature is missing

### Relevant log (logcat/build log)

```shell
None
```

### Additional context

Clear Calling feature was present in CrDroid version 10.2. With v10.3 and v10.4 it's gone, again. Not sure if that's an intentional system change or a bug. 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
pixel feature framework was not ported in initial crDroid 10.3 / 10.4
we have just enabled back the framework and should be live with next updates
