### ISSUE TITLE
Bug: Font Style System UI crash

### ISSUE THREAD

**Issue by cygiel5420** [crdroidandroid/issue_tracker#362]
### Issue type

User interface

### Device

Pixel 7 Pro

### crDroid version

crDroid 10

### Exact version / Build date

10.4

### Bug description

System UI crashes when choosing Font style in CrDroid settings. 

### Steps to reproduce

Go to CrDroid settings
Navigate to User Interface tab
Open Font Style
Choose from listed fonts
Observe System UI crash as you go through different fonts

### Relevant log (logcat/build log)

```shell
Url to crash log related to the issue https://paste.crdroid.net/a0uEhA
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
https://github.com/crdroidandroid/issue_tracker/issues/329
