### ISSUE TITLE
Feature request: add "Transparent" option in OmniJaws weather widget

### ISSUE THREAD

**Issue by MONaH-Rasta** [crdroidandroid/issue_tracker#365]
### Issue type

Feature request

### Device

Poco X3 Pro (vayu)

### crDroid version

crDroid 10

### Exact version / Build date

2024-04-11

### Bug description

In this custom ROM [[lineage-21.0-20240210-UNOFFICIAL-mido](https://github.com/zeelog/OTA/releases/tag/90.0)](https://github.com/zeelog/OTA/releases) OmniJaws weather widget has an option "Transparent". Please, add it into your version.

Here is apk: [OmniJaws.zip](https://github.com/crdroidandroid/issue_tracker/files/14959428/OmniJaws.zip)

### Screenshots or videos

![photo_2024-04-12_13-54-39](https://github.com/crdroidandroid/issue_tracker/assets/71013674/c9a57ec4-4751-41f8-833c-fb914e965183)![photo_2024-04-12_13-53-59](https://github.com/crdroidandroid/issue_tracker/assets/71013674/9da6cccd-acfa-4f7f-b052-fbe52aa84859)

### Acknowledgements

- [x] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
no promises
