### ISSUE TITLE
Bug(or maybe intentional but I don't understand why): Alarm only shows on lock screen when within 12 hours of the set alarm time.  

### ISSUE THREAD

**Issue by RandomGuy512** [crdroidandroid/issue_tracker#37]
### Issue type

User interface

### Device

Redmi Note 10 Pro (sweet)

### crDroid version

crDroid 8

### Exact version

8.9

### Bug description

Alarms only become visible on the lock screen when it is 12 hours or less before they are set to ring, e.g. if I set an alarm for 09:00 (9am) one morning it will not be shown on my lock screen until 21:00 (9pm) the might before.  I do not know if this behaviour is a bug or just an oversight, but I see no reason for it to be an intentional feature, especially as there is no setting to control it (unless I'm just being dumb and there is actually one, please tell me if so.).  

### Steps to reproduce

1: set an alarm for any time within the next 12 hours,
2: see that it is on the lock screen (if not, change settings),
3: set an alarm for any time more than 12 hours in the future,
4: see wether or not is it on the lock screen, in my case it never is.  

### Relevant log (logcat/build log)

```shell
I do not believe any logs are relevant to this, however if they are please let me know exactly what is needed, and how exactly to retrieve it.
```

### Solution

Maybe add `Settings>Display>Lock Screen>Always show next alarm` toggle.  

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
you're not using latest version
https://crdroid.net/sweet/8

**Comment by RandomGuy512** [comment]
Oh sorry about that.  However, I have now updated to the latest version (8.10) and this is still an issue.  The update also broke some google apps so I will have to make a seperate forum issue about that ... :(
