### ISSUE TITLE
"Orange" mobile internet and MMS not working

### ISSUE THREAD

**Issue by jakubalex47** [crdroidandroid/issue_tracker#372]
### Issue type

Source code related

### Device

Dipper

### crDroid version

crDroid 10

### Exact version / Build date

Every 10.x version
Logs recorded on latest 10.4 crDroidAndroid-14.0-20240410-dipper-v10.4.zip

### Bug description

On crdroid A14 with Orange SIM provider mobile internet over ipv4 and MMS don't work. It work for ex. in MIUI and Pixel Experience A13.
APN is automatically set up exactly like in PE A13 and MIUI so it's not a problem with APN configuration.
Partial workaround: set up APN Orange internet to ipv6, which is also supported by Orange (Orange supports 2 different APN configurations for internet - both should work, not only the second one). There is no workaround for MMS not sending and not receiving (Orange supports only one MMS APN configuration). I send screenshots of APN configuration, logs and screen recording during the logs.
Link to screen recording (file is too big to place here): https://youtu.be/5cFioSr0NGk
Logs: [2024-04-14-19-11-31.txt](https://github.com/crdroidandroid/issue_tracker/files/14971582/2024-04-14-19-11-31.txt)

![Screenshot_20240227-153348_Ustawienia](https://github.com/crdroidandroid/issue_tracker/assets/163746175/3707ca64-b88a-4052-86bd-17506f3246c1)
![Screenshot_20240227-153436_Ustawienia](https://github.com/crdroidandroid/issue_tracker/assets/163746175/7d8d5b83-fc8d-4895-9693-bdc5019aad3d)
![Screenshot_20240227-153526_Ustawienia](https://github.com/crdroidandroid/issue_tracker/assets/163746175/de46afbc-639b-4f6c-9b3d-6108fbbd0e77)
![Screenshot_20240227-153538_Ustawienia](https://github.com/crdroidandroid/issue_tracker/assets/163746175/8222ced4-b52c-4d9b-b404-9f8be045350a)

### Steps to reproduce

Steps I done in recorded logs and screen recording:
1. Reset APN settings to default (which are correct, like "Orange" provided)
2. Choose Orange PL by default.
3. Open web browser - internet doesn't work.
4. Try send or reveive MMS - doesn't work.
5. Change APN Orange internet settings to ipv6 - internet works now, but MMS still doesn't work.

### Relevant log (logcat/build log)

```shell
In bug description (length too big)
```

### Solution

It's probably a source issue (missing files/configs?) Definitely not the provider issue because everything works perfectly in every A13 and previous ROMs.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
we use APN sources from LOS upstream
any idea if this happens on LOS?

**Comment by gwolf2u** [comment]
they will need to fix it upstream
probably AOSP bug
