### ISSUE TITLE
Color Palette not fully working 

### ISSUE THREAD

**Issue by Detlev1** [crdroidandroid/issue_tracker#373]
### Issue type

Feature not working as intended

### Device

begonia 

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024.04.12

### Bug description

#347 
Not all color palettes are working. Only the first 4 work.

### Steps to reproduce

#347

### Relevant log (logcat/build log)

```shell
None
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
some code changes were made to theme engine lately, however as with my previous comment on your issue #347, we have no way of telling if code is there on any unofficial device as well as no way to contact device maintainer

**Comment by Detlev1** [comment]
#347 was not my issue. I just saw that the issue was closed without a fix because the device was not supported. That's why I created this issue. I have the exact same issue but on a supported device. (Redmi Note 8 Pro, Begonia). Version and Device are specified correctly

**Comment by yucellmustafa** [comment]
> some code changes were made to theme engine lately, however as with my previous comment on your issue #347, we have no way of telling if code is there on any unofficial device as well as no way to contact device maintainer

I'm experiencing this problem too. After 5 palettes the colors do not match.

**Comment by neobuddy89** [comment]
Not able to reproduce

**Comment by Detlev1** [comment]
Look at the video in the other issue

**Comment by mt190502** [comment]
This problem is continuing to crDroid 10.5 unofficial version.
Someone using crDroid 10.5 official needs to test it.

**Comment by hsantanna** [comment]
I can confirm that on crDroid 10.5, tested on Xiaomi Mi9 (cepheus).

**Comment by neobuddy89** [comment]
Try build after 1st June.

**Comment by gwolf2u** [comment]
Confirmed fixed

**Comment by Detlev1** [comment]
I am using a selfmade build from 12 June. At my end only the first 5 color options produce unique colors. All the others even though they look different, produce the same colors as the first option.
