### ISSUE TITLE
feature request: show volume value on volume panel

### ISSUE THREAD

**Issue by Tarlafic** [crdroidandroid/issue_tracker#376]
### Issue type

User interface

### Device

Poco F2 Pro (lmi)

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024-04-13

### Bug description

Android's volume panel get worse and worse upon every update, making it so hard to recognize your current volume level. Showing a exact value of your volume level could fix it.

### Steps to reproduce

What it could be like:
1. press volume button
2. volune panel popup
3. the volume level of your device showing on the bottom of the volume panel, or replacing the musical note icon.

### Relevant log (logcat/build log)

```shell
Doesn't have.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
am not sure what issue you have here
volume indicator is same since few android revisions now

**Comment by Tarlafic** [comment]
> am not sure what issue you have here volume indicator is same since few android revisions now

I often listen to music and live streamings with earphones on my device, and because audio loudness are very inconsistent acrossing different media, I always set my volume down to a specific level before listening to music, to prevent my ears getting boomed.
I was using an app which pops a toast message with current volume level upon volume adjusting before, but sadly it stop working on newer android versions, so I could only hope some custom roms can make an integrated volume value indicator.

**Comment by jason-eu** [comment]
### I'm not sure if this will help you achieve what you want, but it may get you close.

1. 

> You can enable “Per-app volume control” under “Sound and vibration” in Settings to help you around the variance in sound levels across different apps.
> 
> This is not relevant if the media itself has variation in volume levels, across different tracks for example, in that case you will need active normalisation in the apps you're using (or the device itself), similar to what the Spotify app itself has.
> As far as I know, enabling system-wide normalisation doesn't exist, at least not in this way.

2. 

> Under ; Settings > crDroid Settings > Sound tab :
> 
> You can use finer grained volume steps.

These in combination should help get you closer to where you'd like, but with the caveat of not having a volume indicator that show percentage or a number over 100 for example.

**Comment by Tarlafic** [comment]
> ### I'm not sure if this will help you achieve what you want, but it may get you close.
> 
> > You can enable “Per-app volume control” under “Sound and vibration” in Settings to help you around the variance in sound levels across different apps.
> > This is not relevant if the media itself has variation in volume levels, across different tracks for example, in that case you will need active normalisation in the apps you're using (or the device itself), similar to what the Spotify app itself has.
> > As far as I know, enabling system-wide normalisation doesn't exist, at least not in this way.
> 
> 
> > Under ; Settings > crDroid Settings > Sound tab :
> > You can use finer grained volume steps.
> 
> These in combination should help get you closer to where you'd like, but with the caveat of not having a volume indicator that show percentage or a number over 100 for example.

The volume differences of my daily drived apps are widely spreaded over 5 different volume steps, and most of those apps are video apps like newpipe which doesn't support volume normalisation.
Anyway, I'm now using a third-party volume panel overlay app, and it works pretty fine. Although I still hope this feature could be integrated into the os itself, because such third-party overlay can block touch inputs and don't works well with some players built-in volme panel.
