### ISSUE TITLE
Game Space FPS monitor transparency.

### ISSUE THREAD

**Issue by jason-eu** [crdroidandroid/issue_tracker#377]
### Issue type

Feature not working as intended

### Device

POCO F3 (alioth)

### crDroid version

crDroid 10

### Exact version / Build date

crDroidAndroid-14.0-20240413-alioth-v10.4

and

crDroidAndroid-14.0-20240419-alioth-v10.4

### Bug description

When the transparency option is enabled, outside or inside of the game, it only enables transparency for the in-game Game Space menu, as opposed to being enabled for the FPS monitor as well.

### Steps to reproduce

Use Game Space with FPS monitor enabled.

### Relevant log (logcat/build log)

```shell
None
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/13890252/83b94506-2854-438d-9ef9-7145f29fbfeb

### Solution

None found.

### Additional context

None required.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is like so by design

**Comment by jason-eu** [comment]
Understood @gwolf2u thank you but also, ew lol

For anyone else who comes later on, I'm using the FPS Info QS tile for monitoring, and it has a decent enough representation minus the fact that it says “FPS” as well, but it gets the job done.
