### ISSUE TITLE
OK Google doesn't work

### ISSUE THREAD

**Issue by jakubalex47** [crdroidandroid/issue_tracker#378]
### Issue type

Source code related

### Device

dipper

### crDroid version

crDroid 10

### Exact version / Build date

10.4

### Bug description

Google assistant cannot be activated with voice. It doesn't work when screen is on or off. The bug is present in 10.4. On every previous version it was working. Did clean install and try 2 different gapps. It's crdroid or QPR2 bug.

### Steps to reproduce

Set up google assistant. Say "OK Google" when the screen is on or off. It doesn't work.

### Relevant log (logcat/build log)

```shell
Empty
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unofficial device - crDroid version
official dipper doesn't have crDroid 10

also I understand the issue, yet even so, may not be crDroid related

**Comment by jakubalex47** [comment]
> unofficial device - crDroid version official dipper doesn't have crDroid 10
> 
> also I understand the issue, yet even so, may not be crDroid related

You are wrong - dipper is officially supported. Latest version is 10.4 by twoxa. You can download the ROM from official website. Also about the issue - I guess it's crdroid related. Someone should try if it works in other phone.

**Comment by gwolf2u** [comment]
> > unofficial device - crDroid version official dipper doesn't have crDroid 10
> > also I understand the issue, yet even so, may not be crDroid related
> 
> You are wrong - dipper is officially supported. Latest version is 10.4 by twoxa. You can download the ROM from official website. Also about the issue - I guess it's crdroid related. Someone should try if it works in other phone.

you're right, it is official
somehow missed it
anyway, since that is a google app, is not crDroid related
blobs may need to be updated if possible, but to get things right, working here (using daily) so not really source issue, but maybe device issue
@ttwoxa please check at your end
I'll reopen this ticket afterwards
