### ISSUE TITLE
bug: charging problem 

### ISSUE THREAD

**Issue by tgiraud2007** [crdroidandroid/issue_tracker#38]
### Issue type

Other

### Device

Miatoll 

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

My phone does not charge and makes random voltages (watch the video) 

### Steps to reproduce

Put the device to charge 

### Relevant log (logcat/build log)

```shell
There's no
```

### Screenshots or videos

https://user-images.githubusercontent.com/101748895/202548159-a860a6a0-4c0d-433c-8f3f-bc3d4879b4c6.mp4

https://user-images.githubusercontent.com/101748895/202548168-5a928263-fc79-417d-b2e7-c5ea5b13c43d.mp4

### Solution

An update maybe? 

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
logs are needed

**Comment by tgiraud2007** [comment]
> logs are needed also maybe check with changing kernel and see if issue persists

![Screenshot_20221119-165212_MatLog](https://user-images.githubusercontent.com/101748895/202859574-61dc1705-edef-41bc-b046-2216667b2c5a.png)
that tells me that

**Comment by gwolf2u** [comment]
still happening on newer release ?

**Comment by gwolf2u** [comment]
tracking in https://github.com/crdroidandroid/issue_tracker/issues/42
