### ISSUE TITLE
Weather Provider

### ISSUE THREAD

**Issue by gerasimov-mv** [crdroidandroid/issue_tracker#381]
### Issue type

Feature not working as intended

### Device

Vayu

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024-04-17

### Bug description

OpenWeatherMap has changed the API of its weather service, now the user key generated by the new API does not work in the weather application embedded in crDroid (OmniJaws).

### Steps to reproduce

Step 1. Go to OmniJaws app from status bar
Step 2. Insert your new OWM API 3.0 key into the user API key input field.

### Relevant log (logcat/build log)

```shell
04-23 00:41:13.875 D/WeatherUpdateService(21322): updateWeather
04-23 00:41:13.991 W/WeatherService::NetworkUtils(21322): response:401
```

### Additional context

I can't get normal logs:
https://paste.crdroid.net/P9Zf4O

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by jason-eu** [comment]
This might be device specific, as I cannot reproduce the issue on POCO F3 (alioth).
I am able to use the provided key or my own key without problems.

**Comment by gerasimov-mv** [comment]
> This might be device specific, as I cannot reproduce the issue on POCO F3 (alioth). I am able to use the provided key or my own key without problems.

Are you using the OWM API key version 3.0?

**Comment by jason-eu** [comment]
I just made an account to get the free key to test, no idea what version it is but if it's newer than 3.0 then maybe try a new key or make a new account to get one

**Comment by gwolf2u** [comment]
just checked
all working as it should with own key and todays build
