### ISSUE TITLE
Unexpected app closing

### ISSUE THREAD

**Issue by Theboyh** [crdroidandroid/issue_tracker#382]
### Issue type

User interface

### Device

Poco F3 Alioth 8/256

### crDroid version

crDroid 10

### Exact version / Build date

CrDroid 10.4 Official update:13/04/24

### Bug description

Unexpected closure when running game application.(Toram online, Iruna online...)

### Steps to reproduce

Install the game Iruna online or Toram online, then try to run them.

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/Y4fNoH
```

### Acknowledgements

- [x] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment]
Check here https://github.com/crdroidandroid/issue_tracker/issues/374
