### ISSUE TITLE
Fingerprint for second user cannot be added

### ISSUE THREAD

**Issue by S-v-e-n-S** [crdroidandroid/issue_tracker#383]
### Issue type

Other

### Device

Pocophone F1 beryllium

### crDroid version

crDroid 10

### Exact version / Build date

latest / weekly: 21.04.2024
crDroidAndroid-14.0-20240422-beryllium-v10.4.zip

### Bug description

I added a second phone user added a PIN for lockscreen etc. which works fine. Trying to add a fingerprint for unlocking fails.
After placing a finger onto the sensor 9 to 11 times the process aborts (Can't complete fingerprint setup) and asks whether to try again or aboort and try later. None option leads to later success.

### Steps to reproduce

prepare / pre-requisite:
1) create second user via Settings / System / Multiple Users, allow phone usage / switch to second user, add PIN

After switching to second user
2) Settings / Security and privacy / Device unlock / Unlock via fingerprint setup / 
3) Fingerprint (setup needed) -> scroll down and agree
4) Start touching sensor
After a couple touch: error

### Relevant log (logcat/build log)

```shell
n.a.
```

### Screenshots or videos

n.a.

### Solution

wish I had one to share

### Additional context

n.a.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
logcat would help

**Comment by S-v-e-n-S** [comment]
Hi,

 

sorry for late reply and thanks for picking this topic up.

 

Issue is resolved with V 10.6

 

Best regards

 

Sven

 

 

Von: Lup Gabriel ***@***.***> 
Gesendet: Samstag, 1. Juni 2024 19:02
An: crdroidandroid/issue_tracker ***@***.***>
Cc: S-v-e-n-S ***@***.***>; Author ***@***.***>
Betreff: Re: [crdroidandroid/issue_tracker] Fingerprint for second user cannot be added (Issue #383)

 

logcat would help
