### ISSUE TITLE
System crash

### ISSUE THREAD

**Issue by cygiel5420** [crdroidandroid/issue_tracker#384]
### Issue type

User interface

### Device

Pixel 7 Pro (cheetah) 

### crDroid version

crDroid 10

### Exact version / Build date

10.4 / 4/17/2024

### Bug description

System crashes at night randomly and reboots the phone. Happened 3 times already since install date. Watched it happen first hand today as the clock alarm went off. There are surprisingly no tombstone files in "data/tombstones" folder. 

### Steps to reproduce

Leave to phone on charge for the night, set an alarm. I'm not too sure if having multiple notifications waiting could've contributed to this. 

### Relevant log (logcat/build log)

```shell
There are no tombstones in "data/tombstones" folder. Matlog is no use in this scenario either.
```

### Additional context

This crash issue exhibits similar properties to a previous reported issue on bug tracker #196. 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
No logs.
