### ISSUE TITLE
Back curve stroke in notification shade

### ISSUE THREAD

**Issue by maytinhdibo** [crdroidandroid/issue_tracker#385]
### Issue type

User interface

### Device

marble (Poco F5/Redmi note 12 turbo)

### crDroid version

crDroid 10

### Exact version / Build date

10/2024-03-19

### Bug description

Back curve stroke in notification shade on dual tone radius. Will appear turn opacity like (75%) and a screen with light background.
![40087747-5bfc-4e25-a30d-87a265095d09](https://github.com/crdroidandroid/issue_tracker/assets/6669725/871a76cf-fedf-4930-9d21-2eb20da891e2)

### Steps to reproduce

Turn on a light theme or set quick setting opacity like 75%. It will appear on notification panel radius.

### Relevant log (logcat/build log)

```shell
UI Log
```

### Screenshots or videos

![40087747-5bfc-4e25-a30d-87a265095d09](https://github.com/crdroidandroid/issue_tracker/assets/6669725/28626a31-d8c8-409a-8071-062490d00a12)

### Solution

Change the drawable svg on it or remove it.

### Acknowledgements

- [x] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment]
Hi @maytinhdibo  
Yeah same on F3 and presume other devices.

**Comment by neobuddy89** [comment]
dont understand this. elaborate more

**Comment by raystef66** [comment]
It's just a visual 'anomaly'. Nothing more.
Just set light theme, swipe down to see notification panel. Left and right radius corner have some dark pixels visible.

**Comment by gwolf2u** [comment]
tolerated bug I guess
