### ISSUE TITLE
bug: Suddenly shutdown when using usb tethering.

### ISSUE THREAD

**Issue by putraadipradana** [crdroidandroid/issue_tracker#386]
### Issue type

Feature not working as intended

### Device

Redmi note 12 4G NFC (Topaz)

### crDroid version

crDroid 10

### Exact version / Build date

10.2/2024-02-05

### Bug description

When I use USB for tethering, my device shutdown it self.

### Steps to reproduce

Go to settings, network & internet, usb tethering.

### Relevant log (logcat/build log)

```shell
i don't know where to find the log
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
connect phone to pc
run `adb logcat > log.txt` in terminal
reproduce issue
attach log.txt file here

**Comment by NikitaSavc** [comment]
You have flashed custom kernel 100%. It is custom kernel issue. I am using stock kernel, where usb tethering is working.  Contact to kernel maintainer.

I am closing this issue.

Regards,
Nikita
