### ISSUE TITLE
bug: Wrong Design and Max battery Capacity

### ISSUE THREAD

**Issue by crastex** [crdroidandroid/issue_tracker#387]
### Issue type

User interface

### Device

Redmi Note 8 ginkgo

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024/04/22

### Bug description

Battery Max Capacity and Design Capacity are wrongly displayed and so the calculated health

### Steps to reproduce

Settings > Battery > Battery Information 

### Relevant log (logcat/build log)

```shell
NaN
```

### Screenshots or videos

![IMG_20240426_135955_620](https://github.com/crdroidandroid/issue_tracker/assets/140511728/01e776e3-6041-437f-bcd1-ce33f6ec1a87)

### Solution

Either can fix it or just hide it by creating a overlay for battery capacity too like this
https://github.com/crdroidandroid/android_packages_apps_Settings/commit/e1cea87cc610720fa62b564506b908f873a4024e

### Additional context

@neobuddy89 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
@neobuddy89 maybe remove it to make sure we also remove confusion in some cases
