### ISSUE TITLE
bug: Navbar Icons keep shifting up/-downwards

### ISSUE THREAD

**Issue by FaySmash** [crdroidandroid/issue_tracker#388]
### Issue type

User interface

### Device

SHIFT Shift6mq (axolotl)

### crDroid version

crDroid 9

### Exact version / Build date

9.15/2024-04-04

### Bug description

When using the device, the Navbar icons often shift a little more upwards (or sometimes also downwards), seemingly randomly, mostly when switching apps or changing the orientation.

### Steps to reproduce

1. Enable 3 Button navigation
2. open some apps
3. switch between them

### Relevant log (logcat/build log)

```shell
I couldn't find anything related in the logcat
```

### Screenshots or videos

Normal:
![normal](https://github.com/crdroidandroid/issue_tracker/assets/30392780/309a8426-21b5-4b8e-aa08-7f3aabf1ce58)

Shifted downwards:
![downwards](https://github.com/crdroidandroid/issue_tracker/assets/30392780/3a442f3d-af58-4035-9c6e-64667e6b8bfe)

### Solution

The workaround is to restart the SystemUI or disable and re-enable the Navbar

### Additional context

I observed this issue since I started using crDroid with version 9.10

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
it's called burn in protection
helps with screen burn in on display
this is not bug

**Comment by FaySmash** [comment]
> it's called burn in protection helps with screen burn in on display this is not bug

Thanks for the info! Any way (build flag / set prop) to disable it?

**Comment by gwolf2u** [comment]
no way to disable it
is done via source side change at build time
