### ISSUE TITLE
External storage app keeps stopping

### ISSUE THREAD

**Issue by kali9c9** [crdroidandroid/issue_tracker#390]
### Issue type

Feature not working as intended

### Device

Poco x3 pro (vayu)

### crDroid version

crDroid 9

### Exact version / Build date

2024-03-21

### Bug description

External storage keeps stopping cannot use files and cannot give permission to use files like ppssspp

### Steps to reproduce

Open files external storage stops,try to go to android/data in zarchiver and try to give permission to the app external storage stops

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/dVhFul
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
vayu no longer supports crdroid 9, do update to crdroid 10.
