### ISSUE TITLE
bug: title bug de driver customizado turnip outros erro que nao sei

### ISSUE THREAD

**Issue by SummrDragon541** [crdroidandroid/issue_tracker#391]
### Issue type

Other

### Device

poco x3 pro crdroid 10.4 ultima `atualizacao`
[logs.txt](https://github.com/crdroidandroid/issue_tracker/files/15169789/logs.txt)
``

### crDroid version

crDroid 10

### Exact version / Build date

eu nao sei como vou dizer que eu nao sei onde extact versio em build date mas  eu estou versao crdroid em 29/04/2024 que foi atualizado ontem.

### Bug description

o bug que eu estou tendo e o problema de driver customizado turnip ante funcionar miui todas delas direto poco x3 pro para jogos portado e software emitacao para usar meus jogos preservado originais como cuphead, hollow kignht, streets of rage (sega genesis 16bit) que meu jogos de cartucho de sega genesis 16bit morreu por causa por ser velho ante estragar fiz engenheria para preservar jogo original direto do pc depois usar software pode continua jogando normalmente direto celular ou pc. apena so quero corrigir isso e tambem encontrei outros erro nao de driver envolver sistema pode da bootloop ou algo coisa que esta acontecendo do crdroid direto poco x3 pro.
Eu nao conseguir organizar direito por causa tem maior parte de erros encontrei entao fiquei perdido totalmente mas conseguir tiver tempo olhar todas elas obrigado pelo esforço. 

Eu vou esperar checar e corrigir por atualizacao eu vou aguarda. por favor me banir por motivo que achar eu estou apoiando nao apoiando meio ilegalmente que eu morro meu país que e considerado legalmente de forma preservaçao de jogos antigos e modernos.

### Steps to reproduce

eu nao tenho isso que eu nao sei

### Relevant log (logcat/build log)

```shell
que eu vir teve varios erros so que meio confuso parte do sistema e outros de driver customizado turnip e driver prinicipal origian gpu adreno 640
```

### Screenshots or videos

pessoal do seu grupo colocou a regra que achar e ilegal que eu nao coloquei nada ilegal so quero corrigir mais nada

### Solution

eu nao sei qual soluçao so que sei o  unico jeito e o atualizaçao que voces quiser fazer ou nao

### Additional context

eu nao quero ser banindo por motivo que achar que e ilegal mas eu nao estou ilegal que estou fazendo legalmente
so quero o crdroid corrigir e deixar melhor possivel de bugs e error sem tornar insupotavel so isso por favor entendar e nao seja ruim comigo eu estou tentando so isso.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
english only
