### ISSUE TITLE
bug: fingerprint sensor not disabled in apps when device locked

### ISSUE THREAD

**Issue by CalvinImray** [crdroidandroid/issue_tracker#393]
### Issue type

Other

### Device

Xiaomi Mi 11 (Venus)

### crDroid version

crDroid 10

### Exact version / Build date

Crdroid 10.4
Build date
Mon Apr 29 22:18:36 EEST 2024

### Bug description

when device is locked, fingerprint scanner remains on and scanning whilst in apps (camera, Google home)

### Steps to reproduce

Enable fingerprint unlock. Enable lock screen shortcuts or quickly open camera. Enter desired app without unlocking phone and fingerprint sensor will light up when the area of the scree. Is disturbed. 

### Relevant log (logcat/build log)

```shell
I don't have a log as there is no crash. This is easy to understand and replicate.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Screen off UDFPS is turned on in crDroid settings?

**Comment by CalvinImray** [comment]
Makes no difference

-------- Original Message --------

**Comment by FlowerSea0208** [comment]
udfps are always called out on the lock screen
Until you unlock it or the number of recognitions exceeds the limit
Otherwise you can always trigger it

This is not a bug

**Comment by CalvinImray** [comment]
Okay, I understand. On miui and hyperos however, I could use the camera without unlocking my device and the fingerprint sensor would not get triggered

-------- Original Message --------
