### ISSUE TITLE
Proximity sensor always on with screen off.

### ISSUE THREAD

**Issue by Matooo86** [crdroidandroid/issue_tracker#395]
### Issue type

Feature not working as intended

### Device

Dipper (Xiaomi MI8)

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024-4-10

### Bug description

Proximity sensor always on with screen off.

### Steps to reproduce

Use another camera to check the proximity sensor status while screen is off.

### Relevant log (logcat/build log)

```shell
No log
```

### Additional context

On Android 13 is ok, the issue present on Android 14.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
pocket lock enabled?

**Comment by Matooo86** [comment]
Hello, tried also without pocket lock, same issue.

**Comment by gwolf2u** [comment]
logcat needed

**Comment by Matooo86** [comment]
I've switched back to PE13 unfortunately.

**Comment by gwolf2u** [comment]
then no way to fix

**Comment by Matooo86** [comment]
If you are in the crDroid10 you can check with another camera and you will see the issue.

**Comment by Matooo86** [comment]
Tried Lineage 21 same issue with android 14

**Comment by gwolf2u** [comment]
log would help nonetheless

**Comment by Matooo86** [comment]
When the new crdorid10 will be out, I'll flash and test the issue again, if the issue is present I'll give you the logs

**Comment by Matooo86** [comment]
Are you using a dipper with crdroid10?

**Comment by gwolf2u** [comment]
not personally, but could have helped to diagnose the issue and forward to device maintainer

**Comment by Matooo86** [comment]
I'll try to obtain the logs from somebody who is using dipper with crdroid10.

**Comment by CarlosGilbertoHF** [comment]
> When the new crdorid10 will be out, I'll flash and test the issue again, if the issue is present I'll give you the logs

It's out:

![firefox_mXrBDL4t1M](https://github.com/crdroidandroid/issue_tracker/assets/10945499/99a4040c-577c-468d-85ff-160d5130ba23)

**Comment by Matooo86** [comment]
Thx but the issue is stillwater there

**Comment by CarlosGilbertoHF** [comment]
> Thx but the issue is still there

Then grab a logcat as requested ¯\_(ツ)_/¯

**Comment by Matooo86** [comment]
![2024-05-28-02-09-22.txt](https://github.com/crdroidandroid/issue_tracker/files/15462593/2024-05-28-02-09-22.txt)

**Comment by Matooo86** [comment]
Link to video: https://t.me/crdroid_dipper/3736

**Comment by Matooo86** [comment]
Link to video: https://t.me/crdroid_dipper/3736

**Comment by CarlosGilbertoHF** [comment]
@gwolf2u log above.
