### ISSUE TITLE
bug: GPS not working

### ISSUE THREAD

**Issue by CalvinImray** [crdroidandroid/issue_tracker#396]
### Issue type

Feature not working as intended

### Device

Xiaomi Mi 11 (Venus)

### crDroid version

crDroid 10

### Exact version / Build date

Crdroid 10.4
Build date Mon Apr 29 22:18:36 EEST 2024

### Bug description

When I open Google maps, Fitbit or Strava, location doesn't connect. Only once in Google maps it worked and I was able to follow a route for 20 minutes but after that the gps was stuck showing my destination for the rest of the day, long after I was in a different location. Sometimes if you clear cache and force stop, it loads location, crashes and doesn't update after.

### Steps to reproduce

Open Google maps, go on a walk and see if your GPS moves.

### Relevant log (logcat/build log)

```shell
N.a
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
try and log the issue

**Comment by CalvinImray** [comment]
Ever so sorry for wasting your time. I think it was because i booted UP crdroid before installing gapps

-------- Original Message --------

**Comment by gwolf2u** [comment]
will mark this as complete then

**Comment by CalvinImray** [comment]
Thanks

-------- Original Message --------
