### ISSUE TITLE
bug: Navbar response/touch area shifting up/downwards

### ISSUE THREAD

**Issue by Yaspee** [crdroidandroid/issue_tracker#397]
### Issue type

Feature not working as intended

### Device

Mars

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024-04-22
![u6rwj5ysvw71](https://github.com/crdroidandroid/issue_tracker/assets/34875338/46f0ba9f-f982-4d0c-816c-6853e32ea9c4)

### Bug description

2/3 Button NavBar buttons' touch areas moves up/down, not just icon, but whole touch response area too.

In those cases when the buttons' boundaries move up, it'll make it really hard to use the NavBar buttons since touching/pressing the dead bottom of the screen will not be able to trigger them.

### Steps to reproduce

Clean flash
Using 3 Button navigation,

After first boot, navbar button will move up than intended height.

Then depending on the screen size/dpi settings, the buttons will move up/down.

From what I've observed, if the display size if small, buttons moves up, and vice versa. But there's no definitive threshold as long as I've tested.

### Relevant log (logcat/build log)

```shell
Not possible to pinpoint where/when this bug happens, if you have any clues what process/application I should be looking for I'll show the log here.
```

### Screenshots or videos

![ege5fv6u51wo](https://github.com/crdroidandroid/issue_tracker/assets/34875338/c9726544-d68b-4acb-bbeb-e5fbe16492c3)

Ex. for moving up with default display size setting

![image](https://github.com/crdroidandroid/issue_tracker/assets/34875338/7fc18559-a680-4fe8-85ac-eb9f202b9740)
Ex. moving up with different display size setting, additionally in this screenshot, I pressed the Home button, which shows the touch trigger areas moves up too, making it impossible to trigger the button when pressing the buttom of the screen.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by FlowerSea0208** [comment]
![IMG_20240511_022322](https://github.com/crdroidandroid/issue_tracker/assets/71331551/aedd1e9a-1bbb-4ae8-9acc-7cb273f61215)
![IMG_20240511_022331](https://github.com/crdroidandroid/issue_tracker/assets/71331551/61a42402-c6fc-44cd-80be-1ab3bfa2b30b)

**Comment by Yaspee** [comment]
Hi, maintainer of device Mars, I appreciate the responses, but I failed to interpret the meaning behind the images you attached. 

Judging from the images, I assume there's a possibility for the buttons' trigger zones to move down on your end, but the relevant information to the aforementioned issue I wrote is still unresolved: what procedures should I take into practice to achieve the same outcome? And ultimately, to make sure the buttons' trigger zones stay in place.

Thanks in advance.

**Comment by R411gun** [comment]
Hey there, I also noticed this "bug" with my device (Alioth) on crdroid 10.11

My guess is, that this is part of oled burn in protection
so it randomly shifts buttons + touch zone up and down after some time, this resets after a restart until ot shifts after a timer again

a better solution would be, to only shift the icons, not the touch area itself
especially the max and min value for navbar shifts are really hard to press, because the touch area becomes really small in those cases
