### ISSUE TITLE
bug: logcat report

### ISSUE THREAD

**Issue by MARCOS752wh** [crdroidandroid/issue_tracker#4]
### Issue type

Source code related

### Device

Poco x3 pro (vayu)
M2102J20SI

### crDroid version

crDroid 8

### Bug description

I think it is necessary to send a matlog so that you can see the system failures, an apology if it is not necessary but I thought it necessary to send it in any case

### Steps to reproduce

No se

### Relevant log (logcat/build log)

```shell
I put it in videos or screenshots
```

### Screenshots or videos

[logs-2022-09-25-22-48-00.zip](https://github.com/crdroidandroid/issue_tracker/files/9643005/logs-2022-09-25-22-48-00.zip)

### Solution

know dog I'm not a programmer

### Additional context

I really love crdroid and hopefully it always has great potential and is but very perfect for gaming and others and also updatable and profitable much more

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
what's the issue exactly?

**Comment by MARCOS752wh** [comment]
for lags in the quick user settings interface or sometimes slight hitches
when entering the application information
