### ISSUE TITLE
bug: connection defaulting to hdspa instead of lte

### ISSUE THREAD

**Issue by assasukasse** [crdroidandroid/issue_tracker#40]
### Issue type

Feature not working as intended

### Device

Device ginkgo

### crDroid version

crDroid 8

### Exact version

8.10

### Bug description

Connection default to 3g even if lte preferred is set. Entering engineer mode and selecting lte/wcdma moves the connection to 4g temporarily. Once the phone automatically switches to 3g does not self move to lte when it is available.

### Steps to reproduce

Activate mobile internet
Move from 4g area to a 3g area.
Return to a 4g area.
Phone remains on 3g.

### Relevant log (logcat/build log)

```shell
N/A
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
This is carrier related
Not much we can change there

**Comment by assasukasse** [comment]
Not sure about the carrier issue. Forcing 3g only then switching to
preferred LTE immediately switches to 4G. Tried going indoor (switches to
3g) then going outdoor again (where 4g works), sometime works sometime
stuck on 3g. Usually longer than 10m on 3g means won't automatically switch
to 4G anymore unless manually triggered.

Same SIM on a Samsung phone doesn't exhibit the issue.
