### ISSUE TITLE
Charging Control doesn't work

### ISSUE THREAD

**Issue by 1130381752** [crdroidandroid/issue_tracker#400]
### Issue type

Feature not working as intended

### Device

guacamole

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024-04-28

### Bug description

The function "Charging Control" doesn't work

### Steps to reproduce

Step1. I enable the function "Charging Control"
Step2. I set the Charging mode to "Limit charging"
Step3. I set the Limit to "70%"
Step4. I start charging my phone, but the battery level can increase to 100% finally rather then 70%

### Relevant log (logcat/build log)

```shell
N/A
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
@ShevT 
can you check this out if you get the time

**Comment by ShevT** [comment]
> @ShevT can you check this out if you get the time

Yes, it works sometimes, sometimes it doesn't work. Also, tested on Lineage. The behavior is identical to ours.

LOS bugs:
https://gitlab.com/LineageOS/issues/android/-/issues/6761
https://gitlab.com/LineageOS/issues/android/-/issues/7086
