### ISSUE TITLE
Bug: Battery design capacity/maximum capacity both show Unavailable

### ISSUE THREAD

**Issue by Avrution** [crdroidandroid/issue_tracker#403]
### Issue type

User interface

### Device

Oneplus 7T - hotdogb

### crDroid version

crDroid 10

### Exact version / Build date

10.4 - [crDroidAndroid-14.0-20240407-hotdogb-v10.4.zip](https://sourceforge.net/projects/crdroid/files/hotdogb/10.x/crDroidAndroid-14.0-20240407-hotdogb-v10.4.zip/download)

### Bug description

Battery design capacity and maximum capacity show as "Unavailable"

### Steps to reproduce

Settings > Battery > Battery Information

### Relevant log (logcat/build log)

```shell
Not applicable
```

### Screenshots or videos

![Screenshot_20240509-223817_Settings](https://github.com/crdroidandroid/issue_tracker/assets/38819283/eb4d5eaf-f93c-4302-bbcc-ed7841872751)

### Additional context

Unsure if this is normal, never had this spot empty on a rom.  Similar issue to https://github.com/crdroidandroid/issue_tracker/issues/387, except mine is displaying nothing.

If there is a location to set this number, please let me know.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ryukftw** [comment]
This needs kernel support. Not a CrDroid bug
