### ISSUE TITLE
MP3 player apps always play at maximum volume through speaker

### ISSUE THREAD

**Issue by quickishfm** [crdroidandroid/issue_tracker#404]
### Issue type

Other

### Device

Device (guacamole) (oneplus 7 pro)

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024-04-28

### Bug description

MP3 player apps such as the system Music app but also 3rd party ones like PowerAudio Pro play music or other MP3s at the highest possible volume, despite what volume the Media (and other volumes such as Notification and Alarm) is set to.
Spotify, Youtube and VLC media player do NOT have this issue.

Changing the volume while playing does not have any effect, it just changes the Media volume as expected but the mp3 still plays at maximum volume.

This does NOT occur if a bluetooth speaker is connected and used. Even if the Bluetooth speaker/headphones are connected, but the phone speaker is selected from the Volume panel, it will play at maximum volume through the phone's speaker.

### Steps to reproduce

1. Load an MP3 into the phone.
2. Open the system Music app (or use PowerAudio or another mp3 player) and play the MP3 player.

### Relevant log (logcat/build log)

```shell
Not sure which logs to include here.
```

### Acknowledgements

- [x] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
some apps may not use android audio routing properly
not much I can do without full log
