### ISSUE TITLE
Google photos problem 

### ISSUE THREAD

**Issue by Manavgupta12** [crdroidandroid/issue_tracker#406]
### Issue type

Feature not working as intended

### Device

OnePlus 7 pro (guacamole)

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-05-12

### Bug description

When I try to edit images in Google photos it crashes

### Steps to reproduce

Try to edit photo in Google photos

### Relevant log (logcat/build log)

```shell
Nothing
```

### Screenshots or videos

Nothing

### Solution

Nothing

### Additional context

Nothing

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DrFunkenbreakz** [comment]
That sounds like a gapps issue to me. Make sure you are using the Gapps package recommended by your device maintainer. A simple test would be to read in your device group and see if anyone else on your device has the same issue.

**Comment by neobuddy89** [comment]
Cannot reproduce. No log.
