### ISSUE TITLE
bug: title (<-- change me) Not showing notification in landscape mode 

### ISSUE THREAD

**Issue by dash-09** [crdroidandroid/issue_tracker#407]
### Issue type

User interface

### Device

Moto g32 devon

### crDroid version

crDroid 10

### Exact version / Build date

Version 10.4

### Bug description

Everytime the new notification come and you can't see in landscape mode.
![Screenshot_20240510-044241_Telegram](https://github.com/crdroidandroid/issue_tracker/assets/74849401/0e6254e7-5415-4884-8b69-3d674eb1dcb2)

### Steps to reproduce

As u go from potrait to landscape mode and any notification comes in then we can't see notification at all. By

### Relevant log (logcat/build log)

```shell
NA
```

### Screenshots or videos

![Screenshot_20240513-125752_Firefox](https://github.com/crdroidandroid/issue_tracker/assets/74849401/8b535c38-6e3b-473b-abcc-ee1e3c71e74a)
![Screenshot_20240513-125743_Firefox](https://github.com/crdroidandroid/issue_tracker/assets/74849401/1eea1a2b-a37f-4436-a6eb-02f49af638fa)

Both images shows notification in potrait and landscape mode . For Gmail app . In potrait mode u can see notification but in landscape mode u can't 

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DrFunkenbreakz** [comment]
I believe this issue was fixed in later builds of 10.4. Please wait for your device maintainer to release 10.5 and re-test for the issue. No ETA on when your device maintainer will release 10.5 update as it depends on when they have free time to do so.

As a work around, I believe if you increase the column or row amount in QS settings, it may fix it.

**Comment by dash-09** [comment]
I have one more issue regarding digital wellbeing app that tracks daily
usage of smartphone. It doesn't work on this moto g32 devon . What should I
do? .

**Comment by DrFunkenbreakz** [comment]
Probably investigate in your device group first to make sure other users have same issue. If they do and it's not just your device and setup, make a new issue on here complete with logs amd details

**Comment by DrFunkenbreakz** [comment]
Digital wellbeing is part of gapps i think, so worth checking you are using correct gapps that your device maintainer recommends
