### ISSUE TITLE
bug: high system ui power and cpu usage after qpr2

### ISSUE THREAD

**Issue by Gold3nF3nix** [crdroidandroid/issue_tracker#409]
### Issue type

Source code related

### Device

stone

### crDroid version

crDroid 10

### Exact version / Build date

Since 10.4/2024-04-12

### Bug description

After qpr2 uodate I saw that system ui started using more power than before which after deeper investigations lead me to see that system ui uses between 4-6% cpu on idle compared to before qpr2 1%, rarely 2%. This affects all crdroid based roms and crdroid itself and a few aosp based roms too (not all)

### Steps to reproduce

Step 1. Go to battery stats in battery settings and see how unusually high power usage by system ui is
Step 2. Go to Franco kernel manager (or other app with processes manager) and see that system ui is using around 5% cpu on idle 

### Relevant log (logcat/build log)

```shell
Sorry, can't paste, very big file. I attached to the screenshots section.
```

### Screenshots or videos

[logcat.log](https://github.com/crdroidandroid/issue_tracker/files/15302549/logcat.log)
![Screenshot_20240514-071516_Franco Kernel Manager](https://github.com/crdroidandroid/issue_tracker/assets/75486623/797cdf1b-76b1-472b-b94e-12b327f9e654)
![Screenshot_20240514-071459_Battery Stats Viewer](https://github.com/crdroidandroid/issue_tracker/assets/75486623/6e74dce9-786b-4eb3-8a55-7f60cccdc5ad)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by x325d** [comment]
I'm having the same issue here on an unofficial build 10.5 for rosemary

**Comment by x325d** [comment]
And i have also noticed that the excessive SystemUI CPU usage continues even while the screen is off

**Comment by ByAndrius** [comment]
I also noticed this over the months with my device. (Xiaomi Redmi Note 8 Pro ; codename: begonia).
![325018721-ce654def-6e32-43b1-b86a-37aac6b601e6](https://github.com/crdroidandroid/issue_tracker/assets/167932988/f106e0a2-d15f-4ef8-80c9-2733a5de34e7)

The screenshot is from about 1 month ago, but the problem still persists in version 10.5 of crDroid.

**Comment by halfbytecode** [comment]
I'm facing the same issue since QPR2 on Pixel 7 Pro (cheetah) on crDroid 10.4 & 10.5.

The phone overheats and fast charging also gets disabled due to that, with charging time almost doubling. Battery life has also taken a hit.

Below screenshot shows the high battery usage of System UI (battery level was at 40%, down from a full charge).

![Screenshot_20240524-124032_Pixel Launcher](https://github.com/crdroidandroid/issue_tracker/assets/17142444/588a3e0b-4e34-496c-abe2-0fc5914f89b1)

**Comment by gwolf2u** [comment]
fixed in https://github.com/crdroidandroid/android_frameworks_base/commit/b701d231f6f9a76888a6b103e8eac357e908d601
