### ISSUE TITLE
bug: small connection problems and logcat flood from wifihal and wifi vendor

### ISSUE THREAD

**Issue by MARCOS752wh** [crdroidandroid/issue_tracker#41]
### Issue type

Feature not working as intended

### Device

Poco x3 pro 

M2102J20SI

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

problem of small connection failures that suddenly I don't have internet and even so the wifi is connected and working but it appears that I am without internet and until 5 minutes later it works again.

2-the logcat is flooded, not much of which is the wifihal and wifivendor error

### Steps to reproduce

1-connect to wifi and wait and then wifi fails

### Relevant log (logcat/build log)

```shell
11-19 11:20:28.996 E/WifiHAL (848): get_wifi_interface_info: QCA_WLAN_VENDOR_ATTR_LL_STATS_IFACE_INFO_TS_DUTY_CYCLE not found

11-19 11:08:26.753 E/WifiVendorHal(1660): getWifiLinkLayerStats_1_6_Internal(l.1199) failed {.code = ERROR_INVALID_ARGS, .description = }

11-19 11:20:56.689 E/DecorView[](5591): Destroying unexpected ActionMode instance of TYPE_FLOATING; com.android.internal.view.FloatingActionMode@42d2ad1 was not the current floating action mode! Expected null

11-19 11:21:23.437 E/WifiHAL (848): get_wifi_interface_info: QCA_WLAN_VENDOR_ATTR_LL_STATS_IFACE_INFO_TS_DUTY_CYCLE not found

11-19 11:14:28.946 E/cr_ChildProcessConn(5591): Child process code mismatch: sharedLibraryFiles mismatch; parent=[/system/framework/org.apache.http.legacy.jar, /product/app/webview/webview.apk, /product/overlay/NavigationBarMode3Button/NavigationBarMode3ButtonOverlay.apk, /product/overlay/AndroidBlackTheme/AndroidBlackThemeOverlay.apk, /product/overlay/IconShapeRoundedRect/IconShapeRoundedRectOverlay.apk, /product/overlay/IconPackOOSAndroid/IconPackOOSAndroidOverlay.apk, /data/resource-cache/com.android.systemui-neutral-BXka.frro, /data/resource-cache/com.android.systemui-accent-u3TB.frro] child=[/system/framework/org.apache.http.legacy.jar]; browser version has changed: false
```

### Screenshots or videos

![Screenshot_20221119-112254_MatLog](https://user-images.githubusercontent.com/114353020/202863583-647b6176-1270-456b-a330-586da2005c5d.png)
![Screenshot_20221119-112257_MatLog](https://user-images.githubusercontent.com/114353020/202863588-4c81f8a2-c849-4f8f-a640-08c1f03e0eea.png)

### Solution

I don't know bro

### Additional context

Logcat 1

[logcat.txt](https://github.com/crdroidandroid/issue_tracker/files/10047600/logcat.txt)

Logcat 2

[logcat.txt](https://github.com/crdroidandroid/issue_tracker/files/10047602/logcat.txt)

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by MARCOS752wh** [comment]
It should also be clarified that the connection error also happens with mobile data, the download speed being very low and even being in a place with a very good signal.

**Comment by MARCOS752wh** [comment]
Another point also that and tried with another firmware h the error always appears in the legcat and the connection error being all stock of the rom

**Comment by gwolf2u** [comment]
still happening on newer revision?
