### ISSUE TITLE
Laggy control center when playing audio in the background

### ISSUE THREAD

**Issue by RisumiKujizawa** [crdroidandroid/issue_tracker#411]
### Issue type

User interface

### Device

Topaz

### crDroid version

crDroid 10

### Exact version / Build date

CrDroid 10.4 
Build Date: 2024-05-05

### Bug description

When playing audio in the background, the control center would be laggy and go at like 15/30fps, it's very annoying

### Steps to reproduce

Play audio in the background and the control center will be laggy

### Relevant log (logcat/build log)

```shell
No log
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DrFunkenbreakz** [comment]
Full logs while the issue occurs would be helpful.

**Comment by gwolf2u** [comment]
no log
