### ISSUE TITLE
Bluetooth headset stutters during phone call

### ISSUE THREAD

**Issue by oeglesius** [crdroidandroid/issue_tracker#412]
### Issue type

Feature not working as intended

### Device

Oneplus 9 Pro (lemonadep)

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-05-12

### Bug description

I have a problem with Bluetooth - my headset PLT Poly 5200, during phone calls I can hear the sound of the other person always stuttering, the other person can hear me all right. It was the same at least since crdroid 10.2, before I didn't test it. The same problem occurs while connecting per Bluetooth with my car (VW Passat), then there is permanently stuttering in phone calls from the other side to me. I have no other headsets to test, but it occurs every time during phone calls, so it is virtually not possible to use the headset or the Bluetooth of the car for calls

### Steps to reproduce

See above

### Relevant log (logcat/build log)

```shell
See below
```

### Screenshots or videos

[2024-05-15-20-33-33.txt](https://github.com/crdroidandroid/issue_tracker/files/15325813/2024-05-15-20-33-33.txt)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unfortunately this is a nofix
happens with some bt devices
did try a fix long time ago, but in vain
