### ISSUE TITLE
Wifi icon needs some right margin

### ISSUE THREAD

**Issue by chemha** [crdroidandroid/issue_tracker#413]
### Issue type

User interface

### Device

LMI

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024-05-04

### Bug description

In A13 the Wifi icon added some right marging when wifi standard was enabled. This is not happening since A14 was released.

### Steps to reproduce

Just enable "Show Wifi standard" in CrDroid settings

### Relevant log (logcat/build log)

```shell
No logs as this is a user interface feature that needs to be corrected.
```

### Screenshots or videos

This is a old screenshot of how it used to look in A13. As you can see it's separated from the signal icon.

![Screenshot_20230804-103918_Discord_1_1](https://github.com/crdroidandroid/issue_tracker/assets/36114312/6ff3af76-5ccc-4919-823d-7445dabeba82)

This is how it looks since A14 was released. It doesn't look that nice because all the icons have the same marging except for the wifi one. This makes me avoid using it.

![Screenshot_20240517-100134_Galería_1](https://github.com/crdroidandroid/issue_tracker/assets/36114312/6f775fcd-6e01-43d3-b3dd-c81e98a6a6e6)

Both screenshots use the same iconpack

### Solution

I guess the solution is to add some right marging when the wifi standard option is enabled.

### Additional context

This is super low priority obviously.

I've created this issue before but it got closed as not planned. I don't know if I was not clear enough with the explanation. I tried to reopen the issue and it didn't work. That's why I'm creating a new one.

The problem is obviously there, as you can see in the images. I don't mind how long it takes to fix it but I don't think you should list this as not planned as this is a real issue.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by chemha** [comment]
Here you can see a better example how all the icons are aligned in A13 (grey) and not in A14 (black)

![Screenshot_20230804-103918_Discord_1](https://github.com/crdroidandroid/issue_tracker/assets/36114312/19f6d228-e58b-49e5-bbc9-9dc8e77ce89e)

![Screenshot_20240517-095854_Ajustes_1](https://github.com/crdroidandroid/issue_tracker/assets/36114312/64c748ea-b234-49e1-9e5b-6d96f3ea722a)

**Comment by raystef66** [comment]
Already mentioned here but closed.
https://github.com/crdroidandroid/issue_tracker/issues/313

**Comment by chemha** [comment]
As this is not a feature request but a feature fix. It would be nice to get a reason for this to not be planned like until the end of times.

If it just simply can't be done due to new A14 restrictions just say it so other users/researchers know what is happening.

If the reason is the one above. Why even bother adding feature if it's not going to work as spected?

I tried to fix it myself using different methods without success. As the CrDroid team is also not fixing this I will just stop using this feature until it's fixed.

**Comment by chemha** [comment]
Congrats to the team for fixing this while not being planned
