### ISSUE TITLE
Bring back the "show old signal icon" option.

### ISSUE THREAD

**Issue by chemha** [crdroidandroid/issue_tracker#414]
### Issue type

User interface

### Device

LMI

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024-05-04

### Bug description

The "show old signal icon" option is missing since A14 release.

### Steps to reproduce

Go to CrDroid settings and the option is not there.

### Relevant log (logcat/build log)

```shell
No logs as this is a request to bring back a feature.
```

### Screenshots or videos

This is how it used to look in A13 when you enabled that option. You could choose between a big 5G icon or a small one

![Screenshot_20230901-220525_WhatsApp_1](https://github.com/crdroidandroid/issue_tracker/assets/36114312/9195bab6-5eca-461d-a8b4-d5aed6a90072)

This is the only way it shows now.

![Screenshot_20240517-103725_Galería_1](https://github.com/crdroidandroid/issue_tracker/assets/36114312/6089f5ca-4d97-4c29-8226-b519820271b3)

### Solution

Implement the feature from CrDroid 9 source code

### Additional context

This is super low priority.

I'd understand if you label this as not planned. I just wanted to inform about this to the team. I think this is a feature a lot of people enjoyed and now it's gone.

From my point of view it looked way better with that option enabled.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by notorangee** [comment]
I like this feature, it looks more beautiful, I hope developers can add this feature again🙏

**Comment by gwolf2u** [comment]
not possible with current Android API
