### ISSUE TITLE
bug: the type of battery in the crdoid settings does not change anything

### ISSUE THREAD

**Issue by AvenCores** [crdroidandroid/issue_tracker#415]
### Issue type

User interface

### Device

Redmi Note 8 Pro (Begonia)

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-05-13

### Bug description

The type of battery in the crdoid settings does not change anything

### Steps to reproduce

Settings => crdroid settings => quick settings => battery type/battery percentage

### Relevant log (logcat/build log)

```shell
device_info: https://raw.githubusercontent.com/AvenCores/hlam/main/device_info.txt?token=GHSAT0AAAAAACRGZPEYURGYOP2333FWRUNWZSHI77Q
logcat: https://raw.githubusercontent.com/AvenCores/hlam/main/logcat.txt?token=GHSAT0AAAAAACRGZPEZFHPIUPNZCWKCX6WCZSHJAFA
```

### Screenshots or videos

![Screenshot_20240517-145039_Настройки](https://github.com/crdroidandroid/issue_tracker/assets/64781822/7bfb482d-b92e-4377-ac2a-e309ad5391ea)

### Solution

Through a general search for settings, find “battery type” and change the parameter there (there are two items and one of them will be working)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
what are you trying to change? statubar battery or qs battery?

**Comment by AvenCores** [comment]
> what are you trying to change? statubar battery or qs battery?

statubar battery

**Comment by gwolf2u** [comment]
> > what are you trying to change? statubar battery or qs battery?
> 
> statubar battery

then wrong page
go to first page - status bar
just confirmed, still working
