### ISSUE TITLE
Google Pixel 8 crashes in the search engine

### ISSUE THREAD

**Issue by Kalpeshter** [crdroidandroid/issue_tracker#417]
### Issue type

User interface

### Device

Google Pixel 8(shiba)

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024.05.07

### Bug description

In the device settings, when you try to enable search, it crashes to the main screen

### Steps to reproduce

1.go to the device settings
2.click on the search button
3.crash on the main screen 

### Relevant log (logcat/build log)

```shell
I don't know what it is
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
adb logcat needed
