### ISSUE TITLE
Charge weird behavior

### ISSUE THREAD

**Issue by JuaniThor00** [crdroidandroid/issue_tracker#42]
### Issue type

Other

### Device

Poco X3 Pro Vayu 

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

When i connect the charger, the Phone shows the charge process starts, but few seconds later, the Phone shows like the charge starts again... Also, the turbo charge is not working, sometimes the Phone shows "charging" or "slow charging" with more or less the same mAh, and sometimes shows "fast charging" but with the same mAh as "charging" no matter the battery charge percent. Also, the voltage changes randomly too. After testing it seems when the charger is first plugged in the turbo charge kicks in and starts fast charging the battery but turns off and starts slow charging. It doesn't go above 2 amps after it does the process of undetecting the charger and redetecting it.

### Steps to reproduce

Step one: connect the Phone charger
Step two: wait for the charging animation
Step Three: wait for a few seconds and the charging animation will appear again

### Relevant log (logcat/build log)

```shell
11-20 23:28:02.166 D/PowerUI (3030): can't show warning due to - plugged: true status unknown: false

11-20 23:28:03.879 D/PowerUI (3030): can't show warning due to - plugged: true status unknown: false
```

### Screenshots or videos

https://user-images.githubusercontent.com/50645133/203218101-30fc90ed-bb54-4b7f-b01b-43d2405ac7d5.mp4

### Solution

Possibly it is a bug in the battery charging process, or in the detection of the charger and/or its status.

### Additional context

[2022-11-20-23-28-06.txt](https://github.com/crdroidandroid/issue_tracker/files/10053414/2022-11-20-23-28-06.txt)

[2022-11-21-22-50-30.txt](https://github.com/crdroidandroid/issue_tracker/files/10063371/2022-11-21-22-50-30.txt)

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by JuaniThor00** [comment]
@neobuddy89

**Comment by gwolf2u** [comment]
This seems bit more widespread and not device specific
Happens also on some other devices

**Comment by tgiraud2007** [comment]
I have exactly the same problem on miatoll...
So I changed rom while waiting for a fix

**Comment by tgiraud2007** [comment]
> Cela semble un peu plus répandu et non spécifique à l'appareil Se produit également sur certains autres appareils

I hope they will fix the problem soon

**Comment by gwolf2u** [comment]
still happening on newer releases?

**Comment by JuaniThor00** [comment]
> still happening on newer releases?

No, with New releases the problem has been fixed

**Comment by MONaH-Rasta** [comment]
> still happening on newer releases?

I have this problem on latest release.

Version	9.6
Android	13
Build date	2023-06-29
