### ISSUE TITLE
bug: Notification light settings not working

### ISSUE THREAD

**Issue by AngelBePro** [crdroidandroid/issue_tracker#420]
### Issue type

Feature not working as intended

### Device

vayu

### crDroid version

crDroid 10

### Exact version / Build date

2024-05-19

### Bug description

Trying to change notification light speed and duration doesn't seem to do anything and after pressing OK sometimes settings crashes

### Steps to reproduce

Step 1. Open crDroid Settings
Step 2. Go to notifications tab
Step 3. Open notification light
Step 4. Change the length or speed
Step 5. Click OK and there is a chance it crashes

### Relevant log (logcat/build log)

```shell
Take a look at the attachment in additional context for a matlog zip
```

### Additional context

[logs-2024-05-24-19-05-37.zip](https://github.com/crdroidandroid/issue_tracker/files/15437172/logs-2024-05-24-19-05-37.zip)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
This is likely fixed in 
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/commit/7174d0c279a5a142f5a1999125c58a065ca0b0f0

Wait for new build.
