### ISSUE TITLE
Youtube PiP Mode 5-10 FPS

### ISSUE THREAD

**Issue by erenx23** [crdroidandroid/issue_tracker#421]
### Issue type

Feature not working as intended

### Device

Redmi Note 8 Pro 128 GB

### crDroid version

crDroid 10

### Exact version / Build date

10.5 / 2024-05-14 / Simone Esposito for Redmi Note 8 Pro

### Bug description

Youtube Revanced Extended or Youtube application runs at a value of 5-10 FPS when in Picture in Picture mode. We would like a setting where we can force it to run at 60 FPS and at least a fixed value of 30 FPS.

### Steps to reproduce

1. Open the Youtube application.
2. Go to your own account and click on the settings icon.
3. Open the General option and enable the screen-in-screen feature.
4. Open any video and press the home button. If you have activated the picture in picture feature in the system, go to step 5.
5. Start navigating the system or different applications.

### Relevant log (logcat/build log)

```shell
-
```

### Additional context

First of all, thank you for this ROM. I used MIUI 12.5.7 and crDroid 9.5 before. They were providing at least around 30 FPS, and we still deserve at least 30 FPS or more.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
there's no setting to add
needs log, should have ran at display resolution
