### ISSUE TITLE
Unable to install / Not Supported Kick App

### ISSUE THREAD

**Issue by erenx23** [crdroidandroid/issue_tracker#422]
### Issue type

User interface

### Device

Redmi Note 8 Pro 128 GB

### crDroid version

crDroid 10

### Exact version / Build date

10.5 / 2024-05-14 / Simone Esposito for Redmi Note 8 Pro

### Bug description

Unfortunately, the current kick application is not installed on crdroid. I am getting the error "Your device is not compatible with this version". I had used crdroid 9.5 before and it worked there but it was quite laggy. I want to use this updated application, but unfortunately crdroid 10.5 does not support it.

### Steps to reproduce

1. Go to https://kick.com/ with your phone.
2. Press the get the app button and it will direct you to the play store application.
3. You will encounter the error in the screenshot below. "Your device is not compatible with this version"

### Relevant log (logcat/build log)

```shell
-
```

### Screenshots or videos

![Screenshot_20240526-204956_Google_Play_Store](https://github.com/crdroidandroid/issue_tracker/assets/170882500/5ff37f94-c0e6-439b-a99d-e2bb01c5ad82)

### Additional context

Thank you for this ROM. There are a few problems, but I have to report them.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
needs play integrity fix, that is fixed in source this week
check with next update from July
