### ISSUE TITLE
Switching users / Multiple users

### ISSUE THREAD

**Issue by erenx23** [crdroidandroid/issue_tracker#423]
### Issue type

User interface

### Device

Redmi Note 8 Pro 128 GB

### crDroid version

crDroid 10

### Exact version / Build date

10.5 / 2024-05-14 / Simone Esposito for Redmi Note 8 Pro

### Bug description

When changing profiles (settings>system>multiple users), I need to fix lag, freezing, and lag by doing things like turning off/on the screen. The screen brightness can drop to 0 percent. I may also encounter an error such as the system interface is not responding and have to close the application by clicking close and the system restarts.

### Steps to reproduce

Open Settings > System > Multiple Users and switch to the other user.

### Relevant log (logcat/build log)

```shell
-
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
no log
