### ISSUE TITLE
An error occurred while creating a screen recording

### ISSUE THREAD

**Issue by erenx23** [crdroidandroid/issue_tracker#424]
### Issue type

User interface

### Device

Redmi Note 8 Pro 128 GB

### crDroid version

crDroid 10

### Exact version / Build date

10.5 / 2024-05-14 / Simone Esposito for Redmi Note 8 Pro

### Bug description

When I try to record the screen by pulling the top tab and pressing the screen recording button, I encounter the error "There was an error starting the screen recording."

### Steps to reproduce

1. Pull the top tab and press the screen recording button.
2. In the window that opens, pull the screen down a little and click the start recording button. The same problem will appear after 3 seconds.

### Relevant log (logcat/build log)

```shell
-
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
no log
