### ISSUE TITLE
bug: BT Music coming out from speaker during a notification

### ISSUE THREAD

**Issue by CoolDude-amber** [crdroidandroid/issue_tracker#425]
### Issue type

Feature not working as intended

### Device

Xiaomi 11T (amber)

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-05-24

### Bug description

During music playback on a BT headset, a notification would make a sound through the speaker, but a fragment of the song/audio would also be played alongside getting paused for a second in the headset.

### Steps to reproduce

1- Connect a headset (preferably BT)
2- Play some music
3- Make sure your phone isn't on silent mode
4- Wait for a notification sound while playing the music

### Relevant log (logcat/build log)

```shell
.
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this device is not officially supported, so no way to check dt stuff
anyway, this bug is deemed acceptable so it will be flagged as #nofix
