### ISSUE TITLE
bug: Pure Black affects text color

### ISSUE THREAD

**Issue by czubaka1234** [crdroidandroid/issue_tracker#426]
### Issue type

User interface

### Device

Redmi Note 10 Pro/Max (sweet)

### crDroid version

crDroid 10

### Exact version / Build date

10.5 / 2024-05-19

### Bug description

Enabling Pure Black in Dark theme settings affects also the text color. 
1. In QS all label colors change to the accent color. 
2. In other places the text gets colorized. This happens only with some specific accent colors like FF408F10.
Before enabling the text color is FFF1F0F7. After Pure Black it turn on the text color changes to FFE7F6D8.

### Steps to reproduce

1. In Monet settings change the accent color to FF408F10.
2. In Dark theme settings turn on Pure black.

### Relevant log (logcat/build log)

```shell
None
```

### Screenshots or videos

![QS](https://github.com/crdroidandroid/issue_tracker/assets/59745385/850ca290-4efd-4389-a287-d35615892637)
![Monet Settings](https://github.com/crdroidandroid/issue_tracker/assets/59745385/11629f16-f76c-4c4e-bdad-2ff93eafd3f8)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
This is following design by LOS.

**Comment by czubaka1234** [comment]
So no chance to fix it or make a separate "Pure Black" option in crDroid settings?

**Comment by gwolf2u** [comment]
At this time, this is acceptable "bug"
