### ISSUE TITLE
bug: CallRecording failing in long calls

### ISSUE THREAD

**Issue by trivi** [crdroidandroid/issue_tracker#427]
### Issue type

Feature not working as intended

### Device

Xiaomi POCO F2 Pro (lmi)

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024.05.19

### Bug description

After a long call using the CallRecording feature from the dialer, the file generated is muted after a few minutes.

### Steps to reproduce

Step 1. Record a long call (20 minutes at least).
Step 2. Check that call is muted after a few minutes.

### Relevant log (logcat/build log)

```shell
I didn't find relevant logs, but log is too long to paste the full file. The full log can be found in https://github.com/trivi/logs/blob/main/logcat.txt and the test call was done between 21:23 and 21:43
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by trivi** [comment]
Checking old records it has been happening since [10.02.2024 release](https://xdaforums.com/t/rom-14-0-official-lmi-crdroid-v10-5-19-05-2024.4640996/page-5#post-89331095)

**Comment by gwolf2u** [comment]
Issue from LOS upstream
for now #nofix

**Comment by raystef66** [comment]
@gwolf2u 
Afaik this should fix : https://gitlab.com/LineageOS/issues/android/-/issues/7143#note_2026961272

**Comment by raystef66** [comment]
@trivi  will run a test build today so you can check if fixed

**Comment by raystef66** [comment]
@gwolf2u 
We did a test build on LMI and working fine (https://gitlab.com/LineageOS/issues/android/-/issues/7143#note_2026961272)

Let me know if PR needed? Or we track later on?
