### ISSUE TITLE
bug:Battery Saver

### ISSUE THREAD

**Issue by pablos31s** [crdroidandroid/issue_tracker#429]
### Issue type

User interface

### Device

Earth

### crDroid version

crDroid 8

### Exact version / Build date

10.5/2024-05-29

### Bug description

when you try to turn on extreme battery saver, nothing happens

### Steps to reproduce

Go to setting->Battery->Battery saver->choose extreme saver

### Relevant log (logcat/build log)

```shell
check aditional context
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/162755789/2920cf28-316a-4552-81ff-d7ba6d362e8c

### Additional context

[log.txt](https://github.com/crdroidandroid/issue_tracker/files/15490438/log.txt)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
That is pixel exclusive
Option has been removed
https://github.com/crdroidandroid/android_vendor_pixel-framework/commit/421dc11fe99e416ebfafdc7bd2fc5ebc79585658
