### ISSUE TITLE
QS Panel messed with Status Bar

### ISSUE THREAD

**Issue by Avnesh007** [crdroidandroid/issue_tracker#43]
### Issue type

User interface

### Device

Beryllium

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

When we access QS panel than status bar messed up with QS like icons overlap each other.

### Steps to reproduce

[logs-2022-11-21-22-43-11.zip](https://github.com/crdroidandroid/issue_tracker/files/10058630/logs-2022-11-21-22-43-11.zip)

### Relevant log (logcat/build log)

```shell
11-21 22:29:20.248 D/b/223498680(2440): BaseRecentsViewStateController setStateWithAnimation state=Normal, config.skipOverview=false
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
try disabling network traffic monitor and see how it goes
