### ISSUE TITLE
signal bars icon is slightly offset vertically downward

### ISSUE THREAD

**Issue by gstjee** [crdroidandroid/issue_tracker#433]
### Issue type

User interface

### Device

dubai

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-5-30

### Bug description

signal bars are not in line with other status bar icons.
it is slightly downward offset.

### Steps to reproduce

ui issue.

### Relevant log (logcat/build log)

```shell
ui issue.
```

### Screenshots or videos

![Screenshot_20240603-014619_Pixel Launcher](https://github.com/crdroidandroid/issue_tracker/assets/127391704/7c11f882-2386-4b53-b9f9-a15f7e1eaefa)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
#nofix
