### ISSUE TITLE
Wallpaper and style stops responding when opened from settings 

### ISSUE THREAD

**Issue by DemonSneider** [crdroidandroid/issue_tracker#436]
### Issue type

Feature not working as intended

### Device

Miatoll

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-06-03

### Bug description

When I try to open backgrounds and styles from the device settings the application does not respond 

### Steps to reproduce

Step 1. Go to settings Step 2. Give wallpaper and style option 

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/6fdY7z
```

### Screenshots or videos

https://github.com/crdroidandroid/issue_tracker/assets/75942732/a357475d-2031-4a8d-90dd-51d9feb1e74e

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DrFunkenbreakz** [comment]
Works fine here. Sounds like you have setup your device incorrectly. Please research in your device group to see if other users of your device have same issue

**Comment by gwolf2u** [comment]
Also working here just fine
