### ISSUE TITLE
phone calls wont switch of carrier to default call sim selected on configuration

### ISSUE THREAD

**Issue by ilcreatore96** [crdroidandroid/issue_tracker#437]
### Issue type

Feature not working as intended

### Device

lancelot

### crDroid version

crDroid 10

### Exact version / Build date

UQ1A.240105.004 release-keys Sat Jan 20 04:04:42 GMT 2024 crdroid 10.1 Android14

### Bug description

when hitting call  to a contact on the call history it will call using other chip instead of the desired chip selected on Network > internet > sims

### Steps to reproduce

when hitting call  to a contact on the call history it will call using other chip instead of the desired chip selected on Network > internet > sims

select chip 1 for calls and data on setting up device (first set up after installing crdroid)

then go to config network and internet > sims

select chip sim 2 as call prefered 

then call a number from contacts default app or call history, it will call using the chip selected on device previous setup but is not grabbing the actual config from config menu

### Relevant log (logcat/build log)

```shell
i dont have root for logcat
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
lancelot is no no longer supported
