### ISSUE TITLE
Volume bar

### ISSUE THREAD

**Issue by Manavgupta12** [crdroidandroid/issue_tracker#438]
### Issue type

Feature not working as intended

### Device

Oneplus 7 pro (guacamole)

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-06-02

### Bug description

Volume bar is not working properly.When I hold the volume button to volume up then it vibrates only and I have to tap it again and again to volume it up

### Steps to reproduce

Nope

### Relevant log (logcat/build log)

```shell
Nope
```

### Screenshots or videos

Nope

### Solution

Nope 

### Additional context

Nope

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
can't reproduce here on guacamole
disable any mods (audio, ui)
