### ISSUE TITLE
Themed icons outdated & poor icon / icon bottom ratio (see pics)

### ISSUE THREAD

**Issue by huuhaa** [crdroidandroid/issue_tracker#439]
### Issue type

User interface

### Device

amber

### crDroid version

crDroid 10

### Exact version / Build date

Mon Jun  3 17:21:38 EEST 2024

### Bug description

This isn't actually bug, BUT I was told to open this issue anyway at your telegram group..
https://t.me/crDroidAndroid/445156

**Themed icons are outdated and have quite poor icon / icon bottom ratio** (compare phone screen to body ratio).

I will include example comparisons here. images with number 1 at file name are from LOS 21 with default launcher & themed icons on. Images with number 2 at file name are from crDroid 10.5 with default launcher and themed icons on ( if changes at filenames during upload / github handlings, first set is from LOS, second for crDroid)...

**Examples of icon / icon bottom ratio:**

![icons1](https://github.com/crdroidandroid/issue_tracker/assets/469355/ff199289-69f8-4546-a4d8-c525b5dc1d76)

![icons2](https://github.com/crdroidandroid/issue_tracker/assets/469355/f942f13b-8571-47a8-8ce6-43f7fd79a083)

In here I hope by default crDroid would also show actual icon bigger, about size of comparison pic. Or at least option to increase icon size. I know you can adjust icons bigger, but it will increase size of icon background too, leaving that ratio still bad. Could there be somekind of ratio adjustment if default can't be bigger? Note: obviously those looks smaller at phone home screen than on computer or even at mobile when looking screenshot..

**Outdated icon:**

![mull1](https://github.com/crdroidandroid/issue_tracker/assets/469355/4d8091e3-4731-4fc6-b698-3b9f8d1d7a62)

![mull2](https://github.com/crdroidandroid/issue_tracker/assets/469355/727da775-930d-4049-a707-1a8cf229c4a8)

In this example there is icon of Mull browser. crDroid themed icon is very outdated version. This might apply some other icons too, so might be good to check at same time all. And by saying this, I mention Tuta mail as an example. They have decided to renew their icon too, but seems not even f-droid has yet their new icon.. But that just one example of apps which will have new icon very soon..

### Steps to reproduce

Step1: Turn themed icons on for crDroid home screen.

Step2: See icon size / icon bottom ratios at icons

Step 3: Install Mull browser and add icon to homescreen.

### Relevant log (logcat/build log)

```shell
As mentioned, this isn't actually but, so no logcat here.

Anyway I was recommended to open this issue with these examples at:

https://t.me/crDroidAndroid/445156
```

### Solution

There are at least newer & bigger versions of themed icons available at LOS-21 launcher. Maybe those icons could be used at crDroid too?

### Additional context

As not actual bug, I hope I filled this right way for you not just closing issue. Issue itself isn't big, but will give nice final touch when fixed.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
We use thin line icons - uniform across all apps.
Icons updated as discussed on telegram: https://github.com/crdroidandroid/android_vendor_addons/commit/3404574fa983fd1ca4b45eab6ffb9d51378721ee
