### ISSUE TITLE
bug: Battery consumption 

### ISSUE THREAD

**Issue by MatureNoob** [crdroidandroid/issue_tracker#44]
### Issue type

User interface

### Device

OnePlus 7 pro

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

Battery is draining more than anything when device is idle. Overnight the phone is draining nearly 25% battery. 
I'm sleeping at night on 63% and when I woke up battery was 40%.

### Steps to reproduce

I don't know 

### Relevant log (logcat/build log)

```shell
I don't know this either
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
closing as traking here
https://github.com/crdroidandroid/issue_tracker/issues/46
