### ISSUE TITLE
Apps closing in the background

### ISSUE THREAD

**Issue by AdrianEverhart** [crdroidandroid/issue_tracker#442]
### Issue type

Other

### Device

Redmi 9 (lancelot)

### crDroid version

crDroid 10

### Exact version / Build date

10.1/2024-01-20

### Bug description

Background apps close when opening any app (after flashing NikGapps Stock)

### Steps to reproduce

Step 1. Open any app (like YouTube Music)
Step 2. Close it and enter another application

### Relevant log (logcat/build log)

```shell
I don't know how to do that.
```

### Additional context

Almost any application closes when I open another one. Before flashing the Gapps, there was no problem. It is not something related to RAM, because with other ROMs this problem did not occur and Magisk modules don't change anything. I have tried disabling applications that usually consume RAM, such as Google, but nothing happens either. As far as I can see, Google Play is the only app that stays open in the background.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
lancelot is no longer maintained officially
