### ISSUE TITLE
navigation gesture

### ISSUE THREAD

**Issue by alibm79** [crdroidandroid/issue_tracker#443]
### Issue type

Feature not working as intended

### Device

surya poco x3 nfc

### crDroid version

crDroid 10

### Exact version / Build date

10.5/ 31/05.2024

### Bug description

navigation gestures for split screen does not working

### Steps to reproduce

step1:go to crdroid settings step2:go to navigation settings step3:set a navigation gesture to split screen and it doesn't work

### Relevant log (logcat/build log)

```shell
no log
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
using gesture navigation or button?
