### ISSUE TITLE
My cellphone always restarts and reboots the system

### ISSUE THREAD

**Issue by IstrikuSayang03** [crdroidandroid/issue_tracker#446]
### Issue type

Other

### Device

Redmi 9 lancelote

### crDroid version

crDroid 10

### Exact version / Build date

10.1/2024-01-20

### Bug description

Hello, I'm a new CRdroid user, thanks to the developer or CRDroid developers. I've been using it for almost 2 months.

I use a Redmi 9 (Lancelot) cellphone then I install Android version 10.1 Android 14 on the cellphone. I experienced many problems or bugs including,
1. When I install an application then I open the application, my cellphone immediately restarts or reboots the system.
2. Even though you haven't opened the application, just restart or reboot the system in the menu display (home). Most of the time I experienced a system restart or reboot.
3. The home application always stops, I don't know what the problem is
4. Can't choose wallpaper

The crux of my problem is that my cellphone keeps restarting or rebooting the system.
If there is a way to fix it or a solution, please teach me how to do it

### Steps to reproduce

don't do anything, the cellphone will return to normal

### Relevant log (logcat/build log)

```shell
No
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ByAndrius** [comment]
They can't help, if you don't provide the Logcat. Search a tutorial of how get log with logcat using ADB.

**Comment by gwolf2u** [comment]
lancelot is no longer maintained officially, so no way to provide any fixes
also no logs
