### ISSUE TITLE
Keyboard doesn't close in app drawer

### ISSUE THREAD

**Issue by Detlev1** [crdroidandroid/issue_tracker#448]
### Issue type

User interface

### Device

begonia 

### crDroid version

crDroid 10

### Exact version / Build date

10.4/2024-06-17

### Bug description

The keyboard doesn't close in the app drawer when returning to the home screen when there is no text inside. 

### Steps to reproduce

Step 1. Open the app drawer
Step 2. Click search 
Step 3. Swipe down to close
Step 4. The keyboard stays opened

### Relevant log (logcat/build log)

```shell
-
```

### Solution

Type something and then swipe down

### Additional context

Even though this is a self compiled build utilizing the latest trees, the same issue occurres at the official builds as well

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
ref: old bug
https://github.com/crdroidandroid/issue_tracker/issues/25
