### ISSUE TITLE
Launcher bugs 

### ISSUE THREAD

**Issue by ebh5e4bh5** [crdroidandroid/issue_tracker#449]
1- animation bugs
2-keyboard bug on the app drawer
3- recently downloaded apps not showing on the homepage 
4-slow search results in the settings app
Device and BUILD: latest build of android 14 for oneplus 7t pro

 here is a clip:
https://drive.google.com/file/d/1DBIGFANwaeKn_yAIjw4kbqlfEgwbwHyZ/view?usp=drivesdk

Feature request: add the option to remove apps from the homepage upon pressing them in the context menu interface

**Comment by ebh5e4bh5** [comment]
Recent apps in the app drawer isn't working accurately either

**Comment by ebh5e4bh5** [comment]
Please also include the ability to show search results for crdroid settings and other root modules that integrate into the system settings app

**Comment by ebh5e4bh5** [comment]
I remembered another one, it's missing the option to change the resolutions.

**Comment by ebh5e4bh5** [comment]
Sorry, one more bug, certain settings are not being saved for example in the dev options upon reboot

**Comment by ebh5e4bh5** [comment]
Finger print also stopped working.

**Comment by ebh5e4bh5** [comment]
Another homepage bug https://drive.google.com/file/d/1EC6HCOdka4ZeLgpTZIM_L5uA2vrEEii4/view?usp=drivesdk

**Comment by gwolf2u** [comment]
use template and one issue at a time

**Comment by ebh5e4bh5** [comment]
Why do I have to report one issue at a time when I can report all of them at once? What do you mean by template?

**Comment by ebh5e4bh5** [comment]
Are you a developer for this project? Did you close this with their permission if you aren't?

**Comment by ebh5e4bh5** [comment]
All info besides the log has been provided.

**Comment by ebh5e4bh5** [comment]
If you have any questions regarding them and/or need the log I will be more than happy to provide them.

**Comment by 306bobby-android** [comment]
> Why do I have to report one issue at a time when I can report all of them at once? What do you mean by template? Like the way the bug reports are setup to be filled?

You have to report them one issue at a time because that is what the rules are.

The reason the rules are that way is not all features are from one system component, and each bug will get tagged the proper maintainer
