### ISSUE TITLE
bug: Status bar network label

### ISSUE THREAD

**Issue by DCA318** [crdroidandroid/issue_tracker#450]
### Issue type

User interface

### Device

OP6T

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-05-29

### Bug description

Network speed in status bar shows Bit/s when switching to B/s, while actual format changes.

### Steps to reproduce

Permanent

### Relevant log (logcat/build log)

```shell
No log
```

### Screenshots or videos

![Screenshot_20240619-212358_Einstellungen](https://github.com/crdroidandroid/issue_tracker/assets/32304205/7885c2d5-686d-4f05-aa7b-e5a45d5c5a12)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
What is your system language

**Comment by DCA318** [comment]
German

Pranav Vashi ***@***.***> schrieb am Do., 20. Juni 2024,
06:28:

**Comment by gwolf2u** [comment]
can't reproduce in todays 10.6
strings are not translatable also so not language dependent
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/blob/14.0/res/values/cr_strings.xml#L507#L508

@DCA318, can you try and see if english is fine for a chance?
