### ISSUE TITLE
bug: Font reverts to default in quick setting pulldown menu when changing between profiles

### ISSUE THREAD

**Issue by secretServant** [crdroidandroid/issue_tracker#451]
### Issue type

User interface

### Device

Devon

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-06-11

### Bug description

Visual bug, switching profiles reverts some elements in primary profile's pull down quick setting menu to default. The impacted elements are stuck as default font until reboot. 

### Steps to reproduce

Step 1. Set primary profile as non-default font.
Step 2. Create additional profile.
Step 3. Switch to newly created profile.
Step 4. Switch back to primary profile.
Step 5. Swipe down on the notification shade.
Step 6. View default font on some elements ( namely clock and cell provider) while most items are correctly using the font applied to the primary profile.

### Relevant log (logcat/build log)

```shell
Visual bug.
```

### Screenshots or videos

Primary profile is Storopia font.
![Screenshot_20240620-143318_crDroid Home_1](https://github.com/crdroidandroid/issue_tracker/assets/123250700/21b5c6ad-5725-45da-b265-98ad7f4aa9a2)

It seems to have reverted to default for the clock & cell provider in the qs menu. You can see the correct Storopia font next to the battery.
![Screenshot_20240620-143324_crDroid Home_1](https://github.com/crdroidandroid/issue_tracker/assets/123250700/aac39ca9-8482-467c-af1f-73d2c216ad94)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by secretServant** [comment]
I also noticed that elements like the privacy dots (location, camera, mic) and the bluetooth device displayed in the media player seemed to retain the guest profile's theme/color despite changing back to the primary profile. I think that system ui needs to be fully reinitialized when switching between profiles. Android 14's implementation of profiles seems a tad buggy. Since font choices are a crdroid addition the ticket's scope shouldn't be expanded to include theming as an issue. Although I thought it was worth mentioning.

**Comment by gwolf2u** [comment]
this is rather acceptable bug especially since reboot seems to fix it

**Comment by neobuddy89** [comment]
I am not able to reproduce this.
