### ISSUE TITLE
Screen record button not visible without scrolling with "Entire screen"

### ISSUE THREAD

**Issue by Theo-user** [crdroidandroid/issue_tracker#452]
### Issue type

User interface

### Device

POCO F3 (alioth)

### crDroid version

crDroid 10

### Exact version / Build date

10.5 28-05-2024

### Bug description

Scrolling is required to screen record only when entire screen is selected. 

### Steps to reproduce

Quick setting > Screen record > Select  "Entire screen"

### Relevant log (logcat/build log)

```shell
No logs required.
```

### Screenshots or videos

![Screenshot_20240621-123532_Vivaldi](https://github.com/crdroidandroid/issue_tracker/assets/75871295/ec0b5b2c-5f86-41bf-a4bf-01cda03b333e)
![Screenshot_20240621-123534_Vivaldi](https://github.com/crdroidandroid/issue_tracker/assets/75871295/ccc6451b-87e2-4033-b2cd-bd69ad849793)

### Solution

Title could be reduced in size, adjust margins. 
Start recording title wouldn't be needed if the button was visible. 
![Screenshot_20240621-124703_crDroid Home_1](https://github.com/crdroidandroid/issue_tracker/assets/75871295/ff3c8faf-ab25-49fa-b228-94acac8dba4a)

Text here could be reworded. Shortened.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
can't reproduce here
recording is done properly 
try with latest 10.6

**Comment by Theo-user** [comment]
Recording is done properly but since adding the screen recording mode you've introduced two extra steps to record entire screen.
Before the change you tapped the quick setting, start recording. Now you need to tap the quick setting, change to entire screen, scroll down, start recording.
This is why I asked to remember last chosen record method, this was rejected.
