### ISSUE TITLE
Save Screen record state for next use

### ISSUE THREAD

**Issue by Theo-user** [crdroidandroid/issue_tracker#453]
### Issue type

User interface

### Device

POCO F3 (alioth)

### crDroid version

crDroid 10

### Exact version / Build date

10.5 28-05-2024

### Bug description

The recent feature addition to select the screen record mode (per app/entire screen) means per app is now the default. Before this new feature entire screen was the only mode.

Make this option save state for next use like all the other options.

### Steps to reproduce

Quick settings > Screen record

### Relevant log (logcat/build log)

```shell
No log required
```

### Screenshots or videos

![Screenshot_20240621-125449_Vivaldi_1](https://github.com/crdroidandroid/issue_tracker/assets/75871295/077f7548-0e43-44c6-a065-0a37ed3da549)

### Solution

Save state for next time.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is by design
no bug
