### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Gupzz7** [crdroidandroid/issue_tracker#455]
### Issue type

User interface

### Device

Xiaomi 11T

### crDroid version

crDroid 10

### Exact version / Build date

Sun Jun  9 19:11:49 EEST 2024

### Bug description

Bug Bluetooth delay

### Steps to reproduce

?

### Relevant log (logcat/build log)

```shell
AP1A.240505.005 release-keys
```

### Solution

Update versi bluetooth

### Additional context

No

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DrFunkenbreakz** [comment]
No logs, no steps to reproduce. Not sure how you think others will be able to help you with such limited info.

This issue will probably be closed without the above. I suggest you use your device specific support group to investigate if other users of your device have same issue. Alternatively add the debug logs and steps to reproduce so others can help you.

**Comment by gwolf2u** [comment]
update to newer build and submit a full bug logcat if still happening
