### ISSUE TITLE
black

### ISSUE THREAD

**Issue by pablovinicius332** [crdroidandroid/issue_tracker#457]
### Issue type

User interface

### Device

Onclite

### crDroid version

crDroid 8

### Exact version / Build date

20240601

### Bug description

Black screen when starting

### Steps to reproduce

Boot

### Relevant log (logcat/build log)

```shell
[https://pastebin.com/raw/00NYsXyG
```

### Additional context

I tried to compile the ROM on the a11 and a12 in the latest versions and whenever I start my screen goes black on the home screen, this doesn't happen with other roms
the log was not accepting here, I attached it to pastebin
### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
device not maintained
