### ISSUE TITLE
bug?: Lockscreen wallpaper has light or dark layer applied over it now that can't be disabled

### ISSUE THREAD

**Issue by Terminator-J** [crdroidandroid/issue_tracker#459]
### Issue type

User interface

### Device

enchilada & fajita (Oneplus 6 & 6T), also happens in other devices (issue originally raised by user in Community TG group)

### crDroid version

crDroid 10

### Exact version / Build date

10.6, 20240707 (repo sync time at 1720298511.8111212)
(my current testing build, newer than 10.5 release available on crdroid.net site)

### Bug description

In 10.5 and earlier sources, wallpaper could be made identical between lock screen & home.
Now that 10.6 is out of BETA phase and has July ASB merged, wallpaper on lockscreen always has slight lightening or darkening adjustment layer applied over it that tracks light/dark theme, with no way to disable effect & just show actual image colors the same as home screen wallpaper.

Changing Monet settings in Settings > crDroid Settings > User Interface > Monet Settings has no impact, enabling/disabling "Use Pure Black" for dark theme has no impact, changing "blur" radius values in crDroid Home settings (used for modifying effect in Recents view) has no impact, choosing a different wallpaper image has no impact.

This effect seems like it might be intentional in AOSP source, but there's no exposed means of disabling it that I can find in Settings > Display > Lock screen, Settings > crDroid Settings > Lock Screen, Settings > crDroid Settings > User Interface, or Wallpaper & Styles, and it's a rather unwelcome change in that case.

### Steps to reproduce

- Update from 10.5 or earlier release to 10.6.
- Take screenshots on lock screen & unlocked home screen & compare wallpaper colors.

### Relevant log (logcat/build log)

```shell
Would a log be relevant? I can attach a lot of logcat if desired.
```

### Screenshots or videos

![light-dark-lockscreen-layer](https://github.com/crdroidandroid/issue_tracker/assets/34873300/fd9fbd89-a334-49d9-8110-4c5678d582e8)
Top: Lock screen while in light theme
Middle: Regular wallpaper while unlocked (both light & dark theme are identical, top shade is enabled)
Bottom: Lock screen with "Dark Theme" toggle enabled in Settings > Display

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ByAndrius** [comment]
Same issue here with Redmi Note 8 Pro (begonia).

**Comment by gstjee** [comment]
10.5 vs 10.6

- not only lockscreen but system wide there is little white tint
- lockscreen(severally visible tint). system wide(little less viisible than lockscreen).

[
![IMG_20240722_095812_849](https://github.com/user-attachments/assets/1db4a8b2-3522-4cb9-8d1e-48168bf622cb)
![Screenshot_20240722-094336_Pixel Launcher](https://github.com/user-attachments/assets/a69142f3-a658-423a-8079-b47cdf9a13df)
](url)

**Comment by gwolf2u** [comment]
seems to me like AOSP bug

**Comment by Adityasarkar1999** [comment]
Same issue with redmi note 10 mojito/sunny
![Uploading Screenshot_20240727-121558_crDroid Home.png…]()

**Comment by Adityasarkar1999** [comment]
![Screenshot_20240727-121602_crDroid Home](https://github.com/user-attachments/assets/8f67d0c5-41ba-4903-a6a8-066850f040a0)

**Comment by Adityasarkar1999** [comment]
Same issue with redmi note 10 mojito/sunny
![Uploading Screenshot_20240727-121602_crDroid Home.png …]()

![Uploading Screenshot_20240727-121558_crDroid Home.png …]()

**Comment by gwolf2u** [comment]
Issue was fixed in source

**Comment by Adityasarkar1999** [comment]
Same issue with redmi note 10 (mojito)
![Screenshot_20240727-121558_crDroid Home.png](https://github.com/user-attachments/assets/ad3453f4-644f-45d2-8dd8-053d5830f06e)

![Screenshot_20240727-121602_crDroid Home.png](https://github.com/user-attachments/assets/13f153be-c682-4e35-95d5-e0e688b4962e)
