### ISSUE TITLE
Status bar icons 

### ISSUE THREAD

**Issue by funnysith** [crdroidandroid/issue_tracker#460]
### Issue type

User interface

### Device

Poco X5 Pro 5G (redwood)

### crDroid version

crDroid 10

### Exact version / Build date

10.6/2023-07-07

### Bug description

1. VoLTE icon is not hidden when turned on in "Status bar icons"
2. After unplugging cable, battery % display remains when "Battery percentage when charging" is enabled

### Steps to reproduce

![photo_2024-07-10_15-13-43](https://github.com/crdroidandroid/issue_tracker/assets/121553039/26cbfaa5-297d-41f6-aaa1-8cefd00604ed)
![photo_2024-07-10_15-13-44](https://github.com/crdroidandroid/issue_tracker/assets/121553039/cadc7e18-1a6f-402c-b4e3-6571970bd8a2)
![photo_2024-07-10_15-15-30](https://github.com/crdroidandroid/issue_tracker/assets/121553039/1c098542-61f5-4a4e-83e9-ffe78eada63b)
![photo_2024-07-10_15-15-30 (2)](https://github.com/crdroidandroid/issue_tracker/assets/121553039/2ad9b15d-bff4-4e4c-b762-6f5f93c07bc7)

### Relevant log (logcat/build log)

```shell
No logcat. If necessary, I'll add it.
```

### Solution

Reboot SystemUI

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by meiser79** [comment]
regarding battery percentage: https://github.com/crdroidandroid/android_frameworks_base/commit/cf119a74514b56da1776afb3c9eb31edfc2b7532

**Comment by gwolf2u** [comment]
implementation is now changed
so this is fixed
