### ISSUE TITLE
Gesture navigation - Haptic back gesture not working

### ISSUE THREAD

**Issue by Jmrchy** [crdroidandroid/issue_tracker#461]
### Issue type

Feature not working as intended

### Device

miatoll / Joyeuse  (redmi note 9 pro)

### crDroid version

crDroid 10

### Exact version / Build date

AP2A.240705.005  (and previous since 10.4) 

### Bug description

Haptic back gesture is enable in crDroid/settings/System/Gesture/Navigation mode/Gesture navigation/haptic back gesture but no longer working since crDroid 10.4 on my redmi note 9 pro (Joyeuse).
Ok with 2 or 3 buttons interface.

### Steps to reproduce

Step 1 - Open any application
Step 2 - Perform back gesture from right to left or left to right to exit from the app.
No haptic feedback is produced.

### Relevant log (logcat/build log)

```shell
07-10 22:35:05.754  1745  5008 D CoreBackPreview: startBackNavigation currentTask=Task{449b925 #10 type=standard A=10425:org.telegram.messenger}, topRunningActivity=ActivityRecord{8408f69 u0 org.telegram.messenger/.DefaultIcon t10}, callbackInfo=OnBackInvokedCallbackInfo{mCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@7de57c, mPriority=0, mIsAnimationCallback=false}, currentFocus=Window{dca4b4e u0 org.telegram.messenger/org.telegram.messenger.DefaultIcon}
07-10 22:35:05.756  3039  3087 D ShellBackPreview: Received backNavigationInfo:BackNavigationInfo{mType=TYPE_CALLBACK (4), mOnBackNavigationDone=android.os.RemoteCallback@419e89e, mOnBackInvokedCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@c1c5f7f, mPrepareRemoteAnimation=false, mAnimationCallback=false, mCustomizeAnimationInfo=null}
07-10 22:35:05.762  1745  5008 I InputDispatcher: Channel [Gesture Monitor] edge-swipe (server) is stealing input gesture for device 2 from [dca4b4e org.telegram.messenger/org.telegram.messenger.DefaultIcon, [Gesture Monitor] swipe-up]
07-10 22:35:05.799  1745  1884 V WindowManager: Loading animations: layout params pkg=com.android.systemui resId=0x0
07-10 22:35:05.817  1063  1063 D vendor.qti.vibrator: Vibrator perform effect 2
07-10 22:35:05.818  1063 10823 D vendor.qti.vibrator: Starting perform on another thread
07-10 22:35:05.858  1063 10823 D vendor.qti.vibrator: Notifying perform complete
07-10 22:35:05.860  1063  1063 D vendor.qti.vibrator: QTI Vibrator off
07-10 22:35:06.062  3039  3087 D ShellBackPreview: Finishing gesture with event action: 1
07-10 22:35:06.063  3039  3087 D ShellBackPreview: onGestureFinished() mTriggerBack == true
07-10 22:35:06.063  3039  3087 D ShellBackPreview: Trigger back without dispatching to animator.
07-10 22:35:06.064  3039  3087 D ShellBackPreview: BackAnimationController: finishBackNavigation()
```

### Solution

This is probably a device issue, but I like this feedback so I investigated, by adding debug points and Java stack analyses.
The back gesture is  processed by framework/base/../EdgeBackGestureHandler.java, but in the end vendor/qcom/.../Vibrator.cpp receives a parameter effect = 2 (Vibratoire::perform(Effect effect  - Line #596) which does not produce any vibration.

By forcing a value effect = 0 at this level, the haptic back gesture returns but with side effects.

At the framework/base/.../view/View.java level, a feedbackConstant  parameter= 23 is passed to the performHapticFeedback function (Line #28371).
By forcing this value to 16 the feedback gesture is restored without any other side effects identified.
The following patch is applied on my device :
================================================================
framework/base/core/java/android/view/View.java - line # 28371 

    public boolean performHapticFeedback(int feedbackConstant, int flags) {
++					// cf frameworks/base/core/java/android/view/HapticFeedbackConstants.java
++       if(feedbackConstant == 23) {     	// public static final int GESTURE_THRESHOLD_ACTIVATE = 23
++			feedbackConstant = 16;			// public static final int CONFIRM = 16;
++			Log.w(VIEW_LOG_TAG, " performHapticFeedback feedbackConstant: " + feedbackConstant
++								+ " flags: " + flags);	
++		}		
       if (feedbackConstant == HapticFeedbackConstants.NO_HAPTICS
                || mAttachInfo == null) {
            return false;
       }		
================================================================
 The VIEW_LOG_TAG record allows you to trace the effects of the patch.
The switch in system/gestures parameters is fully operational to enable/disable the feature.

### Additional context

Log with patch :+1: 

07-10 17:00:10.001  2537  2568 D ShellBackPreview: Received backNavigationInfo:BackNavigationInfo{mType=TYPE_CALLBACK (4), mOnBackNavigationDone=android.os.RemoteCallback@1dd6717, mOnBackInvokedCallback=android.window.IOnBackInvokedCallback$Stub$Proxy@3781704, mPrepareRemoteAnimation=false, mAnimationCallback=false, mCustomizeAnimationInfo=null}
07-10 17:00:10.013  1987  5998 I InputDispatcher: Channel [Gesture Monitor] edge-swipe (server) is stealing input gesture for device 3 from [63cf0ca org.telegram.messenger/org.telegram.messenger.DefaultIcon, [Gesture Monitor] swipe-up]
07-10 17:00:10.041  1987  2283 W ProcessStats: Tracking association SourceState{a291dd8 com.android.phone/1001 ImpFg #59439} whose proc state 5 is better than process ProcessState{1e774b5 com.android.smspush/10389 pkg=com.android.smspush} proc state 14 (16 skipped)
07-10 17:00:10.063  1987  2077 V WindowManager: Loading animations: layout params pkg=com.android.systemui resId=0x0
**07-10 17:00:10.075  2537  2537 W View    :  performHapticFeedback feedbackConstant: 16 flags: 0**
07-10 17:00:10.080  1051  1051 D vendor.qti.vibrator: Vibrator perform effect 0
07-10 17:00:10.081  1051 20741 D vendor.qti.vibrator: Starting perform on another thread
07-10 17:00:10.121  1051 20741 D vendor.qti.vibrator: Notifying perform complete
07-10 17:00:10.122  1051  1051 D vendor.qti.vibrator: QTI Vibrator off
07-10 17:00:10.238  2537  2568 D ShellBackPreview: Finishing gesture with event action: 1
07-10 17:00:10.239  2537  2568 D ShellBackPreview: onGestureFinished() mTriggerBack == true
07-10 17:00:10.239  2537  2568 D ShellBackPreview: Trigger back without dispatching to animator.
07-10 17:00:10.240  2537  2568 D ShellBackPreview: BackAnimationController: finishBackNavigation()

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Jmrchy** [comment]
Sorry for my bad english and bold text i could not remove !

**Comment by gwolf2u** [comment]
I can not confirm this on todays build

**Comment by Jmrchy** [comment]
Hi, @popoASM,  others reported this malfunction on telegram miatoll/crDroid, keyword "haptic". 
At your service for any further information.
