### ISSUE TITLE
bug: notification led/light not triggering for notifications

### ISSUE THREAD

**Issue by dicamarques14** [crdroidandroid/issue_tracker#463]
### Issue type

Feature not working as intended

### Device

Monet and Raphael

### crDroid version

crDroid 10

### Exact version / Build date

Monet -> 10.6/2024-07-12
Raphael -> 10.6/2024-07-07

### Bug description

The notification light is not turning on when a new notifications shows up (for example, SMS or whatsapp)
The light works while charging the device

### Steps to reproduce

To test the light: 
go to settings, crdroid settings, notifications, notification light
Toggle on "lights with screen on" and try custom values, the light should blink

### Relevant log (logcat/build log)

```shell
I cant paste here, the log is too long
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Terminator-J** [comment]
Current (post-QPR3) sources for oneplus 6 (enchilada) also include updates to new Lights HAL that converts to aidl, and...

It also stopped working for actual notifications (apps, missed calls, voicemail, and sms/mms).

Only works in the UI for setting notification LED color/pulse pattern, when the "dummy" notification is in the statusbar.
@dicamarques14 Does your LED work in that specific situation?

**Comment by dicamarques14** [comment]
> Current (post-QPR3) sources for oneplus 6 (enchilada) also include updates to new Lights HAL that converts to aidl, and...
> 
> It also stopped working for actual notifications (apps, missed calls, voicemail, and sms/mms).
> 
> Only works in the UI for setting notification LED color/pulse pattern, when the "dummy" notification is in the statusbar. @dicamarques14 Does your LED work in that specific situation?

Yes, it works only while chargin or trying to set the pattern on the mi 10 lite (monet)

**Comment by Terminator-J** [comment]
So this is a known issue with LineageOS at this point.
Likely has to do with some recent changes in AOSP 14.0 QPR3 about notification handling and zen modes.

Can track status at https://gitlab.com/LineageOS/issues/android/-/issues/7423 for now; ideally we get to see a fix get merged upstream.

**Comment by raystef66** [comment]
Cepheus and lmi suffering as well.
Tried changing config_deviceLightCapabilities as someone did on PixelOS LMI and he was fortunate to revive his led notification.
But on crDroid didn't work. 
Also read on EvoX (cepheus) they have to dis/reanable it to work.

**Comment by iozho** [comment]
Same issue with crDroid 10.6 on Redmi Note 8

**Comment by raystef66** [comment]
Fixed on LMI after: 
https://github.com/crdroidandroid/android_frameworks_base/commit/5fd13ff2fdfba87d4f0eec53102ed6200a189e81

**Comment by Terminator-J** [comment]
Yep, fixed in enchilada as well. Thanks for testing!
