### ISSUE TITLE
bug: Clone App feature use Work Profile under the hood but does not expose Work profile related settings.

### ISSUE THREAD

**Issue by luigir-it** [crdroidandroid/issue_tracker#464]
### Issue type

Feature not working as intended

### Device

Xiaomi Mi8 (dipper)

### crDroid version

crDroid 10

### Exact version / Build date

10.6

### Bug description

After cloning any app, a Work profile is created, with "AudioFX" "Game Space" and "Settings" by default + cloned app.
If you remove the cloned app, the work profile is not deleted with it.
If you go under _Settings > Passwords, passkeys & autofill_ you should see Work Profile related settings, like the option to delete it, but nothing is shown. 

[What should you see](https://github.com/user-attachments/assets/0e806f4f-fadb-47dc-8a5c-6824d79b08cd)
[What you actually see](https://github.com/user-attachments/assets/e9c0a60c-c78e-4eea-91f3-14b8ffce07a6)

But that aside, is you manually delete the cloned app, the Work Profile is not deleted, and in order to delete it you have to go back in Cloned Apps, tap the tree vertical dots in the top right corser and choose "Delete all App clones".
Which is very counter intuitive, since the only app you effectively cloned has already been deleted.

### Steps to reproduce

1. Settings > Apps > Cloned Apps > _clone 1 app_
2. Go to launcher, you see Work profile
3. Settings > Apps > Cloned Apps > _delete the cloned app by clicking the trash icon beside it"
4. Go to launcher, you expect the work profile to be removed, but it's still there
5. Settings > Passwords, passkeys & autofill > _nothing is here_ 

### Relevant log (logcat/build log)

```shell
None
```

### Solution

1. Expose Work Profile settings where is should be, that is under Settings > Passwords, passkeys & autofill
2. Be transparent when cloning an app: pop up saying that this will use the Work Profile feature, and how to permanently delete it.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unfortunately there's not much we can do
google shipped half baked clone apps option with A14
hopefully will get better when A15 drops
