### ISSUE TITLE
bug: Fingerprint Animation misaligned

### ISSUE THREAD

**Issue by KiwiKing3** [crdroidandroid/issue_tracker#465]
### Issue type

Feature not working as intended

### Device

Google Pixel 7 (panther)

### crDroid version

crDroid 10

### Exact version / Build date

10.6/2024-07-06

### Bug description

All custom Fingerprint animations are misaligned and ~0,5cm under the reader

### Steps to reproduce

Go to crDroid settings
Set a custom on screen fingerprint reader animation
Unlock the phone

### Relevant log (logcat/build log)

```shell
There were no errors in the log and it just showed that it loaded the animation, so there's no need to show it.
```

### Screenshots or videos

![Screenshot_20240716-205111_Firefox](https://github.com/user-attachments/assets/8987b0a6-d15e-4438-8858-09ce71e4b4d5)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Albinoman887** [comment]
a log would be helpful still

**Comment by gwolf2u** [comment]
> a log would be helpful still

log won't help here
is some overlay issue
https://github.com/crdroidandroid/android_frameworks_base/blob/14.0/packages/SystemUI/res/values/cr_dimens.xml#L53#L55
@Vikas-V2
