### ISSUE TITLE
bug: Sound and vibration

### ISSUE THREAD

**Issue by Sprite1337** [crdroidandroid/issue_tracker#466]
### Issue type

Feature not working as intended

### Device

miatoll

### crDroid version

crDroid 10

### Exact version / Build date

12.07.2024

### Bug description

After each device reboot, the sound and vibration playback when the screen is on feature automatically turns off  in Crdroid settings

### Steps to reproduce

1. Reboot
2. Sounds and vibration do not work when the screen is on

### Relevant log (logcat/build log)

```shell
.
```

### Solution

Go to Crdroid settings and turn off this setting and then turn it on

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
which setting you are referring to? not clear.
