### ISSUE TITLE
bug: title (When you finish changing to dark mode, you go straight to the Resent Apps, a system crash occurs

### ISSUE THREAD

**Issue by qyramitsu** [crdroidandroid/issue_tracker#470]
### Issue type

User interface

### Device

Sweet K6a

### crDroid version

crDroid 10

### Exact version / Build date

Sun Feb 25 09:41:29 UTC 2024
UQ1A.240205.004

### Bug description

When you finish changing to dark mode, you go straight to the Resent Apps, a system crash occurs

### Steps to reproduce

???

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/atHZka
```

### Screenshots or videos

?

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
old build 
update to newer
