### ISSUE TITLE
Bug title: Bug when fingerprint unlocking

### ISSUE THREAD

**Issue by himanga0414** [crdroidandroid/issue_tracker#471]
### Issue type

User interface

### Device

POCO M3 (Chime)

### crDroid version

crDroid 9

### Exact version / Build date

9.14/2024-02-26

### Bug description

Lock screen appears for a second when I'm unlocking with the fingerprint while the screen turned off

### Steps to reproduce

.

### Relevant log (logcat/build log)

```shell
.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
device no longer supported
