### ISSUE TITLE
bug: after restart, notifications act as if "noisy notifications" was off

### ISSUE THREAD

**Issue by dicamarques14** [crdroidandroid/issue_tracker#472]
### Issue type

User interface

### Device

Xiaomi 10 Lite 5G (Monet)

### crDroid version

crDroid 10

### Exact version / Build date

10.6/2024-07-12

### Bug description

I have noisy notifications turned on, when I receive a notification and the device is unlocked, it should vibrate/make a notification sound
If I go to settings it shows up as ON, if I restart the device it still shows as ON but acts as OFF. 
Need to turn off and on to act as expected 

### Steps to reproduce

Go to crdroid settings>notifications:
Check the state of "noisy notifications"
Try to get a notification with sound /vibrate allowed with the device unlocked and screen on
Check if the behaviour is as expected with the toggle state
Reboot the device and check again the state of the toggle and what's the behaviour when a notification comes

### Relevant log (logcat/build log)

```shell
No log
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Fixed in https://github.com/crdroidandroid/android_frameworks_base/commit/53f6d28b2a0baf8316cbbb000caaf437bfda86c7
