### ISSUE TITLE
bug: Call recording become blank after a random time.

### ISSUE THREAD

**Issue by VVStz** [crdroidandroid/issue_tracker#476]
### Issue type

Other

### Device

spes / spesn

### crDroid version

crDroid 10

### Exact version / Build date

14.0-20240314-spes-v10.2

### Bug description

in the default phone app `com.android.dialer` under setting\Sound and vibration\Call recording `Auto call recording` is enabled
The output file (amr) are the length of the call , but when playing we notice the the record only happen the first RANDOM second and then the rest of the file is white (no sound)

### Steps to reproduce

See description.

### Relevant log (logcat/build log)

```shell
*
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by VVStz** [comment]
Additional info

it seem the same issues as https://github.com/crdroidandroid/issue_tracker/issues/427

**Comment by raystef66** [comment]
Could well be related https://github.com/crdroidandroid/issue_tracker/issues/427

**Comment by gwolf2u** [comment]
tracking in #427
