### ISSUE TITLE
bug: Unable to change some custom options in crdroid settings in the workspace to default options

### ISSUE THREAD

**Issue by wanzh5** [crdroidandroid/issue_tracker#477]
### Issue type

User interface

### Device

oneplus 11 (salami)

### crDroid version

crDroid 10

### Exact version / Build date

10.5/2024-06-02

### Bug description

Because workspace and personal space share crdroid settings, modifying these options will take effect on both users.
Everything works fine in personal space. However, in the workspace, after changing some settings in crdroid settings that involve selecting certain styles (such as font style or icon pack), you cannot return to the default style.

### Steps to reproduce

1, Create a workspace. I use a software called "Shelter" (You can find it at [https://f-droid.org/packages/net.typeblog.shelter](url)), maybe it is also a factor causing the bug.
2, Change one of the options mentioned above.
3, Return it to default.
4, You can see the bug in all the apps in the workspace.

### Relevant log (logcat/build log)

```shell
none
```

### Screenshots or videos

In this screenshot, the default font preview shows the last selected font.
![1000021758](https://github.com/user-attachments/assets/470df6bf-5d64-4ba8-95bd-78ba2bfdcb90)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [x] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
10.7 is cooking
so try when released and report back

**Comment by gwolf2u** [comment]
Closed since as neobuddy said, you can not change that due to being same

**Comment by polygraphene** [comment]
I have the same issue.
Work profiles are backed by android multi user.
This issue affects both work profiles and standalone (sub) users.

I have yet to determine exact cause, but at least resource overlays are not properly applied on a multi user environment.
When setting fonts to other than default one, overlays are applied to all user (including work profile).
But when setting font back to default, they are applied only to user id 0.
It causes sub users and profiles stuck in non default font. No matter what I do, they can't go back to the default.

I could get it back to the default, by the following command in `adb shell`.
```sh
cmd user list | tail -n +2 | sed 's/\tUserInfo{\([0-9]*\).*/\1/' | while read i; do cmd overlay enable-exclusive --user $i --category com.android.theme.font.accuratist; cmd overlay disable --user $i com.android.theme.font.accuratist; done
```

You can check current overlay settings by the following commans:

List users:
```sh
pm list users
```
Check for user 0:
```sh
cmd overlay list --user 0 android | grep com.android.theme.font
```
or for user 10:
```sh
cmd overlay list --user 10 android | grep com.android.theme.font
```

After settings font to Accuratist, I got:
```sh
$ cmd overlay list --user 0 android | grep com.android.theme.font
...
[x] com.android.theme.font.accuratist
$ cmd overlay list --user 10 android | grep com.android.theme.font
...
[x] com.android.theme.font.accuratist
# Applied also for user 10.
```
Then after reverting to default:
```sh
$ cmd overlay list --user 0 android | grep com.android.theme.font
...
[ ] com.android.theme.font.accuratist
$ cmd overlay list --user 10 android | grep com.android.theme.font
...
[x] com.android.theme.font.accuratist
# User 10 can't disable font overlay.
```
