### ISSUE TITLE
bug: SystemUI Memory leak

### ISSUE THREAD

**Issue by Zachhambo** [crdroidandroid/issue_tracker#478]
### Issue type

Other

### Device

Poco F2 Pro (lmi)

### crDroid version

crDroid 10

### Exact version / Build date

10.6/ 2024-07-26

### Bug description

While using device, systemUI experiences a memory leak that eventually fills the entire system ram after several hours of usage, resulting in all background (launcher, live wallpaper, music player, matlog) and sometimes foreground apps being killed until systemUI or system is restarted which fixes the RAM hog issue until it fills up again. 

### Steps to reproduce

Step 1. Observe normal system RAM usage in running services
Step 2. Use Phone normally with background apps (eg live wallpaper)
Step 3. Wait until background or foreground apps crash 
Step 4. Observe now bloated system RAM usage 
Step 5. Restart system UI or entire device to temporarily fix

### Relevant log (logcat/build log)

```shell
08-03 13:54:33.140 D/ConnectivityService( 1791): releasing NetworkRequest [ REQUEST id=9831, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED&NOT_VCN_MANAGED Uid: 10395 RequestorUid: 10395 RequestorPkg: com.google.android.gms UnderlyingNetworks: Null] ] (release request)
08-03 13:54:33.141 I/ActivityManager( 1791): Process com.google.android.gms.unstable (pid 12191) has died: svc SVC 
08-03 13:54:33.141 I/Zygote  (  955): Process 12191 exited due to signal 9 (Killed)
08-03 13:54:33.141 I/libprocessgroup( 1791): Removed cgroup /sys/fs/cgroup/uid_10395/pid_12191
08-03 13:54:33.141 W/ActivityManager( 1791): Scheduling restart of crashed service com.google.android.gms/.droidguard.DroidGuardService in 28947ms for start-requested
08-03 13:54:33.142 I/WearBitmaps(11839): Returning circular bitmap
08-03 13:54:33.142 I/WatchFacesModel(11839): Got circular bitmap for 16
08-03 13:54:33.142 I/WatchFacesModel(11839): Getting bitmap for 17
08-03 13:54:33.142 I/WatchFacesCommunicator(11839): In getBitmapFromDataItemAsset
08-03 13:54:33.144 W/ActivityManager( 1791): Rescheduling restart of crashed service com.afkettler.pro.earth/com.afkettler.earth.Wallpaper in 6833ms for mem-pressure-event
08-03 13:54:33.144 W/ActivityManager( 1791): Rescheduling restart of crashed service com.google.android.inputmethod.latin/com.android.inputmethod.latin.LatinIME in 26833ms for mem-pressure-event
08-03 13:54:33.144 W/ActivityManager( 1791): Rescheduling restart of crashed service com.google.android.gms/.droidguard.DroidGuardService in 46833ms for mem-pressure-event
```

### Screenshots or videos

![Screenshot_20230726-085015_Settings](https://github.com/user-attachments/assets/62fb9a61-efa2-4f3a-a5b4-ac433b08a4f1)
![Screenshot_20230712-094723_Settings](https://github.com/user-attachments/assets/d61bc0df-efad-40d3-ae41-f48857f8ecfa)

### Solution

Temporary fix is to restart device or systemui, which reduces system ram usage by 1-2gb and stops apps crashing.

### Additional context

Bug has been present since at least 31 May build (likely before). I believe it is present on other devices (hotdog).

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Hellohi3654** [comment]
Can confirm I'm running crDroid 10 on my OnePlus 7T Pro
And have the same issue
Started happening with crDroid 10.5 QPR2
Takes about a day for systemui to use this much memory 

![Screenshot_20240807-182617_3C Task Manager](https://github.com/user-attachments/assets/c3625696-d6b4-4a58-bc71-f32eadc1b933)

After restarting systemui 

![Screenshot_20240807-182708_3C Task Manager](https://github.com/user-attachments/assets/33aaed0d-5445-4b44-b5cb-e1c15ee53906)

I'm using kernelsu and have nikgapps full installed

**Comment by polq1200** [comment]
I have the same thing on realme gt master![Screenshot_20240730-124950_Termux.png](https://github.com/user-attachments/assets/ef960b1b-7146-4b34-b848-a5a2e28fadda)

**Comment by gwolf2u** [comment]
As 10.6 is now old code since we rebased 10.7, please try latest update 10.7 to see if same issue

**Comment by Zachhambo** [comment]
10.7 seems to have fixed it, [https://github.com/crdroidandroid/android_frameworks_base/commit/891fc4c3b8fec467f92428ce9b35a1e821d10c7d](url) presumably this commit? 
Thanks Devs

**Comment by Zachhambo** [comment]
Still present on lmi, just took longer to happen than before.
![Screenshot_20240814-141324_3C Task Manager](https://github.com/user-attachments/assets/228c3476-d28b-4606-a63b-f426686520f7)

**Comment by raystef66** [comment]
@Zachhambo 
Tbh your systemui numbers are quite normal. Issue is when the numbers are in the GB range.

**Comment by Hellohi3654** [comment]
Memory still not fixed but better in latest build for my OnePlus 7T Pro
![Screenshot_20240817-105402_3C Task Manager](https://github.com/user-attachments/assets/7f3ec225-d89c-4c32-93ce-29b3ae965f85)
Takes longer to fill up
Been running for 18 hrs usually would be over 1gb of usage by systemui by now

**Comment by Hellohi3654** [comment]
![Screenshot_20240817-133214_3C Task Manager](https://github.com/user-attachments/assets/80cf9229-0023-4a52-8b42-8ece6634b540)

Yeah latest 10.7 update for my Oneplus 7T Pro hasn't helped at all
Still bad memory leak in systemui

**Comment by Hellohi3654** [comment]
![Screenshot_20240822-022951_3C Task Manager](https://github.com/user-attachments/assets/e236d2eb-571f-44d1-ab69-c6779b471171)

Still got memory leak with latest 10.7 build for my OnePlus 7T Pro 
Only 13 hours of uptime and already over 1 GB

**Comment by Hellohi3654** [comment]
![Screenshot_20240823-130112_3C Task Manager](https://github.com/user-attachments/assets/2ad21e9c-5650-442b-bd3a-e198b7f01777)

Now over 2gb with 47 hours of uptime 
Nothing stays running in the background and whole UI is laggy

**Comment by Zachhambo** [comment]
![Screenshot_20240823-164828_3C Task Manager](https://github.com/user-attachments/assets/ebe11971-a656-43ff-8aa6-874cefe1e500)
Not sure if this is related but system server has high CPU usage I think when I open Google maps navigation which causes it to continuously crash due to low ram or some other issue. I think I'm done with this rom.

**Comment by wizard1405** [comment]
I have had this exact same bug in  miatoll as well for a while, and I'm glad it's finally been reported.

Btw in 10.7, it has slightly improved.i.e it takes longer for memory to fill up.

But after 70-80h of uptime it gets very difficult to use the device without rebooting

**Comment by Hellohi3654** [comment]
> I have had this exact same bug in miatoll as well for a while, and I'm glad it's finally been reported.
> 
> Btw in 10.7, it has slightly improved.i.e it takes longer for memory to fill up.
> 
> But after 70-80h of uptime it gets very difficult to use the device without rebooting

Only takes 2 days for ram usage to be at almost 2gb for systemui for me

**Comment by Hellohi3654** [comment]
Does not everyone have this issue or something 
To me this should be top priority to fix

**Comment by trivi** [comment]
Please, stop spamming this thread. The developers are definitely aware of the problem, if you have no relevant logs or solutions to provide just up vote the first message.
It's not gonna be solved sooner for complaining about it again and again.

**Comment by Sabbirfluxion** [comment]
Yes this also happens with me most rom affect with that issu now im in 10.7 issu not solv

**Comment by gwolf2u** [comment]
guys please stop commenting "happening to me too" and stop posting screenshots that are not relevant
as you can see I've marked old comments for that purpose 
it doesn't help debug the issue
most of the team members can't reproduce the issue, but since this seems to indeed happen, issue is still open
wait for a fix or help debug properly with logs or code if possible
all non helping comments will from now be deleted
have patience please

**Comment by Hellohi3654** [comment]
> Please, stop spamming this thread. The developers are definitely aware of the problem, if you have no relevant logs or solutions to provide just up vote the first message. It's not gonna be solved sooner for complaining about it again and again.

Mate

This has been like this for months for me and it's starting to get really annoying.
I would be happy to help with any debugging, providing logs and etc but where would I even get relevant logs from? 

There hasn't been any real respond from the developers on this issue and one of them has now marked it as needs more info. 

You tell me where to get the info. It's a memory leak there are probably no errors anywhere and I don't know where to get logs from in the first place.

This is extremely frustrating as this is not the only bug with this rom for me and I would make more issues on this repo but I want to wait until this issue is fixed in case the devs take time to fix one of the other issues first instead of focusing on this one.

It honestly feels like crdroid is getting buggier and buggier with every update just completely negating any sort of quality of life changes or features the devs add.

**Comment by Hellohi3654** [comment]
> guys please stop commenting "happening to me too" and stop posting screenshots that are not relevant as you can see I've marked old comments for that purpose it doesn't help debug the issue most of the team members can't reproduce the issue, but since this seems to indeed happen, issue is still open wait for a fix or help debug properly with logs or code if possible all non helping comments will from now be deleted have patience please

Please tell me how I can help

**Comment by Hellohi3654** [comment]
Got a memory map of systemui

First one is before memory leak 
Systemui is using 120MB of ram
[uimaps.txt](https://github.com/user-attachments/files/16775664/uimaps.txt)

This second one is once systemui memory usage has started to grow 
Systemui is using 360mb of ram
[uimemleak.txt](https://github.com/user-attachments/files/16775672/uimemleak.txt)

I will edit and include another map once systemui usage has reached around 1gb of usage

**Comment by raystef66** [comment]
Check new build on LMI if improved.

**Comment by PptO07** [comment]
@gwolf2u @raystef66 @neobuddy89 

There is a method to reproduce it
just change color pallets multiple time from wall paper picker
like keep clicking on various color pallets at same time, spam it hard
and then check ram usage from recents
it will be less than 1 gb free ram available

Maybe this is only happening on 4.14.x kernels, is what i observed till now

**Comment by raystef66** [comment]
@PptO07  LMI is 4.19.x

**Comment by Hellohi3654** [comment]
Must still increase without changing colours slowly over time, but yes can confirm on OP 7T Pro changing colours does massively increase ram usage of systemui. Have also noticed lately that Android System:system_server mem usage is up at 400MB does not go down with systemui restart which fixes systemui's mem usage.

**Comment by neobuddy89** [comment]
Hi all,

The source has been cleaned up. Please try newer builds built on/after 2nd September and report back.

https://github.com/crdroidandroid/android_frameworks_base/commits/14.0/

**Comment by Hellohi3654** [comment]
Framework cleanup has reduced baseline systemui memory usage to 100mb but still mem leak.
Changing colours in wallpaper and style still causes it to go up.

**Comment by Hellohi3654** [comment]
Theme engine rebase has again reduced baseline systemui memory usage to 70MB but switching colours in wallpaper and style still causes mem usage to go up alot.

**Comment by asizon** [comment]
![Screenshot_20240903-142958_Ajustes](https://github.com/user-attachments/assets/9d2f92b3-832b-4589-9051-cebe53f38c1c)
All is working fine in my device,miatoll joyeuse

**Comment by Hellohi3654** [comment]
On build 20240903 for OnePlus 7T Pro still have memory leak
Systemui mem usage is 675MB
Memory map of systemui
[systemui5092024.txt](https://github.com/user-attachments/files/16883416/systemui5092024.txt)

**Comment by neobuddy89** [comment]
SystemUI usage doesnt shoot up for me on new builds even after changing themes.
@gstjee which build date rom you using?

**Comment by gwolf2u** [comment]
> > which build date rom you using?
> 
> 3 sept evening. let me know if you want one to one test/logs/dumps as device is rooted so it won't be a problem.
> 
>     * to highlight once again: as i have shared RAM usage earlier in below link. it seems like native  code being cached but then later on no garbage collection happen for non referenced object (atleast that i can see at frontend usage logs, but i don't have much idea about inside code execution ;p )
>       [bug: SystemUI Memory leak #478 (comment)](https://github.com/crdroidandroid/issue_tracker/issues/478#issuecomment-2311719085)

Do you use any mods?

**Comment by Hellohi3654** [comment]
I'm on 20240904 for OnePlus 7T Pro
Changing themes causes memory to increase but here I haven't touched the theme setting and just let systemui mem usage go up on its own
3C task manager reports it at 2gb of usage
Mem map of systemui: 
[sysuimap20240807.txt](https://github.com/user-attachments/files/16910463/sysuimap20240807.txt)

**Comment by raystef66** [comment]
Latest build I made for LMI (06.09) seems to be doing well. SystemUI not going above 500MB even with tampering theme color under WP. So far so well...

![Screenshot_20240906-195126_Settings](https://github.com/user-attachments/assets/412ca92d-7877-4b91-bb45-c409d5d36404)

**Comment by gwolf2u** [comment]
let's keep one bug at a time 
do please check for SystemUI memory issue on released 10.8

**Comment by Hellohi3654** [comment]
Memory usage still goes up over time for systemui and also still goes up when switching colours themes in wallpaper and style on crdroid 10.8.
I'm on build 20240909 for OP 7T Pro

I installed update earlier and sysui mem usage went up to 1.13GB I then switched colour theme a few times in a row and it went to 1.61GB usage.

Here is memory map of sysui at 1.61GB usage:
[sysui20240911.txt](https://github.com/user-attachments/files/16947852/sysui20240911.txt)

I have however noticed the memory usage of all other processes is lower then is was before and the zygote bug is gone as well. What I mean by this is processes that used say 120MB before now are only using 80MB according to 3C task manager.

**Comment by oscar-tm89** [comment]
Updated to the latest version 10.8, the memory problems persist, even reaching the point of completely saturating the system again and seeing that consumption shot up to 4GB for "System UI".
Build 20240909 for OP 7T Pro.

I don't know if the specific configuration of the device will have something to do with it, like some module enabled specifically in Magisk that causes a conflict.

I haven't tested it yet but I don't know if the Dolby Atmos Moto Core module has anything to do with it, especially the one that modifies the system framework ("Moto Core"). I have read that more than one person who has this problem has had this type of modules installed, it may be interfering with the behavior of the system and RAM management.

We would need to confirm if those experiencing this problem have this Magisk module installed.

**Comment by Hellohi3654** [comment]
> Updated to the latest version 10.8, the memory problems persist, even reaching the point of completely saturating the system again and seeing that consumption shot up to 4GB for "System UI". Build 20240909 for OP 7T Pro.
> 
> Simply stopping the System UI process eliminates this RAM saturation problem, the process restarts between 200-600MB, a consumption considered normal for this process.
> 
> I don't know if the specific configuration of the device will have something to do with it, like some module enabled specifically in Magisk that causes a conflict.
> 
> I haven't tested it yet but I don't know if the Dolby Atmos Moto Core module has anything to do with it, especially the one that modifies the system framework ("Moto Core"). I have read that more than one person who has this problem has had this type of modules installed, it may be interfering with the behavior of the system and RAM management. I will do a test and remove the Moto Core module temporarily, if it doesn't work I will remove the Magisk Dolby Atmos Moto g52 and I will review how the system behaves after this.
> 
> We would need to confirm if those experiencing this problem have this Magisk module installed.

I'm on the same device and don't have Moto Core module
I use kernelsu and still have the memory leak
I have also updated to 20240911 and remember leak is still the same nothing has changed

**Comment by oscar-tm89** [comment]
Do you have any dolby module that modifies the system sound or the system framework?
I have also just found that the problem persists when removing the "Moto Core" module and after a while, even when playing videos, the system becomes overloaded.
In my case, this has happened to me a lot more when watching videos in any browser. I thought it was due to excessive Chrome consumption, so I switched to Firefox and the problem persists. As I mentioned before, the UI System consumes more than 4GB of RAM. The process itself is accumulating cache memory, perhaps from the content that is being played, and it is not deleting it.

**Comment by Hellohi3654** [comment]
> Do you have any dolby module that modifies the system sound or the system framework? I have also just found that the problem persists when removing the "Moto Core" module and after a while, even when playing videos, the system becomes overloaded. In my case, this has happened to me a lot more when watching videos in any browser. I thought it was due to excessive Chrome consumption, so I switched to Firefox and the problem persists. As I mentioned before, the UI System consumes more than 4GB of RAM. The process itself is accumulating cache memory, perhaps from the content that is being played, and it is not deleting it.
> 
> I think we should try to find a common configuration pattern for all of us who experience this problem to determine the cause of it. Installed Magisk modules, LSPosed modules, CrDroid specific configuration...
> 
> The Magisk modules I have installed in KernelSU are: Dolby Atmos Moto G52, OP7 Pro Camera Enhance (Savitar), Systemless hosts kernelSU module, Zygisk - LSPosed, Zygisk - Detach, Zygisk - Sui, Zygisk Next. LSPosed: 3C Task, Bootloader Spoofer, E-Gobermment Liberator, Enable Screenshot (Disable flag secure), Wa Enhancer, XPL - EX (XPrivacyLua).

Should probably add nikgapps config if you have modified it or just say crdroid release if you haven't modified it.

I use kernelsu and have: Busybox for Android NDK, Global Optimized GPS file replacer, Play integrity fix, Tricky store, Viper4androidFX repackagedhoch87, Zygisk Next

And my nikgapps config 
[nikgapps.txt](https://github.com/user-attachments/files/17001912/nikgapps.txt)

**Comment by w568w** [comment]
I can confirm that the issue persists in the latest update.

After some research, I found that Android's built-in profiler, [Perfetto](https://perfetto.dev/), is capable of [profiling native memory usage in SystemUI](https://perfetto.dev/docs/case-studies/memory) and obtaining backtraces, only when using [a userdebug build](https://perfetto.dev/docs/data-sources/native-heap-profiler#heapprofd-targets). Additionally, other methods for debugging memory leaks are documented [here](https://source.android.com/docs/core/tests/debug/native-memory).

Any ideas? I can help test the memory leak in a userdebug build, but I have no idea how to compile the ROM.

**Comment by ChocolateLoverRaj** [comment]
This is a "me too" but I think it is useful information. I think I have experienced problems caused by a SystemUI memory leak on my Pixel 2 XL (taimen) in LineageOS too. When I had the march update of LineageOS I did not have any problems. When I got the July update, I started having problems. Since crDroid is based on LineageOS maybe it is a bug that exists for both of them. 

When I was using LineageOS with GAPPS, I did not root the phone or install any apps that made customizations. Around once every 2 days I would get the message "System UI is not responding", then the screen would turn off (but the phone was still responsive, and sqeeze for flashlight was working). Then it seemed like the phone restarted but if I checked the up time it was not reset.

**Comment by Hellohi3654** [comment]
> This is a "me too" but I think it is useful information. I think I have experienced problems caused by a SystemUI memory leak on my Pixel 2 XL (taimen) in LineageOS too. When I had the march update of LineageOS I did not have any problems. When I got the July update, I started having problems. Since crDroid is based on LineageOS maybe it is a bug that exists for both of them.
> 
> When I was using LineageOS with GAPPS, I did not root the phone or install any apps that made customizations. Around once every 2 days I would get the message "System UI is not responding", then the screen would turn off (but the phone was still responsive, and sqeeze for flashlight was working). Then it seemed like the phone restarted but if I checked the up time it was not reset.
> 
> Edit: I just experienced the SAME problem on crDroid as I did on LineageOS. Here is what happened:
> 
> * It was 10:30, but the ambient display showed 9:59
> * Pressing the power button did not show the lock screen
> * I rotated the phone and the ambient display rotated (doesn't normally rotate)
> * Squeeze to toggle flashlight worked
> * I kept pressing the power button
> * The screen went black
> * ~10 seconds later, the crDroid startup animation played
> * It made me enter the pin saying "PIN required after device restarts"
> * I unlocked, went to settings, and up time was 10hr, which means that the phone did not restart. The blue charging light indicator on the phone also never turned off, more evidence that the phone didn't restart
>   So unfortunately I have the same issue on crDroid as I did with LineageOS. I am not sure if it is related to the memory leak.
> 
> Here is my issue on LineageOS: https://gitlab.com/LineageOS/issues/android/-/issues/7444. And https://gitlab.com/LineageOS/issues/android/-/issues/7383.
> 
> > Format data and try again, I don't see these, nor do many other users
> 
> So idk why this is happening to my specific phone. Maybe it's a different problem, like a hardware problem?

Sounds like a different issue 
Could be related but I have never had anything like that happen 

Ever since the framework rebase more apps have been running in the background even though allow background is toggled off for some of them. Seems like apps just do what they want since the rebase.
Since memory usage is higher by default due to more apps running in the background could be something to do with your issue. 

Have you checked average memory usage for systemui in developer settings -> memory -> apps

**Comment by ChocolateLoverRaj** [comment]
> Have you checked average memory usage for systemui in developer settings -> memory -> apps

When I do that, all I see is "Android OS" with 2.6GB used. (Phone has 4GB total).

Also I would have to continuously log the memory usage to find out because I can't predict when the problem will happen.

**Comment by Hellohi3654** [comment]
> > Have you checked average memory usage for systemui in developer settings -> memory -> apps
> 
> When I do that, all I see is "Android OS" with 2.6GB used. (Phone has 4GB total).
> 
> Also I would have to continuously log the memory usage to find out because I can't predict when the problem will happen.

That memory view is average memory for me systemui is at the top with 1.6gb even though I restart systemui whenever ui starts to become laggy from memory leak which is at about 1.2gb. Android OS is second at 1.4gb so seems it's quite high for you. Can you see systemui if you scroll down or is it not there at all

**Comment by ChocolateLoverRaj** [comment]
I can see "System UI" memory usage now. I'm not sure why I couldn't before. It says 298MB.

**Comment by oscar-tm89** [comment]
I recently installed the latest build from October 6th and can confirm that the memory leak is still present.
The System UI process has again reached 3GB of usage, crashing the system, it happened while watching multimedia content as it normally happens to me. This multimedia content is played simultaneously between Firefox browser and YouTube videos.After a while of playing, when closing one of the applications and returning to the previous one (from YouTube to Firefox) the processes start to close due to memory collapse.

**Comment by w568w** [comment]
**Update** I found a **reliable method to reproduce the memory leak immediately**:

1. Navigate to the light/dark mode toggle in the settings.
2. Check the memory usage of SystemUI.
3. Toggle the mode switch.
4. Observe that SystemUI memory usage immediately increases by approximately 0.4GB and does not decrease afterward.

By repeating these steps, I managed to make SystemUI consume over 5GB of memory, at which point it froze and restarted automatically.

Additionally, I can confirm that the automatic light/dark mode switching is a major contributor to the leak. Every morning, when the phone switches to light mode, SystemUI always takes up around 1.2GB of memory.

**Comment by ChocolateLoverRaj** [comment]
I toggled dark mode mode a bunch of times on my pixel 5 (redfin) and the system UI memory usage did not increase. I was not having this issue on it so I think this bug does not affect redfin. I will try those steps on my pixel 2 xl (taimen), which does have system UI restarts.

**Comment by TheRealGramdalf** [comment]
I will add that I don't use the light/dark switchet (I'm permanently dark), but I still get the leak. Not sure if that's helpful or not but it's there.

**Comment by ChocolateLoverRaj** [comment]
Same with me. Always on dark mode.

**Comment by TheRealGramdalf** [comment]
Also can confirm, switching on and off dark mode in the Oct 13 build causes the ui to stutter and the memory usage to go up by ~200-300 MB. Using the restart menu to restart SystemUI brings the total free to about 3.8G

**Comment by w568w** [comment]
> I don't use the light/dark switchet (I'm permanently dark), but I still get the leak

@TheRealGramdalf 

1. Can you confirm that following my steps will *NOT* trigger the leak?
2. What is the phone model you are using? So far, I have only reproduced with the steps on my own LMI (and on the devices of other users in the LMI Telegram group).

> Same with me. Always on dark mode.

@ChocolateLoverRaj 

I think the dark mode toggling is just a triggering factor. Switching between light/dark modes almost certainly triggers a lot of system UI components rebuilding, re-rendering and something like that. Maybe it is these things that cause the memory leak.

**Comment by TheRealGramdalf** [comment]
I can check tomorrow on a pixel 8 pro running the latest CrDroid available as well, but I don't think it's been affected. If someone can give me a build number/commit that is known to be working I can start on the task of hunting through git diff etc. I may also try and see if I can get Android studio to run a crdroid build in an emulator, see if I can get any insight from that.

**Comment by ChocolateLoverRaj** [comment]
Idk about commit but I was using taimen on LineageOS with the 29 of march update without the system ui crashing. Then when I updated LineageOS in July the bug happened.

**Comment by oscar-tm89** [comment]
I can confirm that the memory leak is directly related to switching from light to dark theme.
I have reproduced what you have commented and the consumption has skyrocketed just by activating and deactivating the dark theme until the process collapsed and restarted.
I'm currently using the latest CrDroid build, 10.9 (20241013) and my device is a OnePlus 7 Pro (guacamole).

**Comment by walkonbothsides** [comment]
> @neobuddy89 @gwolf2u @raystef66 After closely observing for more than 1.5 day on two different devices including 1+ 6T, i think found the issue, which is leading to daily slow rise in SystemUI memory leak (except leaking due to changing theme color issue which may or may not be linked to below).
> 
> UDFPS's Custom icon and Animations are the cause. In that observation i also found new bug related to UDFPS, will explain one by one:
> 
> **Issue 1**:
> 
>     * if we enable custom icon(less probability) and custom animation(very high probability for memory leak) of UDFPS then it leads to SystemUI memory leak.  leaks goes till RAM full(in approximate 2 to 3 days).
> 
>     * on default UDFPS icon and animation, SystemUI process remains in range of 400 +-50MB
> 
> 
> **Issue 2**(seems independent for now but underlying code might be related):
> 
>     * if we use default UDFPS icon the FP doesn't unlock while flashlight is on. it  keeps on animating (seems like either flashlight overlay obstructing it or FP registering mechanism is failing).
> 
>     * as soon i select any custom UDFPS icon the FP starts working while flashlight is active.
> 
>     * 6T doesn't have this issue but faced on Dubai (could be only newer biometric hals/code impacted).
> 
>     * while logging steps performed:
>       default icon selected > turn flash on > turn on screen > try FP(keep animating) > turn flash off  > retry  FP(works) > select  custom icon > turn on Flash > turn on screen > try FP(works).
>       [FP-behaviour-on_default_and_custom-icon.log](https://github.com/user-attachments/files/16921809/FP-behaviour-on_default_and_custom-icon.log)
> 
> 
> **Issue 3**:
> 
>     * when Feature Flags in Developer Option are set to  default i.e. specifically  settings_biometrics2_enrollment and settings_biometrics2_fingerprint set to disabled then on enrollment screen  'Do i later' cover up bottom half UDFPS icon. but enrollment process is not impacted. it is just UI.
>       ![disabledFeatureFlags](https://private-user-images.githubusercontent.com/127391704/365431029-4b6c3b5d-b59d-4304-a3f7-933da19f09c0.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzg0NDcsIm5iZiI6MTczMTEzODE0NywicGF0aCI6Ii8xMjczOTE3MDQvMzY1NDMxMDI5LTRiNmMzYjVkLWI1OWQtNDMwNC1hM2Y3LTkzM2RhMTlmMDljMC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwNzQyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05N2QyNjYyYmViYjMxMDI2Mjc5ZjYzMTM1NmNmMWM1NDFiNDVkODA3MmM4MTgxY2VlNWM5OTFjOWYyZjBiZmUyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Fq66kC5Bt5Eqc2IDOUTKwFLgr9q_FEVsF01uyma-Rno)
> 
>     * if settings_biometrics2_enrollment and settings_biometrics2_fingerprint are set to enabled then enrollment screen is perfect.
> 
>     * for this as well 6T doesn't have this issue but faced on Dubai (could be only newer biometric hals/code impacted).
>       ![enabledFeatureFlags](https://private-user-images.githubusercontent.com/127391704/365431034-19dda21e-bce2-42b2-bb16-5ebbdba9fe89.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExMzg0NDcsIm5iZiI6MTczMTEzODE0NywicGF0aCI6Ii8xMjczOTE3MDQvMzY1NDMxMDM0LTE5ZGRhMjFlLWJjZTItNDJiMi1iYjE2LTVlYmJkYmE5ZmU4OS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQwNzQyMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMmEzOWExODVkYzdhMmYxZjFjNWM0ZDIwOGZhOTI0ZDEyMDVhMjA0ODNhMThkMzUzNDM3YTJiYzMxNzcwNzJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.5tceZSNOkwh5xgTurnluYmu81xSAMr-4YHgCE_GrEE8)

A few minutes after turning UDFPS to NONE, com.android.systemui regained its normal memory usage.

**Comment by neobuddy89** [comment]
@walkonbothsides UDFPS icons or animations or both?

**Comment by walkonbothsides** [comment]
> @walkonbothsides UDFPS icons or animations or both?

Only animations, I can't find where to change my UDFPS icons.

**Comment by neobuddy89** [comment]
@walkonbothsides have addressed memory leaks in UDFPS animation.

**Comment by w568w** [comment]
I can confirm that this issue has been mostly fixed after Nov 15 update of crDroid 10.9. Thanks for all your efforts!

Before:

- At startup: ~800 MB
- In daily use: ~850 MB
- Switching between light/dark mode: +400 MB per toggling, will never decrease until restarting SystemUI

After:

- At startup: ~250MB
- In daily use: 480~650 MB
- Switching between light/dark mode: +50MB per toggling, quickly dropped back to ~540 MB after several toggles

**Comment by raystef66** [comment]
@Zachhambo  Tried latest LMI as well to confirm?
https://xdaforums.com/t/rom-14-0-official-lmi-crdroid-v10-9-15-11-2024.4640996/post-89807264

@w568w Thx for the feedback. Try to keep an eye on it though for a few days and report back.

**Comment by gwolf2u** [comment]
according to reports, this is now fixed so closing
please re-open new ticket if happening still on crDroid version 10.10 or higher
