### ISSUE TITLE
bug: screenoff FOP not working

### ISSUE THREAD

**Issue by MeguminKato** [crdroidandroid/issue_tracker#48]
### Issue type

Feature not working as intended

### Device

lemonade

### crDroid version

crDroid 9

### Exact version

9.0-20221118,9.0-20221125

### Bug description

"screenoff FOP" switch in lockscreen settings can't enable,is this a bug or something wrong?

### Steps to reproduce

enable screenoff FOP in "Display" ->  "lockscreen settings" , and then go back,it will not enable

### Relevant log (logcat/build log)

```shell
nothing
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this option should no be available
@neobuddy89 
config_supportScreenOffUdfps is not set (did grep dt and common dt) and yet the option is available for some reason
https://github.com/crdroidandroid/android_packages_apps_crDroidSettings/blob/13.0/src/com/crdroid/settings/fragments/lockscreen/UdfpsSettings.java#L72
and hints?

**Comment by MeguminKato** [comment]
is this function available on the future? i tried pixelextend A13,this function is worked
