### ISSUE TITLE
bug: tik tok videos in blue and pinterest won't open with gmail

### ISSUE THREAD

**Issue by NormanG03** [crdroidandroid/issue_tracker#480]
### Issue type

Other

### Device

A71

### crDroid version

crDroid 10

### Exact version / Build date

10.6

### Bug description

Some tik tok videos turn the whole background blue and when you leave a video for a long time the same thing happens and you can't enter some applications like pinterest with gmail, mathgapps or whatever it's called has errors and it doesn't let you install and I installed nickgapps and those do let you

### Steps to reproduce

??

### Relevant log (logcat/build log)

```shell
??
```

### Screenshots or videos

??

### Solution

??

### Additional context

??

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
please update to latest 10.7 and submit logcat if still an issue

**Comment by Haky86** [comment]
@NormanG03 what about other apps? I don't have tiktok lol

**Comment by neobuddy89** [comment]
This was fixed as reported in sweet device.
