### ISSUE TITLE
bug: title Battery drain and Slow charging 

### ISSUE THREAD

**Issue by Abhishek0008000** [crdroidandroid/issue_tracker#484]
### Issue type

Other

### Device

Raphael

### crDroid version

crDroid 10

### Exact version / Build date

10.6/2024-07-05

### Bug description

On crdroid 10.6 
Charging takes approx 6 hours 
And some battery drain issue there

### Steps to reproduce

Charging issue 

### Relevant log (logcat/build log)

```shell
08-11 15:53:17.207 W/HidlServiceManagement(20637): Waited one second for android.hardware.nfc@1.2::INfc/default
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
please update to latest 10.7 and submit logcat if still an issue
