### ISSUE TITLE
bug: left padding issue on sttbar

### ISSUE THREAD

**Issue by Lordlight0** [crdroidandroid/issue_tracker#486]
### Issue type

User interface

### Device

RMX1971

### crDroid version

crDroid 10

### Exact version / Build date

10.7/2024-08-24

### Bug description

left padding issue on status bar, please fix it, sir

### Steps to reproduce

It on status bar, sir

### Relevant log (logcat/build log)

```shell
log is unnecessary as I think
```

### Screenshots or videos

![6190242609339941550](https://github.com/user-attachments/assets/86a37458-a621-439d-9a9f-de9c6d901a69)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
RMX1971 is not officially supported on 10.x so no way to contact device maintainer to assist on a fix
