### ISSUE TITLE
bug: VPN profiles not installing on CrDroid v7.2 Galaxy note 3

### ISSUE THREAD

**Issue by languagemaniac** [crdroidandroid/issue_tracker#49]
### Issue type

Feature not working as intended

### Device

SM-N9005

### crDroid version

crDroid 7

### Exact version

7.2 official

### Bug description

I tried [Cloudflare warp](https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone). When I click on the tab, a message pops up saying that it needs to install a vpn profile, and then it should activate, but it's not doing so.  The same app is working nicely in a couple of other more modern samsung devices I have running official android, so I know the app itself works.

### Steps to reproduce

1. Install [cloudflare warp](https://play.google.com/store/apps/details?id=com.cloudflare.onedotonedotonedotone)
2. Touch the orange tab
3. Click Ok on the notification that pops up saying that it needs to install a vpn profile
4. The tab should activate, but it doesn't. If you touch it again, it will try to activate but it's going to give you an error.

### Relevant log (logcat/build log)

```shell
Don't have any more info, not sure if I selected the right type of issue. Sorry about that
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
no longer maintained device

**Comment by languagemaniac** [comment]
> no longer maintained device

Oh sorry about this, I thought it was
