### ISSUE TITLE
camera issue

### ISSUE THREAD

**Issue by MikeSaya1** [crdroidandroid/issue_tracker#490]
### Issue type

User interface

### Device

OP11 Salami

### crDroid version

crDroid 10

### Exact version / Build date

08/18/2024

### Bug description

Camera doesn't work.  This commit will resolve issue.
https://github.com/MikeSaya1/android_device_oneplus_sm8550-common

### Steps to reproduce

apex problem resolved, recommend commit change to crDroid source

### Relevant log (logcat/build log)

```shell
issue in device/oneplus/sm8550
camera issue
resolved with: https://github.com/MikeSaya1/android_device_oneplus_sm8550-common
```

### Screenshots or videos

https://github.com/MikeSaya1/android_device_oneplus_sm8550-common

### Solution

https://github.com/MikeSaya1/android_device_oneplus_sm8550-common

### Additional context

https://github.com/MikeSaya1/android_device_oneplus_sm8550-common

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
official will be posted soon.
