### ISSUE TITLE
Not all QS Icons are changing.

### ISSUE THREAD

**Issue by fauyds** [crdroidandroid/issue_tracker#492]
### Issue type

Source code related

### Device

OnePlus 7T Pro (hotdog)

### crDroid version

crDroid 10

### Exact version / Build date

Version: 10.7
Date: 2024-08-20

### Bug description

The quick settings icons that came from Android 11, are not changing.

### Steps to reproduce

Go to crDroid Settings > User Interface > Icon Packs > Choose any icon pack from the screenshot.

![photo_2024-08-21_00-44-55](https://github.com/user-attachments/assets/46e6e6fe-6bdb-4ede-8e49-144e6151b8bc)

### Relevant log (logcat/build log)

```shell
No log required for this.
```

### Screenshots or videos

![Screenshot_20240820-092916_Settings](https://github.com/user-attachments/assets/d82bffcf-5b0a-4577-99f0-12e96cccd933)
![Screenshot_20240820-092923_Settings](https://github.com/user-attachments/assets/1967e292-2445-4368-b62e-684b11b92499)
![Screenshot_20240820-092934_Settings](https://github.com/user-attachments/assets/54bcc848-bf07-41bb-87a9-1b85c50b95ec)
![Screenshot_20240820-092943_Settings](https://github.com/user-attachments/assets/2921ae1e-11a5-48b3-8065-b5ca75633f6c)
![Screenshot_20240820-093001_Settings](https://github.com/user-attachments/assets/967093e2-69c8-4a86-baf6-93e2f3619f4c)
![Screenshot_20240820-093010_Settings](https://github.com/user-attachments/assets/6dbdeb8a-6bd5-4d0f-8c58-3f17a35eec9a)
![Screenshot_20240820-093018_Settings](https://github.com/user-attachments/assets/548c70b3-9056-4e70-8f2b-a51d40b4bf3a)
![Screenshot_20240820-093548_Settings](https://github.com/user-attachments/assets/9b4606fd-70b6-411a-91a3-b65751f1327e)
![Screenshot_20240820-092858_Settings](https://github.com/user-attachments/assets/0eecf13e-3b8a-4184-9087-ab889c96d7d5)
![Screenshot_20240820-092909_Settings](https://github.com/user-attachments/assets/cbbeb987-4bdf-4bc2-93a4-52d929d11d61)

### Solution

Take fixed icons from Project Elixir ROM
Or edit the source of each icon pack manually.

### Acknowledgements

- [x] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ShevT** [comment]
@gwolf2u, @neobuddy89 We need to check it somehow, but I don't see a problem for myself.

**Comment by gwolf2u** [comment]
happening after restarting SystemUI also?

**Comment by fauyds** [comment]
> happening after restarting SystemUI also?

Yeah
