### ISSUE TITLE
bug: screenshot swiping three fingers not working

### ISSUE THREAD

**Issue by karlitozebc** [crdroidandroid/issue_tracker#494]
### Issue type

User interface

### Device

Ginkgo - redmi note 8

### crDroid version

crDroid 10

### Exact version / Build date

Version 10.7, build 19/08/2024

### Bug description

screenshot swiping three fingers not working

### Steps to reproduce

No

### Relevant log (logcat/build log)

```shell
No
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
This was fixed yesterday.

https://github.com/crdroidandroid/android_frameworks_base/commit/d9b463a2a8a33d4198a3762b5143918ad66e7e4e
