### ISSUE TITLE
CrDroid 10.7, notifications activate screen once but didn't repeat

### ISSUE THREAD

**Issue by lanmaster** [crdroidandroid/issue_tracker#495]
### Issue type

Feature not working as intended

### Device

Redmi Note 13 Pro 5G

### crDroid version

crDroid 10

### Exact version / Build date

10.7

### Bug description

Notifications on locked screen didn't repeat, screen activated only once.

### Steps to reproduce

In Settings enabled Active Screen, side lights and repeat animations.
Notifications activate screen only once and didn't repeat it. 

### Relevant log (logcat/build log)

```shell
No logs
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by JYRRC** [comment]
Hello, I have checked and I do not have the error, have you checked the screen lock screen settings on the device? We also have an ambient screen there, check the options, maybe you are leaving something unchecked, I await your verifications, thank you for using crdroid and sorry for the inconvenience

**Comment by lanmaster** [comment]
Hi. I checked it again. Can you list all options over settings menu path that i need to check? And one more time detailed description:
- phone on table, locked;
- it receive notification, activate screen where i can see app which receive notification. Also left and right lighting see on screen;
- after about 5 sec screen is off;
- no more repeated screen on occured;
-

**Comment by JYRRC** [comment]
Is there a possibility that I can show you this test on Telegram?

**Comment by lanmaster** [comment]
> Is there a possibility that I can show you this test on Telegram?

Yeah. @lanmaster323 tg

**Comment by JYRRC** [comment]
Hello again, how are you? I have checked it again and even now it still works better in the latest version because I made adjustments in the ambient screen, I thought it was no longer a problem, no user has reported the error to me and on my device and other users it is working, I want to help you but the error does not exist for me

**Comment by lanmaster** [comment]
Thanks, i will test it

**Comment by lanmaster** [comment]
It is ok. Thank you!
