### ISSUE TITLE
Pixel 8A - Face Unlock setup crash

### ISSUE THREAD

**Issue by rikuddo91** [crdroidandroid/issue_tracker#496]
### Issue type

Feature not working as intended

### Device

Pixel 8A (akita)

### crDroid version

crDroid 10

### Exact version / Build date

CrDroid 10.7

### Bug description

When trying to setup Face Unlock, when it try to open camera app for face scan, it immediately crashes.

### Steps to reproduce

Device Unlock -- Setup Face Unlock 

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/HS6Lf7
```

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
which gapps

**Comment by rikuddo91** [comment]
> which gapps

NikGapps-full-pixels-arm64-14-20240813-signed

**Comment by ionutgherman** [comment]
Known issue. Will be fixed with next update

**Comment by ionutgherman** [comment]
Fixed. Update to latest update available
