### ISSUE TITLE
bug: Zygote process not stopping after app is closed

### ISSUE THREAD

**Issue by Hellohi3654** [crdroidandroid/issue_tracker#501]
### Issue type

User interface

### Device

OnePlus 7T Pro (hotdog)

### crDroid version

crDroid 10

### Exact version / Build date

10.7/20240826

### Bug description

Zygote process stays forever for some apps until killed in an app like 3c task manager. This slowly fills up memory. Could be a zygisk next bug I'm using latest 1.1.0 on kernelsu. Could be related to systemui memory leak, started happening around same time. 

### Steps to reproduce

1. Open chrome, momo or native test 
2. Close app and clear from recents
3. Open app again after 10 seconds 
4. There will be two zygote processes 

### Relevant log (logcat/build log)

[2024-08-27-12-14-25.txt](https://github.com/user-attachments/files/16755571/2024-08-27-12-14-25.txt)

Native test log

### Screenshots or videos

![Screenshot_20240827-120226_3C Task Manager](https://github.com/user-attachments/assets/a50382db-7af1-486f-985c-12a727a62087)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
track in https://github.com/crdroidandroid/issue_tracker/issues/478
