### ISSUE TITLE
bug: Three fingers swipe for screenshot (or any other option) not working

### ISSUE THREAD

**Issue by kicaBo** [crdroidandroid/issue_tracker#502]
### Issue type

Feature not working as intended

### Device

Redmi Note 8/8T
Ginkgo / Willow

### crDroid version

crDroid 10

### Exact version / Build date

crDroidAndroid-14.0-20240826-ginkgo-v10.7

### Bug description

Three fingers swipe for screenshot not working. Nothing hapened when choosed and try out.

### Steps to reproduce

Step 1 - Goto crDroid Settings
Step 2 - Choose Miscellaneous
Step 3 - Tap Three fingers swipe
Step 4 - Choose and tap on Taka screenshot
Step 5 - Swipe to take screenshot on any windows, but nothing happens

### Relevant log (logcat/build log)

```shell
*** Cant get LOG, nothing happened ***
```

### Additional context

Seems that Three finger swipe in global is not a functional option.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
this is working.  wait for updated build.

**Comment by kicaBo** [comment]
New build - https://sourceforge.net/projects/crdroid/files/ginkgo/10.x/crDroidAndroid-14.0-20240830-ginkgo-v10.7.zip
Issue still exist :(

**Comment by gwolf2u** [comment]
Can't confirm 
Disable 3 finger screenshot option and check if still happening

**Comment by kicaBo** [comment]
Same for another user - https://xdaforums.com/t/rom-official-ginkgo-14-crdroidandroid-v10-x.4644282/page-12#post-89687561
