### ISSUE TITLE
Ambient display time feature request

### ISSUE THREAD

**Issue by jakubalex47** [crdroidandroid/issue_tracker#506]
### Issue type

Feature not working as intended

### Device

Dipper

### crDroid version

crDroid 10

### Exact version / Build date

10.7 and below

### Bug description

It's probably not a bug but a feature request. When ambient display for notifications enabled, ambient notification time is only ~4 seconds so you cannot even read the text of the notification. Please increase ambient display time or add option to choose notification time.
Also would be good to apply the same option when notification appears in normal lockscreen. It's something like "Set how much time (ambient) display is on when notification wakes up the screen"

### Steps to reproduce

None

### Relevant log (logcat/build log)

```shell
None
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
for now we use standard notification timeout from android
no such feature is planned
