### ISSUE TITLE
Issue with SanDisk SD Card

### ISSUE THREAD

**Issue by RookieOneYt** [crdroidandroid/issue_tracker#507]
### Issue type

Source code related

### Device

Poco M2 Pro (miatoll)
![Screenshot_20240903-083625_Settings](https://github.com/user-attachments/assets/8f5c2817-80f0-4ee2-9a5a-a98937dfe360)

### crDroid version

crDroid 10

### Exact version / Build date

10.7/any

### Bug description

sd card not working... there's a notification after every reboot + same with roms using CrDroid as base (ex: rising)

### Steps to reproduce

notification after every reboot

### Relevant log (logcat/build log)

```shell
I've log file... didn't understand what to copy/ paste.
```

### Screenshots or videos

![990](https://github.com/user-attachments/assets/49b6aa65-3f8b-42b6-8815-94ccb1962eab)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
run adb logcat > log.txt in terminal with phone connected to PC
reproduce the issue
close terminal
attach log.txt file here in comment textbox (can drag-n-drop)
