### ISSUE TITLE
bug: Bluthooth active but not connecting to devices

### ISSUE THREAD

**Issue by BenjaminSteimer** [crdroidandroid/issue_tracker#508]
### Issue type

User interface

### Device

ginkgo

### crDroid version

crDroid 10

### Exact version / Build date

2024-09-02

### Bug description

Bluetooth is on but cannot connect to known devices or new devices.

### Steps to reproduce

toggle the Bl, try to connect known-device, watch the it fail without error message.

### Relevant log (logcat/build log)

```shell
-
```

### Screenshots or videos

![Screenshot_20240903-180006_Kiwi Browser](https://github.com/user-attachments/assets/1b798868-f5c4-4103-9443-b79bc1d15ac0)

### Solution

None

### Additional context

None

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
logcat needed

**Comment by DarkJoker360** [comment]
A logcat is required to understand what's wrong.
