### ISSUE TITLE
bug: USB-C to 3.5mm Adapter Not Working on Custom ROM, but Functional on Stock ROM" 

### ISSUE THREAD

**Issue by darsaliq00** [crdroidandroid/issue_tracker#509]
### Issue type

Other

### Device

OnePlus 11 (Salami)

### crDroid version

crDroid 10

### Exact version / Build date

CrDroid 10.7/2024-08-31

### Bug description

The USB-C to 3.5mm female adapter isn't working, but it functions correctly with the stock ROM. I tested USB-C earphones, and they work fine. The issue seems to be with only adapters , not the type C earphones.
Whenever i used adapter audio comes from phone speaker 
Note: i used 3 different types of adapters and the one that works on samsung device (usually most adapter doesn't work on samsung devices) none of them works

### Steps to reproduce

Plug in usb c to 3.5mm adapter 
And listen to music 
Phone speakers will work
Not the earphones 

### Relevant log (logcat/build log)

```shell
I cant take logcat of this issue as adapter isn't detecting in phone
```

### Solution

There was same issue with my previous phone changing kernel solved this issue maybe there are missing audio drivers in this build

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
working fine. tested on 10.8.
