### ISSUE TITLE
bug: big text

### ISSUE THREAD

**Issue by bphd** [crdroidandroid/issue_tracker#51]
### Issue type

User interface

### Device

RealMe (RMX3171) 

### crDroid version

crDroid 9

### Exact version

9

### Bug description

Big text

### Steps to reproduce

Install

### Relevant log (logcat/build log)

```shell
Where
```

### Screenshots or videos

![Screenshot_20221127-185721_‎‏‎‎‎‎‎‏‎‏‏‏‎‎‎ ‎‎‏‎‏ ‎‏‎‎‎‏‎‎‏‏‎‎‎‎‏‏‎‏‎‏‎‎‏‎‎‎‎‎‎‏‎‏‎‎‎‎‎Settings‎‏‎‎‏‎](https://user-images.githubusercontent.com/10251866/204298212-eef7b395-95f9-4e77-b9aa-4729f45b35ff.png)

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
try changing DPI

**Comment by bphd** [comment]
> try changing DPI

![image](https://user-images.githubusercontent.com/10251866/205611874-ae4c1817-a14b-4f8a-a48e-f31f3366d524.png)

**Comment by gwolf2u** [comment]
> > try changing DPI
> 
> ![image](https://user-images.githubusercontent.com/10251866/205611874-ae4c1817-a14b-4f8a-a48e-f31f3366d524.png)

screen size under display

**Comment by bphd** [comment]
> > > try changing DPI
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/10251866/205611874-ae4c1817-a14b-4f8a-a48e-f31f3366d524.png)
> 
> screen size under display

![image](https://user-images.githubusercontent.com/10251866/205631965-4e832de8-9fed-4b3a-a89e-e231811f74d6.png)

**Comment by gwolf2u** [comment]
since unofficial, we have no way to test this and help device maintainer
so for now closing this

**Comment by bphd** [comment]
I want to help debug that. Where can I search the problem?

**Comment by gwolf2u** [comment]
ask maintainer to build with latest code

**Comment by bphd** [comment]
The problem is here since more than 5 minor versions. Nothing has been reported since. It will be the same. We should try to search for root cause instead

I'm on 8.12 for now
