### ISSUE TITLE
Disable camera access not working

### ISSUE THREAD

**Issue by ZuoRd** [crdroidandroid/issue_tracker#510]
### Issue type

Feature not working as intended

### Device

Xiaomi Redmi Note 9s (miatoll, curtana)

### crDroid version

crDroid 10

### Exact version / Build date

10.7/2024-09-02

### Bug description

Camera still accessible after disabling access via Quick Settings

### Steps to reproduce

Disable camera access, open any camera app and see it's still accessible 

### Relevant log (logcat/build log)

```shell
Not available
```

### Screenshots or videos

https://github.com/user-attachments/assets/494d8ef5-90e2-4e6a-ae05-a524be1c7be1

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [x] I filled out all of the requested information in this issue properly.

**Comment by ZuoRd** [comment]
Just updated to 10.8, the problem still exists, here's the logcat

[Log_2024-9-10_01-03-40.txt](https://github.com/user-attachments/files/16937477/Log_2024-9-10_01-03-40.txt)

**Comment by ZuoRd** [comment]
Just updated to 10.8, problem still exists. Here's the logcat

[Log_2024-9-10_01-03-40.txt](https://github.com/user-attachments/files/16937477/Log_2024-9-10_01-03-40.txt)

**Comment by neobuddy89** [comment]
Log is incomplete. Not able to reproduce.
