### ISSUE TITLE
WiFi 7 standard icon in status bar

### ISSUE THREAD

**Issue by Corentinrhr** [crdroidandroid/issue_tracker#511]
### Issue type

User interface

### Device

Pixel 8 pro (Husky)

### crDroid version

crDroid 10

### Exact version / Build date

crDroid 10.7, build 27 August 2024

### Bug description

Found a small display bug in the status bar : when connected to a WiFi 7 router, it only displays WiFi 6 in status bar.

### Steps to reproduce

1. Go to crDroid settings 
2. Activate "WiFi Standard" in status bar section
3. Connect to a WiFi 7 router

### Relevant log (logcat/build log)

```shell
No log
```

### Screenshots or videos

![Screenshot_20240909-150104_Settings~2](https://github.com/user-attachments/assets/5739ab4f-8102-4042-9757-184e815e91f5)

### Solution

Add WiFi 7 standard icon for status bar ?

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Think AOSP only knows about WiFi 6 currently, even if connection works on 7
Reason no icon for it
Would need to check though
