### ISSUE TITLE
bug: some google option are greyed out and cannot be enabled

### ISSUE THREAD

**Issue by El-Nice** [crdroidandroid/issue_tracker#513]
### Issue type

Feature not working as intended

### Device

Redmi 9 Lancelot 

### crDroid version

crDroid 10

### Exact version / Build date

2024/01/20

### Bug description

Some google option are greyed out and cannot enabled like the google search bar in the main screen

### Steps to reproduce

Go to settings search for any google related option

### Relevant log (logcat/build log)

```shell
Doesn't have one
```

### Screenshots or videos

![Screenshot_20240911-194237_crDroid Home](https://github.com/user-attachments/assets/15d2f7e3-c9d9-41ff-9a27-062ff2a3161f)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
install Google Search.

**Comment by El-Nice** [comment]
> install Google Search.

Wdym install google search i have downloaded all google app but i never heard abou google search can you send me a link to it
