### ISSUE TITLE
bug: recovery not updating to latest version with OTA

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/issue_tracker#515]
### Issue type

Feature not working as intended

### Device

vayu

### crDroid version

crDroid 10

### Exact version / Build date

v10.8 build 14-09-2024

### Bug description

I enabled the update recovery toggle in updater settings and updated from 8th sep build to 14th sep build via ota. but it seems recovery image not get updated in the process. it still remain on 8th sep.

### Steps to reproduce

Go to system updates > preferences > enable update recovery toggle.

then do ota update and check recovery updates to latest version or not

### Relevant log (logcat/build log)

```shell
--
```

### Screenshots or videos

![Screenshot_20240914-160227_Updater](https://github.com/user-attachments/assets/140f033c-33b4-4f2a-b551-bb70fb4dc8e0)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
This device is A/B, so recovery is part of boot.img and that is updated every time rom is updated 
Your issue may be with flashing a different boot.img (possible for magisk?)
