### ISSUE TITLE
bug: Contact images appear in negative shades 

### ISSUE THREAD

**Issue by ghost** [crdroidandroid/issue_tracker#516]
### Issue type

User interface

### Device

vayu

### crDroid version

crDroid 10

### Exact version / Build date

v10.8 build 2024-09-14

### Bug description

Some contact pfps are appearing in negative shades instead of original image.

But it appears correctly on contacts app.

### Steps to reproduce

open dialer >> contacts tab >> see contacts with pfps. (not all contacts. it appears randomly)

### Relevant log (logcat/build log)

```shell
--
```

### Screenshots or videos

![Screenshot_20240915-132836_Phone_cropped](https://github.com/user-attachments/assets/bfebbf76-d038-41fa-85c7-658e06120ed8)
![Screenshot_20240915-132836_Phone](https://github.com/user-attachments/assets/16e68e28-5a71-40e9-8726-3ad57c843724)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Can't confirm this on todays build with Contact app
You sure is not Google Contacts app?
What gapps used?
