### ISSUE TITLE
bug: dock icons not properly visible while in landscape home screen mode

### ISSUE THREAD

**Issue by gdr9725** [crdroidandroid/issue_tracker#518]
### Issue type

User interface

### Device

spacewar 

### crDroid version

crDroid 10

### Exact version / Build date

10.8

### Bug description

When turn on the home screen rotation, then turning the home screen landscape, the app-icons which normally stay on the dock, some of the apps are not visible.

### Steps to reproduce

1. Turn on home screen rotation
2. Go to home screen 
3. Tilt the phone and see it in landscape mode
4. Some icons doesnt appear properly 

### Relevant log (logcat/build log)

```shell
logs
```

### Screenshots or videos

![Screenshot_20240916-211118_crDroid Home](https://github.com/user-attachments/assets/91ec9fce-e45e-4d9f-ba1f-c94efea812f3)
![Screenshot_20240916-200737_crDroid Home](https://github.com/user-attachments/assets/38524dd3-6c74-460a-bd68-3de805bdddb1)
![Screenshot_20240916-202236_crDroid Home](https://github.com/user-attachments/assets/01512a7b-0122-491a-bf08-083ff03e875b)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
is this crDroid launcher?

**Comment by gdr9725** [comment]
> is this crDroid launcher?

Yes

**Comment by gwolf2u** [comment]
can't seem to find option to rotate launcher in landscape (probably because never cared about it 🤣 )

**Comment by gdr9725** [comment]
> can't seem to find option to rotate launcher in landscape (probably because never cared about it 🤣 ) what gapps you used?

You can find it here: Home settings by long pressing on home screen>Miscellaneous>home screen rotation.

What do you mean by what gapps I use? 😗

**Comment by gwolf2u** [comment]
There's no such option here, reason I suspect you flashed gapps (the google apps zip allowing to login with google and all google services) that replaced crDroid Home.
![Screenshot_20241006-140049_crDroid Home](https://github.com/user-attachments/assets/0f36f103-0819-4783-92fb-38719bb6aa55)

**Comment by gdr9725** [comment]
> There's no such option here, reason I suspect you flashed gapps (the google apps zip allowing to login with google and all google services) that replaced crDroid Home. ![Screenshot_20241006-140049_crDroid Home](https://private-user-images.githubusercontent.com/877292/373941125-0f36f103-0819-4783-92fb-38719bb6aa55.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTI5NzcsIm5iZiI6MTcyODIxMjY3NywicGF0aCI6Ii84NzcyOTIvMzczOTQxMTI1LTBmMzZmMTAzLTA4MTktNDc4My05MmZiLTM4NzE5YmI2YWE1NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwNlQxMTA0MzdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ZjBlYWQ2NTkyY2UyMDViNjU1Y2I4YjM4NjdlNjdmMWZhMzg4YmE5ZGJkZjhkMWQzMDZmYzkyNzU0OTA1OTM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.OMeuaKF_0FV2aoBTUNUEuCMwT8-mCcwpBjEyy_WdqCE)

It is right there, allow home screen rotation

**Comment by gdr9725** [comment]
> There's no such option here, reason I suspect you flashed gapps (the google apps zip allowing to login with google and all google services) that replaced crDroid Home.

 Here are some screen shots, if it helps 
![Screenshot_20241006-163704_Permission controller](https://github.com/user-attachments/assets/7dc90deb-1204-46dd-bebf-b7b6cdd61d44)
![Screenshot_20241006-163710_crDroid Home](https://github.com/user-attachments/assets/dc7dcb84-b5cc-4eaf-a337-baf900266c6b)

**Comment by gwolf2u** [comment]
man I feel stupid
must be tired already for replying to all those issues
yeah option is there and can confirm the issue

**Comment by gdr9725** [comment]
> man I feel stupid must be tired already for replying to all those issues yeah option is there and can confirm the issue

Yeah, it happens sometimes haha! Glad you confirmed the issue.

**Comment by neobuddy89** [comment]
Should be fixed in
https://github.com/crdroidandroid/android_packages_apps_Launcher3/commit/9870b5e435d97aabf07b912098a27b057da4515a
https://github.com/crdroidandroid/android_packages_apps_Launcher3/commit/c5e233c9f65df2b79c8df3aef91653561635a373
