### ISSUE TITLE
QS Panel page indicator jumping to the left, not staying in center

### ISSUE THREAD

**Issue by GaucovyAero** [crdroidandroid/issue_tracker#519]
### Issue type

User interface

### Device

alioth

### crDroid version

crDroid 10

### Exact version / Build date

10.8/2024-09-14

### Bug description

The QS panel page indicator jumps to the left after using the phone for a while, centering can be restored by restarting the phone or changing the dpi/screen size or any other similar setting
breaks immediately after a SystemUI restart

### Steps to reproduce

1. Restart your phone
2. Restart SystemUI and see the indicator jump to the left

### Relevant log (logcat/build log)

```shell
not applicable
```

### Screenshots or videos

![27792](https://github.com/user-attachments/assets/e3833f0c-6219-4b21-bb1e-e5357744718d)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by GaucovyAero** [comment]
Note: the indicator randomly goes back in the middle and to the left during use.

**Comment by neobuddy89** [comment]
Possible fix added.

**Comment by secretServant** [comment]
Re-opening still an issue after building for crdroid 10.9
