### ISSUE TITLE
status bar UI inconsitencies

### ISSUE THREAD

**Issue by wjtk4444** [crdroidandroid/issue_tracker#520]
### Issue type

User interface

### Device

lynx (Pixel 7a)

### crDroid version

crDroid 9

### Exact version / Build date

10.8/14.08.2024

### Bug description

1. Status bar left/right alignment.
![image](https://github.com/user-attachments/assets/1d3da8fb-68a2-4816-b257-82df9a7db2ca)
Notifications/clock on the left side are aligned differently from status bar icons on the right. With "logo" enabled they more or less align, but there's no option to choose a transparent logo icon so it looks weird still.

2. It's possible to click on statusbar clock in QS to open the Clock app, but clicking on date doesn't open the Calendar (it should, as it currently does nothing)

### Steps to reproduce

-

### Relevant log (logcat/build log)

```shell
-
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this has been fixed in source
