### ISSUE TITLE
bug: Mobile automatically switch off

### ISSUE THREAD

**Issue by Nandanmourya14** [crdroidandroid/issue_tracker#521]
### Issue type

User interface

### Device

Haydn

### crDroid version

crDroid 10

### Exact version / Build date

AP2A.240805.005

### Bug description

When i left my phone for idle for some time and do not use it for 2 or 3 hours or more and when I came back for using my phone, it is found to be switched off . Then i need to switch it on again and again .

2nd bug is  sometimes many apps crashed while using . (Not a big bug )
3rd issue is sometimes it stuck on the screen whatever happening in phone, and does not respond anything and after some time it automatically restarts (major problem ) .  When phone is stucked sometimes it shows **CrDroid home does not responds **

4th is not a Major issue but is does not support adaptive charging time option 

5th point is Thanks for doing such a hard and wonderful 😊😊 work for us for providing smooth experience while using our mobile phone 📱🤳 .

### Steps to reproduce

It stucks mainly whenever i was doing some multi tasks or playing games 

### Relevant log (logcat/build log)

```shell
N.A.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by GaucovyAero** [comment]
seems to me like you are experiencing hardware problems, try reporting this to your device maintainer instead (e. g. in an XDA thread)

**Comment by gwolf2u** [comment]
a lgocat is needed in order to fix this

**Comment by neobuddy89** [comment]
No log.
