### ISSUE TITLE
bug: QS autobrightness toggle doesn't visually change when clicked

### ISSUE THREAD

**Issue by secretServant** [crdroidandroid/issue_tracker#522]
### Issue type

User interface

### Device

Devon

### crDroid version

crDroid 10

### Exact version / Build date

10.8

### Bug description

See steps

### Steps to reproduce

Step 1. Open QS.
Step 2. Click auto brightness toggle.
Step 3. See no color change unlike other QS toggles.
Step 4. Close QS.
Step 5. Open QS.
Step 6. See auto brightness toggle changed as it was supposed to when originally clicked.

### Relevant log (logcat/build log)

```shell
nada
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
This was fixed in code already
Wait for a build update
