### ISSUE TITLE
bug: crdroid android 14 samsung a70 latest update flash light not working

### ISSUE THREAD

**Issue by alexanderoo7** [crdroidandroid/issue_tracker#523]
### Issue type

Feature not working as intended

### Device

Device sasmung a70fn

### crDroid version

crDroid 10

### Exact version / Build date

Crdroid update September, 23,2024 

### Bug description

After the latest update the flash light doesn't work ,but it Does work only when taking photo using google camera .

### Steps to reproduce

1-Swipe down quick settings  2- turn on flash

### Relevant log (logcat/build log)

```shell
.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
we don't offer support for a70fn but only for a70q
