### ISSUE TITLE
Issue- Oneplus 7T android 14 - External display not working via HDMI

### ISSUE THREAD

**Issue by Omkar-Sabharwal** [crdroidandroid/issue_tracker#524]
### Issue type

Feature not working as intended

### Device

Hello team,
My oneplus 7t was on stock android 10 before upgrading and was working fine on USB hdmi device. 
It used to charge+ run hdmi + run usb devices at the same time. I'm a streamer and before this upgrade everything was working.

After upgrade -
1) It shows popup to mirror the screen and does nothing.
2) USB devices like mouse and keyboard works but I noticed that it doesn't connect some usb port and works when reconnected
3) If a charger is connected, the device is disconnected and reconnected in every 5-10 seconds. And every time screen mirror request pop ups. 

Device I used to test
1) Pibox usb c hub
2) CableCreation usb hub

I find Crdroid a best solution for using older device like op 7t smoooth. I will not go back to stock ones. If this is fixed then I think its the best solution in the market.
 

### crDroid version

crDroid 10

### Exact version / Build date

10.8/2024-9-19

### Bug description

Details shared in main description 

### Steps to reproduce

Connect a usb c hub with a hdmi >usb works with no display 
Connect a usb c hub with charger> disconnects the usb hub in 5-10 secs

### Relevant log (logcat/build log)

```shell
N/A
```

### Acknowledgements

- [x] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
logcat needed
