### ISSUE TITLE
bug: Google sign-in crashes on devices without camera

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [crdroidandroid/issue_tracker#525]
### Issue type

Other

### Device

Nintendo Switch (nx_tab)

### crDroid version

crDroid 10

### Exact version / Build date

10.8/2024-09-16

### Bug description

On devices that lack cameras, such as the Nintendo Switch, when attempting to sign into a Google account, the sign-in crashes due to the lack of camera. This bug isn't present in LineageOS, so I think it's safe to say it's a bug in crDroid itself and not the device source. This issue is present when using either GApps or microG. Sometimes, you may get a message saying "Google Play Services keeps stopping"/"microG Services keeps stopping"

### Steps to reproduce

1. Download any app that supports Google signin
2. Attempt signing in to Google
3. After a few seconds, sign-in crashes.

### Relevant log (logcat/build log)

```shell
time: 1726770847010
msg: java.lang.NullPointerException: Attempt to get length of null array
stacktrace: org.chromium.base.JniAndroid$UncaughtExceptionException: Native stack trace:
#00 pc 0x0000000004146737 /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#01 pc 0x0000000002c4c0fb /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#02 pc 0x00000000052cd66b /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#03 pc 0x000000000784f11f /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#04 pc 0x0000000005b9c28f /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#05 pc 0x0000000005ba3093 /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#06 pc 0x0000000005ba2943 /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#07 pc 0x00000000052d26a7 /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#08 pc 0x0000000002d0202b /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#09 pc 0x0000000002d00fdf /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#10 pc 0x0000000002d0182b /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#11 pc 0x0000000002cfe9c7 /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#12 pc 0x0000000002cfe05f /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#13 pc 0x0000000002d00e43 /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#14 pc 0x0000000002cfeec7 /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#15 pc 0x0000000002cfd3b7 /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#16 pc 0x0000000002c1243b /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#17 pc 0x0000000002c11baf /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#18 pc 0x0000000002ac8c73 /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#19 pc 0x00000000041f4bb3 /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#20 pc 0x0000000002ac8677 /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#21 pc 0x0000000002c14dc3 /data/app/~~Lsf_l7Sy0gbFPYp2U7sMPg==/com.google.android.trichromelibrary.canary_672500033-WU-nYSUWFW3AmChGKVoBXA==/base.apk (offset 0x8dc000)
#22 pc 0x0000000000067fab /apex/com.android.runtime/lib64/bionic/libc.so
#23 pc 0x000000000005b217 /apex/com.android.runtime/lib64/bionic/libc.so

	at org.chromium.base.JniAndroid.handleException(chromium-TrichromeWebViewGoogle6432.aab-canary-672500033:21)
Caused by: java.lang.NullPointerException: Attempt to get length of null array
	at org.chromium.media.VideoCaptureFactory.getNumberOfCameras(chromium-TrichromeWebViewGoogle6432.aab-canary-672500033:23)
```

### Screenshots or videos

https://github.com/user-attachments/assets/e0de156a-64d4-4157-99c5-5b30be820af8

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
this seems to google crash. try different gapps

**Comment by Lost-Entrepreneur439** [comment]
crash occurs no matter what gapps is being used (and occurs with microG too, confirming this isnt a gapps issue)

**Comment by Lost-Entrepreneur439** [comment]
> share complete log.
[logcat.txt](https://github.com/user-attachments/files/17175912/logcat.txt)

**Comment by gwolf2u** [comment]
try building without face unlock

**Comment by Lost-Entrepreneur439** [comment]
> try building without face unlock

I already have "TARGET_FACE_UNLOCK_SUPPORTED := false" in my lineage-nx_tab.mk, would there be something else I need to add to disable face unlock?

**Comment by neobuddy89** [comment]
@Lost-Entrepreneur439 have added a fix in 
https://gitlab.com/crdroidandroid/android_packages_apps_FaceUnlock/-/commit/c97ae1aeb90a90ae1e75f131ac20740cc0f15d9c

Let know if issue persist

**Comment by Lost-Entrepreneur439** [comment]
may be a few weeks before i can test -- busy with some personal things as of right now, will test when i'm able to

**Comment by Lost-Entrepreneur439** [comment]
> @Lost-Entrepreneur439 have added a fix in https://gitlab.com/crdroidandroid/android_packages_apps_FaceUnlock/-/commit/c97ae1aeb90a90ae1e75f131ac20740cc0f15d9c
> 
> Let know if issue persist

Issue is still present.

**Comment by gwolf2u** [comment]
try with 10.9
this has been merged
https://github.com/crdroidandroid/android_vendor_crdroid/commit/7de94870063e1c559445b7887b1024f732e9ad36

**Comment by Lost-Entrepreneur439** [comment]
> try with 10.9 this has been merged [crdroidandroid/android_vendor_crdroid@7de9487](https://github.com/crdroidandroid/android_vendor_crdroid/commit/7de94870063e1c559445b7887b1024f732e9ad36)

This did fix the "face unlock keeps stopping" message on startup, but Google sign in still crashes.

**Comment by gwolf2u** [comment]
send clean logcat

**Comment by Lost-Entrepreneur439** [comment]
> send clean logcat

[logcat.txt](https://github.com/user-attachments/files/17359599/logcat.txt)

**Comment by gwolf2u** [comment]
there are lots of GMS avc denials
also something complaining on webview

booting permissive does something?
suspecting gapps issue, but idk yet
can't see anything specific to crDroid, maybe 
```
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: Failed to set prop TIME
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: java.lang.IllegalArgumentException: field android.os.Build.TIME has type long, got java.lang.String
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at java.lang.reflect.Field.set(Native Method)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at com.android.internal.util.crdroid.PixelPropsUtils.setPropValue(PixelPropsUtils.java:439)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at com.android.internal.util.crdroid.PixelPropsUtils.setPropValue(PixelPropsUtils.java:425)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at com.android.internal.util.crdroid.PixelPropsUtils.setProps(PixelPropsUtils.java:309)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1356)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1399)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7368)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.os.Handler.dispatchMessage(Handler.java:107)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.os.Looper.loopOnce(Looper.java:232)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.os.Looper.loop(Looper.java:317)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.ActivityThread.main(ActivityThread.java:8601)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at java.lang.reflect.Method.invoke(Native Method)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
```
yet no idea why happening only with you

**Comment by Lost-Entrepreneur439** [comment]
I tried with SELinux set to Permissive, issue still occurs. 

The GMS denials may be coming from the fact I use microG and not real GApps, I only know the issue happens with GApps from people on XDA and Discord telling me, with multiple different GApps packages being used. If wanted, I can factory reset and install real GApps, and take a logcat there.

**Comment by gwolf2u** [comment]
yes
do install gapps (go with Nikgapps core)

**Comment by Lost-Entrepreneur439** [comment]
> yes do install gapps (go with Nikgapps core)

here's the log with nikgapps core 
[logcat.txt](https://github.com/user-attachments/files/17360119/logcat.txt)

**Comment by neobuddy89** [comment]
> there are lots of GMS avc denials also something complaining on webview
> 
> booting permissive does something? suspecting gapps issue, but idk yet can't see anything specific to crDroid, maybe
> 
> ```
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: Failed to set prop TIME
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: java.lang.IllegalArgumentException: field android.os.Build.TIME has type long, got java.lang.String
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at java.lang.reflect.Field.set(Native Method)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at com.android.internal.util.crdroid.PixelPropsUtils.setPropValue(PixelPropsUtils.java:439)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at com.android.internal.util.crdroid.PixelPropsUtils.setPropValue(PixelPropsUtils.java:425)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at com.android.internal.util.crdroid.PixelPropsUtils.setProps(PixelPropsUtils.java:309)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1356)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1467)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1399)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7368)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2379)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.os.Handler.dispatchMessage(Handler.java:107)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.os.Looper.loopOnce(Looper.java:232)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.os.Looper.loop(Looper.java:317)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at android.app.ActivityThread.main(ActivityThread.java:8601)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at java.lang.reflect.Method.invoke(Native Method)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
> 10-14 03:11:59.926  4246  4246 E PixelPropsUtils: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:863)
> ```
> 
> yet no idea why happening only with you

this error is now fixed. but error seems irrelevant to issue.

**Comment by gwolf2u** [comment]
any progress here?

**Comment by Lost-Entrepreneur439** [comment]
I haven't done any further testing on crDroid 10 since my last comment on this issue, however I have tested on the crDroid 11 beta and the issue seems to be patched there. In general, the crDroid 11 beta seems to work a lot better than crDroid 10 on nx_tab.

**Comment by gwolf2u** [comment]
Closing this then
