### ISSUE TITLE
bug: Microphone not working on Galaxy S10e

### ISSUE THREAD

**Issue by mrbadstuff** [crdroidandroid/issue_tracker#527]
### Issue type

Feature not working as intended

### Device

Samsung Galaxy S10e

### crDroid version

crDroid 10

### Exact version / Build date

10.6/
2024-07-28

### Bug description

I have two S10e phones. On one of them, the microphone doesn't work for phone calls. On the other phone, the other person can hear an echo of their own voice when they talk to me.

### Steps to reproduce

1. Flash crDroid 10.6 using LOS recovery on Samsung Galaxy s10e
2. Make a phone call

### Relevant log (logcat/build log)

```shell
.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
device outside of support
