### ISSUE TITLE
bug: Cant receive sms until restart the SIM

### ISSUE THREAD

**Issue by ThaiDuy12345** [crdroidandroid/issue_tracker#529]
### Issue type

Feature not working as intended

### Device

Sapphire

### crDroid version

crDroid 10

### Exact version / Build date

cdDroid 10.8 29/9/2024

### Bug description

Can't receive any SMS until I restart the SIM

### Steps to reproduce

Step 1: Restart the phone
Step 2: Try someway to get receive but wont get any

### Relevant log (logcat/build log)

```shell
I dont know
```

### Screenshots or videos

Video link: https://t.me/crDroidAndroid/477801

### Solution

Restart the SIM like in the video

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
full logcat needed

**Comment by ThaiDuy12345** [comment]
> full logcat needed

How can I take one tho ?

**Comment by gwolf2u** [comment]
adb logcat
or
MatLog app

**Comment by ThaiDuy12345** [comment]
[logcat.txt](https://github.com/user-attachments/files/17270425/logcat.txt)

**Comment by kibria5** [comment]
> here [logcat.txt](https://github.com/user-attachments/files/17270425/logcat.txt)

already fixed check changelog
