### ISSUE TITLE
Font isn't changing in any 3rd party app

### ISSUE THREAD

**Issue by sifatefat** [crdroidandroid/issue_tracker#53]
### Issue type

Feature not working as intended

### Device

spes

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

font isn't changing in any 3rd party app

### Steps to reproduce

crdroid settings> font

### Relevant log (logcat/build log)

```shell
Log isn't needed
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is fixed with cr 9.1
