### ISSUE TITLE
bug: When the tablet is in landscape orientation, the one-click clear notification button is not displayed

### ISSUE THREAD

**Issue by YiQiuYes** [crdroidandroid/issue_tracker#531]
### Issue type

User interface

### Device

Xiaomi Pad 5 Pro

### crDroid version

crDroid 10

### Exact version / Build date

10.8/2024-10-04

### Bug description

The portrait screen is displayed normally：
![Screenshot_20241006-135523_设置](https://github.com/user-attachments/assets/689e8256-7ce7-4f0f-a326-21c5f084cba4)
Disappears in landscape orientation：
![Screenshot_20241006-135530_设置](https://github.com/user-attachments/assets/e95e12d6-386f-4133-9ed7-17493913ff76)

### Steps to reproduce

1.When there is a notification and it is in landscape mode

### Relevant log (logcat/build log)

```shell
.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is by design

**Comment by YiQiuYes** [comment]
> this is by design

It would be more reasonable to display it because in the crdroid settings, after enabling the material button, it is quite troublesome to manually swipe away notifications when there are too many notifications in landscape mode.
