### ISSUE TITLE
Touching physical fingerprint sensor scrolls to top of webpage

### ISSUE THREAD

**Issue by varaki** [crdroidandroid/issue_tracker#535]
### Issue type

User interface

### Device

Poco X3 Pro (vayu)

### crDroid version

crDroid 10

### Exact version / Build date

10.8/2024-09-22

### Bug description

When opening any website in Cromite browser then scrolling down a bit and if you touch the physical fingerprint sensor, the webpage scrolls up to the top of the website.
One additional thing is that if I log in with Bitwarden after unlocking the vault with fingerprint, then sometimes the sites's scrolling stuck as if I was constantly pressing the fingerprint sensor. This particular issue goes away if I touch the fingerprint sensor again.

### Steps to reproduce

1. Open any website in Cromite
2. Scroll down
3. Touch fingerprint sensor

### Relevant log (logcat/build log)

```shell
-
```

### Screenshots or videos

https://github.com/user-attachments/assets/dfa0974d-2cae-4293-95d7-4326b130ed60

### Additional context

I think it might have to do something with the Android version combined with Cromite.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Logcat needed

**Comment by varaki** [comment]
[14_10-09-09-47_987.log](https://github.com/user-attachments/files/17360369/14_10-09-09-47_987.log)

**Comment by varaki** [comment]
Touching the fingerprint scanner in Cromite registers as a Home keypress:

```
(unknown) keydown KeyboardEvent {isTrusted: true, key: 'Home', code: 'Home', location: 0, ctrlKey: false, …}
(unknown) keyup KeyboardEvent {isTrusted: true, key: 'Home', code: 'Home', location: 0, ctrlKey: false, …}
```

**Comment by varaki** [comment]
Disabling a certain Cromite specific flag solves the issue.
