### ISSUE TITLE
bug: Funky touch target issues for swiping quick settings pages under certain circumstances.

### ISSUE THREAD

**Issue by tmsrise** [crdroidandroid/issue_tracker#538]
### Issue type

User interface

### Device

One Plus 7 Pro (guacamole)

### crDroid version

crDroid 10

### Exact version / Build date

10.9 / 2024-10-13

### Bug description

Certain tile text labels in the quick settings panel can cause "dead zones" where any swipe to go to another QS page that starts on these labels will not do anything. I've personally found this occurs under 2 circumstances:

1. When Vertical Layout is enabled, all QS tile labels (e.g "Flashlight") in this mode seem to cause the issue.
2. When screen real estate does not allow a full label for a tile/toggle, so it is replaced with a dynamic/scrolling label. 

This is most noticeable with the default pill quick settings tiles.

------------------------

Additionally, regardless of the above, swiping pages in the QS panel will induce a toggle vibration if the start of the swipe lands on a tile touch target, despite not actually toggling the tile. 

### Steps to reproduce

1. Enable crDroid Settings -> Quick Settings -> Vertical Layout
2. Swipe down fully to QS Panel (making sure it has multiple pages)
3. Test swiping from various locations.

### Relevant log (logcat/build log)

```shell
N/A
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
any chances to try over with crDroid 11 as cr10 will get retired soon
