### ISSUE TITLE
Ginkgo defaults to HSDPA instead of 4G

### ISSUE THREAD

**Issue by assasukasse** [crdroidandroid/issue_tracker#54]
### Issue type

Feature not working as intended

### Device

Gingko

### crDroid version

crDroid 8

### Exact version

8.10

### Bug description

This is NOT a carrier related issue as the same sim card doesn't exhibit the behaviour when used in a Samsung phone (with original software) or into a Xiaomi redmi 6 (with original software)

Connects to 4G at startup, after switching to 3G doesn't switch back to 4G.
It is required to change the preferred connection type to 3G and then back to 4G, and only then it connects to 4G.
Selecting a different radio band (from automatic) for example Europe brings back to 4G, after a while drops to edge and remains locked there.
This behaviour is not observed on the same sim card when using on a different phone, so it is either an hardware issue or a software one.

### Steps to reproduce

Turn on the phone
connect to 4G
move to an area with 3G coverage only
go back to 4G coverage area
the phone remains stuck on 3G

### Relevant log (logcat/build log)

```shell
N/A
```

### Solution

Tried to change the radio band to Europe - not helping
to class 11-  not helping
kinda out of options but happy to try others

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
@DarkJoker360 still supported?

**Comment by assasukasse** [comment]
Confirmed the same behaviour on crdroid 9.0.
Clean install after formatting data, system, vendor.
The phone locks into 3g and doesn't switch to 4g. Manually selecting 3g then 4g temporarily solves the issue allowing connection to 4g.

**Comment by DarkJoker360** [comment]
Have you tried updating APN from your carrier website?

**Comment by assasukasse** [comment]
Yes, I did.

**Comment by assasukasse** [comment]
Solved installing the China weekly firmware downloaded from here 
[xda firmware repository](https://forum.xda-developers.com/t/firmware-xiaomi-redmi-note-8-8t-ginkgo-willow-auto-updated-daily.3973285/) 

Do not install any other as they do not seem to solve the issue.
