### ISSUE TITLE
Hide QS on lockscreen

### ISSUE THREAD

**Issue by amittel** [crdroidandroid/issue_tracker#540]
### Issue type

Feature not working as intended

### Device

Xiaomi Redmi Note 13 Pro 5G (garnet)

### crDroid version

crDroid 10

### Exact version / Build date

10.9/2024-10-13

### Bug description

QS menu is still pullable on the lockscreen, but all empty when disabled in crdroid settings.
It makes no sense to have an empty QS menu.

### Steps to reproduce

- Open crdroid settings
- Tab QS 
- Enable "Do not show QS on lockscreen" (4th point in list)

### Relevant log (logcat/build log)

```shell
None. It's UI.
```

### Solution

If QS Settings are disabled for the lockscreen, it should not be possible to pull the drawer down.

### Additional context

I found an old issue, but it got closed without a comment https://github.com/crdroidandroid/issue_tracker/issues/337

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by JordyEGNL** [comment]
Can confirm, same on my OnePlus 9 Pro (lemonadep) on v10.9
![Screenshot_20241022-133745_Firefox](https://github.com/user-attachments/assets/15ff07a0-ffdf-461d-9f61-651173239bcc)

**Comment by gwolf2u** [comment]
So apparently this is by design 
There's currently no other way to do this some other way
