### ISSUE TITLE
Bug: can use rear camera and face unlock

### ISSUE THREAD

**Issue by VladimirB52** [crdroidandroid/issue_tracker#541]
### Issue type

Feature not working as intended

### Device

Redmi note 7 lavender

### crDroid version

crDroid 10

### Exact version / Build date

16/10/2024

### Bug description

When open the camera and turn it to rear camera. It Suddenly turned off

### Steps to reproduce

Can use rear camera and also can use unlock face to unlock device

### Relevant log (logcat/build log)

```shell
16/10/2024
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by VladimirB52** [comment]
Uploading VID_20241022_184745.mp4…

**Comment by gwolf2u** [comment]
logcat needed
