### ISSUE TITLE
Wifi instability

### ISSUE THREAD

**Issue by klemen866** [crdroidandroid/issue_tracker#542]
### Issue type

Feature not working as intended

### Device

Redmi note 11 5G Pro (veux)

### crDroid version

crDroid 10

### Exact version / Build date

10.9/2024-10-15

### Bug description

Wifi connection is abruptly interrupted from time to time. It might happen when connecting to another AP on the same network. Trying to switch wifi off (once it has been interrupted) results in device rebooting. Turning on/off airplane mode restores wifi connection.

### Steps to reproduce

Connect to wifi - wait - connection interrupted and switch to mobile data

### Relevant log (logcat/build log)

```shell
No log.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
logcat needed for reboot
