### ISSUE TITLE
Notification bug (CrDroid 9)

### ISSUE THREAD

**Issue by lyyako** [crdroidandroid/issue_tracker#544]
### Issue type

User interface

### Device

Redmi Note 8 (Ginkgo)

### crDroid version

crDroid 9

### Exact version / Build date

9.15/20240322
(Same on 9.20, that I build myself)

### Bug description

In crDroid 9, which has a split control panel, if you receive a notification in landscape mode, it simply does not display. Previously, there was no such problem with this because the control panel was not split

### Steps to reproduce

Step 1. Go to landscape mode
Step 2. Receive a notification

### Relevant log (logcat/build log)

```shell
No need
```

### Screenshots or videos

https://github.com/user-attachments/assets/daf9283e-2a6b-4263-9e30-3211d28012ba

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
It is AOSP bug. It is therefore not enabled by default.
