### ISSUE TITLE
bug: not localised power menu

### ISSUE THREAD

**Issue by zolenid** [crdroidandroid/issue_tracker#545]
### Issue type

User interface

### Device

m52qx

### crDroid version

crDroid 11

### Exact version / Build date

11.0-BETA/2024-11-01

### Bug description

Power menu isn't localised on russian

### Steps to reproduce

1.Long press power button
2.press restart(is't localised)

### Relevant log (logcat/build log)

```shell
.
```

### Screenshots or videos

![Screenshot_20241102-000736_crDroid Home](https://github.com/user-attachments/assets/6cf661a3-68cc-4e77-9acd-06e829e4d473)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
translations were not merged in BETA
