### ISSUE TITLE
QS Lag 

### ISSUE THREAD

**Issue by Heisenberg38219** [crdroidandroid/issue_tracker#546]
### Issue type

Other

### Device

OnePlus 8T (kebab)

### crDroid version

crDroid 11

### Exact version / Build date

11.0/2024-11-01

### Bug description

QS Lag is still present on latest 11.0 (OnePlus 8T) when the media player is being used and the light theme is activated. 

### Steps to reproduce

1. Turn on Light Mode
2. Stack some notifications (5 at least)
3. Use the media player (YouTube, Spotify, doesn't matter)
4. Scroll down the QS panel from Launcher3

### Relevant log (logcat/build log)

```shell
Not logable.
```

### Solution

Commits from RisingOS which has fixed the bug described above. 

1. https://github.com/RisingTechOSS/android_frameworks_base_new/commit/fda00bf18892127fcee5fbb10ac59ad4d3250535

2. https://github.com/RisingTechOSS/android_frameworks_base_new/commit/92c2ed3e93c570688c9d058b41d9a99eb689c413

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unfortunately this is how it is
