### ISSUE TITLE
Macro Camera removed from aperture

### ISSUE THREAD

**Issue by JuaniThor00** [crdroidandroid/issue_tracker#55]
### Issue type

Feature not working as intended

### Device

Poco X3 Pro Vayu

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

In the previous compilation (2022 - 11 - 16), the macro camera worked fine, but with the latest update (2022 - 12 - 04) the macro camera was removed, also, the portrait camera doesn't work as it should

### Steps to reproduce

Step 1. Open Camera app (aperture)
Step 2. That's all... The macro camera was removed and the ". 9" camera shows as Black and white

### Relevant log (logcat/build log)

```shell
12-04 19:39:55.686 D/CameraStateRegistry(17163): Camera@94f40ff[id=3]                         UNKNOWN              

I don't know... I don't thibk there's really a logcat for that error
```

### Screenshots or videos

![2022-12-04-19-42-26-987](https://user-images.githubusercontent.com/50645133/205526297-366b7942-9713-4138-bde8-517aef927d1e.jpg)
![2022-12-04-19-42-43-526](https://user-images.githubusercontent.com/50645133/205526303-eee0ee17-f54d-4cea-840d-5f6ef9de5a26.jpg)
![2022-12-04-19-42-51-743](https://user-images.githubusercontent.com/50645133/205526306-6d1a8ff7-c8d8-4ac6-9cb5-25de1347c96e.jpg)
![Screenshot_20221204-194335_Camera](https://user-images.githubusercontent.com/50645133/205526355-8cb8e058-a2e2-4408-b338-956a0e403d2d.png)
![Screenshot_20221204-194341_Camera](https://user-images.githubusercontent.com/50645133/205526359-6c51d81b-0868-41be-9eab-08ab1e65e44b.png)
![Screenshot_20221204-194345_Camera](https://user-images.githubusercontent.com/50645133/205526362-0846ca91-38d7-4d2a-bbc8-56c73256ef90.png)

### Solution

Reconfigure camera (aperture) application or try yo reintroduce the MIUI Camera App... Or try with the Leica Camera App

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by JuaniThor00** [comment]
@neobuddy89

**Comment by gwolf2u** [comment]
as of now Aperture is WIP
