### ISSUE TITLE
bug: title (<-- change me)

### ISSUE THREAD

**Issue by Yrvine3** [crdroidandroid/issue_tracker#553]
### Issue type

User interface

### Device

Mi9 cepheus

### crDroid version

crDroid 10

### Exact version / Build date

10.9 
08/11/2024

### Bug description

My phone freezes and I have to restart it to unlock it

### Steps to reproduce

it's random

### Relevant log (logcat/build log)

```shell
Subject: Process ProcessRecord{5e8249e 14968:.pasr/u0a324} failed to complete startup
RssHwmKb: 105688
RssKb: 105640
RssAnonKb: 58960
RssShmemKb: 16608
VmSwapKb: 0


--- CriticalEventLog ---
capacity: 20
events <
  timestamp_ms: 1731377349067
  anr <
    pid: 14710
    process: ".pasr"
    process_class: 2
    subject: "Process ProcessRecord{5e8249e 14710:.pasr/u0a324} failed to complete startup"
    uid: 10324
  >
>
events <
  timestamp_ms: 1731377369101
  anr <
    pid: 14731
    process: "com.android.settings"
    process_class: 2
    subject: "Process ProcessRecord{970fb38 14731:com.android.settings/1000} failed to complete startup"
    uid: 1000
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
badly written issue
logcat needed
