### ISSUE TITLE
Bluetooth audio cuts out for  ~5 seconds when now playing feature is enabled

### ISSUE THREAD

**Issue by bartned** [crdroidandroid/issue_tracker#554]
### Issue type

User interface

### Device

Alioth

### crDroid version

crDroid 9

### Exact version / Build date

11.0/2024-11-09

### Bug description

When the now playing feature is enabled, playing Bluetooth audio and the phone is turned off and then turned on again, the Bluetooth audio cuts for ~ 5 seconds. You also see the output change from "Bluetooth device" to "this device".

### Steps to reproduce

Make sure "now playing" is turned on. Play music over Bluetooth device. Turn the device off and then wake again.

### Relevant log (logcat/build log)

```shell
Provided as file
```

### Screenshots or videos

https://github.com/user-attachments/assets/02013965-9d08-4075-98de-21c8b9419449

[2024-11-12-21-02-22.txt](https://github.com/user-attachments/files/17722423/2024-11-12-21-02-22.txt)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by raystef66** [comment]
Unless I'm wring it's related to https://github.com/crdroidandroid/issue_tracker/issues/552
If not I can always re-open.

**Comment by raystef66** [comment]
Also, the 10.9 won't be updated anymore, unless the things I change on 11.x will fix the issue, I can update 10.9 once more.
