### ISSUE TITLE
bug: bluetooth device battery info on widget 

### ISSUE THREAD

**Issue by meilluer** [crdroidandroid/issue_tracker#555]
### Issue type

Feature not working as intended

### Device

Redmi note 12 4g(tapas/topaz)

### crDroid version

crDroid 11

### Exact version / Build date

lineage_topaz-userdebug 15 AP3A.241005.015 eng.nobody.20241107.085555 dev-keys

### Bug description

Information about battery level of tws devices is unavailable on battery widget only device battery info is available 

### Steps to reproduce

1.connect tws to device
2.long press on home screen
3.seach for "battery"
4.under services select battery widget
5. Add on home screen 
6. It would be stuck on loading 
7. Restart device 
8. Only info related to device is available 

### Relevant log (logcat/build log)

```shell
StatsLog

D LAUNCHER_WIDGETSTRAY_APP_EXPANDED

Launcher I

App widget created with id: -1

b/267448... D provider: ComponentInfo{com.google.andro... ... Bound widget 22 to provider ProviderId{u...

AppWidge

Launcher

... I App widget created with id: 22

Activity I

Start proc 4899:com.google.android.setti...

BatteryA...

WON UPDATE.

BatteryW...

WisLongLife: chargingStatus=0

BatteryW...

WisLongLife: chargingStatus=0

BatteryW...

W storePhoneIntent: level=47 saveMode=fals...

BatteryA.

WonReceive: Intent { act=android.appwidge...

b/267448... D provider: ComponentInfo{com.google.andro...

StatsLog D

LAUNCHER_WIDGET_RESIZE_STARTED

AppWidge... D

Trying to notify provider update

AppWidge... D Trying to notify provider update

AppWidge... D Trying to notify provider update

AppWidge... D Trying to notify widget providers changed

AppWidge... D Trying to notify widget providers changed

AppWidge... D Trying to notify widget providers changed

AppWidge... D Trying to notify widget providers changed

b/267448... D provider: ComponentInfo{com.google.andro...

BatteryA

WON UPDATE.

BatteryW...

WisLongLife: chargingStatus=0

BatteryW...

WisLongLife: chargingStatus=0

BatteryW... W storePhone Intent: level=47 saveMode=fals...

Activity

Start proc 4935:com.kieronquinn.app.smar...

BatteryA... WonReceive: Intent { act=android.appwidge...

Activity Start proc 4954: com.google.android.keep/...

AppWidge... D Trying to notify provider update

AppWidge... D Trying to notify provider update

AppWidge... D Trying to notify provider update

AppWidge... D Trying to notify widget providers changed

AppWidge... D Trying to notify widget providers changed

AppWidge... D Trying to notify widget providers changed

AppWidge... D Trying to notify widget providers changed

b/267448... D provider: ComponentInfo{com.google.andro...

Batter Ba CharvA MON LUPDATE
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by meilluer** [comment]
> not all bt devices support those stats some are just not compatible with AOSP code also does it work on any other ROM than stock, or even works on stock?

Yes it worked fine in rising os , stock and even on previous version of crdroid gapps build , this build is vanilla

**Comment by neobuddy89** [comment]
Where is complete log?

**Comment by meilluer** [comment]
Fixed : flash full nikgapps
