### ISSUE TITLE
bug: random reboot

### ISSUE THREAD

**Issue by Avnesh007** [crdroidandroid/issue_tracker#56]
### Issue type

Other

### Device

Beryllium 

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

I have faced random reboot issue from last 4 weekly updates. But now I was clean flashed rom and today I was faced same issue again while my device was connected to charger.

### Steps to reproduce

[issue.txt](https://github.com/crdroidandroid/issue_tracker/files/10182927/issue.txt)

### Relevant log (logcat/build log)

```shell
12-06 23:06:15.048 27136 27136 E AndroidRuntime: FATAL EXCEPTION: main @coroutine#31
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by JuaniThor00** [comment]
Same issue in Vayu using CrDroid 9.0 Last version

**Comment by juamaleta** [comment]
Yo también lo tengo

**Comment by gwolf2u** [comment]
with latest code, seems to not happen anymore
care to confirm guys !?

**Comment by KL7000F** [comment]
No problem since build 02.12.
