### ISSUE TITLE
Unable to grant Storage Access Framework access to any app

### ISSUE THREAD

**Issue by SledgeSune** [crdroidandroid/issue_tracker#560]
### Issue type

Other

### Device

Poco X3 Pro (Vayu)

### crDroid version

crDroid 10.10

### Exact version / Build date

10.10/2024-11-16

### Bug description

When trying to grant Storage Access Framework access, com.android.documentsui (Files) only returns a blank Recents [page](https://github.com/user-attachments/assets/e085a719-f9c0-4a01-89bf-6b059ed6d026)
This happens with any app, the provided example happened when trying to [access](https://github.com/user-attachments/assets/72b49c8e-3928-4dcc-925f-ba4093d952b8) Android/data/[app.name] folder with [Amaze](https://github.com/TeamAmaze/AmazeFileManager)
Can't say for sure, but Im almost certain the problem first happened when i first start using crdroid

Using com.android.documentsui version 14 (34)

### Steps to reproduce

- try to access any folder in /Android/data/
- App requests SAF access
- Files oly shows an empty page, where the only option on the menu is to show hidden files

### Relevant log (logcat/build log)

```shell
none
```

### Screenshots or videos

![image](https://github.com/user-attachments/assets/688f62d6-2473-4dd1-8312-6528b2163db9)
![image](https://github.com/user-attachments/assets/f37e3cde-4b6a-4f36-882c-4694ff1944f0)

## What Ive tried

I have:
- Cleared Dalvik Cache
- Cleared Files data
- Hidden root from Files
- Uninstalling and Reinstalling Files (with ```adb shell cmd package install-existing com.android.documentsui```)
- Read somewhere it was an issue with MiXExplorer, so uninstalled it.
- Rebooting after every step

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by xAdSFx** [comment]
Was an issue with the NoStorageRestrict v5 by DanGLES3 magisk module, disabling it and restarting the phone solved the problem
