### ISSUE TITLE
bug: VoLTE/VoWiFi doesn't work after reboot on topaz

### ISSUE THREAD

**Issue by skittels15** [crdroidandroid/issue_tracker#561]
### Issue type

Source code related

### Device

Redmi Note 12 4G (topaz)

### crDroid version

crDroid 11

### Exact version / Build date

11.0/2024-11-07

### Bug description

VoLTE/VoWiFi doesn't work (screenshot 1) but enabled in SIM settings (screenshot 2) after system reboot because IMS service doesn't start. VoLTE/VoWiFi icons enabled in crDroid Settings (screenshot 3) but not available in statusbar because that features not started automatically.

### Steps to reproduce

1. Enable VoLTE and VoWiFi in SIM settings.
2. Reboot phone.

### Relevant log (logcat/build log)

```shell
11-19 23:57:52.243 E/QImsService(2719): ImsServiceSub : [1] changeEnabledCapabilities :: ignoring unsupported disable capability request: CapabilityPair{mCapability=2, radioTech=3}
11-19 23:57:52.243 E/QImsService(2719): ImsServiceSub : [1] changeEnabledCapabilities :: ignoring unsupported disable capability request: CapabilityPair{mCapability=16, radioTech=0}
11-19 23:57:52.243 E/QImsService(2719): ImsServiceSub : [1] changeEnabledCapabilities :: ignoring unsupported disable capability request: CapabilityPair{mCapability=16, radioTech=3}
11-19 23:57:52.243 E/QImsService(2719): ImsServiceSub : [1] changeEnabledCapabilities :: ignoring unsupported disable capability request: CapabilityPair{mCapability=32, radioTech=0}
11-19 23:57:52.243 E/QImsService(2719): ImsServiceSub : [1] changeEnabledCapabilities :: ignoring unsupported disable capability request: CapabilityPair{mCapability=32, radioTech=3}
11-19 23:57:54.349 E/QImsService(2719): ImsServiceSub : [1] changeEnabledCapabilities :: ignoring unsupported enable capability request: CapabilityPair{mCapability=2, radioTech=3}
```

### Screenshots or videos

![photo_2024-11-20_00-09-49](https://github.com/user-attachments/assets/d57702a5-6de0-4097-8193-8aa985e1e9f5)
![photo_2024-11-20_00-09-11](https://github.com/user-attachments/assets/1b49e351-1947-4c04-8cf3-49ce985bf9fa)
![photo_2024-11-20_00-09-11 (2)](https://github.com/user-attachments/assets/1c73d2fc-f80b-40be-9f9f-6b79ed240bf8)

### Solution

Weird solution after every system reboot:
Disable and re-enable both SIMs in SIMs settings. That is temporary fix until next reboot.

### Additional context

Other custom roms launched on Android 15 by other maintainers doesn't have this bug.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
happening still on build 20241217 ?

**Comment by skittels15** [comment]
Yes. Bug not fixed for me. I didn't see any fixes for VoLTE/VoWiFi in device tree from previous build.

**Comment by gwolf2u** [comment]
this may be carrier related, so not dt side

**Comment by skittels15** [comment]
This not depend on carrier. In custom roms by other devs and in stock MIUI/HyperOS doesn't have this bug

**Comment by gwolf2u** [comment]
you didn't understand what I wrote, but guess I could have explained it a bit better
MIUI/HyperOS are stock roms - ofc VoLTE may work there, since they certify it with carriers
carriers have specific configurations that they ask OEMS to add in order to comply with their requirements
anyway, those configs are not always updated in time for AOSP
those configurations can be added dt side in some case while in other cases to base code
now the question
does VoLTE work with any other custom rom AOSP based?
asking that especially since as I said maintainer doesn't have VoLTE carrier so no actual way to test

**Comment by skittels15** [comment]
> **In custom roms by other devs** and in stock MIUI/HyperOS **doesn't have this bug**
I says about AOSP/LOS-based custom roms too.

**Comment by skittels15** [comment]
> asking that especially since as I said maintainer doesn't have VoLTE carrier so no actual way to test

I know right way. Need testing by users from device's international communities before release.

**Comment by mirabelle1999** [comment]
> Need testing by users from device's international communities before release.

I have international testers. Russia and from Spanish countries actually. and from the last build, testers said VoLTE works fine. Other users also are not asking me about a bug like that. I also would like to add-up that my testers try to check before restarting and after restarting and still, VoLTE is working.
