### ISSUE TITLE
SmartPixel Feature breaks Interaction with certain controls

### ISSUE THREAD

**Issue by susch19** [crdroidandroid/issue_tracker#563]
### Issue type

User interface

### Device

alioth

### crDroid version

crDroid 11

### Exact version / Build date

crDroidAndroid-15.0-20241116-alioth-v11.0

### Bug description

Enabling the smart pixels features will prevent certain controls from reacting on touch input.
They still work when using phsyical keyboard and navigating via arrows and enter.
Like enabling usb debugging, security settings and banking apps. 

### Steps to reproduce

1. Enable Smart Pixels in CR Droid Settings
2. Restart Phone (Important, otherwise this bug will occur after some yet unknown time)
3. Try to interact with "security controls", they will not react on touch, but will work with physical keyboard
4. Disable Smart Pixels
5. Everything works fine again

### Relevant log (logcat/build log)

```shell
None
```

### Screenshots or videos

https://github.com/user-attachments/assets/65d84e10-e884-43d3-b4ac-09fe7e03a1f2

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Smart pixels has a note that states this

**Comment by susch19** [comment]
Oh that is poorly translated, in german it says `Dies kann dazu führen, dass der Touchscreen teilweise schlecht auf Berührungen reagiert`, which would translate into `Note that in some cases it can result in can worsen the touchscreen responsiveness`. So it works, but not as good.
The correct german translation should be: `Dies kann dazu führen, dass bestimmte Elemente mit dem Touchscreen nicht reagieren.` which in contrast means, that it doesn't work for some areas at all, which is written in english.

But maybe this warning should be more pronounced, as this actually breaks specific apps completely.

The only thing is, why does it not happen directly after starting smart pixels, but only after reboot?

**Comment by raystef66** [comment]
Sure but the issue here is that I can use my phone fully when smart pixels is ON before that reboot. After a reboot it got stuck. What difference would a reboot make here?

**Comment by raystef66** [comment]
@susch19 Translations can be found here : https://crowdin.com/project/crdroid-translation/de

**Comment by susch19** [comment]
> @susch19 Translations can be found here : https://crowdin.com/project/crdroid-translation/de

Thanks, I'll provide a suggestion for a change, so that the german translation matches the intent of the english one.

Another thing is, with android 13 (EvoX in this case), i didn't have this behavior, so upgrading from A13 to A15 had this issue pop up. That's why I thought the upgrade process was the issue, since sometimes features are enabled which you don't remember, since you have them enabled for such a long time already. 
So maybe I'm biased in this case, but such a small note for a big usage impact seems to be not enough. I would rather display a dialog with the warning (Like usb debugging does). 
And (I don't know if this is possible), after upgrading the os versions, show a warning, that this feature is enabled and may break things or disable it during the flash process.

**Comment by susch19** [comment]
Okay, so this is an actual non issue? Even though it only happens after restart? That is somewhat disappointing, but okay, let's update the german translation and hope that no one else has these issues and spends days finding out why it's not working after upgrading

**Comment by gwolf2u** [comment]
smart pixels is not on by default on clean install

**Comment by raystef66** [comment]
Regarding if it was ON or OFF, why would a reboot change behaviour of the smart pixel feature which was initally working fine?

**Comment by susch19** [comment]
Of course it is not, but not all do a clean install (Even though it is recommended, but if alot of users say, i worked without problem which is good, most likely more users will do it). 
And let's imagine someone enables it after clean install. Reboots the phone 7 days later and suddenly things stopped working. Will those users actually think about smart pixels note in this case?

**Comment by ShevT** [comment]
I confirm, on hodog (op7t pto)

**Comment by susch19** [comment]
@ShevT https://github.com/crdroidandroid/issue_tracker/issues/569#issuecomment-2498082757 See here, this feature will be removed, as it doesn't save that much battery. I liked it as an OLED burn-in prevention, but in this state it wouldn't be usable as such
