### ISSUE TITLE
Reopen #519 (QS Panel page indicator jumping to the left, not staying in center)

### ISSUE THREAD

**Issue by secretServant** [crdroidandroid/issue_tracker#564]
### Issue type

User interface

### Device

Devon

### crDroid version

crDroid 10

### Exact version / Build date

10.9/2024-11-15

### Bug description

See #519
[
Issue persists even after commit 52ff58a](https://github.com/crdroidandroid/android_frameworks_base/commit/52ff58a5584ca6ca66034e8134537f23374db672)

### Steps to reproduce

See #519

### Relevant log (logcat/build log)

```shell
See #519
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
Steps to reproduce?

**Comment by secretServant** [comment]
Interesting, so rather than waiting, a way to trigger the issue is by toggling dark mode repeatedly from QS. Randomly the QS sometimes generates the page indicator dots to the left, often they stay there for a second before moving to center, other times they stay to the left. It's like elements aren't loading quickly enough or are fighting for priority.
