### ISSUE TITLE
Custom header image doesn't work

### ISSUE THREAD

**Issue by thecapibara** [crdroidandroid/issue_tracker#566]
### Issue type

User interface

### Device

Moto G32 (devon)

### crDroid version

crDroid 11

### Exact version / Build date

11.0/2024-11-19

### Bug description

Custom header image doesn't appear in QS after selecting image.

### Steps to reproduce

1. Open crDroid settings
2. Choose QS setting - Header Image 
3. Enable it, choose Custom Image and select any image
4. Check QS

### Relevant log (logcat/build log)

```shell
No log
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
Unable to reproduce and no logs.
