### ISSUE TITLE
bug: Smart Pixel Causes Allow Permissions Window to Pause/Hang

### ISSUE THREAD

**Issue by finaldata** [crdroidandroid/issue_tracker#569]
### Issue type

Feature not working as intended

### Device

OnePlus 7 Pro (guacamole)

### crDroid version

crDroid 11

### Exact version / Build date

11.0-BETA/2024-11-24

### Bug description

When apps asks for permission and Smart Pixel is enabled, the permission window hangs/pauses. No amount of tapping would proceed to allow or not allow. It just is stuck there. When Smart Pixel is disabled, the permission window goes through or you are now able to tap on Allow or Not Allow.

### Steps to reproduce

Step 1: Enable Smart Pixel in CRDroid Settings
Step 2: Install or Open an App
Step 3: App asks for Permission to Allow or Not Allow ( This is where it gets stuck)
Step 4 : Go back to CrDroid Settings, Disable Smart Pixel
Step 5: Go back to app and tap Allow or Sometimes it goes through already.

### Relevant log (logcat/build log)

```shell
No logs were captured. Will update issue once logs are captured.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
Smart Pixels comes with warnings. It is likely to break things. We will remove Smart Pixels altogether.

**Comment by finaldata** [comment]
Thank you. I finally go the log but since its already closed. It;s cool! Smart pixel is useful for reducing battery drain. Hope it can be implemented properly the next time around. Thank you.

**Comment by gwolf2u** [comment]
at the time being is not helping in battery that much
maybe 1-2%

**Comment by susch19** [comment]
Just a suggestion, leave one Smart Pixels Bug open with the resolution, that it will be removed in the near future. So that people, who want to open tickets for it, will see, that there is already an opened ticket. At least I have made the observation, that people are more likely to look into open issues for duplicates, than in closed ones.
