### ISSUE TITLE
bug: 3rd party icons shape have white background

### ISSUE THREAD

**Issue by usamaiqbal1177** [crdroidandroid/issue_tracker#570]
### Issue type

Feature not working as intended

### Device

Pixel 8 pro

### crDroid version

crDroid 11

### Exact version / Build date

11.0, Nov 18 2024

### Bug description

White background is appearing behind 3rd party icons in CrDroid launcher according to the shape selection in system settings. 

There should be no white background as it's forcefully cutting the intended shape of icons. Not all icon packs are circle and square only. Many are non fixed shapes as well like Candycons icon pack for example

### Steps to reproduce

apply any 3rd party icons in settings 

### Relevant log (logcat/build log)

```shell
Can't give as there is no error
```

### Screenshots or videos

![Screenshot_20241125-221550_crDroid Home](https://github.com/user-attachments/assets/9dfbb45a-7203-487a-acbf-452fd1cedc19)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
which icon pack is this

**Comment by usamaiqbal1177** [comment]
> which icon pack is this

Minimal O
