### ISSUE TITLE
bug: title (<-- change me)

### ISSUE THREAD

**Issue by velox11** [crdroidandroid/issue_tracker#574]
### Issue type

Other

### Device

vayu

### crDroid version

crDroid 11

### Exact version / Build date

AP2A.240905.003

### Bug description

My phone did shutdown by itself

### Steps to reproduce

I had to start my phone

### Relevant log (logcat/build log)

```shell
1-29 15:46:36.511  2387  2387 E AndroidRuntime: FATAL EXCEPTION: main
11-29 15:46:36.511  2387  2387 E AndroidRuntime: Process: com.android.dialer, PID: 2387
11-29 15:46:36.511  2387  2387 E AndroidRuntime: java.lang.RuntimeException: Unable to bind to service com.android.incallui.InCallServiceImpl@4ceaf37 with Intent { act=android.telecom.InCallService cmp=com.android.dialer/com.android.incallui.InCallServiceImpl }: java.lang.IllegalStateException: SharedPreferences in credential encrypted storage are not available until after user (id 0) is unlocked
11-29 15:46:36.511  2387  2387 E AndroidRuntime: 	at android.app.ActivityThread.handleBindService(ActivityThread.java:4964)
11-29 15:46:36.511  2387  2387 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindService(Unknown Source:0)
11-29 15:46:36.511  2387  2387 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2415)
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
log not sufficient. 
need pstore kernel log
