### ISSUE TITLE
Fingerprint sensor does not work if phone was locked in landscape mode.

### ISSUE THREAD

**Issue by quickishfm** [crdroidandroid/issue_tracker#576]
### Issue type

User interface

### Device

Oneplus 7 Pro (guacamole)

### crDroid version

crDroid 9

### Exact version / Build date

11.0-BETA (29-11-2024)

### Bug description

When phone is in landscape mode full screen (such as Youtube but paused) and goes to sleep by itself, the fingerprint sensor cannot be used when the phone is woken up again, the password/PIN must be input instead.

### Steps to reproduce

1. Open youtube, VLC, or any full-screen app
2. Pause video if needed (so the screen will turn off by itself)
3. Wait for e.g. 30 seconds for screen to turn off due to inactivity.
4. Wake device and try to unlock with fingerprint sensor 

### Relevant log (logcat/build log)

```shell
https://pastebin.com/XWc7Yv5K
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ShevT** [comment]
This problem has already been fixed on crDroid 11.
