### ISSUE TITLE
bug: title (<-- change me)

### ISSUE THREAD

**Issue by Alireza-Crdroid** [crdroidandroid/issue_tracker#579]
### Issue type

User interface

### Device

2107113SG

### crDroid version

crDroid 10

### Exact version / Build date

crDroid 10.10 an also has same problem on beta 11

### Bug description

Selfie mirror don't work correctly

### Steps to reproduce

1.Go to Camera settings.
2.Enable Mirror Selfie.
3.Launch the Leica Camera app.
4.Switch to the selfie camera.
5.Take a picture, and you will see that the mirror selfie feature does not work correctly.

### Relevant log (logcat/build log)

```shell
E [ERROR] [STATS_AF] camxcafstatsprocess...
E [ERROR] [NCS ] camxncsservice.cpp:1...
E [ERROR] [gf_hal_common_irq_key] create double...
```

### Screenshots or videos

https://github.com/user-attachments/assets/54d08005-bc23-4dcc-bb96-4b7a9bab81d7

### Solution

"Please fix the mirror selfie issue in the Leica camera app by ensuring the feature works correctly after enabling 'Mirror Selfie' in camera settings. The issue persists when switching to the selfie camera and taking a picture. The app does not display the image as intended."

### Additional context

I am using crDroid 10.10 on Xiaomi 11T Pro, and the issue occurs after enabling the 'Mirror Selfie' option in the camera settings. The problem persists in both the crDroid 11 beta and official builds. The issue is observed only with the Leica camera app. Other apps like GCam don't exhibit this issue, but the selfie quality is lower."

![Uploading AGC_20241212_212444207.RAW-01.COVER.jpg…]()

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Alireza-Crdroid** [comment]
Hello, I am experiencing an issue with the selfie mirror functionality in the crDroid camera app. Despite enabling the 'Mirror Selfie' option in settings, the effect is not applied correctly when I take a selfie. This issue is present both in the crDroid 11 beta and the current stable release. Please advise if this will be addressed in upcoming updates. Thank you for your support

**Comment by gwolf2u** [comment]
https://github.com/crdroidandroid/issue_tracker/issues/578
