### ISSUE TITLE
bug: app grid options are too limited

### ISSUE THREAD

**Issue by ossilator** [crdroidandroid/issue_tracker#580]
### Issue type

User interface

### Device

vili

### crDroid version

crDroid 11

### Exact version / Build date

11.0-beta/2024-12-06

### Bug description

the home screen config offers only limited options for the app grid.
while i would find two sliders to set the dimensions independently most sensible, my acute need would be satisfied by adding a 4x6 option, which fits today's usual screen dimensions better than the already present 4x5.

### Steps to reproduce

trivial

### Relevant log (logcat/build log)

```shell
nope
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
for now there's no plan to change this

**Comment by ossilator** [comment]
huh? to me that seems like a weird way to treat issues, esp. when you add the qualification "for now".

fwiw, the "acute" fix is probably trivial. according to some stackexchange post (iirc), it's a matter of editing an xml file. though i failed to find it on the device in acceptable time when i went looking. it's presumably a lot easier at the source level.

**Comment by gwolf2u** [comment]
this is not an issue actually
but while I understand you specific need, this is not planned as I said
is not just about adding a layout
