### ISSUE TITLE
bug: title (TYPE C TO 3.5 MM HEADPHONE JACK, NO SOUND ISSUE

### ISSUE THREAD

**Issue by nyteisdark707** [crdroidandroid/issue_tracker#582]
### Issue type

User interface

### Device

POCO F4(MUNCH) 

### crDroid version

crDroid 10

### Exact version / Build date

crDroid version 10.9.Build date=2024-10-17

### Bug description

Type c to 3.5 mm headphone jack no sound issue.No sound while connecting my type c earphones.And no 5g internet access not connecting to 5g network. 

### Steps to reproduce

When I connect the earphones to type c connector I  my phone, there is no sound in the earphones while the inbuild phone speaker is working 

### Relevant log (logcat/build log)

```shell
Type c to 3.5 mm headphone jack no sound issue.No sound while connecting my type c earphones.And no 5g internet access not connecting to 5g network.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
device no longer supported
