### ISSUE TITLE
bug: signature spoofing is broken for some apps

### ISSUE THREAD

**Issue by 33KK** [crdroidandroid/issue_tracker#583]
### Issue type

Source code related

### Device

garnet

### crDroid version

crDroid 11

### Exact version / Build date

8.12.24

### Bug description

Google updated the way signatures are checked and now the current implementation fails.

### Steps to reproduce

Open Google Maps with microG, it doesn't work.

### Relevant log (logcat/build log)

```shell
None
```

### Solution

Patch examples here: https://github.com/microg/GmsCore/issues/2680#issuecomment-2538425189

This will probably get fixed in LineageOS too so not sure if you want to wait for that.

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by ale5000-git** [comment]
The patch for LineageOS (not yer merged) is here: https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/411374

**Comment by ale5000-git** [comment]
Already merged here: https://github.com/crdroidandroid/android_frameworks_base/commit/d3dcfccbf266075906f612277ea622a744a3b0bd
