### ISSUE TITLE
bug: The application closes when trying to open the camera

### ISSUE THREAD

**Issue by rootbreak** [crdroidandroid/issue_tracker#584]
### Issue type

Other

### Device

POCO X3 NFC

### crDroid version

crDroid 11

### Exact version / Build date

11-10-2024

### Bug description

This bug started happening to me recently, when I try to open the camera in an application that requires analyzing something it closes.

### Steps to reproduce

Go to "Tarjetas de Claves BHD"
Tap on "Open Camera"
The app has stop working

### Relevant log (logcat/build log)

```shell
https://paste.crdroid.net/mlH7Y0
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by 306bobby-android** [comment]
The error log is stating an issue about missing GMS features found in the app manifest

If you do not have gapps installed, they need to be for whatever you are doing

If you do, maybe try reinstalling them

**Comment by gwolf2u** [comment]
looks like gms issue
as bobby said, check with reinstall of gapps

**Comment by rootbreak** [comment]
Now i see another version stable of crdroid 11 has launched I going to make a clean install.
Install and I'll come back and see how it goes.

**Comment by rootbreak** [comment]
Issue solved installing chrome, now the app open the camera correctly
