### ISSUE TITLE
Build issue cuttlefish dependencies

### ISSUE THREAD

**Issue by secretServant** [crdroidandroid/issue_tracker#590]
### Issue type

Source code related

### Device

Devon

### crDroid version

crDroid 10

### Exact version / Build date

Attempting to build 10.11

### Bug description

`error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:28:1: "libkmr_cf" depends on undefined module "libkmr_common".
Or did you mean ["libbt_common" "libc_common" "libdvrcommon"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:28:1: "libkmr_cf" depends on undefined module "libkmr_crypto_boring".
Or did you mean ["libcore-crypto-tests" "libcrypto_utils_test" "libfscrypt_unit_test"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:28:1: "libkmr_cf" depends on undefined module "libkmr_ta".
Or did you mean ["libhdr_tm"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:28:1: "libkmr_cf" depends on undefined module "libkmr_wire".
Or did you mean ["libhardware"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:62:1: "libkmr_cf_test" depends on undefined module "libkmr_common".
Or did you mean ["libbt_common" "libc_common" "libdvrcommon"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:62:1: "libkmr_cf_test" depends on undefined module "libkmr_crypto_boring".
Or did you mean ["libcore-crypto-tests" "libcrypto_utils_test" "libfscrypt_unit_test"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:62:1: "libkmr_cf_test" depends on undefined module "libkmr_ta".
Or did you mean ["libkmr_cf"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:62:1: "libkmr_cf_test" depends on undefined module "libkmr_tests".
Or did you mean ["libdm_test" "libkll_test" "libkver_test" "library_tests"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:62:1: "libkmr_cf_test" depends on undefined module "libkmr_wire".
Or did you mean ["libhardware" "libkmr_cf"]?
fatal errors encountered`

### Steps to reproduce

1. sync repo via `repo sync --force-sync`
2. issue `source build/envsetup.sh`
3. issue `brunch lineage_devon-ap2a-user`
4. see build errors related to cuttlefish

### Relevant log (logcat/build log)

```shell
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:28:1: "libkmr_cf" depends on undefined module "libkmr_common".
Or did you mean ["libbt_common" "libc_common" "libdvrcommon"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:28:1: "libkmr_cf" depends on undefined module "libkmr_crypto_boring".
Or did you mean ["libcore-crypto-tests" "libcrypto_utils_test" "libfscrypt_unit_test"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:28:1: "libkmr_cf" depends on undefined module "libkmr_ta".
Or did you mean ["libhdr_tm"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:28:1: "libkmr_cf" depends on undefined module "libkmr_wire".
Or did you mean ["libhardware"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:62:1: "libkmr_cf_test" depends on undefined module "libkmr_common".
Or did you mean ["libbt_common" "libc_common" "libdvrcommon"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:62:1: "libkmr_cf_test" depends on undefined module "libkmr_crypto_boring".
Or did you mean ["libcore-crypto-tests" "libcrypto_utils_test" "libfscrypt_unit_test"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:62:1: "libkmr_cf_test" depends on undefined module "libkmr_ta".
Or did you mean ["libkmr_cf"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:62:1: "libkmr_cf_test" depends on undefined module "libkmr_tests".
Or did you mean ["libdm_test" "libkll_test" "libkver_test" "library_tests"]?
error: device/google/cuttlefish/host/commands/secure_env/rust/Android.bp:62:1: "libkmr_cf_test" depends on undefined module "libkmr_wire".
Or did you mean ["libhardware" "libkmr_cf"]?
fatal errors encountered
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
you seem to have a misconfiguration in your dt

check with LOS gerrit to see what's missing for you
https://review.lineageos.org/q/project:LineageOS/android_device_motorola_devon
and 
https://review.lineageos.org/q/project:LineageOS/android_device_motorola_sm6225-common

we no longer support cr10 for devon, so our dt may be outdated
