### ISSUE TITLE
bug: Incorrect QS style in landscape with media player.

### ISSUE THREAD

**Issue by SaltedFishesNG** [crdroidandroid/issue_tracker#595]
### Issue type

User interface

### Device

Mi 10S(thyme)

### crDroid version

crDroid 11

### Exact version / Build date

AP2A.240905.003

### Bug description

In AOSP, the horizontal QS column should be 4, which automatically changes to 2 if there is a media player.

However, in crdroid the landscape QS column is locked to a fixed value by "Customeize QS columns and raws" in crdroid settings.

I think users should be allowed to restore AOSP behavior separately.

### Steps to reproduce

1. Play audio in the background.
2. Open QS in landscape mode.

### Relevant log (logcat/build log)

```shell
None
```

### Screenshots or videos

![1-1](https://github.com/user-attachments/assets/dce98982-6408-4cd0-8ca9-0696ab2bb9b3)
![1-2](https://github.com/user-attachments/assets/a9d4dadc-7e8d-480a-9af8-664a9afecb26)

The two pictures below are the intended results
![2-1](https://github.com/user-attachments/assets/732139d8-e7a9-4cdf-a650-b436ea093b2a)
![2-2](https://github.com/user-attachments/assets/59d6c508-3010-4c2b-87cb-c20a41aa94ed)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Duplicate 
https://github.com/crdroidandroid/issue_tracker/issues/591
