### ISSUE TITLE
Emulation fake device won't turn off

### ISSUE THREAD

**Issue by Izorkin** [crdroidandroid/issue_tracker#6]
### Issue type

Feature not working as intended

### Device

Mi 9T (Davinci)

### crDroid version

crDroid 8

### Bug description

Disabling the option `Unlimited photo storage` does not work. Gogole account still shows `Google Pixel 6 Pro` device.

### Steps to reproduce

1. Install firmware.
2. Disable option `Unlimited photo storage`.
3. Install GAPPS.
4. Login to Google Account

### Relevant log (logcat/build log)

```shell
None
```

### Additional context

Is it possible to add `Xiaomi Mi 8` device emulation? Adds more compatibility for games in the Play Market.

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
can't confirm
tested here on guacamole and lemonadep
do try to close app if you toggle option off in settings and reopen
@Laker87 can you confirm

**Comment by Izorkin** [comment]
I tested with a clean install.
What other way is there to check besides google account?

**Comment by gwolf2u** [comment]
there's no other way
any magisk mods installed that maybe are for safetynet?

**Comment by Izorkin** [comment]
When I tested I installed magisk and only microG module.

**Comment by gwolf2u** [comment]
won't work with microG as far as I know

**Comment by Laker87** [comment]
> can't confirm tested here on guacamole and lemonadep do try to close app if you toggle option off in settings and reopen @Laker87 can you confirm

Works fine for me. I have unlimited storage in Google photo if option is enabled and don't have it if option is disabled.

**Comment by Izorkin** [comment]
@gwolf2u does this option only work for google photos?
Reinstalled firmware with NikGapps. Option `Unlimited photo storage` disabled:
![vivaldi_2022-09-26_22-53-52](https://user-images.githubusercontent.com/26877687/192368616-560d9a26-ce9c-4e1f-aba2-ef9f496f572f.png)

**Comment by gwolf2u** [comment]
> @gwolf2u does this option only work for google photos? Reinstalled firmware with NikGapps. Option `Unlimited photo storage` disabled: ![vivaldi_2022-09-26_22-53-52](https://user-images.githubusercontent.com/26877687/192368616-560d9a26-ce9c-4e1f-aba2-ef9f496f572f.png)

Well, yeah
It's stated as that
In all other cases, you get listed as Pixel due to PixelPropUtils that is used for passing SafetyNet

**Comment by Izorkin** [comment]
@gwolf2u got it, thanks for the clarification.
After updating the firmware, the Asphalt 9 game stopped working, and in the Play Market it says that the game is not supported by the device. I thought this feature might help when running an unsupported game.
On previous firmware, my device was defined as Xiaomi Mi 8. Is it possible to add a similar feature to the current firmware?

**Comment by gwolf2u** [comment]
> @gwolf2u got it, thanks for the clarification. After updating the firmware, the Asphalt 9 game stopped working, and in the Play Market it says that the game is not supported by the device. I thought this feature might help when running an unsupported game. On previous firmware, my device was defined as Xiaomi Mi 8. Is it possible to add a similar feature to the current firmware?

Not really a focus right now

**Comment by mmortal03** [comment]
> > @gwolf2u does this option only work for google photos? Reinstalled firmware with NikGapps. Option `Unlimited photo storage` disabled: ![vivaldi_2022-09-26_22-53-52](https://user-images.githubusercontent.com/26877687/192368616-560d9a26-ce9c-4e1f-aba2-ef9f496f572f.png)
> 
> Well, yeah It's stated as that In all other cases, you get listed as Pixel due to PixelPropUtils that is used for passing SafetyNet

Just FYI, the Pixel spoofing has been causing High CPU and data usage in a number of ROMs: https://forum.xda-developers.com/t/temp-fix-root-reqd-high-cpu-usage-and-battery-drain-due-to-google-play-services.4406617/
