### ISSUE TITLE
bug: lockscreen unresponsive after wake up

### ISSUE THREAD

**Issue by widardd** [crdroidandroid/issue_tracker#61]
### Issue type

Feature not working as intended

### Device

Poco X3 Pro

### crDroid version

crDroid 9

### Exact version

crDroidAndroid-13.0-20221117-vayu-v9.0

### Bug description

When I wake the device up and try to swipe up to unlock, nothing happens. Takes a few tries and seconds and it finally works.

### Steps to reproduce

1. Lock device
2. wake up
3. swipe up
4. nothing happens

### Relevant log (logcat/build log)

```shell
Is this necessary in this case? Sorry
```

### Solution

Wait a few seconds after wake up

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
log needed
