### ISSUE TITLE
bug: No ADB access/permission while RNDIS/USB tethering

### ISSUE THREAD

**Issue by bphd** [crdroidandroid/issue_tracker#62]
### Issue type

Feature not working as intended

### Device

Moon

### crDroid version

crDroid 8

### Exact version

8.10

### Bug description

As I read on internet, it seems to be a ROM related issue, because it works on any devices depending of the installed ROM

### Steps to reproduce

USB Tethering => On
Computer: `adb shell`

### Relevant log (logcat/build log)

```shell
Nope
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
unofficial device
