### ISSUE TITLE
bug: Very slow tethering for DNS names

### ISSUE THREAD

**Issue by bphd** [crdroidandroid/issue_tracker#63]
### Issue type

Feature not working as intended

### Device

moon

### crDroid version

crDroid 8

### Exact version

8.10

### Bug description

The DNS resolution is lightning fast
The http request on IP is lightning fast
But an HTTP request on a DNS name is either utterly slow, either unsolvable

For example, resolving eff.org into 173.239.79.196 takes `;; Query time: 200 msec`
Requesting https://173.239.79.196 takes `Time: 0.13 s`
But requesting https://eff.org takes a very long time, until timeout

### Steps to reproduce

Connect USB to computer
Enable USB tethering
Connect to any domain name by any protocol you want

### Relevant log (logcat/build log)

```shell
Nope
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this is specific to your network and connection
not much we can do there

**Comment by bphd** [comment]
It happens on multiple networks and connection. You didn't asked before even closing

**Comment by gwolf2u** [comment]
DNS is managed by carrier and not on device

**Comment by bphd** [comment]
Not really, there is not always a carrier. Here even on local network with own DHCP server it happens
I want to dig out this problem to find why it have difficultires to resolve IPv6, do you know any way to get relevant logs from Android?

**Comment by gwolf2u** [comment]
Sorry not really
Only way is to check with external monitor tools / hardware
Think on android only thing to check much may be the congestion algorithm (kernel side)

**Comment by bphd** [comment]
I know that IP stack can be debugged at router level, server level. But here, in my network, everything can flawlessly make HTTP/S requests, use any IP version, but when it comes to Android it makes such things. What should I do for real?
