### ISSUE TITLE
bug: Bluetooth audio not working

### ISSUE THREAD

**Issue by ulisesindigo** [crdroidandroid/issue_tracker#64]
### Issue type

Feature not working as intended

### Device

miatoll

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

Audio devices connected via Bluetooth don't play media files. Voice calls and notification sounds work without problems. Tested the issue with different speakers and headsets before eventually rolling back to the previous version and problem was gone.
Miatoll build where everything works fine: October 30, 2022
Miatoll build where the problem exists: December 18, 2022

### Steps to reproduce

Step 1, Turn on Bluetooth
Step 2, Select device to connect or pair
Step 3, Play music (YouTube Music, Amazon Music) and/or video (YouTube, Netflix) 

### Relevant log (logcat/build log)

```shell
No log, I dug into all settings available for Bluetooth including developer options and nothing worked.
```

### Solution

Reverting back to the previous build solved the issue but you have to format device

### Additional context

This is only a problem for media files. Calls, ringtones, and notifications work fine.

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
no log can't help much
