### ISSUE TITLE
bug: VoLTE/VoWIFI status bar icon wrong numbering 

### ISSUE THREAD

**Issue by Ammi55** [crdroidandroid/issue_tracker#65]
### Issue type

User interface

### Device

Poco F1 (beryllium)

### crDroid version

crDroid 9

### Exact version

9.0 December 17 bulid

### Bug description

The VoLTE/VoWIFI icon on status bar has wrong numbering for sim. It shows number 2 for sim 1 and number 1 for sim 2

### Steps to reproduce

Step 1. Goto setting and turn off 4G calling on sim 1.
Step 2. Now as the VoLTE for sim 1 is off. The VoLTE icon on the status bar should show 2 on the icon but it shows 1 and vice versa.

### Relevant log (logcat/build log)

```shell
12-22 10:56:42.171 W/View    (2255): requestLayout() improperly called by com.android.keyguard.AlphaOptimizedLinearLayout{a0f36c1 V.E...... ......ID 7,0-48,61 #7f0a0796 app:id/wifi_group} during second layout pass: posting in next frame
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
fixed in https://github.com/crdroidandroid/android_frameworks_base/commit/cf7145404492950385dc17608c7da98d510f090f & https://github.com/crdroidandroid/android_frameworks_base/commit/e366494ff266b56408925a8c816fa23e605fd439
