### ISSUE TITLE
bug: device decryption does not work anymore

### ISSUE THREAD

**Issue by ossilator** [crdroidandroid/issue_tracker#66]
### Issue type

Other

### Device

Xiaomi Redmi 4X (santoni)

### crDroid version

crDroid 7

### Exact version

7.21

### Bug description

starting with crDroid 7.21, an encrypted device won't boot. i get the "encryption unsuccessful" message/dialog before the PIN is queried.

### Steps to reproduce

turn on the device ...

### Relevant log (logcat/build log)

```shell
i don't know how to obtain one, as adb doesn't connect at that point.
```

### Additional context

i tried up to the current 7.25.
downgrading to 7.20 instantly fixes the issue without any other action.

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
@Jabiyeff
if still supported, check it out
