### ISSUE TITLE
Call transfer doesn't works

### ISSUE THREAD

**Issue by gcmmrt** [crdroidandroid/issue_tracker#67]
### Issue type

Other

### Device

Poco X3 NFC surya

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

Hi support,
Please can you verify call transfer function? 
When I transfer calls to another phone  Number, if my phone Is Just rebooted, then all works, but if you try to remove this transfer, there Is a problem, start the procedure but don't ends.
With crdroid 8.x never problem, but only in crdroid 9.x.
Tried clean  flesh 2 Times but same prob. 
I tried both with keyboard codes and via phone app function.
Thans for your support

### Steps to reproduce

Phone app, call account, click on SIM then call transfer

### Relevant log (logcat/build log)

```shell
I don't have it
```

### Solution

Reboot phone

### Additional context

Is simple to reproduce bug, try call transfer via keyboard or via phone app

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
Log needed

**Comment by gcmmrt** [comment]
please, describe me exact procedure tu have it, I'm not a developer,
otherwise close the ticket.
Thank you

Il giorno lun 26 dic 2022 alle ore 09:28 Lup Gabriel <
***@***.***> ha scritto:

**Comment by gwolf2u** [comment]
adb logcat > log.txt from CMD terminal 
Then reproduce the steps for the issue
Close CMD window
Attach log.txt file
