### ISSUE TITLE
bug: Bootloop after formatting SD Card as Internal Storage

### ISSUE THREAD

**Issue by Mattiam2** [crdroidandroid/issue_tracker#7]
### Issue type

Other

### Device

lavender

### crDroid version

crDroid 8

### Bug description

Formatting SD Card as Internal Storage causes bootloop.

### Steps to reproduce

Step 1. Click the notification telling to format the SD Card (with SD Card inserted)
Step 2. Format as Internal Storage
Bootloop!

### Relevant log (logcat/build log)

```shell
Can't get one
```

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
logcat is needed

**Comment by MARCOS752wh** [comment]
I think it indicates that he put the sd card as main internal storage and formatted it which caused the failure maybe, well that's how I understand xd

**Comment by Mattiam2** [comment]
There is something called Adoptable Storage that very few rom maintainers seems to know. Formatting an sd card as internal storage (which is an Android function) permits to install apps on it, and set as default location for media

**Comment by Mattiam2** [comment]
There is something called Adoptable Storage that very few rom maintainers seems to know. Formatting an sd card as internal storage (which is an Android function) permits to install apps on it, and set as default location for media the sd card.

(I missclicked and wrongly closed the thread)

**Comment by gwolf2u** [comment]
no logcat
