### ISSUE TITLE
Playback error

### ISSUE THREAD

**Issue by lordgregorymsk** [crdroidandroid/issue_tracker#71]
### Issue type

Other

### Device

OnePlus 7 Pro (guacamole)

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

Decoder for video doesn't work properly on YouTube and Telegram Videos. Also even if it load video it will load it 10x slower than usually.

### Steps to reproduce

Step 1. Open YouTube / Telegram app
Step 2. Open any video / video file.

### Relevant log (logcat/build log)

```shell
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal: Playback error
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:   axl: MediaCodecVideoRenderer error, index=1, format=Format(303, null, null, video/x-vnd.on2.vp9, vp9, 4356722, en, [1920, 1080, 60.0], [-1, -1]), format_supported=YES
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       at ayf.handleMessage(Unknown Source:1676)
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:201)
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:288)
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:   Caused by: blg: Decoder failed: OMX.qcom.video.decoder.vp9
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       at blh.ah(Unknown Source:4)
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       at bfh.R(Unknown Source:738)
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       at ayf.m(Unknown Source:853)
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       at ayf.handleMessage(Unknown Source:1439)
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       ... 4 more
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalStateException
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_dequeueOutputBuffer(Native Method)
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       at android.media.MediaCodec.dequeueOutputBuffer(MediaCodec.java:3572)
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       at log.b(Unknown Source:8)
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       at bfh.R(Unknown Source:316)
12-28 16:55:36.746 22125 23787 E ExoPlayerImplInternal:       ... 6 more
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal: Disable failed.
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:   java.lang.IllegalStateException
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_flush(Native Method)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at android.media.MediaCodec.flush(MediaCodec.java:2387)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at log.g(Unknown Source:3)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at bfh.at(Unknown Source:2)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at bfh.ao(Unknown Source:52)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at bfh.w(Unknown Source:15)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at blh.w(Unknown Source:9)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at axd.r(Unknown Source:25)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at ayf.l(Unknown Source:24)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at ayf.w(Unknown Source:35)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at ayf.G(Unknown Source:12)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at ayf.handleMessage(Unknown Source:1748)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:201)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:288)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal: Reset failed.
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:   java.lang.IllegalStateException
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_flush(Native Method)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at android.media.MediaCodec.flush(MediaCodec.java:2387)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at log.h(Unknown Source:12)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at bfh.al(Unknown Source:5)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at bfh.z(Unknown Source:4)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at blh.z(Unknown Source:0)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at axd.E(Unknown Source:15)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at ayf.w(Unknown Source:68)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at ayf.G(Unknown Source:12)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at ayf.handleMessage(Unknown Source:1748)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:201)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:288)
12-28 16:55:36.747 22125 23787 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
```

### Additional context

It happens randomly, not sure what cause this issue. But I see many errors with ExoPlayerImplInternal in logs.

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by lordgregorymsk** [comment]
[logcat.txt](https://github.com/crdroidandroid/issue_tracker/files/10314608/logcat.txt)
Full log file

**Comment by gwolf2u** [comment]
I can't confirm this one
playing videos on youtube daily and no such issue here
what youtube version you have?
for telegram just sent a video recording from my other device and playback was good

**Comment by lordgregorymsk** [comment]
YouTube Version 17.33.42
There are two Magisk modules on my device : Dialer Framework and Universal SafetyNet Fix. On previous version all was good.

**Comment by lordgregorymsk** [comment]
Disabled all Modules. Still slow video buffer (loading). Checking the logs shows something wrong with it.

**Comment by gwolf2u** [comment]
issue is something else not related to ROM as far as I see
check if gapps are working properly

```
12-28 16:55:02.703 22125 22175 W GmsClient: unable to connect to service: com.google.android.gms.phenotype.service.START on com.mgoogle.android.gms
12-28 16:55:02.706 22125 23649 W GmsClient: unable to connect to service: com.google.android.gms.measurement.START on com.mgoogle.android.gms
12-28 16:55:02.708 22125 22175 W GmsClient: unable to connect to service: com.google.android.gms.icing.LIGHTWEIGHT_INDEX_SERVICE on com.mgoogle.android.gms
12-28 16:55:02.709 22125 22175 W GmsClient: unable to connect to service: com.google.android.gms.icing.APP_INDEXING_SERVICE on com.mgoogle.android.gms
12-28 16:55:02.723 22125 22175 W GmsClient: unable to connect to service: com.google.android.gms.cast.service.BIND_CAST_DEVICE_CONTROLLER_SERVICE on com.mgoogle.android.gms
12-28 16:55:02.733 22125 22165 D StrictMode: StrictMode policy violation: android.os.strictmode.UnbufferedIoViolation
12-28 16:55:02.733 22125 22165 D StrictMode: 	at android.os.StrictMode$AndroidBlockGuardPolicy.onUnbufferedIO(StrictMode.java:1647)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at libcore.io.IoTracker.trackIo(IoTracker.java:35)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at libcore.io.IoTracker.trackIo(IoTracker.java:45)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at java.io.FileInputStream.read(FileInputStream.java:320)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at java.io.FileInputStream.read(FileInputStream.java:261)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at swb.n(Unknown Source:0)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at swb.h(Unknown Source:18)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at swb.j(Unknown Source:0)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at swb.a(Unknown Source:37)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at svf.run(Unknown Source:91)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at nrq.run(Unknown Source:6)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at nru.run(Unknown Source:49)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at nsn.run(Unknown Source:619)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at mwc.run(Unknown Source:52)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at com.google.android.apps.youtube.embeddedplayer.service.jar.client.p.run(Unknown Source:53)
12-28 16:55:02.733 22125 22165 D StrictMode: 	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by lordgregorymsk** [comment]
Will check ASAP. Also will try to install minimum (core) NikGApps

**Comment by lordgregorymsk** [comment]
Installed clean without gapps. Still run this issue with VP9

12-28 22:57:36.717  4203  4397 W MediaCodecRenderer: Failed to initialize decoder: OMX.qcom.video.decoder.vp9
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:   java.lang.IllegalArgumentException
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at android.media.MediaCodec.native_configure(Native Method)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at android.media.MediaCodec.configure(MediaCodec.java:2215)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at android.media.MediaCodec.configure(MediaCodec.java:2131)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at mak.b(PG:67)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at bmf.av(PG:7)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at bmf.ak(PG:31)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at bmf.ah(PG:4)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at bsf.ah(PG:1)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at bmf.aG(PG:4)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at bmf.R(PG:2)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at bfc.m(PG:87)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at bfc.handleMessage(PG:185)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at android.os.Looper.loopOnce(Looper.java:201)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at android.os.Looper.loop(Looper.java:288)
12-28 22:57:36.717  4203  4397 W MediaCodecRenderer:       at android.os.HandlerThread.run(HandlerThread.java:67)
12-28 22:57:36.717  1313  1431 I OMX-VDEC-1080P: Exit OMX vdec Destructor: fd=9
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer: Video codec error
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:   bme: Decoder init failed: OMX.qcom.video.decoder.vp9, Format(244, null, null, video/x-vnd.on2.vp9, null, 524288, en, [854, 480, -1.0], [-1, -1])
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at bmf.ak(PG:35)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at bmf.ah(PG:4)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at bsf.ah(PG:1)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at bmf.aG(PG:4)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at bmf.R(PG:2)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at bfc.m(PG:87)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at bfc.handleMessage(PG:185)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at android.os.Handler.dispatchMessage(Handler.java:102)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at android.os.Looper.loopOnce(Looper.java:201)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at android.os.Looper.loop(Looper.java:288)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at android.os.HandlerThread.run(HandlerThread.java:67)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:   Caused by: java.lang.IllegalArgumentException
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at android.media.MediaCodec.native_configure(Native Method)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at android.media.MediaCodec.configure(MediaCodec.java:2215)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at android.media.MediaCodec.configure(MediaCodec.java:2131)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at mak.b(PG:67)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at bmf.av(PG:7)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       at bmf.ak(PG:31)
12-28 22:57:36.718  4203  4397 E MediaCodecVideoRenderer:       ... 10 more
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal: Playback error
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:   beh: MediaCodecVideoRenderer error, index=1, format=Format(244, null, null, video/x-vnd.on2.vp9, null, 524288, en, [854, 480, -1.0], [-1, -1]), format_supported=YES
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at bfc.handleMessage(PG:197)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:102)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:201)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:288)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:67)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:   Caused by: bme: Decoder init failed: OMX.qcom.video.decoder.vp9, Format(244, null, null, video/x-vnd.on2.vp9, null, 524288, en, [854, 480, -1.0], [-1, -1])
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at bmf.ak(PG:35)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at bmf.ah(PG:4)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at bsf.ah(PG:1)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at bmf.aG(PG:4)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at bmf.R(PG:2)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at bfc.m(PG:87)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at bfc.handleMessage(PG:185)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       ... 4 more
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:   Caused by: java.lang.IllegalArgumentException
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at android.media.MediaCodec.native_configure(Native Method)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at android.media.MediaCodec.configure(MediaCodec.java:2215)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at android.media.MediaCodec.configure(MediaCodec.java:2131)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at mak.b(PG:67)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at bmf.av(PG:7)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       at bmf.ak(PG:31)
12-28 22:57:36.720  4203  4397 E ExoPlayerImplInternal:       ... 10 more

**Comment by lordgregorymsk** [comment]
[logcat.txt](https://github.com/crdroidandroid/issue_tracker/files/10316199/logcat.txt)
Clean log without GApps installed.
Also i check Video on YouTube Revanced with microg only

**Comment by gwolf2u** [comment]
not totally sure what's wrong there
reading the log, initially is complaining about some network restriction and eventually payback error
as I said, can't really reproduce here and also another user on Telegram confirms all good
https://t.me/crDroidOP7Pro/104938

**Comment by lordgregorymsk** [comment]
Fixed by flashing again all firmware files. Not sure what the problem was but it seems disappeared
