### ISSUE TITLE
bug: Speaker volume can't be turned down when using third-party app's call function

### ISSUE THREAD

**Issue by 1130381752** [crdroidandroid/issue_tracker#72]
### Issue type

Other

### Device

OnePlus 7 Pro (guacamole)

### crDroid version

crDroid 9

### Exact version

9.0 (2022/12/26)

### Bug description

When I launch the third app(such as WhatsApp or WeChat), I call somebody by using this app and enable the speaker, when I adjust the volume, there is no change in speaker volume, it is always at max volume

But if I call somebody by using the system's dialer, the speaker volume can be adjust normally...

### Steps to reproduce

As above

### Relevant log (logcat/build log)

```shell
Maybe no need, you can just try it
```

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
can't confirm with cr9.1 so marking this as completed
