### ISSUE TITLE
bug: Status bar graphical 

### ISSUE THREAD

**Issue by Don-Keballs** [crdroidandroid/issue_tracker#74]
### Issue type

User interface

### Device

Beryllium 

### crDroid version

crDroid 9

### Exact version

9.0

### Bug description

Status bar graphical bug. Upon pull down icons overlap eachother but slightly apart.

### Steps to reproduce

Step 1: from home screen pull down status bar to view notifications.

Step 2: Hopefully you'll see the small graphical bug where the icons overlap.

### Relevant log (logcat/build log)

```shell
N/A
```

### Screenshots or videos

![Screenshot_20221226-120808_crDroid Home](https://user-images.githubusercontent.com/73664856/210000790-c9869181-dd1a-4490-83ea-c52eae83a7d4.png)

### Acknowledgements

- [X] I've checked device is officially supported.
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
from what build date is this?

**Comment by Don-Keballs** [comment]
> from what build date is this?

22nd December 2022

**Comment by gwolf2u** [comment]
please update to build 2022-12-30 as there are some possible fixes there

**Comment by Don-Keballs** [comment]
> 



> please update to build 2022-12-30 as there are some possible fixes there do reply back your outcome

Ok thanks. I'll report back one I've updated. Should get round to updating over the next few days.

**Comment by Don-Keballs** [comment]
Update; Bug has been fixed in build 2022-12-30

Thanks Dev [gwolf2u](https://github.com/gwolf2u)
