### ISSUE TITLE
Sound and vibration related

### ISSUE THREAD

**Issue by Ayrus1** [crdroidandroid/issue_tracker#77]
### Issue type

Feature not working as intended

### Device

Beryllium

### crDroid version

crDroid 9

### Exact version

9.0 Dec 30 build

### Bug description

Feature not working: vibrate on connect

### Steps to reproduce

Crdroid settings
Sound 
Check vibrate on connect

### Relevant log (logcat/build log)

```shell
Crdroid settings
Sound 
Check vibrate on connect
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
this happens with stock dialer app?

**Comment by gwolf2u** [comment]
can't confirm with latest build

**Comment by Ayrus1** [comment]
Hi Gabriel Lup,

Extremely sorry for no response. I had completely missed this mail.

Regarding the issue and your query - I've installed NikGapps Basic and
hence running the Google dialer and not the AOSP dialer.

The issue still persists in the latest build.

Just to recall - the vibration on call connect is not working though i
enable it in Crdroid settings.

Thanks & Regards,
