### ISSUE TITLE
bug(miatoll): device does not play sound on Bluetooth audio

### ISSUE THREAD

**Issue by omaemae** [crdroidandroid/issue_tracker#80]
### Issue type

Feature not working as intended

### Device

Redmi Note 9 Pro (joyeuse, miatoll)

### crDroid version

crDroid 9

### Exact version / Build date

9.0/2022-12-18

### Bug description

Device connects to Bluetooth headphones, but does not play anything on Bluetooth audio, in some cases playing over the device's speakers instead

### Steps to reproduce

1. Make sure Bluetooth is enabled
2. Turn on your headphones
3. Connect to your headphones
4. Try to play audio (via YouTube, Spotify, etc...)

### Relevant log (logcat/build log)

```shell
See comment below for relevant logcat output.
```

### Additional context

Bluetooth audio worked fine on 9.0/2022-11-11, however broke after updating to 9.0/2022-12-18.

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by omaemae** [comment]
[Here is the logcat output from the device.](https://github.com/crdroidandroid/issue_tracker/files/10331211/bt-logcat.txt)

**Comment by omaemae** [comment]
Might be fixed by the following commits:
- https://github.com/crdroidandroid/android_device_xiaomi_miatoll/commit/82c2d4d9ab7abb9ab97449922e1e11bd1a54d4d5
- https://github.com/crdroidandroid/android_device_xiaomi_miatoll/commit/3782ce0ede2b04ac029fab08097c85763c4e021f
- https://github.com/crdroidandroid/android_device_xiaomi_miatoll/commit/f75ee90683d8da139146e71f0fe298bdb7111047
- https://github.com/crdroidandroid/android_device_xiaomi_miatoll/commit/4517870cafcc55b94510e477c76f5e8e3c092f56

These are not yet in any build however.

**Comment by omaemae** [comment]
As of now, there was an update released which supposedly fixes this.
![image](https://user-images.githubusercontent.com/17727163/210256050-9656e28b-096c-4032-953c-8111174b7022.png)
![image](https://user-images.githubusercontent.com/17727163/210255939-0d6a7ab8-5541-4354-94a8-488043fdc362.png)

This update does not exist.
![image](https://user-images.githubusercontent.com/17727163/210255946-f64f4e2f-ac57-413e-a271-c40743b29ef2.png)

The 2022-12-18 build also has an identity crisis classifying itself as a 2022-12-13 build, which doesn't exist.

**Comment by gwolf2u** [comment]
Update has been released 
Do check it out
https://github.com/crdroidandroid/android_vendor_crDroidOTA/commit/cf11d5c7034fd65af1f4065140bd8fa2634b8de4

**Comment by omaemae** [comment]
The update does solve the issue.
