### ISSUE TITLE
bug(Chime): System Ui Crashes on Android 13/ crdroid 9.0

### ISSUE THREAD

**Issue by Luciogi** [crdroidandroid/issue_tracker#81]
### Issue type

User interface

### Device

Redmi 9t (chime)

### crDroid version

crDroid 9

### Exact version / Build date

9.0 / 2022-12-28

### Bug description

System Ui sometimes freezes and crashes 

### Steps to reproduce

Randomly happens

### Relevant log (logcat/build log)

```shell
(It is unpredictable to capture log)
```

### Screenshots or videos

none

### Additional context

Clean install

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
ANR or crashes can be checked only with log

**Comment by Luciogi** [comment]
@gwolf2u Does log persist after reboot?

**Comment by gwolf2u** [comment]
no

**Comment by Luciogi** [comment]
@gwolf2u I was able to capture logs , attached file in issue
