### ISSUE TITLE
bug: "app isn't responding" message continues to pop-up even after an app unfreezes

### ISSUE THREAD

**Issue by potchy** [crdroidandroid/issue_tracker#84]
### Issue type

User interface

### Device

POCO F1 (Beryllium)

### crDroid version

crDroid 9

### Exact version / Build date

20221230

### Bug description

Whenever an app stops responding, the "app isn't responding" message continues to pop-up even after the app unfreezes.
I originally reported this issue on [XDA Forums](https://forum.xda-developers.com/t/rom-13-beryllium-crdroid-v9-0-20-12-2022.4511631/post-87737155), but it still isn't solved as of the latest build (20221230).

### Steps to reproduce

It's difficult to reproduce, but all you have to do is have some random app to stop responding.

### Relevant log (logcat/build log)
[2023-01-03-22-43-05.txt](https://github.com/crdroidandroid/issue_tracker/files/10340905/2023-01-03-22-43-05.txt) (Discord)

### Screenshots or videos
Discord

https://user-images.githubusercontent.com/4316326/210470889-50de0b94-ab42-40b5-bfe4-fc7bf1c3bba7.mp4

Mercado Livre

https://user-images.githubusercontent.com/4316326/210457029-381268f5-2e49-4786-a995-7bdd718e33d7.mp4

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Don-Keballs** [comment]
Can confirm. Facing the same issue.

**Comment by gwolf2u** [comment]
Fixed
https://github.com/crdroidandroid/android_frameworks_base/commit/e8e3ad6a29ce8d80dc4e1a9115fcb4b28db17516

**Comment by Lost-Entrepreneur439** [comment]
This issue appears to be present again on the crDroid 11 beta.
