### ISSUE TITLE
build data not visible in Hungarian

### ISSUE THREAD

**Issue by vargasimon** [crdroidandroid/issue_tracker#85]
### Issue type

User interface

### Device

beryllium
courbet

### crDroid version

crDroid 9

### Exact version / Build date

beryllium: 9.0/2022-12-30
courbet: 9.0/2022-12-22

### Bug description

When opening updater there is no build date, type and maintainer information displayed when language is set to Hungarian. Changing language to English shows build information correctly. Changing again to Hungarian and build information is gone again.

### Steps to reproduce

1. Go to settings
2. Go to system
3. Go to update

### Relevant log (logcat/build log)

```shell
not sure any log needed
```

### Solution

Switching to English

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
screenshot please

**Comment by vargasimon** [comment]
Sure, English an Hungarian screenshot attached.
![Screenshot_20230113-182259_Updater](https://user-images.githubusercontent.com/34687546/212421305-d80cb204-5b55-4d4d-bc32-18379dd65a21.png)
![Screenshot_20230113-182401_Frissítés](https://user-images.githubusercontent.com/34687546/212421374-556f9531-3724-4c28-ba22-c4b628bd36c3.png)

**Comment by vargasimon** [comment]
Hi, can you please reopen? Issue is back on beryllium with build 03 August 2023. Thanks!
