### ISSUE TITLE
System Ui Stop responding 

### ISSUE THREAD

**Issue by 1SlicKker1** [crdroidandroid/issue_tracker#86]
### Issue type

User interface

### Device

Poco f1 (Berrylium)

### crDroid version

crDroid 9

### Exact version / Build date

V9.0 / 29dec 2022

### Bug description

System ui is crashing everyday atleast for 2times in a day and reboot to system ui ... This is annoying.. please fix this on upcoming build.. 

### Steps to reproduce

Auto happened 

### Relevant log (logcat/build log)

```shell
No logcat cause automatically happened anytime..
```

### Screenshots or videos

![Screenshot_20230107-234737_Swift Backup](https://user-images.githubusercontent.com/121731485/211165401-4105634b-b493-4346-a305-1db7c1ace8c5.png)

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
Fixed in https://github.com/crdroidandroid/android_frameworks_base/commit/e8e3ad6a29ce8d80dc4e1a9115fcb4b28db17516
