### ISSUE TITLE
Device Health Services: error work with microG

### ISSUE THREAD

**Issue by Izorkin** [crdroidandroid/issue_tracker#9]
### Issue type

Other

### Device

Mi 9T (Davinci)

### crDroid version

crDroid 8

### Bug description

After installing microG, the "Device Health Services" service starts asking to update Google Play Services.

### Steps to reproduce

1. Install firmware.
2. Install Magisk.
3. Install microG.

### Relevant log (logcat/build log)

```shell
None
```

### Screenshots or videos

![Screenshot_20220928-201848](https://user-images.githubusercontent.com/26877687/192848999-2d93f6bb-7792-4b3c-bcc5-13bf96167a40.png)
![Screenshot_20220928-202005](https://user-images.githubusercontent.com/26877687/192849010-383b1a9a-aa92-4998-8efb-97e1a2424248.png)

### Additional context

Version MicroG: 0.2.24.214816

### Acknowledgements

- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
This is expected since the services is intended to be used with gapps not microG

**Comment by africabloe** [comment]
For MicroG. If notifications appear from the :
1. Device Health Services (com.google.android.apps.turbo), 
2. Settings Services (com.google.android.settings.intelligence), 
3. Android System Intelligence (com.google.android.as), 
4. Private Compute Services (com.google.android.as.oss) applications, turn off notifications for these apps. You can of course update them if you need to. 
Also, uninstall/disable the application :
5. Intent Filter Verification Service (com.android.statementservice), it is useless.
