### ISSUE TITLE
Battery estimate not showing

### ISSUE THREAD

**Issue by repparw** [crdroidandroid/issue_tracker#92]
### Issue type

Feature not working as intended

### Device

Redmi note 11 (spes)

### crDroid version

crDroid 9

### Exact version / Build date

9.1/2023-01-11

### Bug description

Battery estimate shows battery percentage only

### Steps to reproduce

Enable battery estimate on QS settings
Check QS panel and only see percent, even if percent is disabled

### Relevant log (logcat/build log)

```shell
---
```

### Screenshots or videos

![Screenshot_20230113-203111_Bromite](https://user-images.githubusercontent.com/45952970/212437179-affa4d45-9ee3-433a-843a-f98f6ef14c01.png)

### Acknowledgements

- [ ] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by Jabiyeff** [comment]
Need to use device some time to system can calculate estimate time.

**Comment by gwolf2u** [comment]
my thought would be
"but is there enough space for the stats to show up ?"

**Comment by Jabiyeff** [comment]
> my thought would be "but is there enough space for the stats to show up ?"

But I can't do anything for this, he using biggest font size, its not default font size.

**Comment by gwolf2u** [comment]
> > my thought would be "but is there enough space for the stats to show up ?"
> 
> But I can't do anything for this, he using biggest font size, its not default font size.

Aware you can't
My point is that it might be that and not an issue actually
You can fit so much on status bar

**Comment by Jabiyeff** [comment]
> > > my thought would be "but is there enough space for the stats to show up ?"
> > 
> > 
> > But I can't do anything for this, he using biggest font size, its not default font size.
> 
> Aware you can't My point is that it might be that and not an issue actually You can fit so much on status bar

Actually sir, did your tested battery estimate feature on your device? I tested it now, before it worked fine, but now it doesn't show.

**Comment by repparw** [comment]
> Need to use device some time to system can calculate estimate time.

Not the problem. I have it enabled since installing. It used to work on my phone on crdroid 8
