### ISSUE TITLE
bug: Dymanic Clock and Calendar not working

### ISSUE THREAD

**Issue by kirbyloco** [crdroidandroid/issue_tracker#94]
### Issue type

Source code related

### Device

Oneplus 7 Pro (guacamole)

### crDroid version

crDroid 9

### Exact version / Build date

9.1 20230113

### Bug description

Dymanic Clock and Calendar not working

### Steps to reproduce

Step .1 reapply icon theme on Clock and Calendar

### Relevant log (logcat/build log)

```shell
01-16 12:02:42.332  3485  3485 E Launcher.Utilities: mapToRange: range has 0 length
01-16 12:02:42.343  3485  3485 E Launcher.Utilities: mapToRange: range has 0 length
01-16 12:02:42.354  3485  3485 E Launcher.Utilities: mapToRange: range has 0 length
01-16 12:02:42.365  3485  3485 E Launcher.Utilities: mapToRange: range has 0 length
01-16 12:02:42.376  3485  3485 E Launcher.Utilities: mapToRange: range has 0 length
01-16 12:02:42.388  3485  3485 E Launcher.Utilities: mapToRange: range has 0 length
01-16 12:02:42.399  3485  3485 E Launcher.Utilities: mapToRange: range has 0 length
```

### Screenshots or videos

https://user-images.githubusercontent.com/17351171/212596676-1eb0c3c2-ac37-41c7-9689-ae6f4208d6f9.mp4

### Solution

reapply icon theme can temp fix

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by gwolf2u** [comment]
can't reproduce with latest code
can you confirm?

**Comment by kirbyloco** [comment]
https://user-images.githubusercontent.com/17351171/216769505-e3fdb10d-6733-463c-8901-dff6c58ca842.mp4
