### ISSUE TITLE
bug: Unable to install app in different user

### ISSUE THREAD

**Issue by Luciogi** [crdroidandroid/issue_tracker#95]
### Issue type

Feature not working as intended

### Device

Redmi 9t (chime)

### crDroid version

crDroid 9

### Exact version / Build date

9.1/2023-01-14

### Bug description

App installed in Owner(default user) , does not install in Different user(created by me)

### Steps to reproduce

1. Install app in Owner user e.g https://github.com/adil192/saber/releases
2. Create another user
3. switch to other user
4. Install https://github.com/adil192/saber/releases
5. You will find that package conflicts

### Relevant log (logcat/build log)

```shell
https://github.com/crdroidandroid/issue_tracker/files/10424886/user.txt
```

### Screenshots or videos

https://user-images.githubusercontent.com/84625092/212657658-6d3a25bc-d7c5-4eeb-94c1-ba0d9e9a1be0.mp4

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by neobuddy89** [comment]
seems to be issue with package

01-16 15:12:51.510  1433  1796 W PackageManager: Existing package com.adilhanney.saber signatures do not match newer version; ignoring!

**Comment by Luciogi** [comment]
@neobuddy89 It also happening with other apps.

like [neostore](https://github.com/NeoApplications/Neo-Store/releases)

**Comment by Luciogi** [comment]
More Tested: 
- Neo Store  is installed from F-droid in **Owner** user 
- I Created new user
- Then installed Neo Store from [Github Releases](https://github.com/NeoApplications/Neo-Store/releases)
   - This caused "App not installed as package conflicts with an existing package", although Neo Store does not exist in New user account
- Installing apk from [f-droid](https://f-droid.org/packages/com.machiav3lli.fdroid/) installed fine , **Owner user** has Neo Store apk from f-droid

**Comment by gwolf2u** [comment]
what's the status of this no cr 9.3?

**Comment by Luciogi** [comment]
@gwolf2u bug is present in 9.3
