### ISSUE TITLE
bug: system freeze

### ISSUE THREAD

**Issue by Avnesh007** [crdroidandroid/issue_tracker#97]
### Issue type

User interface

### Device

 Beryllium

### crDroid version

crDroid 9

### Exact version / Build date

9.1/2023-01-13

### Bug description

I faced system ui freeze issue again on latest cr9.1 build. I am non rooted user and using cr recovery (encrypted). i am attaching log, i hope it has captured issue. That time device not working ; gestures not working and after that device got sleep also woke up through power button were not working so i did hard reboot.
@gab

### Steps to reproduce

Step 1: Enable usb debugging from developer mode
Step 2: Connect device with Computer
Step 3: Use adb & take log when issue happened

### Relevant log (logcat/build log)

```shell
06-17 13:42:25.200   615   615 W keystore2: keystore2::metrics_store: In update_keystore_crash_sysprop: Failed to read the existing system property due to: In read_keystore_crash_count: Property not set..Therefore, keystore crashes will not be logged.
```

### Acknowledgements

- [X] I've checked device is officially supported (for device specific reports and not source related).
- [X] I'm running latest version available on crdroid.net for this device
- [X] I have searched the existing issues and this is a new and no duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I filled out all of the requested information in this issue properly.

**Comment by DANILKA1802** [comment]
I had something like this 3 times, first a window appeared that an error occurred in the application, as I understood it was not one specific application, but several applications at the same time (if not all) after that a black screen, then a boot animation, it lasts an infinite time, only a hard reboot helps.


device:
Jason
crdroid:
7.25

**Comment by gwolf2u** [comment]
can't can't confirm this one
